### ISSUE TITLE
Errors exist in required project(s)

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1027]
I'm trying to configure cloud dbeaver in eclipse but I get the following error is like missing source code
![error projects](https://user-images.githubusercontent.com/52106718/183084333-045b2613-f478-4ee6-9004-bb13f90d6ade.png)
I need your help please

**Comment by kseniiaguzeeva** [comment]
I close the ticket as duplicate of [Error in all packages in following folders to deploy cloudbeaver in eclipse java](https://github.com/dbeaver/cloudbeaver/issues/988).

**Comment by miltonchirinos44** [comment]
ok, Sorry @kseniiaguzeeva
