### ISSUE TITLE
Question regarding sources in provided-connections.json

### ISSUE THREAD

**Issue by nicolamarangoni** [dbeaver/cloudbeaver#104]
I have the the following data source in the file `provided-connections.json`:
```
   "postgres-jdbc-171e5ec3621-491942a29a4c8e9e": {
      "provider": "postgresql",
      "driver": "postgres-jdbc",
      "name": "My_connection",
      "save-password": false,
      "show-system-objects": true,
      "read-only": false,
      "folder": "PostgreSQL",
      "configuration": {
	"host": "myhostname",
        "port": "5432",
        "database": "pharos_framework",
        "url": "jdbc:postgresql://myhostname:5432/mydatabase",
	"type": "dev",
	"properties": {
          "connectTimeout": "20",
          "loginTimeout": "20"
        },
	"provider-properties": {
	  "@dbeaver-show-non-default-db@": "false",
          "@dbeaver-show-template-db@": "false",
          "postgresql.dd.plain.string": "false",
          "postgresql.dd.tag.string": "false"
        },
	"auth-model": "native"
      }
    },
```
Un the server console log I see the following:
`Global datasource 'My_connection' ignored - driver is not applicable`
What does it mean?

The source is visible in the left tree, but when trying to connect, it opens only the "Info" tab but it doesn't connect to the source. In the console I just see this:
Connect with 'My_connection' (postgres-jdbc-171e5ec3621-491942a29a4c8e9e).
What I'm doing wrong?
I also see that the documentation is wrong. Here
https://github.com/dbeaver/cloudbeaver/wiki/Configuring-server-datasources
it should be specified that `provided-connections.json` is to be used, not `data-sources.json` to see data sources in the left tree.

**Comment by serge-rider** [comment]
I can't reproduce that. At least in default configuration.
Error "driver is not applicable" happens when:
1. Parameter enabledDrivers specified in cloudbeaver.conf and your driver is not in that list
2. Driver libraries (jars) are missing in driver directory.

Do you use default build or some custom build?

**Comment by nicolamarangoni** [comment]
Also, the only way to make it work is to put clear-text passwords in `provided-connections.json`. I tried putting `credentials-config.json` but it looks to be ignored.
