### ISSUE TITLE
Greenplum

### ISSUE THREAD

**Issue by ASEthan** [dbeaver/cloudbeaver#1040]
Can i  add Greenplum into the cloudbeaver and how to do it

**Comment by kseniiaguzeeva** [comment]
Thank you for your interest in CloudBeaver. Greenplum driver is available by default in [Enterprise version](https://cloudbeaver.io/try-it-now/).
You can add it manually to Community Edition. Here is [the instruction](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers).

**Comment by ASEthan** [comment]
I add greenplum to Community Edition but it is not work
![image](https://user-images.githubusercontent.com/37731136/183593369-e389990e-90fc-4fb2-b411-e9a965e8d1a6.png)
![image](https://user-images.githubusercontent.com/37731136/183593615-d05b5da0-f696-493c-8a0a-c586778d2a64.png)
![lQLPJxaSX4BdwELNAXzNAk6wnhkfmKLs5cgC8OJH20BvAA_590_380](https://user-images.githubusercontent.com/37731136/183593785-3632321a-82ca-4903-8e10-e00978dc9bcd.png)

**Comment by kseniiaguzeeva** [comment]
Could you please describe how did you configure it step by step?

Related tickets may also help you:
https://github.com/dbeaver/cloudbeaver/issues/37
https://github.com/dbeaver/cloudbeaver/issues/192

**Comment by ASEthan** [comment]
I noticed the Greenplum driver in DBeave
![image](https://user-images.githubusercontent.com/37731136/184049540-38a02f5c-8cc1-4a7b-85fc-a8aef614f476.png)
So I Create a new sub-folder greenplum in server/drivers like this 
![image](https://user-images.githubusercontent.com/37731136/184049929-44212be3-2bee-4fff-ad6b-f44a0af00aa0.png)
and add it to the main server/drivers/pom.xml 
![image](https://user-images.githubusercontent.com/37731136/184050050-c5fa109c-3105-483a-821c-3f226b59e6d9.png)
next I open the server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml  add 
resource name="drivers/greenplum"
![image](https://user-images.githubusercontent.com/37731136/184050601-caeed33f-d299-498c-8b91-de9e94cb284f.png)
 bundle id="drivers.greenplum" label="greenplum drivers"
![image](https://user-images.githubusercontent.com/37731136/184050623-f8d013a7-c87b-452d-ba6c-0423cbd4100b.png)
 driver id="greenplum:greenplum-jdbc"
![image](https://user-images.githubusercontent.com/37731136/184050639-c8fe678c-2077-4150-8b62-18b6be4c63de.png)
Then i just run the cloudbeaver\deploy\build.bat 
finally I find  it is not work
![image](https://user-images.githubusercontent.com/37731136/184050435-fdcab177-e11e-41d7-9ee5-80ad77d3bac5.png)

**Comment by ASEthan** [comment]
I found a solution 
Changed the Greenplum driver code in DBeave ` <file type="jar" path="drivers/greenplum" bundle="drivers.greenplum"/>`

**Comment by kseniiaguzeeva** [comment]
Nice to hear it.
