### ISSUE TITLE
 Add a new menu option, in the main menu

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1048]
What steps do I have to follow to add a new option in the main menu?
![image](https://user-images.githubusercontent.com/52106718/184432357-0cf1b638-bc02-4be6-a8e6-fe664535fc7f.png)

**Comment by devnaumov** [comment]
Hi! Could you please explain what do you want to add exactly?

**Comment by miltonchirinos44** [comment]
@devnaumov 
I want to add a new option to display logs for the administrator role, the new menu option must have the name "LOGS", this menu has to display the name of the user in a table, IP from where the query is executed, query that is executing , database name.
With the objective of establishing statistics of the query executions carried out by users, and in this way identify users who make requests with a long time to the database server, causing problems in the server.

@devnaumov 
It will be possible for you to explain to me how I can create this new menu option in cloudbeaver or what documentation I can review to achieve this objective

**Comment by devnaumov** [comment]
@miltonchirinos44 Seems like what you are looking for is already implemented. It's called [Query Manager](https://github.com/dbeaver/cloudbeaver/wiki/Query-Manager) and is available in the CloudBeaver Enterprise Edition.
But if you want to implement it your way, there is a service named `MainMenuService`, you can create your own plugin and call the `registerRootItem` method to add some specific item to the top bar.

https://github.com/dbeaver/cloudbeaver/wiki/Plugin-system
https://github.com/dbeaver/cloudbeaver/blob/devel/webapp/packages/plugin-top-app-bar/src/TopNavBar/MainMenu/MainMenuService.ts#L59

**Comment by miltonchirinos44** [comment]
@devnaumov 
You tell me about this option that is in the CloudBeaver Enterprice Edition version.

This option of the logs shows me the name of the user, name of the database, what query is executing or executed by the user (I am necessarily looking for this type of log report)?, I am not looking for server errors or cloudbeaver system, More than all that data I want to store for audit purposes.

![image](https://user-images.githubusercontent.com/52106718/188511492-340c9117-a11d-46eb-ae9f-5f8b76c263e4.png)
or is there another option that CloudBeaver offers me

@devnaumov thanks for your collaboration of the links I will be attentive to your answer.

**Comment by miltonchirinos44** [comment]
> @miltonchirinos44Parece que lo que estás buscando ya está implementado. Se llama [Query Manager](https://github.com/dbeaver/cloudbeaver/wiki/Query-Manager) y está disponible en CloudBeaver Enterprise Edition. Pero si desea implementarlo a su manera, hay un servicio llamado `MainMenuService`, puede crear su propio complemento y llamar al `registerRootItem`método para agregar algún elemento específico a la barra superior.
> 
> [https://github.com/dbeaver/cloudbeaver/wiki/Plugin-system ](https://github.com/dbeaver/cloudbeaver/wiki/Plugin-system) [https://github.com/dbeaver/cloudbeaver/blob/devel/webapp/packages/plugin-top-app-bar/src/TopNavBar/MainMenu /MainMenuService.ts#L59](https://github.com/dbeaver/cloudbeaver/blob/devel/webapp/packages/plugin-top-app-bar/src/TopNavBar/MainMenu/MainMenuService.ts#L59)

@devnaumov, 
a query how can i generate new controller and view to create new menu option in main top menu.
and in this way generate a new content in the new view that is intended to be generated
Is it possible that you can explain or indicate how I can do it

![image](https://user-images.githubusercontent.com/52106718/189447886-418e3480-43ec-4e87-ab9d-7ebf78311aab.png)

**Comment by miltonchirinos44** [comment]
@devnaumov, How can I define this service `MainMenuService`, I am defining it this way
`http://10.1.4.56:8080/#/api/MainMenuService`
![servicio de cloudbeaver](https://user-images.githubusercontent.com/52106718/190450594-2edd58bf-80d9-431a-97b8-5c7e81025e5d.png)

Can you tell me if it is correct how I defined the service?

**Comment by miltonchirinos44** [comment]
@devnaumov , How can I define the service and see what data I am receiving from the service ` Query Manager`? and view by postman or another application

**Comment by devnaumov** [comment]
@miltonchirinos44 

You need to inject the ```MainMenuService``` service via dependency injection pattern as shown in the picture below. <br/>Here is a link of the implementation of the ```LogViewer``` plugin where ```MainMenuService``` is used, I reccomend you to take a look at it.
https://github.com/dbeaver/cloudbeaver/tree/devel/webapp/packages/plugin-log-viewer<br/>
We use GraphQL for the API calls, so the query for the query history will be ```getUserQueries``` (public part) and ```getAdminQueries``` (admin part) but you can call it only in the EE Edition and you need to have an opened session. The best way to test our API is using GraphQL console (api/gql/console) 


<img width="492" alt="image" src="https://user-images.githubusercontent.com/48489896/191001732-1fbeaba1-ae41-446a-985f-d3936f3d9e7f.png">

**Comment by miltonchirinos44** [comment]
@devnaumov 
I have configured the LogViewerBootstrap class in the following way
![image](https://user-images.githubusercontent.com/52106718/191341095-068cac20-6a30-4799-b891-b36368d0534b.png)

```
import { Bootstrap, injectable } from '@cloudbeaver/core-di';
import { ToolsPanelService } from '@cloudbeaver/plugin-tools-panel';
import { MainMenuService, EMainMenu } from '@cloudbeaver/plugin-top-app-bar';

import { LogViewer } from './LogViewer';
import { LogViewerService } from './LogViewerService';


@injectable()
export class LogViewerBootstrap extends Bootstrap {
  constructor(
    private readonly mainMenuService: MainMenuService,
    private readonly toolsPanelService: ToolsPanelService,
    private readonly logViewerService: LogViewerService
  ) {
    super();
  }

  register(): void {
    this.mainMenuService.registerMenuItem(
      EMainMenu.mainMenuToolsPanel,
      {
        id: 'openLogViewer',
        order: 1,
        type: 'checkbox',
        isChecked: () => this.logViewerService.isActive,
        title: 'app_shared_toolsMenu_logViewer',
        onClick: () => this.logViewerService.toggle(),
      }
    );

    this.toolsPanelService.tabsContainer.add({
      key: 'log-viewer-tab',
      order: 0,
      name: 'app_shared_toolsMenu_logViewer',
      isHidden: () => !this.logViewerService.isActive,
      onClose: () => this.logViewerService.toggle(),
      panel: () => LogViewer,
    });
  }

  load(): void { }
}
```
and I am calling the service that you indicated in the previous comment
![image](https://user-images.githubusercontent.com/52106718/191346548-6bcf5044-da0f-4d87-a6fa-c6b74667616a.png)

but I think I'm making mistakes when performing the query
or how should I use the GraphQL console?

How should I run the frontend for development, since only the backend is running in eclipse as shown in the image

![image](https://user-images.githubusercontent.com/52106718/191347273-3a5550f2-a05c-46e9-8a91-6de61548f6af.png)
or what am I doing wrong can you help me please

**Comment by miltonchirinos44** [comment]
@devnaumov
I was looking for information on how to run cloudbeaver in development mode the frontend part and it told me to execute the following command in the terminal
 `lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=localhost:8978`
but i get the following error
![image](https://user-images.githubusercontent.com/52106718/191360104-31036145-27c9-4a58-a82c-3238f714abe0.png)

![image](https://user-images.githubusercontent.com/52106718/191360229-fc03044a-8dd5-4556-8bde-9f5a151517c6.png)

![image](https://user-images.githubusercontent.com/52106718/191360882-3264310d-9fd1-4fa0-8dfc-1465f60cf155.png)

@devnaumov what do I have to do to execute the frontend or the backend to be able to visualize the services will you be able to help me

**Comment by miltonchirinos44** [comment]
@devnaumov how can I create a project similar to plugin-log-viewer and how to create the folder structure similar to the plugin-log-viewer example
![image](https://user-images.githubusercontent.com/52106718/191585628-6fbd1dbd-7b51-4796-abfa-77901d93d51d.png)
Is there a command that allows me to create that structure?

sorry for making many questions, I'm new to this cloudbeaver programming

**Comment by miltonchirinos44** [comment]
Hello, how should I add a new item in the main menu?, it will be possible that you can help me

**Comment by Wroud** [comment]
> @devnaumov how can I create a project similar to plugin-log-viewer and how to create the folder structure similar to the plugin-log-viewer example ![image](https://user-images.githubusercontent.com/52106718/191585628-6fbd1dbd-7b51-4796-abfa-77901d93d51d.png) Is there a command that allows me to create that structure?
> 
> sorry for making many questions, I'm new to this cloudbeaver programming

we don't have any toolkit for automated plugins creation
base instruction:
1. copy `.gitignore, package.json, tsconfig.json` from `plugin-connection-custom` to the new folder `plugin-new` (you can replace `new` with any name)
2. create `src` folder under it
3. create `manifest.ts` under `src` folder with following content:
```
import type { PluginManifest } from '@cloudbeaver/core-di';

export const newPlugin: PluginManifest = {
  info: {
    name: 'Your plugin name', // you can set any name
  },

  providers: [
    // you can register here your services
  ],
};

```
4. create `index.ts` in `src` folder with following content:
```
import { newPlugin } from './manifest';

export { newPlugin };
export default newPlugin;

```
5. change `name` in `package.json` file under your plugin folder
6. in `packages/product-default/package.json` add your package in dependencies `"name from previous point": "0.1.0"`
7. in `packages/product-default/src/index.ts` add your package:
  near importd add `import newPlugin from 'name from 5 point';`
  add `newPlugin` to `PLUGINS` array
8. run `lerna bootstrap` in `cloudbeaver/webapp` folder

**Comment by Wroud** [comment]
after that you need to create you own Bootstrap and Services where you can register menu item to top app bar https://github.com/dbeaver/cloudbeaver/issues/1048#issuecomment-1250924673

**Comment by miltonchirinos44** [comment]
@Wroud, thanks for the help I managed to create the plugin folder structure and register it

plugin folder structure
![image](https://user-images.githubusercontent.com/52106718/192634105-3518a576-e460-4fa4-b2b6-956ff9d0b7a2.png)

plugin registration
![image](https://user-images.githubusercontent.com/52106718/192634600-7e28b4ba-f93a-45eb-9de6-9ef3018869bb.png)

the only inconvenience I had was that, when I made the changes in vs code, error alerts appeared, but I had to close and open my vs code editor again to refresh the source code

**@Wroud, how can I create my own Bootstrap and Services, and where do I have to register the menu item in the top bar of the application, could you please tell me as you told me before**

**Comment by miltonchirinos44** [comment]
@Wroud , how can I create my Bootstrap and my service with a simple example so that I can manage the Bootstrap file and the services, could you help me with an example

**Comment by miltonchirinos44** [comment]
@Wroud , how can I test the API is using the GraphQL console (api/gql/console)?

**Comment by devnaumov** [comment]
@miltonchirinos44 We've already provided you a simple example of using Bootstrap and Services. Please take a look https://github.com/dbeaver/cloudbeaver/tree/devel/webapp/packages/plugin-log-viewer You can describe what your service suppose to do and we will try to help with the service structure.

**Comment by kseniaguzeeva** [comment]
There is no update for a long time, please fell free to contant me to reopen the ticket if it's still actual.
