### ISSUE TITLE
Can browse only custom sources

### ISSUE THREAD

**Issue by nicolamarangoni** [dbeaver/cloudbeaver#105]
**Describe the bug**
Can browse only custom sources

**To Reproduce**
- When `provided-connections.json` is filled with a datasource, the source is shown in the tree but it is not possible to connect
- When `provided-connections.json` and `data-sources.json` are filled with the same source, the source is not shown in the tree, but it is possible to connect using "CONNECTION" -> "New Connection" -> "Preconfigured". However, the source is not shown in the tree after connecting (it's possible to run SQLs in the SQL tab).
- The only way to connect and to browse object using the tree-tab is to use a "Custom" connection

**Desktop (please complete the following information):**
 - OS: CentOS7
 - Browser: Mozilla
 - Version 1.0.4

**Comment by serge-rider** [comment]
What do you mean under " not possible to connect"? Is there some authentication error?

Note: you need to put authentication configuration along with datasources configuration.
For pre-configured connections it is stored in credentials-config.json file. But you can generate it only from DBeaver Desktop.

You can also specify user name/password right in datasource config file (in plain form). Use paramaeters "user" and "password".
For example:
```json
   "postgres-jdbc-171e5ec3621-491942a29a4c8e9e": {
      "provider": "postgresql",
      "driver": "postgres-jdbc",
      "name": "My_connection",
      "save-password": false,
      "show-system-objects": true,
      "read-only": false,
      "configuration": {
	"host": "myhostname",
        "port": "5432",
        "database": "pharos_framework",
        "url": "jdbc:postgresql://myhostname:5432/mydatabase",
        "user": "user-name",
        "password": "user-password",
	"type": "dev",
	"properties": {
          "connectTimeout": "20",
          "loginTimeout": "20"
        },
	"provider-properties": {
	  "@dbeaver-show-non-default-db@": "false",
          "@dbeaver-show-template-db@": "false",
          "postgresql.dd.plain.string": "false",
          "postgresql.dd.tag.string": "false"
        },
	"auth-model": "native"
      }
    },
```

Note: we are going to improve datasource authentication in version 1.1.
User credentials will be requested in UI if they weren't specified in the configuration.
Also we plan to merge pre-configured and provided connections in the single configuration file.

**Comment by nicolamarangoni** [comment]
Thank you for your answer, I tried different combinations and the only one that works is putting clear-text passwords in `provided-connections.json`. I look forward to version 1.1!
