### ISSUE TITLE
error @csstools/postcss-sass@4.0.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0". Got "6.17.1"

### ISSUE THREAD

**Issue by 1lz** [dbeaver/cloudbeaver#108]
Following error is reported while building cloudbeaver (commit 1659d7049158a312c76f9035601684fe99cec5f2 ):

> error @csstools/postcss-sass@4.0.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0". Got "6.17.1"

**To Reproduce**
> git clone https://github.com/dbeaver/cloudbeaver.git
> cd cloudbeaver/deploy
> ./build.sh

See error:

> [INFO] ------------------------------------------------------------------------
> Copy server packages
> Build static content
> yarn install v1.22.4
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@1.2.13: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
**> error @csstools/postcss-sass@4.0.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0". Got "6.17.1"**
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Desktop (please complete the following information):**
 - OS: Centos 7
 - yarn v1.22.4
 - node v6.17.1

**Additional context**
Work-around can be to replace "yarn" with "yarn --ignore-engines" in build.sh, but I'm not sure if it's correct way to go.

**Comment by 1lz** [comment]
> Following error is reported while building cloudbeaver (commit [1659d70](https://github.com/dbeaver/cloudbeaver/commit/1659d7049158a312c76f9035601684fe99cec5f2) ):
> 
> > error @csstools/postcss-sass@4.0.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0". Got "6.17.1"
> 
> **To Reproduce**
> 
> > git clone https://github.com/dbeaver/cloudbeaver.git
> > cd cloudbeaver/deploy
> > ./build.sh
> 
> See error:
> 
> > [INFO] ------------------------------------------------------------------------
> > Copy server packages
> > Build static content
> > yarn install v1.22.4
> > [1/4] Resolving packages...
> > [2/4] Fetching packages...
> > info fsevents@1.2.13: The platform "linux" is incompatible with this module.
> > info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
> > **> error @csstools/postcss-sass@4.0.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0". Got "6.17.1"**
> > error Found incompatible module.
> > info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Centos 7
> * yarn v1.22.4
> * node v6.17.1
> 
> **Additional context**
> Work-around can be to replace "yarn" with "yarn --ignore-engines" in build.sh, but I'm not sure if it's correct way to go.

**Comment by 1lz** [comment]
Found that it's not a bug, nodejs version coming with Centos 7 is way too old. Fixed by installing latest stable release (v12.18.1 as of today) as in https://tecadmin.net/install-latest-nodejs-and-npm-on-centos/

**Comment by kseniiaguzeeva** [comment]
I'm glad you have found the decision!
