### ISSUE TITLE
Hide the GlobalConfiguration and Other folders

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#1092]
Hi,

Starting 22.1.4, i see that the connections are listed under a folder structure.
Is there a way to go back to the previous behavior....i.e. no folder structures 

![image](https://user-images.githubusercontent.com/57646596/187523240-0958b604-7da3-4744-bbe8-9c1c4b2e1cfe.png)

Thanks!

**Comment by devnaumov** [comment]
Hi!
We are going to change it. Here is an example.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/48489896/187744242-496aadf9-3606-4f0e-b0e6-3e2d2f087fb4.png">

**Comment by metalshanked** [comment]
Oh ok, will there be an option to revert to the past behavior? 
i.e. everything at the top level. Just like the demo site.


![image](https://user-images.githubusercontent.com/57646596/187765892-45db1fb9-01af-41b8-9aab-1e2419641d01.png)

**Comment by devnaumov** [comment]
It's the same for the demo. When there are shared connections, the groups are visible.
So if you have any specific issues caused by these changes, you can describe them here. The groups are not expandable, so technically, your connections will be on the top level. 

<img width="297" alt="image" src="https://user-images.githubusercontent.com/48489896/188427178-dbd5f991-53e3-4b2a-bec9-c6c5bd102b83.png">

**Comment by metalshanked** [comment]
Thanks @devnaumov for the info. I will wait for the changes you mentioned (will it be on 22.1.5 ?) and confirm.

**Comment by kseniaguzeeva** [comment]
The new Navigator tree view is available in the latest 22.2.0 release (the tree is displayed like on devnaumov's screenshot).

**Comment by metalshanked** [comment]
Thanks @kseniaguzeeva and @devnaumov. I installed 22.2.0 and wanted to check back on my original request.

I run as "allow anonymous" since i have external authentication and access control....so wanted cloudbeaver to not have the concept of shared, not shared etc.  Just like it was in 22.1.3 and older.

When the user logs in...the connections should show at top level. No "Shared" heading required.

Is this possible to achieve with 22.2.0 or any workaround ? i hate to go back to 22.1.3 
![image](https://user-images.githubusercontent.com/57646596/189040444-e2961fd1-a6df-4163-ae59-4d5a4c465ccc.png)

Thanks in advance!

**Comment by kseniaguzeeva** [comment]
We are going to hide the header, if it's the only header in the DB Navigator.

**Comment by kseniaguzeeva** [comment]
The feature is implemened in the latest 22.2.1 release:
- the project header isn't displayed, if it the only available project in the Navigator tree,
- you can hide the projects headers via the Navigator menu (press Settings button to open it and disable Group by Project tool)

**Comment by metalshanked** [comment]
Thanks @kseniaguzeeva!
One problem i am facing with the current release 22.2.1 is that the hamburger icon disappears/gets hidden when resizing the connection/left nav panel after a certain point.

![image](https://user-images.githubusercontent.com/57646596/192913176-f14d4b3e-2d63-4a2e-8f64-004b2592bdc1.png)

the hamburger menu has the crucial disconnect and reconnect option which users need to avoid the issue mentioned in 
https://github.com/dbeaver/cloudbeaver/issues/884

**Comment by kseniaguzeeva** [comment]
It's another case. Could you please create a new ticket if you want to change the behavior.

**Comment by metalshanked** [comment]
Sorry. yep, sure, will do!
