### ISSUE TITLE
Outdated Firebird driver (Jaybird) included in cloudbeaver

### ISSUE THREAD

**Issue by mrotteveel** [dbeaver/cloudbeaver#11]
Cloudbeaver currently includes Jaybird 3.0.3, which is relatively old. However, more importantly, this version does not support the wire protocol encryption of Firebird 3. This can make connecting to Firebird 3 hard, because by default Firebird 3 requires this encryption to connect.

I recommend upgrading to Jaybird 4.0.0 (or otherwise to 3.0.8). Upgrading to Jaybird 4.0.0 will also provide more support for the new data types of Firebird 4 (the second beta is expected next month).

I can also provide a pull request to replace it.

**Comment by serge-rider** [comment]
Yes, it makes sense. I think we will upgrade driver version for both DBeaver and CloudBeaver at once.

**Comment by serge-rider** [comment]
Driver updated to 4.0
