### ISSUE TITLE
Filter toggle

### ISSUE THREAD

**Issue by yoavo-datricks** [dbeaver/cloudbeaver#1145]
Hi,
Any configuration to have the filter toggle (object search) enabled by default?

Thanks

**Comment by kseniaguzeeva** [comment]
Thank you for your interest in CloudBeaver. The filter is already available in the DB Navigator toolbar. 
1. Press the Settings button to see the full menu:

![11](https://user-images.githubusercontent.com/112612526/190063581-d047fcc8-fc75-4f97-8d3e-2419587222a5.png)

2. Then enable **Filter** setting and the Search field will appear

![12](https://user-images.githubusercontent.com/112612526/190063632-212d296f-1ff2-4043-93f3-cb2f76b53496.png)

You can also enable **Show collapsed** setting: the search will look for objects in the folders which have been expanded and then collapsed.

**Comment by yoavo-datricks** [comment]
Sure. I just want it to be enabled by default via configuration. Is there a way to do that?

**Comment by kseniaguzeeva** [comment]
It's not implemented yet. We will discuss whether it can be done.

**Comment by Wroud** [comment]
You can fastly access filter by:
1. click to nav-tree
2. press Ctrl+F

**Comment by kseniaguzeeva** [comment]
I don't see any updates for a long time in this ticket. Feel free contect me to reopen the ticket if it's still actual for you.
