### ISSUE TITLE
eclipse debug problem

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1154]
![image](https://user-images.githubusercontent.com/43168824/190334694-8ef2d2af-8363-42a5-8d68-9de0d4e91c08.png)
![image](https://user-images.githubusercontent.com/43168824/190334819-c3eb1f21-eae2-403d-b3be-d87194c66dae.png)
![image](https://user-images.githubusercontent.com/43168824/190334876-9370dd0f-47cd-459c-afcc-9995a1a4126d.png)
![image](https://user-images.githubusercontent.com/43168824/190335557-56bafef0-0d20-4d4f-8542-37397bde306e.png)

**Comment by kseniaguzeeva** [comment]
Could you please any description to your ticket?

**Comment by ccczhouxin** [comment]
I import the peoject，and run ，it has that errors

**Comment by kseniaguzeeva** [comment]
Could you please describe what do you do step by step and what result do you want to receive?

**Comment by miltonchirinos44** [comment]
the dbeaver repository is failing, that is the main problem, as cloudbeaver depends on dbeaver

**Comment by miltonchirinos44** [comment]
recently dbeaver made an update regarding jdk and maven you should update as follows:

- java 11 switch to java 17
- maven 3.6.3 to 3.8.3

**Comment by kseniaguzeeva** [comment]
@ccczhouxin Have you tried the advice above from @miltonchirinos44? Have it helped?

**Comment by miltonchirinos44** [comment]
@ccczhouxin I managed to solve the problem, I already managed to correct the error that did not let me compile cloudbeaver

**Comment by ccczhouxin** [comment]
> @ccczhouxin I managed to solve the problem, I already managed to correct the error that did not let me compile cloudbeaver

How do you correct the error, and what is the version of dbeaver,cloudbeaver,java,maven

**Comment by miltonchirinos44** [comment]
maven 3.8.6 is correct

**Comment by yagudin10** [comment]
Hi, @ccczhouxin !
Did you update Java and Maven as @miltonchirinos44 advised?

> recently dbeaver made an update regarding jdk and maven you should update as follows:
> 
> * java 11 switch to java 17
> * maven 3.6.3 to 3.8.3

**Comment by kseniaguzeeva** [comment]
I close the ticket because I don't see any updates for a long time.
