### ISSUE TITLE
Development tools CloudBeaver

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1155]
Hello friends, I am new to the development of cloudbeaver, a question? What development tools do you use for cloudbeaer development, apart from eclipse?
I have noticed that with eclipse it only shows me the backend.
What tool do you recommend for me to visualize the frontend?

Or what tools do you use apart from eclipse java, for the development of cloudbeaver or do you recommend any code editor?

I currently only have this:
![eclipse cloudbeaver ejecutando](https://user-images.githubusercontent.com/52106718/190407727-49552316-27e7-4f6c-aeb4-f734d955c288.png)

**Comment by devnaumov** [comment]
Hi @miltonchirinos44! We use VS Code for the front-end development and IntelliJ IDEA for the back-end development.

**Comment by miltonchirinos44** [comment]
@devnaumov I have my backend files configured like this
![image](https://user-images.githubusercontent.com/52106718/191277365-c6deb2a7-35c0-4b9c-bab9-b9d86521e57e.png)

and my files den vscode like this
![image](https://user-images.githubusercontent.com/52106718/191277655-20fae583-2d4d-4cbc-9fe4-3f55a54fc965.png)

@devnaumov a query is it ok that in vscode I have the cloudbeaver and dbeaver folders open? or what suggestion do you suggest me

Another question I have is how can I execute the frontend separately from vscode since the backend is executed as follows in `eclipse java`
![image](https://user-images.githubusercontent.com/52106718/191279313-7b44555c-d5c4-4ac3-8d1c-8e68e5bc37eb.png)

**Comment by miltonchirinos44** [comment]
@devnaumov how to debug the front code in Visual Studio Code, could you tell me how I can do it?

**Comment by kseniaguzeeva** [comment]
Could you please tell is the ticket still actual for you? What result do you want to receive and what for? It looks very similar with https://github.com/dbeaver/cloudbeaver/issues/1175.

**Comment by miltonchirinos44** [comment]
@kseniaguzeeva 

In ticket #1155 you only needed to know what tools were used for cloudbeaver development, this question is about software, and the question I have with this ticket is how to debug cloudbeaver source code with `visual studio code`

In ticket #1175 I need to compile the cloudbeaver project in development mode and make changes that are displayed in real time, since when I run cloudbeaver from eclipse it does not let me debug the frontend, I need help with this ticket, I understand that I should raise the cloudbeaver server with the port (3100)
 http://localhost:3100 with the following command `lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=localhost:8978`, successfully launch the project. the problem is that i can't debug with visual studio code.

**Comment by devnaumov** [comment]
@miltonchirinos44 To run and debug the frontend in visual studio code you need to open the CloudBeaver project in vs code, run backend, run frontend by executing the following command ```lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=localhost:8978``` (please make sure that your backend is running on the 8978 port), open localhost:3100, open any file in cloudbeaver/webapp/packages directory, make some changes and you will see that your project rebuilds itself

**Comment by miltonchirinos44** [comment]
@devnaumov , let me tell you that I managed to run CloudBeaver in development mode, make some changes and verify that the project rebuilds itself.

How could I run cloudbeaver in development mode in` visual studio code` and debug code using breakpoints because when I run cloudbeaver in development mode and add breakpoint in `visual studio code`, visual studio code does not honor breakpoints
![image](https://user-images.githubusercontent.com/52106718/196447734-a6405524-10b8-4c0d-a323-32f98fe61fd8.png)

**Comment by devnaumov** [comment]
@miltonchirinos44 HI! Could you try to console.log something and check if it works? We need to make sure that your app rebuilds and changes are applied. Make your changes, save the file, open the CloudBeaver and check the console.

**Comment by miltonchirinos44** [comment]
@devnaumov I have problems with enabling cloudbeaver dev mode when I run the command

`lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=localhost:8978 `

i have mistakes


![1](https://user-images.githubusercontent.com/52106718/203802605-e6f00a9b-f86e-449b-892d-671640d75ca1.png)

```
$ lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=http://localhost:8978
info cli using local version of lerna
lerna notice cli v5.5.4
lerna info versioning independent
lerna notice filter including "@cloudbeaver/product-default"
lerna info filter [ '@cloudbeaver/product-default' ]
lerna info Executing command in 1 package: "yarn run dev -- --env server=http://localhost:8978"
lerna success run Ran npm script 'dev' in 1 package in 0.4s:
lerna success - @cloudbeaver/product-default
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
(node:4380) UnhandledPromiseRejectionWarning: Error: Command failed with UNKNOWN: yarn run dev -- --env server=http://localhost:8978
spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at execa (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\execa\index.js:83:26)
    at spawnProcess (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\child-process\index.js:127:17)
    at Object.spawnStreaming (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\child-process\index.js:67:19)
    at npmRunScriptStreaming (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\npm-run-script\npm-run-script.js:26:23)
    at RunCommand.runScriptInPackageStreaming (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\run\index.js:302:12)
    at C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\run\index.js:141:23
    at C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\run-topologically\run-topologically.js:34:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I could check the error, check with all versions of cloudbeaver and I get the same error

**Comment by kseniaguzeeva** [comment]
I've noticed there is no updates for a long time. Feel free to contact me to reopen the ticket if it's still actual.
