### ISSUE TITLE
 Connect cloudbeaver with Ldap, openLap or AD windows server

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1156]
Hello friends how can I configure and connect cloudbeaver with Ldap, OpenLDAP or AD windows server

**Comment by kseniaguzeeva** [comment]
CloudBeaver EE supports following authentication methods: OpenID, AzureAD, SAML, AWS. CloudBeaver CE doesn't support any of them.
You can find here https://github.com/dbeaver/cloudbeaver/issues/341 the related ticket.
I close this ticket as the duplicate.
