### ISSUE TITLE
How to add duckDB driver so that add a duckDB connection.

### ISSUE THREAD

**Issue by zengyijian916** [dbeaver/cloudbeaver#1159]
**Is your feature request related to a problem? Please describe.**

There is no duckDB driver while I want to add a duckDB connection.

**Describe the solution you'd like**

I want there is a buildin duckDB driver for user can add duckDB connection, or have a document to describe how can user add a new driver they need.

I have refered this document:  https://cloudbeaver.io/docs/Driver-management/
======
Adding a new driver to the server
Enabled drivers are configured in the file, server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml.
You can copy an existing driver configuration to add a new one.
======
In this section, I can not found server/bundles directory in cloudbeaver container.

Is there any more practical document to refer.

Many thanks!!!

**Comment by kseniaguzeeva** [comment]
Could you please try to use [this instruction](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers).
Feel free to contact me to reopen the ticket if you have any other questions.
