### ISSUE TITLE
Build & Deploy Ubuntu 22.04

### ISSUE THREAD

**Issue by DerGrumpf** [dbeaver/cloudbeaver#1163]
The Build process Fails when using the wiki instructions! Only tested on Ubuntu 22.04!

The Problem are the Dependencies. 
A better way to do would be:

sudo apt install openjdk-17-jdk maven npm -y

then install Node.js from external PPA:

curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install nodejs -y

Now install yarn from the npm repo alongside with lerna:
sudo npm install --global yarn lerna

then do the rest of the build and its works!

**Comment by miltonchirinos44** [comment]
??¿¿ @DerGrumpf 
I can't understand what it means. I don't know if it's a question or a contribution?

**Comment by devnaumov** [comment]
@DerGrumpf Thanks for your suggestion but I am not sure that the problem is our instruction. Could you provide any logs of your build process?

**Comment by kseniaguzeeva** [comment]
I don't see any updates for a long time in this ticket. Feel free contact me to reopen the ticket if it's still actual for you.
