### ISSUE TITLE
 Generate new files in deploy

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1166]
How can I generate new files in the `deploy` folder after making changes?

**Comment by devnaumov** [comment]
@miltonchirinos44  Please provide more information about the issue. What are you trying to achieve and what difficulties you are facing?

**Comment by miltonchirinos44** [comment]
@devnaumov 
I am trying to change the default database (H2) to POSTGRESQL.
I managed to make the modification (https://github.com/dbeaver/cloudbeaver/issues/1148#issuecomment-1251232083) but only in the compiled files that are in the `deploy` folder.
When I run the following commands to deploy and build the app:
```
cd cloudbeaver/deploy
./build.sh
```
the modifications you make are deleted, I understand that this happens because you make the modifications in the compiled files that are in the `deploy ` folder. My question is the following, which file do I have to modify on the backend side so that my changes remain permanently? once you run the following command
```
cd cloudbeaver/deploy
./build.sh
```
so that my configuration persists

**Comment by alexander-skoblikov** [comment]
Answered here https://github.com/dbeaver/cloudbeaver/issues/1148#issuecomment-1256393689

**Comment by miltonchirinos44** [comment]
Thanks I managed to solve the problem
