### ISSUE TITLE
Change request URL

### ISSUE THREAD

**Issue by fredpan** [dbeaver/cloudbeaver#1168]
How can I configure the app so that I can change webpage request destination (URL)?

To this end, all requests were sent to `http://localhost:8978/api/gql` by default. How can I change it to, saying, `http://google.com:8978/api/gql`?

The reason I want to do that is I want to redirect all requests frontend sent to my own server to preprocess before the requests actually reach the backend.

I've tried the `serverHost` in `cloudbeaver.conf` file, but nothing happened.

Certainly, using nginx or httpd works, but this increase network redundancy, which is not desired.

Any help would be appreciated.

Thanks

**Comment by miltonchirinos44** [comment]
@fredpan , how do you enable http://localhost:8978/api/gql ?
![image](https://user-images.githubusercontent.com/52106718/191779743-7d02edfe-ad9e-40f2-be35-840f5348ae04.png)

**Comment by fredpan** [comment]
> @fredpan , how do you enable http://localhost:8978/api/gql ? ![image](https://user-images.githubusercontent.com/52106718/191779743-7d02edfe-ad9e-40f2-be35-840f5348ae04.png)

localhost:8978 is just an address I used during development. By defualt the CB is running on port 8978 anyway.

**Comment by miltonchirinos44** [comment]
@fredpan , how can you compile the frontend I tell you that I can't get to this part?

**Comment by zzskxs** [comment]
Hello, I would like to ask you how you changed the default request? 

> How can I configure the app so that I can change webpage request destination (URL)?
> 
> To this end, all requests were sent to `http://localhost:8978/api/gql` by default. How can I change it to, saying, `http://google.com:8978/api/gql`?
> 
> The reason I want to do that is I want to redirect all requests frontend sent to my own server to preprocess before the requests actually reach the backend.
> 
> I've tried the `serverHost` in `cloudbeaver.conf` file, but nothing happened.
> 
> Certainly, using nginx or httpd works, but this increase network redundancy, which is not desired.
> 
> Any help would be appreciated.
> 
> Thanks
