### ISSUE TITLE
new database

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1174]
Hello，our database not in dbeaver on github,，whether we can use cloudbeaver

**Comment by kseniaguzeeva** [comment]
Thank you for the interest in CloudBeaver. Here you can find [the instruction](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers) to add new drivers .

**Comment by miltonchirinos44** [comment]
?¿, your comment is not understood
