### ISSUE TITLE
start the project in development mode

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1175]
Hello, a query how I can start the project in development mode, I found documentation that talks about it but executing the command ` lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=http://backend.server:8095`running inside the `cloudbeaver/webapp` folder, it fails to launch the project in development mode.

Objective: to debug the project and make changes that are displayed in real time.
As a reference I have the following link provided by the community https://github.com/dbeaver/cloudbeaver/wiki/Plugin-system

Run the command but I get the following error
![image](https://user-images.githubusercontent.com/52106718/191603424-b1a869ea-b04f-4d60-a6b1-7a3b5b0fb0b8.png)

Execution: These are the pages I should be able to get to once I run the command
![image](https://user-images.githubusercontent.com/52106718/191603710-516f7a5d-c5b3-4f67-9cc9-82f20c29d833.png)
![image](https://user-images.githubusercontent.com/52106718/191603896-7914d058-bbff-45f4-8545-4fd86102da52.png)

It will be possible that they can help me to raise the project in development mode.

**Comment by miltonchirinos44** [comment]
I have the following error when executing the following command from the console
`lerna run dev --stream --scope=@cloudbeaver/product-default -- -- env server=localhost:8978`

![image](https://user-images.githubusercontent.com/52106718/192042701-1d6aaa7c-b210-4afe-a572-3996eed146ae.png)

![image](https://user-images.githubusercontent.com/52106718/192042970-52555a64-3f5d-4697-a531-deb5c60ee3d8.png)

**Comment by Wroud** [comment]
`lerna run dev --stream --scope=@cloudbeaver/product-default -- -- env server=http://localhost:8978/`
please try this command

**Comment by miltonchirinos44** [comment]
@Wroud  thanks i managed to solve the problem

**Comment by miltonchirinos44** [comment]
@Wroud , I am reopening the ticket because with the command lerna run dev --stream --scope=@cloudbeaver/product-default -- -- env ​​server=localhost:8978, it does not allow me to view, run a development build that watch for file changes and rebuilds.
How can I run cloudbeaver to do a development build that looks at file changes and rebuilds.
@Wroud , how do you run the frontend in development mode

**Comment by devnaumov** [comment]
@miltonchirinos44 It's pretty strange because ```lerna run dev --stream --scope=@cloudbeaver/product-default -- -- env ​​server=localhost:8978``` command runs CloudBeaver in dev mode and rebuilds the app if there are changes. Please provide more information about the issue. You can record the screen for example.

**Comment by miltonchirinos44** [comment]
@devnaumov, I got confused explaining the problem I'm having. The command `lerna run dev --stream --scope=@cloudbeaver/product-default -- -- env ​​​​server=localhost:8978 `if you run cloudbeaver in development mode and rebuild the application when there are changes to port 3100, as seen in the image
![image](https://user-images.githubusercontent.com/52106718/196442839-cd981395-68ac-4a1c-8378-8f4e2b857509.png)

the problem I have is that I cannot execute and debug the source code through `visual studio code`, even though I add breakpoints when I run the application it does not stop where the breakpoints are located

![image](https://user-images.githubusercontent.com/52106718/196443744-ec9f2907-9a66-43f3-b8b6-38899c088b44.png)

Is there a way to run and debug cloudbeaver source code using breakpoints in development mode using visual studio code? or what steps do I have to follow to carry out this source code debugging process using breakpoints

**Comment by miltonchirinos44** [comment]
So far I don't get an answer on how I can debug cloudbeaver using breakpoint from visual studio code **(FRONTEND)**

**Comment by miltonchirinos44** [comment]
So far I don't get any answer on how to debug Cloudbeaver using visual studio code breakpoint (Frontend)

**Comment by miltonchirinos44** [comment]
Configure visual studio code with the configuration that you have to debug with launch.json but when I add the breakpoints it does not stop at compile time and also it should be mentioned that it does not rebuild the project with the new modifications

**Comment by miltonchirinos44** [comment]
Cloudbeaver development mode doesn't work when running the following:

`lerna run dev --stream --scope=@cloudbeaver/product-default -- -- env server=http://localhost:8978/`
 
due to the new updates they made regarding java 17 and maven 3.8.6

Please check the error

Note:
mention that before the update the command to run cloudbeaver development mode worked

**Comment by miltonchirinos44** [comment]
res
