### ISSUE TITLE
Where is the string array that contains the names of the main menu and submenu?

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1180]
Hello friends
in which part of the source code can I find the array that contains the names of the submenu menu
![image](https://user-images.githubusercontent.com/52106718/192363943-ba6460de-306f-4d6f-a687-06e702ca4e37.png)

**Comment by kseniaguzeeva** [comment]
The issue seems to be related to https://github.com/dbeaver/cloudbeaver/issues/1180. Could you add your question as a comment there?
I am closing this ticket as a duplicate.
