### ISSUE TITLE
Connection hamburger icon hidden on resize

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#1190]
On the current release 22.2.1, I see that the hamburger icon disappears/gets hidden when resizing the connection/left nav panel after a certain point.

![image](https://user-images.githubusercontent.com/57646596/192913176-f14d4b3e-2d63-4a2e-8f64-004b2592bdc1.png)

the hamburger menu has the crucial disconnect and reconnect option which users need to avoid the issue mentioned in 
https://github.com/dbeaver/cloudbeaver/issues/884

**Comment by kseniaguzeeva** [comment]
Thank you for the report. We will fix it.

**Comment by kseniaguzeeva** [comment]
The fix is available in the latest release 22.3.0
