### ISSUE TITLE
Delimiter Support

### ISSUE THREAD

**Issue by boredjo** [dbeaver/cloudbeaver#1194]
**Is your feature request related to a problem? Please describe.**
Currently I get an error when using the `DELIMINATOR` statement like this:

```
DELIMITER $$
DROP TRIGGER IF EXISTS filter $$


Error executing query:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for
the right syntax to use near 'DELIMITER $$' at line 1
```

**Describe the solution you'd like**
I would like CloudBeaver to behave like DBeaver. So the `DELIMINATOR` sets the deliminator to something else for the script. A different color would also be nice.

This is similar to [this ](https://github.com/dbeaver/dbeaver/issues/301)feature request at the DBeaver repositroy

**Comment by kseniaguzeeva** [comment]
Thank you for the suggestion. We will add delimiter support.

**Comment by dariamarutkina** [comment]
Hello, @boredjo !
We added delimiter support in the 23.2.4 version, thank you for your interest in CloudBeaver!
