### ISSUE TITLE
Oracle Package Body Support

### ISSUE THREAD

**Issue by hmmftg** [dbeaver/cloudbeaver#1196]
**Is your feature request related to a problem? Please describe.**
In Oracle db we have a lot of pl/sql packages which have package spec and package body, for now cloudbeaver just displays package spec and most of times we need to view/edit package body.
Also search for such objects is hard by now, we have to scroll all objects to find desired one.

**Describe the solution you'd like**
as we use dbeaver it's normal thing to display package spec and body together .
provide search object menu to search for objects by name, type, date altered and etc.

**Comment by kseniaguzeeva** [comment]
Thank you for the suggestion. We will implement Package body display.
Regarding the Search: name search is available in the Navigator toolbar. You should open the Settings menu and enable it.

![n_se](https://user-images.githubusercontent.com/112612526/194061348-ef44b638-6385-43f7-8821-e357533fbdb7.png)

Also you may also use Ctrl+F shortcut.

**Comment by MarinaVorobeva21** [comment]
Fixed 22.3.3
