### ISSUE TITLE
System tables, indexes, sequences and data types shown in Firebird database

### ISSUE THREAD

**Issue by mrotteveel** [dbeaver/cloudbeaver#12]
Cloudbeaver shows the system tables, indexes, sequences and data types of a Firebird database.

For comparison, DBeaver does not show (most) system object (with the exception of sequences, and - in Firebird 3 - the tables with the `SEC$` prefix).

**To Reproduce**
1. Open a Firebird database
2. Expand tables
3. Observe that tables with `RDB$`, `MON$` and `SEC$` prefix are listed
4. Expand indexes
5. Observe that indexes with `RDB$INDEX` prefix are listed, which are from indexes on system tables (the ones with `RDB$PRIMARY<number>`, `RDB$FOREIGN<number>`, or `RDB$<number>` back unnamed primar/foreign/unique key constraints)
6. Expand Sequences
7. Observe that sequences with `RDB$` and `SQL$` prefix are listed (note: DBeaver does the same), these are either sequences of system tables, or the sequences used to back Firebird 3 identity columns (generated by default as identity)
8. Expand Data Types
9. Observe that data types (domains) with `RDB$` prefix are listed (these are internal domain types linked to a single column)

**Possible solution**

- Tables can be filtered out using the `RDB$SYSTEM_FLAG` in the `RDB$RELATIONS` table (`0` or `null` means user object, `1` means system object)
- Indexes can be filtered out using the `RDB$SYSTEM_FLAG` in the `RDB$INDICES` table (`0` or `null` means user object, `1` means system object)
- Sequences can be filter out using the `RDB$SYSTEM_FLAG` in the `RDB$GENERATORS` table (`0` or `null` means user object, `1` means system object, `6` means sequence backing an identity column)
- Data types can be filtered by ignoring types with the value in `RDB$FIELD_NAME` of `RDB$FIELDS` starting with `RDB$`. These are the 'unnamed' domains of columns using a standard type.

**Screenshots**
![image](https://user-images.githubusercontent.com/5352689/79969332-a618f800-8491-11ea-852a-299e1b60bde7.png)
![image](https://user-images.githubusercontent.com/5352689/79969443-d19be280-8491-11ea-8b14-8a46be03869d.png)
![image](https://user-images.githubusercontent.com/5352689/79969662-14f65100-8492-11ea-9b7e-8db0f08315e3.png)
![image](https://user-images.githubusercontent.com/5352689/79969727-2f302f00-8492-11ea-8941-f8b65c0c7adc.png)

**Comment by serge-rider** [comment]
In fact this behavior is configurable in both DBeaver and CloudBeaver. It is "show-system-objects" config parameter. I will disable it for CB by default.

**Comment by serge-rider** [comment]
Generally we need to add extra connection configuration in CB. 
Similarly to DBeaver.

**Comment by mrotteveel** [comment]
Thanks. I wasn't even aware of the 'Show system object' option in DBeaver.

**Comment by serge-rider** [comment]
We'll track connection config improvements in separate tickets. 
So closing this one.
