### ISSUE TITLE
Installation/Configuration problem on centos 7.6

### ISSUE THREAD

**Issue by pojoguy** [dbeaver/cloudbeaver#120]
I built and deployed cloudbeaver according to the instructions at https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy.

export CLOUDBEAVER_HOME is set to .../cloudbeaver/deploy/cloudbeaver

When I launch it, I can see it is running in the terminal (see screenshot from terminal below)

However, from the browser all I get is a view into a / directory (see screenshot from browser below)

Please advise.

![Annotation 2020-07-15 120950](https://user-images.githubusercontent.com/46756720/87574565-2a93a500-c694-11ea-9309-d31fda8708f3.jpg)
![Annotation 2020-07-15 120951](https://user-images.githubusercontent.com/46756720/87574658-5151db80-c694-11ea-8871-d0bf068bbb44.jpg)

**Comment by serge-rider** [comment]
Is this still an issue?
There were several changes in the build process recently.

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen if it is still actual for you.
