### ISSUE TITLE
Performance degradation in case of SQLite JSON fields with size ~1 MB

### ISSUE THREAD

**Issue by YuraKril** [dbeaver/cloudbeaver#1201]
**Describe the bug**
Performance degradation
The computer lags.
Table view not work 

![image](https://user-images.githubusercontent.com/4184026/194374951-23b4ccfa-eeb3-490a-934c-b82490029f22.png)

**To Reproduce**
1. Create a new SQLite database file with at least one JSON field.
2. Insert some rows of data.
3. Try to open the database file 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Chrome
 - Version 106.0.5249.91 (Official Build) (64-bit)

**Comment by kseniaguzeeva** [comment]
Could you please add more details about your issue? Do I understand right, you have an SQLite table with a big JSON value in a column? Could you please provide me with a table DDL and JSON value examples?

It will help me to find a reason and give better assitance to you.

**Comment by YuraKril** [comment]
I created a table with two columns and five rows in it (each one 2MB). I provide an example of the database in the attachment. 
[example.txt](https://github.com/dbeaver/cloudbeaver/files/9783268/example.txt)

**Comment by kseniaguzeeva** [comment]
Thank you for the example. I have bad perfomance when open the Value panel for a JSON value from your example.

**Comment by YuraKril** [comment]
if the table has more than 1k records, no data is displayed at all.

Also, you don't always need to load 200 rows. This value can be set in the settings or change the default to 50 rows.
![image](https://user-images.githubusercontent.com/4184026/195852648-abefdb7a-a3ef-43ac-b590-2e04e4d9670a.png)

**Comment by kseniaguzeeva** [comment]
We've improved JSON display in 22.2.4:
- The size of displayed JSON values is limited and you can change the limit in the configuration file `sqlBinaryPreviewMaxLength`
- you can change the limit of cell values in the Data Editor in the configuration file `sqlTextPreviewMaxLength` (the detailed information is heree https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration)
- big JSON values can be saved to an external file
