### ISSUE TITLE
access denied to view cloudbeaver graphql terminal

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1213]
I am trying to display the cloudbeaver graphql terminal to query and display, the problem I have is that when I perform a graphql query it sends me an access denied message

![image](https://user-images.githubusercontent.com/52106718/195179377-7af93bdc-53ab-42e5-8c23-8d789d965fb4.png)

- I am using a chrome extension to display the graphql terminal "playground"
![image](https://user-images.githubusercontent.com/52106718/195179665-8c43fec5-f8ce-42ff-8171-3492a5267fcc.png)

- I have cloudbeaver running in development mode on server localhost:3100 and also on eclipse localhost:8978

port 3100
![image](https://user-images.githubusercontent.com/52106718/195180298-ed9e5ac4-d297-4172-8860-8150fd31adba.png)

port 8978
![image](https://user-images.githubusercontent.com/52106718/195180229-cdcd89cf-5ddd-4469-a691-b56d024f7fbd.png)

- I am using the url (http://127.0.0.1:3100/api/gql) to display the graphql terminal

can you help me visualize the graphql terminal, maybe I'm forgetting to configure some line of code or enable some instruction, I'm working on windows, I'm running the program from eclipse java

**Comment by kseniaguzeeva** [comment]
It seems, that the question is related to https://github.com/dbeaver/cloudbeaver/issues/1200. Could you please add the question there by a comment?
I close this ticket as the duplicate.

**Comment by miltonchirinos44** [comment]
So far I'm still having problems accessing queries in the cloudbeaver graphQL terminal.
