### ISSUE TITLE
Migration function

### ISSUE THREAD

**Issue by zzskxs** [dbeaver/cloudbeaver#1215]
Hello, I'd like to know when CloudBeaver can have the migration function

**Comment by kseniaguzeeva** [comment]
Could you please describe in details, what feature would you like to have?
Thank you in advance.

**Comment by zzskxs** [comment]
MySQl data is migrated to Oracle.
What I want is for different databases to migrate to each other

**Comment by kseniaguzeeva** [comment]
We are not going to add this tool in the near future to CloudBeaver. But the tool already exists in DBeaver Enterprise. Could you please try to use it for migration https://dbeaver.com/download/enterprise/?

**Comment by zzskxs** [comment]
thanks
