### ISSUE TITLE
can not start dbeaver

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1226]
I want use dbeaver and cloudbeaver ，but the eclpise can not start 
![image](https://user-images.githubusercontent.com/43168824/196870865-8a361b22-d96a-4378-a408-985ffe42b8a9.png)
![image](https://user-images.githubusercontent.com/43168824/196871037-b06ff680-bdba-40ed-8555-8faf60951f9f.png)

**Comment by miltonchirinos44** [comment]
@ccczhouxin This error is due to problems with the dbeaver source code, I already indicated the error, but it would be good if you request a ticket in the dbeaver group

**Comment by ccczhouxin** [comment]
> @ccczhouxin This error is due to problems with the dbeaver source code, I already indicated the error, but it would be good if you request a ticket in the dbeaver group

ok，i already do it in the last days

**Comment by kseniaguzeeva** [comment]
@ccczhouxin Is this ticket still actual for you?

**Comment by ccczhouxin** [comment]
> @ccczhouxin Is this ticket still actual for you?

Yes,still that error

**Comment by kseniaguzeeva** [comment]
Could you please try to findan answer in the ticket https://github.com/dbeaver/cloudbeaver/issues/630

**Comment by oksana-cherniavskaia** [comment]
@ccczhouxin Hello.

Try to open plugins tab and click select required, maybe some of them missing.
Also make sure after that org.jkiss.dbeaver.sl4j is not include.


<img width="1095" alt="selectRequired" src="https://user-images.githubusercontent.com/114406033/198639735-166d0f4b-1c89-4544-b7ae-af30cd24ab4c.png">

<img width="1100" alt="noSl4j" src="https://user-images.githubusercontent.com/114406033/198639898-108efeb4-97e2-461e-9586-292cc97dcce4.png">

**Comment by ccczhouxin** [comment]
> @ccczhouxin Hello.
> 
> Try to open plugins tab and click select required, maybe some of them missing. Also make sure after that org.jkiss.dbeaver.sl4j is not include.
> 
> <img alt="selectRequired" width="1095" src="https://user-images.githubusercontent.com/114406033/198639735-166d0f4b-1c89-4544-b7ae-af30cd24ab4c.png">
> 
> <img alt="noSl4j" width="1100" src="https://user-images.githubusercontent.com/114406033/198639898-108efeb4-97e2-461e-9586-292cc97dcce4.png">
Hello,I click select required,and slf4j is not include.Also has this error 
![image](https://user-images.githubusercontent.com/43168824/198915849-64778596-035f-4f6c-af38-e525c10753bd.png)
![image](https://user-images.githubusercontent.com/43168824/198915988-52360737-c3dc-4aff-aedd-716721b1cbb2.png)
![image](https://user-images.githubusercontent.com/43168824/198916086-e4973f77-c397-4870-bbe8-66df528fdbaa.png)

**Comment by ccczhouxin** [comment]
> Could you please try to findan answer in the ticket #630

Hello,this seems different from what you sent

**Comment by miltonchirinos44** [comment]
@ccczhouxin , I had the same error, what you have to do is do a migration of the JDK from 11 to 17

**Comment by ccczhouxin** [comment]
> @ccczhouxin , I had the same error, what you have to do is do a migration of the JDK from 11 to 17
Now,i still had the error with dbeaver

**Comment by miltonchirinos44** [comment]
@ccczhouxin tienes que eliminar los archivos que genera eclipse java cuando ejecutas cloudbeaver, los archivos se encuentran en tu carpeta personal y seguramente están con los nombres:

- runtime-DBeaver.product
- runtime-DBeaverWebServer.product

**Comment by yagudin10** [comment]
Hi, @ccczhouxin !
I've tried to start DBeaver with this article https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse and couldn't reproduce this error. Have you tried to run the new version of app?

**Comment by ccczhouxin** [comment]
> Hi, @ccczhouxin ! I've tried to start DBeaver with this article https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse and couldn't reproduce this error. Have you tried to run the new version

**Comment by Amor7527** [comment]
Hello, I have encountered the same error as you, if you have time, can you tell me how to solve this problem

https://github.com/dbeaver/cloudbeaver/issues/1335,

**Comment by Amor7527** [comment]
> I want use dbeaver and cloudbeaver ，but the eclpise can not start ![image](https://user-images.githubusercontent.com/43168824/196870865-8a361b22-d96a-4378-a408-985ffe42b8a9.png) ![image](https://user-images.githubusercontent.com/43168824/196871037-b06ff680-bdba-40ed-8555-8faf60951f9f.png)

你好, 我遇到了和你一样的错误, 如果有时间是否可以告知我是如何解决这个问题的

https://github.com/dbeaver/cloudbeaver/issues/1335

**Comment by ccczhouxin** [comment]
> Hello, I have encountered the same error as you, if you have time, can you tell me how to solve this problem
> 
> #1335,

I had not use dbeaver some time，i don not solve this problem。

**Comment by miltonchirinos44** [comment]
Did you manage to solve the problem?, did you manage to start dbeaver? or managed to start cloudbeaver?
