### ISSUE TITLE
Unable to see connections List even when there are connections

### ISSUE THREAD

**Issue by tarunlalwani** [dbeaver/cloudbeaver#1241]
**Describe the bug**
Unable to see Connections List in the administration

**To Reproduce**
1. Go to Settings->Administration
2. Click on Connection Management
3. Unable to see connections, even though connections are visible and working in the app

**Screenshots**

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5294143/198052028-08bf6ba0-fdcb-4be8-8d44-776fc2f2738b.png">

**Desktop (please complete the following information):**
 - OS: MacOs 12.6
 
 - Browser : Chrome
 - Version : 22.2.3 (tried till 22.1.4)

**Additional context**

Ran using below command

```bash
docker run -it --env-file .env --entrypoint '' -v $PWD/data/workspace:/opt/cloudbeaver/workspace/ -p 8090:8978 dbeaver/cloudbeaver:22.1.4 bash
```

As seen in the screenshot, there is a connection of MSSQL server showing in the API response but the UI doesn't display the same. It only shows the default template connection

**Comment by miltonchirinos44** [comment]
@tarunlalwani 
 I have the same error, either in the cloudbeaver docker and in the cloudbeaver source code, please verify the error, it does not list the connections that have been configured

**Comment by kseniaguzeeva** [comment]
Could you please check what project your connections relate too? 
CloudBeaver has two projects: the Private (available for the current user only) and the Shared (access can be granted to other users by administrators). Connection Management tab shows only the list of connections for the Shared project, hovewer, administrators can create connections for both projects in this tab.

Connections for the Private projects are displayed in the Navigator tree.

https://user-images.githubusercontent.com/112612526/198271441-7c0a1130-5b06-47c1-af29-f3387eb969c0.mp4

**Comment by miltonchirinos44** [comment]
As much as I create the connections in the `Connection Management` administration menu, it is not possible to display the list of connected databases,  there are already two errors, one the construction of the cloudbeaver project and this last the display of the list of connected databases

**Comment by tarunlalwani** [comment]
@kseniaguzeeva , it was not very obvious initially that the default connection is private

<img width="661" alt="image" src="https://user-images.githubusercontent.com/5294143/201110774-864afc13-24e1-4366-93d2-fbb2d1d257fe.png">

That is why it is not very obvious

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5294143/201111011-a487685b-1119-4b26-9272-5e74da22c3d6.png">

My suggestion is the above screen should say Shared Connections and have a note that private connections are not listed on this to avoid any confusion

**Comment by miltonchirinos44** [comment]
@kseniaguzeeva thanks for the help, it would be nice if the default connection is "shared" and not private

**Comment by kseniaguzeeva** [comment]
Thank you for your idea. We will discuss the possibility of its implementing.

**Comment by miltonchirinos44** [comment]
This ticket should be closed and the problem has been solved and clarified

**Comment by kseniaguzeeva** [comment]
The Shared project is selected by default, when the connection is created in the Administration menu in the latest release 22.3.1.
