### ISSUE TITLE
How to enable HTTPS on CloudBeaver (Docker)

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/cloudbeaver#1246]
Hi,

i am just trying CloudBeaver latest version 22.2.3 using the provided docker image.

How can I configure the docker image to use HTTPS instead of plain HTTP?

Cheers,
James

**Comment by kseniaguzeeva** [comment]
Could you please try to configure Nginx for it? Here is the article https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-and-Nginx

To enable Reverse proxy via local configuration file, set the parameter in .cloudbeaver.runtime.conf
```
 "enabledAuthProviders": [
      "local",
      "reverseProxy"
    ]
```

**Comment by kseniaguzeeva** [comment]
I've noticed there is no updates for a long time. Feel free to contact me to reopen the ticket if it's still actual.
