### ISSUE TITLE
Pre-configured connections - role access.

### ISSUE THREAD

**Issue by YuraKril** [dbeaver/cloudbeaver#1261]
_Pre-configured connections
The configuration is located in ${WORKSPACE}/GlobalConfiguration/.dbeaver/data-sources.json_

Is it possible to specify which role or user will have access to these connections via data-sources.json?
if not, then this would be a very useful option in the future

**Comment by kseniaguzeeva** [comment]
You can do it in UI by the following way:

1. GlobalConfiguration keeps connections of the Shared project (you can find the project name in the connection dialog)

![1](https://user-images.githubusercontent.com/112612526/200864947-210963c4-8e5b-4af8-9c68-c8d27b1b1d4e.png)

2. Go to the Access tab of a Shared connection and press the Edit button. 

![2](https://user-images.githubusercontent.com/112612526/200865263-72cc9c02-7292-468c-b521-4fe336ab5c06.png)

You will see the list of available teams and users and can give access to the connection to any of them.

Or do you want to configure the access via configuration file?

**Comment by YuraKril** [comment]
Yes, I want to configure the access via configuration file.
I need to make a lot of connections. And editing each through the user interface takes a very long time.

**Comment by kseniaguzeeva** [comment]
Thank you for your feature request. We can implement it in future milestones.

**Comment by YuraKril** [comment]
Do you have any updates on this?

**Comment by MarinaVorobeva21** [comment]
Hello @YuraKril ,
this feature will be implemented after 23.0.0 milestone.
Thank you for your interest in CloudBeaver.

**Comment by EvgeniaBzzz** [comment]
Hi, @YuraKril 
Access permissions can be specified for pre-configured connections via the configuration file.
Instruction:
https://github.com/dbeaver/cloudbeaver/wiki/Pre%E2%80%90configured-permissions-for-connections

**Comment by alternaivan** [comment]
Hi @EvgeniaBzzz,

I tested this out in my setup, with the configuration file you've provided, but it seems not to work. Does this apply also to users in the *user* role?

Is there some missing configuration that is needed here in perhaps product.conf or somewhere else?

Thanks in advance!

Kind regards,
Marjan
