### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by killerwzb** [dbeaver/cloudbeaver#127]
Hi,

I want build front by this :
following:
Development
Run local server as it described in Build and deploy section
Execute
cd webapp/packages/dbeaver
yarn run dev --server=localhost:8978

But i can not find this path as " webapp/packages/dbeaver"

**Comment by killerwzb** [comment]
I run the yarn run dev --server=localhost:8978 at  cloudbeaver\webapp\packages\product-default
get this error, following:
    Entrypoint mini-css-extract-plugin = *
    [../../node_modules/css-loader/dist/cjs.js?!../../node_modules/postcss-loader/src/index.js?!../../node_modules/sass-loader/dist/cjs.js?!../plugin-ag-grid/src/styles/base.scss] F:/clouddbeaver/test/cloudbeaver/webapp/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-2-1!F:/clouddbeaver/test/cloudbeaver/webapp/node_modules/postcss-loader/src??ref--5-oneOf-2-2!F:/clouddbeaver/test/cloudbeaver/webapp/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-2-3!../plugin-ag-grid/src/styles/base.scss 369 KiB {mini-css-extract-plugin} [built]
    [../../node_modules/css-loader/dist/runtime/api.js] F:/clouddbeaver/test/cloudbeaver/webapp/node_modules/css-loader/dist/runtime/api.js 2.46 KiB {mini-css-extract-plugin} [built]
i ｢wdm｣: Compiled successfully.
[HPM] Error occurred while trying to proxy request /dbeaver/gql from localhost:3100 to localhost:8978 (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by Wroud** [comment]
Hi, please try this:
```
cd webapp/
lerna bootstrap
lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --server=localhost:8978
```

**Comment by killerwzb** [comment]
> Hi, please try this:
> 
> ```
> cd webapp/
> lerna bootstrap
> lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --server=localhost:8978
> ```

Hi，i try to do this and type the url like as localhost:3100 to visit the frontend, but i get this error "Error occurred while loading Refresh"

details :

bootstrap.ts:7 Uncaught (in promise) GQLError: GraphQL Error (Code: 504): {"response":{"error":"Error occured while trying to proxy to: localhost:3100/dbeaver/gql","status":504,"headers":{}},"request":{"query":"\n    mutation openSession {\n  session: openSession {\n    createTime\n    lastAccessTime\n    cacheExpired\n    locale\n    connections {\n      id\n      name\n      driverId\n      connected\n      features\n      authNeeded\n      authModel\n    }\n  }\n}\n    "}}
    at eval (webpack-internal:///../core-sdk/src/GraphQLService.ts:60:17)
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (webpack-internal:///../core-sdk/src/GraphQLService.ts:13:103)
    at _throw (webpack-internal:///../core-sdk/src/GraphQLService.ts:15:291)

**Comment by Wroud** [comment]
It's probably occurred because backend server wasn't start on localhost:8978
Try next steps:
run backend by:
1. `cd deploy/cloudbeaver`
2. `./run-server.sh`
3. `cd ../../webapp/`
4. `lerna bootstrap`
5. `lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --server=http://localhost:8978`

Also I'm changed server from `localhost:8978` to `http://localhost:8978`

**Comment by killerwzb** [comment]
> It's probably occurred because backend server wasn't start on localhost:8978
> Try next steps:
> run backend by:
> 
> 1. `cd deploy/cloudbeaver`
> 2. `./run-server.sh`
> 3. `cd ../../webapp/`
> 4. `lerna bootstrap`
> 5. `lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --server=http://localhost:8978`
> 
> Also I'm changed server from `localhost:8978` to `http://localhost:8978`

Hi ，i do this like you tell me ，but if i run ./run-server.sh it can directory to visit by http://localhost:8978, i can not use frontend .

for example:
i edit the file at @cloudbeaver/product-default/src/index.html.ejs , change "<title>Cloudbeavertest</title>" , but it can not change from web browser.
