### ISSUE TITLE
Support search all tables if tables num > 500

### ISSUE THREAD

**Issue by mojerro** [dbeaver/cloudbeaver#1274]
**Is your feature request related to a problem? Please describe.**
In the tables list, there only show 500 tables. And it returns nothing if I search for a table not in these 500 tables.

![image](https://user-images.githubusercontent.com/15071824/201348560-470acb99-5c2b-4a41-a3fb-c914adc77223.png)
---
![image](https://user-images.githubusercontent.com/15071824/201348639-db88a2df-d5e8-40c5-804f-073cbb028ced.png)
---
![image](https://user-images.githubusercontent.com/15071824/201349047-0f345235-40e7-4096-9b2d-6ceeb176e7d1.png)
---

**Describe the solution you'd like**
It will be very convenient if the search bar supports searching all metadata in this table.

**Comment by kseniaguzeeva** [comment]
Thank you for your feature request. We should find the best way to implement it.

**Comment by mojerro** [comment]
OK, I think the limit now is quite inconvenient, looking forward to your progress

**Comment by TatyanaSsau** [comment]
@mojerro we fixed in 23.0.1 - now shows 1000 nodes in the navigation tree instead of 500.
closing.

please, feel free to contact me if you have any questions!
