### ISSUE TITLE
Generate and create a new docker image with new changes made in cloudbeaver

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1277]
Hello, how can I generate and create a new docker image with new changes that I have made in cloudbeaver?, or cloudbeaver generates the **cloudbeaver image** automatically

![image](https://user-images.githubusercontent.com/52106718/201404305-ba759ffb-cc49-4f1f-9ea9-3cb93176a1a6.png)

**Comment by miltonchirinos44** [comment]
How can I build a new docker image with new cloudbeaver code changes set?

**Comment by miltonchirinos44** [comment]
??

**Comment by alexander-skoblikov** [comment]
Hi! 
You can
- build your local CloudBeaver version using [build](https://github.com/dbeaver/cloudbeaver/blob/devel/deploy/build.sh) script
- after that run [make-docker-container.sh](https://github.com/dbeaver/cloudbeaver/blob/devel/deploy/docker/make-docker-container.sh)

**Comment by miltonchirinos44** [comment]
@alexander-skoblikov , the build command was executed successfully like this:
```
cd cloudbeaver/deploy
./build.sh
```

the problem i have is when i run the command:
```
cd cloudbeaver/deploy/docker
./make-docker-container.sh
```


or how do I have to execute this command?

**Comment by alexander-skoblikov** [comment]
@miltonchirinos44 can you describe  more detail  about problem with make-docker-container.sh script?

**Comment by miltonchirinos44** [comment]
@alexander-skoblikov , the first command works perfect for me I have problems with the following command. I am running the command as follows:

```
cd cloudbeaver/deploy/docker
./make-docker-container.sh
```

**message**
```
#1 [internal] load build definition from Dockerfile
#1 sha256:....
#1 transferring dockerfile:
#1 transferring dockerfile: 32B 0.4s done
#1 DONE 3.1s

#2 [internal] load .dockerignore
#2 sha256:......
#2 transferring context: 2b 0.6s done
#2 DONE 3.3s

#3 [internal] load metadata for docker.io/library/eclipse-temurin:17.0.4.1_1-jre-focal
#3 sha256:.........
#3 ERROR: failed to do request: Head "https://registry-1.docker.io/v2/library/eclipse-temurin/manifests/17.0.4.1_1-jre-focal": dialing registry-1.docker.io:443 no proxy configured: resolving host registry-1.docker.io: lookup registry-1.docker.io: no such host
------
> [internal] load metadata for docker.io/library/eclipse-temurin:17.0,4.1_1-jre-focal:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/eclipse-temurin/manifests/17.0.4.1_1-jre-focal" : dialing registry-1.docker.io:443 no proxy configured: resolving host registry-1.docker.io: lookup registry-1.docker.io: no such host
```

**Comment by alexander-skoblikov** [comment]
@miltonchirinos44 looks like something is wrong with your local docker/network settings.
can you try this command `docker pull eclipse-temurin:17.0.4.1_1-jre-focal` ?

**Comment by miltonchirinos44** [comment]
@alexander-skoblikov , run the command you told me:
`docker pull eclipse-temurin:17.0.4.1_1-jre-focal`

and got the following result
![image](https://user-images.githubusercontent.com/52106718/206778724-5d0797e1-5e88-4fd7-a22e-0899f7ea412a.png)

run again:
```
cd cloudbeaver/deploy/docker
./make-docker-container.sh
```

and I got the following result, apparently the cloudbeaver docker image was generated:
![image](https://user-images.githubusercontent.com/52106718/206779315-2aba5cab-6753-4069-bef6-f95a3f7dd962.png)

Could you tell me if the screenshots are correct?
And if it is correct, in which folder is the docker image stored?

**Comment by miltonchirinos44** [comment]
@alexander-skoblikov , hello , did you manage to replicate the problem I have?

**Comment by alexander-skoblikov** [comment]
@miltonchirinos44 as far as I can see you have successfully built the image, you can see it by running `docker images` command and find `dbeaver/cloudbeaver:dev` image.

**Comment by miltonchirinos44** [comment]
@alexander-skoblikov , a query where I can find the physical file that contains the docker image that docker generates

**Comment by alexander-skoblikov** [comment]
@miltonchirinos44 it's depend on your docker installation, i think you can find answer here 
https://stackoverflow.com/questions/19234831/where-are-docker-images-stored-on-the-host-machine

**Comment by miltonchirinos44** [comment]
@alexander-skoblikov ,  I'll review the link and check if it works correctly

**Comment by kseniaguzeeva** [comment]
There is no update for a long time. Do not hesitate to contact me, if you the issue isn't solved and you want to reopen the ticket.
