### ISSUE TITLE
mysql see all databases

### ISSUE THREAD

**Issue by pmpetit** [dbeaver/cloudbeaver#1278]
**Describe the bug**
Create a mysql template connection with database_1 as database_name :
<img width="842" alt="image" src="https://user-images.githubusercontent.com/4059185/201625486-b008b605-6a4c-4b5b-918e-e21e8d721903.png">

database_1 as dbname (properties):
<img width="983" alt="image" src="https://user-images.githubusercontent.com/4059185/201625600-4e693698-262a-4705-96e0-7166d0d9a05f.png">

when i connect as user (without login)

i create a connection from template mysql, but i can see all the databases (i expect to see only database_1) ?
<img width="724" alt="image" src="https://user-images.githubusercontent.com/4059185/201625735-a202f25a-615e-4bd9-9399-9f681d2462e2.png">

is it a bug ?

thanks

**Comment by kseniaguzeeva** [comment]
When you write a database name in this field, the SQL Editor uses this database as default, when you open it for this connection.

Do not hesitate to ask any other questions.
