### ISSUE TITLE
Adding a new driver does not work

### ISSUE THREAD

**Issue by dgkim11** [dbeaver/cloudbeaver#1286]
Hi, 

I need to add Sap Hana Jdbc driver to Cloudbeaver Community. I followed the guide document(https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers) but I can't see the new driver. This is my works. 
I found "sap_hana" driver in plugin.xml  in dbeaver. So, I used the driver for my Sap Jdbc driver. 
Step1, I add a sap_hana folder in drivers directory of cloudbeaver with the following pom.xml,please refer to the attached file. (https://github.com/dbeaver/cloudbeaver/files/10018941/sap_hana.zip).
Step2. I added '<module>sap_hana</module>' to the root pom.xml in drivers directory.
Step3,  I updated plugin.xml file in bundle/io.cloudbeaver.resources.drivers.base directory. with the following items.
        <resource name="drivers/sap_hana"/>
        <bundle id="drivers.sap_hana" label="SAP Hana drivers"/>
        <driver id="generic:sap_hana"/>
Step4. executed build.sh and I got the following message during building.
...
[INFO] drivers.sap_hana 1.0.0 ............................. SUCCESS [  2.318 s]
...

Is there any missing or wrong task? 

Thanks,
Dongkyun

**Comment by kseniaguzeeva** [comment]
Could you please give me a description what exactly have been wrong in your case (an error message etc.)? What have you received after finishing your steps?

**Comment by dgkim11** [comment]
I could not find any error message during build. The below is the log of build.sh
[build-cloudbeaver.log](https://github.com/dbeaver/cloudbeaver/files/10026385/build-cloudbeaver.log)
As you can see, the result was success.
Then, I executed deploy/cloudbeaver/run-server.sh and I expected to see the Sap hana driver on Cloudbeaver, but I could not see it like the below screen capture. 
<img width="1489" alt="availableDrivers" src="https://user-images.githubusercontent.com/5905957/202315543-e1dd8fd2-cb22-4455-99e1-92b05179cc14.png">
I found sap_hana folder in server/drivers after building. 
As I mentioned, to add the new driver, I created 'drivers/sap_hana' and pom.xml with the maven dependency in the folder.
Then, i updated plugin.xml to add the driver. The below file is the folders I updated.
[아카이브.zip](https://github.com/dbeaver/cloudbeaver/files/10026434/default.zip)
Could you please let me know what is wrong?

**Comment by dgkim11** [comment]
I resolved this issue. The document of 'https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers' is not correct. I think this doc should be updated. There is Sap Hana driver already in Dbeaver. Do not use the generic plugin, but instead, you can find org.jkiss.dbeaver.ext.hana plugin. Use it in the plugin.xml of Cloudbeaver.
