### ISSUE TITLE
Commit Changes Option 

### ISSUE THREAD

**Issue by saikatharryc** [dbeaver/cloudbeaver#129]
**Is your feature request related to a problem? Please describe.**
It happens very often that we might want to do the changes and then commit later at once, required mostly when using with production.
and is available with the dbeaver.

**Describe the solution you'd like**
An option to commit changes would be great just like dbeaver.

**Comment by serge-rider** [comment]
This feature is planned in version 1.3.

**Comment by bossdu15000** [comment]
Good morning,
I would like to know when this new feature is planned because we are in version 21.3.3
Cordially

**Comment by TatyanaSsau** [comment]
@bossdu15000 thank you for reporting.
Unfortunately, we aren't going to implement it in the near future.

**Comment by MatthiasSchnoeke** [comment]
This is bad news for us as we want to use CB for many supporters and developers and plan to buy licenses. 
The ability to make changes without direct commit is very important for working on production customer databases.

Please reconsider your decision!

**Comment by dennymou** [comment]
> This is bad news for us as we want to use CB for many supporters and developers and plan to buy licenses. The ability to make changes without direct commit is very important for working on production customer databases.
> 
> Please reconsider your decision!

yeah，its very important for production database， please reconsider your decision!
@EvgeniaBzzz

**Comment by MatthiasSchnoeke** [comment]
To be clear, this is currently the showstopper for using CB in our company.  Is there no option to solve this missing behavior?

**Comment by JoTerrance** [comment]
You may disable auto commit in connection driver properties

**Comment by dariamarutkina** [comment]
Hello!
We added support for[ two modes for committing changes](https://github.com/dbeaver/cloudbeaver/wiki/SQL-Editor#auto-and-manual-commit) to the database:
                    - Auto-commit transfers all changes that you make immediately to the database;
                    - Manual commit requires your confirmation before committing a change to the database or rolling it back.
Please take a look at the new version of CloudBeaver 24.0.1
Thank you for your interest in CloudBeaver!

**Comment by MatthiasSchnoeke** [comment]
Can you check again whether you can change the default to "Manual"? Currently, every new DB connection is set back to "AutoCommit". Unfortunately, this can easily be overlooked/forgotten in day-to-day business.

**Comment by EvgeniaBzzz** [comment]
@MatthiasSchnoeke 
Currently, auto-commit mode is the default. But we will add this setting in one of the future releases.
Thank you for your engagement with our project 🦫

**Comment by EvgeniaBzzz** [comment]
Commit mode setting has been added to the connection form in v24.1.2. 
So now you can configure each connection. By default auto commit mode is enabled.
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/d6d16f5e-b26b-43a7-9e4e-45a4f003084d)

**Comment by MatthiasSchnoeke** [comment]
great, many thanks
