### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by landsman** [dbeaver/cloudbeaver#13]
It would be nice to have docker deployment which is now top solution for multi-platform managing apps on server or localhost in quick time. Do you agree? Can I send pull request with implementation?

**Comment by tati-kru** [comment]
Docker container is in our plans for future releases. But we always open for new pull requests for review.

**Comment by rongfengliang** [comment]
@landsman i build  one  docker image `dalongrong/cloudbeaver`  you can  try  it

**Comment by serge-rider** [comment]
Eventually we finished our docker config: https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container
