### ISSUE TITLE
can not build cloudbeaver

### ISSUE THREAD

**Issue by Danst-bjtu** [dbeaver/cloudbeaver#1301]
I follow the official website documents

git clone https://github.com/dbeaver/cloudbeaver.git
cd cloudbeaver/deploy
./build.sh

but can not build，it prompts for missing jar package (org.eclipse.tycho:tycho-maven-plugin:3.0.0)

![image](https://user-images.githubusercontent.com/77576766/202598605-70f47a90-3b1d-46a4-9434-116ef77b9bc3.png)

I come from China， and not use VPN，how can I import these jar packages? 
Maybe these jar packages are not important, can I remove them?

jdk version 17.0.5
mvn version 3.8.6

**Comment by Danst-bjtu** [comment]
Pull cloudbeaver platform
Pull dbeaver platform
Build CloudBeaver server
[INFO] Scanning for projects...
Downloading from repo1: http://repo1.maven.org/maven2/org/eclipse/tycho/tycho-maven-plugin/3.0.0/tycho-maven-plugin-3.0.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:3.0.0 @ 
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:3.0.0 @ 
 @ 
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project org.jkiss.dbeaver:dbeaver:1.0.0-SNAPSHOT (/home/danst/CloudBeaver/dbeaver/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:3.0.0: Could not transfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:3.0.0 from/to repo1 (http://repo1.maven.org/maven2/): transfer failed for http://repo1.maven.org/maven2/org/eclipse/tycho/tycho-maven-plugin/3.0.0/tycho-maven-plugin-3.0.0.pom, status: 501 HTTPS Required -> [Help 2]
[ERROR]   
[ERROR]   The project io.cloudbeaver:cloudbeaver:1.0.0-SNAPSHOT (/home/danst/CloudBeaver/cloudbeaver/server/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:3.0.0: Could not transfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:3.0.0 from/to repo1 (http://repo1.maven.org/maven2/): transfer failed for http://repo1.maven.org/maven2/org/eclipse/tycho/tycho-maven-plugin/3.0.0/tycho-maven-plugin-3.0.0.pom, status: 501 HTTPS Required -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by miltonchirinos44** [comment]
@Danst-bjtu you have to setup jdk 17 and maven 3.8.6
You can download the references from the following pages:
- https://maven.apache.org/download.cgi
- https://adoptium.net/es/temurin/releases/?version=17

**Comment by Danst-bjtu** [comment]
> @Danst-bjtu you have to setup jdk 17 and maven 3.8.6 You can download the references from the following pages:
> 
> * https://maven.apache.org/download.cgi
> * https://adoptium.net/es/temurin/releases/?version=17

Thank you，I have already dealt with this problem. Due to mirrors.
