### ISSUE TITLE
Export in Parquet

### ISSUE THREAD

**Issue by alanpaulkwan** [dbeaver/cloudbeaver#1315]
I love Cloudbeaver.  I plan to include it in my class.

Is it possible to export in Parquet? 

It would (1) make the data more usable instantly, and (2) it would lead to lower egress than a CSV.

**Comment by kseniaguzeeva** [comment]
Thank you for your feature request. I moved it to DBeaver board, because it has to be implemented from its side https://github.com/dbeaver/dbeaver/issues/18393.
