### ISSUE TITLE
Docker image and predefined connections

### ISSUE THREAD

**Issue by jakobrosenberg** [dbeaver/cloudbeaver#1333]
Sorry if this has already been explained. If so I couldn't find the answer.

Is it possible to have a predefined connection when using the Docker image? Eg. through environment variables or a configuration file.

**Comment by kseniaguzeeva** [comment]
Yes, it's possible in the CloudBeaver. Here is the [related article](https://github.com/dbeaver/cloudbeaver/wiki/Connection-configuration).
Feel free to ask any other questions.

**Comment by jakobrosenberg** [comment]
Thanks @kseniaguzeeva 

I tried this in `/opt/cloudbeaver/workspace/GlobalConfiguration/data-sources.json`
```json
{
        "folders": {},
        "connections": {
                "postgresql-aml": {
                        "provider": "postgresql",
                        "driver": "postgres-jdbc",
                        "name": "AML",
                        "save-password": true,
                        "show-system-objects": false,
                        "read-only": false,
                        "template": false,
                        "configuration": {
                                "host": "172.17.0.1",
                                "port": "5432",
                                "database": "xxx",
                                "url": "jdbc:postgresql://172.17.0.1:5432/xxx",
                                "type": "dev",
                                "provider-properties": {
                                        "@dbeaver-show-non-default-db@": "false"
                                },
                                "username": "xxx",
                                "password": "xxx"
                      }
                }
        }
``` 
Alas, it's not working.

The GlobalConfiguration folder also contains `.dbeaver` and `.project`, so I assume I'm in the right place.

**Comment by jakobrosenberg** [comment]
Solved.

The path should be ` /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json`
