### ISSUE TITLE
No "Select connection" option for SQL scripts manager's scripts

### ISSUE THREAD

**Issue by methatronc** [dbeaver/cloudbeaver#1347]
Hello,

I am unsure if this is by design or not, but with cloudbeaver latest docker image ( v22.3.0.202212051839 ) I cannot select a connection for an opened "SQL scripts manager" script.
Steps to reproduce :
- I check SQL scripts manager to see the saved scripts
- I double-click on one to open it
- I cannot select a connection since the button doesn't appear, I have to copy the content to a new script ( button "Open SQL Editor" ) where I can select a connection

Here is what I see when opening a saved script :
![image](https://user-images.githubusercontent.com/58328740/205957517-cda565ff-ed83-4571-b828-a0cceb2eaf01.png)

Changing theme, restarting the container or reloading the page changes nothing.
I can see that `id=@menu/connection-selector` is dynamically removed when I switch from a saved script to a new script :
- saved script :
![image](https://user-images.githubusercontent.com/58328740/205958271-75c5d06c-5f77-455f-a9d0-b61efcdc9579.png)
vs
- new script :
![image](https://user-images.githubusercontent.com/58328740/205958416-5d6c2648-2cfc-4b1d-91da-fae1d3fb22ca.png)
 

Thank you for your help

**Comment by kseniaguzeeva** [comment]
Thank you for your question. It's the expected behavior for now - when you have a public permission (e.g. you are in the User team) and all connections in the Navigator tree are from the Shared project. 
Hovewer the possibilty to select shared connections for private scrips seems more suitable.  I've marked the ticket as the feature request.

**Comment by dariamarutkina** [comment]
Added ability to select shared connections for private scripts;
Private connections can be chosen for shared scripts, but this change won’t be saved to the script file.
@methatronc , Please, check CloudBeaver v.23.3.0
Thank you for your interest in CloudBeaver!

**Comment by methatronc** [comment]
Hello Daria, thanks a lot for this new feature, it is - for me at least - well working ! (with back v23.3.0.202312041127 and front 23.3.0.202312041132)
It is going to save time, so thanks again, and have a good day !
