### ISSUE TITLE
Some images Links do not respect custom rootURI property properly

### ISSUE THREAD

**Issue by hbenali** [dbeaver/cloudbeaver#1359]
**Describe the bug**
When setting a custom rootURI, some links are broken and refer to the default rootURI '/'
**To Reproduce**
1- Configure `rootURI` with a custom value : (eg `/cldbeaver`)
2- Refer to Cloudbeaver web interface
3- Open Developers Tools > Network Tab

Some broken links
- `https://<fqdn>/icons/logo_sm.svg` instead of `https://<fqdn>/cldbeaver/icons/logo_sm.svg` (asset is OK on that URL).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 110.0.5449.0
 - Cloudbeaver 22.3.0 (latest)

Thanks

**Comment by cesarjorgemartinez** [comment]
`+ 1` here I see 404 for /icons/spinner-primary-small.svg

**Comment by metalshanked** [comment]
+1 for this issue

**Comment by hbenali** [comment]
Problem resolved on Cloudbeaver `23.0.0`. Thanks a lot!
