### ISSUE TITLE
while：create data-transfer -> java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by itman2022** [dbeaver/cloudbeaver#1360]
Why ? startup failed：
create data-transfer -> java.nio.file.AccessDeniedException
![error01](https://user-images.githubusercontent.com/49448987/206753214-53c8301a-1f9a-453b-af53-400f7d506d65.jpg)

**Comment by kseniaguzeeva** [comment]
Could you please give me more details how do you run CloudBeaver (in docker? What commands and configuration do you use)?

**Comment by itman2022** [comment]
windows11 -> run-server.bat

**Comment by yagudin10** [comment]
Hi, @itman2022,
Could you delete `./work-data` folder in your workspace and try again to run the server?

**Comment by TatyanaSsau** [comment]
There is no updates for a long time. 
@itman2022 please contact me to reopen the ticket if it's still actual.

And thank you for the interest in CloudBeaver.
