### ISSUE TITLE
Leading whitespaces are trmmed

### ISSUE THREAD

**Issue by foriequal0** [dbeaver/cloudbeaver#1368]
**Describe the bug**
Leading whitespaces are trmmed. It is annoying especially when you're querying query plans.

**To Reproduce**
1. Open SQL Editor.
2. Plan some complex query.
3. Indentings are trimmed.

**Screenshots**
It looks like this:
![image](https://user-images.githubusercontent.com/5465658/208601038-cfb29b90-e827-44d4-aa2b-3b47097656a5.png)
It should be:
![image](https://user-images.githubusercontent.com/5465658/208601065-31c73bc2-e48d-40b6-80f9-8f0a6e9759de.png)

**Comment by kseniaguzeeva** [comment]
Thank you for the report.

**Comment by dariamarutkina** [comment]
Fixed in milestone 22.3.5
