### ISSUE TITLE
Why use iframe can not login ? 

### ISSUE THREAD

**Issue by itman2022** [dbeaver/cloudbeaver#1378]
Why use iframe can not login ? 

<!DOCTYPE html>
<head>
  <title>test</title>
</head>
<body>
  <iframe id ="cb" src="http://localhost:8978/" width="1300" height="600">
</body>
</html>

**Comment by devnaumov** [comment]
Hi @itman2022! I'm sorry, but it's difficult for me to provide a helpful answer without more information about the issue you are facing. Could you please provide more details about your question or the problem you are trying to solve?

**Comment by TatyanaSsau** [comment]
@itman2022 I've noticed there is no updates for a long time. 
Please - feel free to contact me to reopen the ticket, if it's still actual.
