### ISSUE TITLE
2FA & Keypair Authentication

### ISSUE THREAD

**Issue by Loki-101** [dbeaver/cloudbeaver#1387]
My feature request is not related to a problem.

I'd like to suggest as options for login/individual database authentication both 2FA and the option to authenticate with Public/Private Keys as an alternative to the current username/password authentication. I realize this may be a lot of work and would just like to put this feature request out in the open in case someone gets bored and feels like attempting this.

**Comment by kseniaguzeeva** [comment]
Thank you for your interest in CloudBeaver. Authentication with Public/Private Keys for AWS is already available in [CloudBeaver EE](https://dbeaver.com/cloudbeaver-enterprise/). You can try it for free.
CloudBeaver EE also supports Federated authentication (SAML, OpenID, Google, Azure) and 2FA should work in the application if configured on the provider side.

![chrome_agUQvxS5bh](https://user-images.githubusercontent.com/112612526/209831943-b3d70662-4cbc-4635-842e-6f4ae9fae2b7.png)

**Comment by kseniaguzeeva** [comment]
Feel free to contact me to reopen the ticket if you have any questions.
