### ISSUE TITLE
demo.cloudbeaver.io SSL certificate expired

### ISSUE THREAD

**Issue by fnicollet** [dbeaver/cloudbeaver#1391]
**Describe the bug**
Web browser complains about an expired certificate when accessing https://demo.cloudbeaver.io/#/

**To Reproduce**
1. Go to https://demo.cloudbeaver.io/#/

**Screenshots**
![image](https://user-images.githubusercontent.com/1240481/209968196-683e9c77-568e-4fc2-957e-05d71d621f68.png)

Reproduced with Chrome, but it should be an issue with any browser

**Comment by kseniaguzeeva** [comment]
Thank you for the report.

**Comment by kseniaguzeeva** [comment]
Fixed.
