### ISSUE TITLE
Pb allow anonymous users the access to the connections

### ISSUE THREAD

**Issue by Geronium** [dbeaver/cloudbeaver#1395]
Hello,

with the new version of cloudbeaver, i think i have a bug. Two connections are configured in the data-sources.json, when i am not logged, i can't see the connections, when i'm logged the two connections appear and they work. Can we authorize the anonymous users the access to the connections of the logged user ? (before the update the anonymous users had access to the same connections of the registred user).

![Capture d’écran de 2023-01-02 11-42-34](https://user-images.githubusercontent.com/73563389/210220967-d9ac3842-dd27-488f-bf0f-66758d8fe3e4.png)

Thank you

**Comment by kseniaguzeeva** [comment]
We have changed the behavior in the latest version. You should set the additional parameter `"grantConnectionsAccessToAnonymousTeam": true` in the .cloudbeaver.runtime.conf. All connections from the Shared project (including data-sources.json) will be available to anonymous users and users from the User team. Example:

```
"app": {
    "anonymousAccessEnabled": true,
    "supportsCustomConnections": true,
    "publicCredentialsSaveEnabled": true,
    "adminCredentialsSaveEnabled": true,
    "enableReverseProxyAuth": false,
    "forwardProxy": false,
    "linkExternalCredentialsWithUser": true,
    "redirectOnFederatedAuth": false,
    "resourceManagerEnabled": true,
    "showReadOnlyConnectionInfo": false,
    "grantConnectionsAccessToAnonymousTeam": true,
    "resourceQuotas": {
      "dataExportFileSizeLimit": 1.0E7,
      "resourceManagerFileSizeLimit": 500000.0,
      "sqlMaxRunningQueries": 100.0,
      "sqlResultSetRowsLimit": 100000.0,
      "sqlResultSetMemoryLimit": 2000000.0,
      "sqlTextPreviewMaxLength": 4096.0,
      "sqlBinaryPreviewMaxLength": 261120.0
    }

```
Feel free to contact me to reopen the ticket if you have any questions.

**Comment by Geronium** [comment]
Thank you for the answer. This help me a lot.
