### ISSUE TITLE
运行lerna run dev --stream --scope=@cloudbeaver/product-default  出现ERR! EFILTER No packages remain after filtering [ '@cloudbeaver/product-default' ]

### ISSUE THREAD

**Issue by wjyzhixing** [dbeaver/cloudbeaver#1397]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/36620969/210471597-c1258c1b-4c54-41dc-aa9c-b16eda617898.png">

**Comment by kseniaguzeeva** [comment]
Could you please change the theme of the ticket and describe a problem there. Also I need a detailed description with the steps to reproduce in the ticket content in order to assess the issue and help you to solve it.

**Comment by wjyzhixing** [comment]
sorry，I run the master branch，now I do not have any problem，thanks
