### ISSUE TITLE
Server DB use mysql，init Schema Error

### ISSUE THREAD

**Issue by yxydde** [dbeaver/cloudbeaver#1399]
cloudbeaver_1  | 07:55:35.554 [main] DEBUG i.c.service.security.db.CBDatabase -         Connected to MySQL 5.7.34
cloudbeaver_1  | 07:55:35.661 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Create new schema CB
cloudbeaver_1  | 07:55:39.668 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
cloudbeaver_1  | org.jkiss.dbeaver.DBException: Error updating management database schema
cloudbeaver_1  |        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:193)
cloudbeaver_1  |        at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:64)
cloudbeaver_1  |        at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:491)
cloudbeaver_1  |        at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:487)
cloudbeaver_1  |        at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:330)
cloudbeaver_1  |        at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:181)
cloudbeaver_1  |        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
cloudbeaver_1  |        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
cloudbeaver_1  |        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
cloudbeaver_1  |        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
cloudbeaver_1  |        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
cloudbeaver_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cloudbeaver_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
cloudbeaver_1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
cloudbeaver_1  |        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
cloudbeaver_1  |        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
cloudbeaver_1  |        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
cloudbeaver_1  |        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
cloudbeaver_1  |        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
cloudbeaver_1  | Caused by: org.jkiss.dbeaver.DBException: Error updating CB schema version
cloudbeaver_1  |        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:108)
cloudbeaver_1  |        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:189)
cloudbeaver_1  |        ... 18 common frames omitted
cloudbeaver_1  | Caused by: java.sql.SQLSyntaxErrorException: Invalid default value for 'LAST_ACCESS_TIME'
cloudbeaver_1  |        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
cloudbeaver_1  |        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
cloudbeaver_1  |        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
cloudbeaver_1  |        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
cloudbeaver_1  |        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
cloudbeaver_1  |        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
cloudbeaver_1  |        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:175)
cloudbeaver_1  |        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.createNewSchema(SQLSchemaManager.java:136)
cloudbeaver_1  |        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:90)
cloudbeaver_1  |        ... 19 common frames omitted
cloudbeaver_1  | 07:55:39.674 [Framework stop - Equinox Container: 397f2227-08d7-4dea-9209-36d4fb10d70f] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown Core...

**Comment by kseniaguzeeva** [comment]
Could you please write the problem in the ticket name and add its detailed description with steps to reproduce in the ticket content. What CloudBEaver version do you use?
It will help me to assess the issue and find a solution of the proble,

**Comment by Amor7527** [comment]
MySQL5.7 may not be compatible with the syntax of this underlying library, and may report an error. I switched to the postgresSQL database

**Comment by yxydde** [comment]
CloudBEaver version: release_22_3_1
MySQL version: 5.7.34
Server config:

 "server": {
    "database": {
      "pool": {
        "minIdleConnections": 4.0,
        "maxIdleConnections": 10.0,
        "maxConnections": 100.0,
        "validationQuery": "SELECT 1"
      },
      "createDatabase": true,
      "initialDataConfiguration": "conf/initial-data.conf",
      "driver": "mysql",
      "user": "cloudbeaver",
      "password": "cloudbeaver",
      "url": "jdbc:mysql://192.168.21.138:3306/cloudbeaver"
    }
  }

**Comment by kseniaguzeeva** [comment]
Thank you for the additional details. The CloudBeaver runs and works correctly when I use an empty MySQL database to run 22.3.1 version.
But I faced with the similar problem (the error is different), when I ran 22.2.0 version at first and then 22.3.1.
Could you please also tell me what version did you use with MySQL database before upgrade to 22.3.1?

**Comment by TatyanaSsau** [comment]
I've noticed there is no updates for a long time. 
Please feel free to contact me to reopen the ticket if it's still actual.
