### ISSUE TITLE
re develop question

### ISSUE THREAD

**Issue by wjyzhixing** [dbeaver/cloudbeaver#1400]
If I want to re develop, many components have been encapsulated to node_ Module, how can I handle it elegantly if I make changes, such as modifying some of your icons and deleting login related functions?

**Comment by wjyzhixing** [comment]
now only about frontend

**Comment by devnaumov** [comment]
Hi @wjyzhixing! To use your own icons, you need to add them to the ```packages/core-app/public/icons/icons.svg``` and use it in your components. We use plugins system so if you want to disable certain functions, you can remove the unwanted plugin from the list of plugins or modify the ```Bootstrap``` file of the plugin to disable certain functions. Keep in mind that not all CloudBeaver features are located in plugins, so it may be difficult to entirely remove some functionality.

**Comment by wjyzhixing** [comment]
Hello, so if I want to delete the modules related to login, in principle, I should delete the plugin-user-profile-administration and other modules in the packages under the webapp directory, and then reinstall the package with commands such as yarn and lerna, so as to test whether the complete deletion is successful?

In addition, the second question is whether to modify part of the logic, such as deleting the login related page code and logic code, means that I cannot modify in the package directory, but need to modify the node_ Module?

**Comment by devnaumov** [comment]
If you want to hide the Login button from the UI remove creator here https://github.com/dbeaver/cloudbeaver/blob/devel/webapp/packages/plugin-authentication/src/PluginBootstrap.ts
and rebuild the app
You don't need to modify node_modules at all

**Comment by wjyzhixing** [comment]
Hello, I will hide this part of the code, as shown in the figure below

<img width="621" alt="image" src="https://user-images.githubusercontent.com/36620969/211231577-d9207b85-202f-40d1-976f-44fb59dce37d.png">

If other logics remain unchanged, do I have to delete something if I want to use the system smoothly, or else there will be many problems using the system due to the lack of login information. How can I use the system without affecting the use of the function with minimal operations?

**Comment by wjyzhixing** [comment]
hi,After I delete it, I can't connect to the database and other related operations. What operations can I use to connect to the database?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/36620969/211232229-c151283d-7c30-48e9-800e-f20b2cb5e6a9.png">

**Comment by wjyzhixing** [comment]
Now there are two ideas:

1. The first is to cancel all logics related to login, including polling login status and other relevant operations on the login status display page and prompt pop ups

2. The second way is to secretly call a login when entering the page, and use the built-in (front end written) account password for a login. But I am not very familiar with our project structure in this way, so I need you to help me see where I add it and what can achieve the same effect as the current dialog login.

I hope you can evaluate these two strategies. If it is the second strategy, you can give me some suggestions and steps. Thank you very much for your support

**Comment by Wroud** [comment]
@wjyzhixing  if you want to disable authentication, you can do it in "Server configuration" page: disable all authentication methods in "AUTHENTICATION SETTINGS" (only Anonymous authentication will be enabled).

To be able to create connections you need to enable "Private connections" at the same page.

**Comment by TatyanaSsau** [comment]
I'm hope that the issue isn't actual anymore.

@wjyzhixing feel free to ask any other questions!

**Comment by wjyzhixing** [comment]
If I operate in this way, I need to log in to the interface first, and I see that my interface does not have this operation. Can I control it from the code? Do I feel like I did something wrong?

![image](https://user-images.githubusercontent.com/36620969/230840070-312af26e-fc7a-478c-b579-7af2846adeb5.png)

**Comment by Wroud** [comment]
Yes you need to login with admin user first.
Then you need to disable "Local" in the "authentication settings"
and you need to enable "Enable private connections".

after this actions button "Login" will dissapear from public part.

You can login with admin user by going to /#/admin

**Comment by wjyzhixing** [comment]
Okay, I understand. Also, I would like to ask which features of this offline mode cannot be used. Since I moved the project to an internal network environment, I would like to see which features will be affected. Can you provide a general overview?

**Comment by Wroud** [comment]
In general you won't be able to controll database acces over different users. Also:
1. anonymous can't use query history
2. can't use scripts (save / load from server)
3. manually created connections will be lost after relogin

**Comment by wjyzhixing** [comment]
ok.Thank you

**Comment by TatyanaSsau** [comment]
@wjyzhixing I'm glad that the issue isn't actual anymore :)
Please, feel free to ask any other questions.
