### ISSUE TITLE
eclipse debug problem

### ISSUE THREAD

**Issue by yjySun** [dbeaver/cloudbeaver#1405]
Please, describe your question in details.
![image](https://user-images.githubusercontent.com/54382029/210732232-3fd5c096-7e42-40c2-9bc7-8c14266901ae.png)
What is the problem with an error when starting the project?

**Comment by Amor7527** [comment]
1. 文件夹的名字需要改正
![1672912626544](https://user-images.githubusercontent.com/91579939/210752566-beb0f7c6-7d13-41b1-abe1-c1005d975d6e.png)

2. 需要执行  项目  \cloudbeaver\deploy  里面的这个脚本 双击执行就可以, 
![1672912681982](https://user-images.githubusercontent.com/91579939/210752754-46e472d5-ac63-4175-ab79-0611ffd148cb.png)


但是不知道你是否安装好了前后端的构建环境, 否则build.sh脚本会执行失败   前端环境 在官网里面自己看看 
jdk17  maven 3.8.6

**Comment by Amor7527** [comment]
我已经跑好了cloudbeaver 和dbeaver 两个项目, 如果你有需要可以vx 联系, github 回复太慢了,

**Comment by kseniaguzeeva** [comment]
Could you please describe step by step what are you doing and what doesn't work? It will help me to asses the issue and find a solution.
Also I kindly ask you to write all information in English.

**Comment by Amor7527** [comment]
OK, it’s okay, this question is from a Chinese, I believe he can understand it, I told him that he needs to enter the directory above the picture and execute the build.bat script

**Comment by kseniaguzeeva** [comment]
@Amor7527 thank you for your help. I really appreciate it.

**Comment by yjySun** [comment]
> 我已经跑好了cloudbeaver 和dbeaver 两个项目, 如果你有需要可以vx 联系, github 回复太慢了,

Eliauk-J-Y这是我的vx，麻烦您加下我哈，还得多想您请教

**Comment by kseniaguzeeva** [comment]
@yjySun I kindly ask you to write all information in the ticket in English. Thank you for your understanding.

**Comment by yjySun** [comment]
> @yjySun I kindly ask you to write all information in the ticket in English. Thank you for your understanding.

My problem has been solved, thank you very much.

**Comment by kseniaguzeeva** [comment]
I'm glad to hear it. Thank you for your interest in CloudBeaver.
