### ISSUE TITLE
Howto create users automatically

### ISSUE THREAD

**Issue by cesarjorgemartinez** [dbeaver/cloudbeaver#1412]
Please, describe your question in details.
Hi,

Howto create users automatically, example create two users test1 and test2 when first deploy or by script programatically?

Regards

**Comment by kseniaguzeeva** [comment]
Thank you for your interest in CloudBeaver. Unfortunately, there is no way to create users automatically.

**Comment by cesarjorgemartinez** [comment]
I finded one form to start (my knowledge in GPL language is near to zero):

curl -g -X POST -H "Content-Type: application/json" \
-d '{"query":"query createUser{createUser(userId: \"test1\", enabled: true, authRole: \"user\") {authRole}}"}' \
https://mycloudbeaver/cloudbeaver/api/gql

**Comment by cesarjorgemartinez** [comment]
Also, I finded a thing using nginx to use authorization, instead of using cookies, use headers following:

Reference: https://ashishchaudhary.in/rewriting-jwt-from-cookies-to-authorization-header

```
server {
  listen  0.0.0.0:3001;

  location / {
     rewrite_by_lua_block {
       local cookie_value = ngx.req.get_headers()["Cookie"];
       if cookie_value ~= nil then
         local jwt = cookie_value:match("access_token=([^ ]+)");
         ngx.req.set_header("Authorization", "Bearer " .. jwt);
       end
       ngx.req.clear_header("Cookie");
     }
     proxy_pass http://0.0.0.0:3000;
  }
}
```

I test and see if works. Instead cookies use: -H "Authorization: Bearer xyz"

Actual request (to nginx proxy by the webapp):

GET  HTTP/1.1
Host: localhost:3001
Cookie: access_token=mah.osum.token


Request relayed to Postgrest:

GET  HTTP/1.1
Host: localhost:3000
Authorization: Bearer mah.osum.token

**Comment by TatyanaSsau** [comment]
I'm glad that the issue isn't actual anymore. Thank you for the interest in CloudBeaver!
