### ISSUE TITLE
Behind LB nginx and specific rootURI and https redirects incorrectly

### ISSUE THREAD

**Issue by cesarjorgemartinez** [dbeaver/cloudbeaver#1413]
**Describe the bug**
Behind LB nginx and specific rootURI redirects incorrectly.
Example without rootURI: https://fqdn (works)
Example with rootURI: https://fqdn/cloudbeaver (not works)

**To Reproduce**
Example without rootURI (/): https://fqdn (works)
In browser enter:
https://fqdn
Show url: https://fqdn/#/
Reload
Show url: https://fqdn/#/

Example with rootURI (/cloudbeaver): https://fqdn/cloudbeaver
In browser enter:
https://fqdn/cloudbeaver
Show url: https://fqdn/cloudbeaver#/
Reload
Show url: http://fqdn/#/
And fails can't connect

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS: CentOS
 - Browser Firefox
 - Version latest (at 2023 january 12)

**Additional context**
Nginx and cloudbeaver all docker containers

**Comment by cesarjorgemartinez** [comment]
I find a weird workaround but is not a solution for this bug, defining in docker nginx:

```
server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name localhost;
  ssl_certificate /root/ssl/cert.pem;
  ssl_certificate_key /root/ssl/key.pem;
  location /cloudbeaver {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://cloudbeaver:8978;
```
**proxy_redirect ~^http://(.*)$ https://$1;**
```
  }
  error_page 500 502 503 504 /50x.html;
}
```

Note only for all dockers, the proxy_pass http://cloudbeaver:8978 is the url of docker cloudbeaver, defined as service container name in compose file.

**Comment by alexander-skoblikov** [comment]
@cesarjorgemartinez Hi, please try to define not the full url in `rootURI` parameter, but just `/cloudbeaver/`.
it's work for me with this nginx config
```
 location /cloudbeaver {
        proxy_pass http://cloudbeaver:8978;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

**Comment by TatyanaSsau** [comment]
I've noticed there is no updates for a long time. 
@cesarjorgemartinez Please, feel free to contact me to reopen the ticket if it's still actual.
