### ISSUE TITLE
about control the operation permissions of each role for each table for each database

### ISSUE THREAD

**Issue by wjyzhixing** [dbeaver/cloudbeaver#1415]
Would you like to know if you have such a development plan? It is to control the operation permissions of each role for each table for each database. The operation permission control of each role on different tables, and the operation control permission of each role on different fields of different tables, etc., are shown in the following figure.

(Permissions include select, insert, update, delete, truncate, references, trigger, etc.)

![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by kseniaguzeeva** [comment]
Closed as dublicate of https://github.com/dbeaver/cloudbeaver/issues/1416
