### ISSUE TITLE
AWS SSO Initiated log-in flow

### ISSUE THREAD

**Issue by Gunslito** [dbeaver/cloudbeaver#1423]
I am using Cloudbeaver AWS configured with IAM Identity Center (SSO) when trying to initiate the login flow from Single Sign On, I get the error

HTTP ERROR 500 Error processing SAML request: No security manager auth id specified
URI:	/api/saml/Legacy/acs
STATUS:	500
MESSAGE:	Error processing SAML request: No security manager auth id specified
SERVLET:	saml

I don't see in the documentation if I have to use a relaystate or an application start URL to initiate the login flow from SSO. If I initiate it from Cloudbeaver AWS it works well because it generates the correct auth_id. How can I make this final configuration?

**Comment by alexander-skoblikov** [comment]
@Gunslito Hi! 
Are you trying to login via CloudBeaver login form, or are you using a direct link from the identity provider?

**Comment by Gunslito** [comment]
Hi Alexander! Thanks for your response.

   When I log from CloudBeaver form it works, but I have a nasty icon on my AWS SSO Portal of Cloudbeaver that doesn't work because there's no auth_id when I initiate the flow from there. In some other applications there's a button or a callback URL to point to. That usually helps initiate the login from the provider but this isn't the case. For our end users that icon isn't going to work and that's a problem. There are some workarounds like just pointing to the URL and make the user do a "second login" but it defies the purpose of Single Sign-On!

**Comment by alexander-skoblikov** [comment]
@Gunslito yes, I can confirm the problem, we plan to fix it in 22.3.4 version

**Comment by alexander-skoblikov** [comment]
@Gunslito Hi, you can try to install the [latest early access version](https://hub.docker.com/layers/dbeaver/cloudbeaver-aws/ea/images/sha256-eb53c433ea33a07d8270829541427574940ec24d6a798ee0e31ea7471869bfe3?context=explore),
you can try to install the latest version, you will also need to copy new authorization link from your  identity provider in CloudBeaver administration page

**Comment by TatyanaSsau** [comment]
@Gunslito And as you are using EE version (AWS), you will have access to your request via personal cabinet here - https://dbeaver.com/profile/_username_/tickets. Support team will get back to you within 3 days.

I'd be happy to answer any additional questions you have!

Thank you for your interest in CloudBeaver!

**Comment by Gunslito** [comment]
> @Gunslito Hi, you can try to install the [latest early access version](https://hub.docker.com/layers/dbeaver/cloudbeaver-aws/ea/images/sha256-eb53c433ea33a07d8270829541427574940ec24d6a798ee0e31ea7471869bfe3?context=explore), you can try to install the latest version, you will also need to copy new authorization link from your identity provider in CloudBeaver administration page

Hi! Thank you for your response,
I installed this early access version, now it has a different behaviour but isn't still there.

When I log in using the Sign in Link from my "AWS SAML Identity provider " initiated from AWS IAM Identity Center as "Start URL" cloudbeaver logs me in the background (I can see my user account logged in) but a little window of "Federated login access" still appears for me to click on the foreground.

And another thing is that when I logout it doesn't take me to my AWS IAM Identity Center Applications Portal it just leaves me hanging on Cloudbeaver "Federated login access"

**Comment by Gunslito** [comment]
> @Gunslito And as you are using EE version (AWS), you will have access to your request via personal cabinet here - https://dbeaver.com/profile/_username_/tickets. Support team will get back to you within 3 days.
> 
> I'd be happy to answer any additional questions you have!
> 
> Thank you for your interest in CloudBeaver!

Hi! Thank you for your response, I don't have an account there do I have to make one? We just launched Cloudbeaver AWS from AWS Marketplace.

**Comment by TatyanaSsau** [comment]
@Gunslito Could you share your email address with us? We will create a ticket on your behalf in the online support system on the DBeaver website. Or you could create it by yourself. There is a  tab called "Tickets"  in your personal account on the website, and you could click "Open a ticket" https://dbeaver.com/support/. CloudBeaver GitHub page is mainly for the Community Edition.
Please let us know if you have any other questions.
