### ISSUE TITLE
How to connect to SQLite file on localhost? 

### ISSUE THREAD

**Issue by Sladoeg** [dbeaver/cloudbeaver#1427]
Hello, I am running the CloudBeaver in container:
docker run --name cloudbeaver --rm -ti -p 8080:8978 --add-host=host.docker.internal:${CB_LOCAL_HOST_ADDR} -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:latest

How to specify the path to SQlite file on the localhost, for example the path to DB file is /var/db/mydb.sqlite

Thank you
![image](https://user-images.githubusercontent.com/17851813/213920128-54a528fb-838f-4afc-aa3f-99d05a543e2d.png)

**Comment by kseniaguzeeva** [comment]
You can write the path by the following way `${application.path}/../your_local_workspace/database_name`.

**Comment by TatyanaSsau** [comment]
There is no updates for a long time. 
@Sladoeg please feel free to contact me if it's still actual. Thank you!
