### ISSUE TITLE
Query Manager - Log export to SIEM

### ISSUE THREAD

**Issue by Sineslito** [dbeaver/cloudbeaver#1444]
Hi! I was trying to make this to work but after reading documentation and trying some things I'm unable to workaround this.

I have Cloudbeaver AWS that has a nice feature called "Query Manager" where I can find every query of every user with results and everything, but I want to know where these are located on the instance or if there's a way to export this using something like Elastic-Search agent?

Thank you in advance!

**Comment by serge-rider** [comment]
Hey,

In single node CloudBeaver we keepquery history in anmbedded H2 database.
You can find it in the workspace (mounted as docker volume) in subfolder .metadata/qmdb.
You can conect to this database with any client which supports JDBC and H2.

We don't keep query history as a log, they are stored in different tables.
You can join table QM_QUERY, QM_STATEMENMT, QM_EVENMT and QM_CONNECTIONto see what queries are executed in hat databases.
Or you can view users information.

If you have additional questions - please ask.

**Comment by Gunslito** [comment]
Thank you for your response!

I'll look into that, I can see the file but I'm not familiarized with H2 databases

**Comment by TatyanaSsau** [comment]
I've noticed there is no updates for a long time. Feel free to contact me and to reopen the ticket if it's still actual.

**Comment by Vormillion** [comment]
What's the user and password for this H2 QMDB in Cloudbeaver EE? When I'm logging in with some random credentials it's showing only empty PUBLIC schema.
