### ISSUE TITLE
Can not type non-english words in sql editor(UI-BUG)

### ISSUE THREAD

**Issue by quguangyu0321** [dbeaver/cloudbeaver#1448]
**Describe the bug**
1. In latest version, I found that it can not type column name well in  non-english(like Japanese or Chinese).
2. Once you tried type non-english(like Japanese or Chinese) words, the underline came out. and if you press [ctrl and A], it should be select all script, but all the script you type are deleted.

Please check screenshot below.

**To Reproduce**
1. Go to 'sql editor'
2. Type column name by using non-english(like Japanese or Chinese)
3. See the bug

**Screenshots**
<img width="698" alt="image" src="https://user-images.githubusercontent.com/61673226/216214685-4a7caf13-9b5c-44bc-bdba-764ef8fa7c01.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [22.3.3]
   - Backend version(22.3.3.202301231340)
   - Frontend version(22.3.3.202301231357)

**Additional context**
Nothing

**Comment by quguangyu0321** [comment]
The bug seems not related to connector.  
I tried sqlserver and Trino. Both of them are doesn't work.

**Comment by MarinaVorobeva21** [comment]
Hello @quguangyu0321 ,
this is a known issue. It will be fixed in the next milestone.
Thank you for your interest in CloudBeaver.
