### ISSUE TITLE
How to Configure server "predefined" connections

### ISSUE THREAD

**Issue by dventimihasura** [dbeaver/cloudbeaver#1454]
Hello,

The documentation [here](https://github.com/dbeaver/cloudbeaver/wiki/Configuring-server-datasources#configuring-server-predefined-connections) indicates that it is possible to configure server predefined connections.  That page goes on to say:

> You can create this configuration in DBeaver and then copy it to your server configuration folder. Then you can patch the configuration manually by editing the configuration json.

Question:  where exactly is the "server configuration folder"?  What I mean is, where does the configuration get copied in order to create the predefined connections?  Is it `/etc/cloudbeaver` or `/opt/cloudbeaver/workspace` or `/opt/cloudbeaver/workspace/.data` or is it somewhere else?  I'm afraid this is a little unclear to me.  Thanks!

**Comment by dventimihasura** [comment]
I think I figured out that I can put data sources into the `/opt/cloudbeaver/conf/initial-data-sources.conf` file, but then my next question is this.  How/where do I store the credentials for these connections?

**Comment by lupeaserban** [comment]
for local development, i've added `"user":"username"` and `"password":"somepass"` in the configuration object of the connection

**Comment by TatyanaSsau** [comment]
@dventimihasura, soorry for the really long answer! Is your question about connections is still actual for you?

**Comment by DanHartman** [comment]
> for local development, i've added `"user":"username"` and `"password":"somepass"` in the configuration object of the connection

@lupeaserban Would you share a masked/redacted copy of `/opt/cloudbeaver/conf/initial-data-sources.conf` that shows where you've added the credentials?

**Comment by lupeaserban** [comment]
here it is 
```json
{
	"folders": {},
	"connections": {
		"postgresql": {
			"provider": "postgresql",
			"driver": "postgres-jdbc",
			"name": "test-db-exporer",
			"save-password": true,
			"show-system-objects": false,
			"read-only": true,
			"configuration": {
				"host": "backend-db-1",
				"port": "5432",
				"database": "test-db",
				"user": "backend",
				"password": "backendpass",
				"url": "jdbc:postgresql://backend-db-1:5432/test-db",
				"type": "dev",
				"provider-properties": {
					"@dbeaver-show-non-default-db@": "true"
				}
			}
		}
	}
}
```

**Comment by DanHartman** [comment]
Thanks!

**Comment by dventimihasura** [comment]
Thanks @TatyanaSsau and @lupeaserban .  I _think_ I have my answer so I think I'm good.  Unless anyone objects, I'm going to close this.  (sorry for the delay)

**Comment by TatyanaSsau** [comment]
@dventimihasura I'm glad that the issue isn't actual anymore.
And really Thank you for the interest in CloudBeaver!
