### ISSUE TITLE
HA Capabilities

### ISSUE THREAD

**Issue by Gunslito** [dbeaver/cloudbeaver#1460]
Hi! thank you in advance for all the support that you guys give me, that's amazing!

I want to ask if there's any HA or cluster capabilities or if its on your roadmap, we want to use this for our production environment and it would be nice to have high availability on this software.

Keep up the good work! 

Greetings

**Comment by tati-kru** [comment]
CloudBeaver Community is limited by one server and cannot be scaled. If you need horizontal scalability and HA for a production environment, we recommend you [Team Edition](https://dbeaver.com/dbeaver-team-edition/).
