### ISSUE TITLE
How to turn off/minimal console logging

### ISSUE THREAD

**Issue by davidchingmy** [dbeaver/cloudbeaver#1469]
For context, I am using docker compose yml to run app and cloudbeaver community. I just want to see log for my app, how do I turn off or reduce cloudbeaver console logging?

**Comment by dariamarutkina** [comment]
Hello @davidchingmy !
Could you clarify what exactly means "console logging" and what exactly you want to reduce? Also please share an example of logs. Can you please describe in more detail?
Thank you for your interest in CloudBeaver.

**Comment by davidchingmy** [comment]
Hello @dariamarutkina , 

Thank you for your response!

I have this in my `docker-compose.yml` (see image below) and used `docker compose up` to run cloudbeaver.
![image](https://user-images.githubusercontent.com/103477413/220815694-0f4bb8d5-0c67-46a0-8de4-407eb737f1aa.png)

I don't want to use docker's `--detach` argument because this docker setup is purely for development purposes and I need to see my app's and db's logs.

Here some sample logs from cloudbeaver.
![image](https://user-images.githubusercontent.com/103477413/220815656-35e13c4e-0dcd-421f-a17b-0ed552e56d7b.png)

**Comment by alexander-skoblikov** [comment]
Hi, if you are building an application from source code, you can change this [log config file](https://github.com/dbeaver/cloudbeaver/blob/devel/config/core/logback.xml), also in the future we plan to add support for custom logging configuration

**Comment by TatyanaSsau** [comment]
Support for custom logging configuration via an external file has been added in 23.0.4

Thank you, @davidchingmy, for the interest in CloudBeaver!!!

**Comment by LonwoLonwo** [comment]
As a result:

Custom cloudbeaver configuration is searched in conf/custom folder.

How to use it:

• create a folder in your local machine with custom `cloudbeaver.conf`  or `logback.xml` files 
• how to customize `logback.xml` - you can open it in Notepad and change the log pattern (date and time, for example, from {HH:mm:ss.SSS} to {HH:mm} )

 ```
<Pattern>
            %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
</Pattern>
```

• Mount a new volume for the `/opt/cloudbeaver/custom` with your local configuration folder where lies `cloudbeaver.conf`  or `logback.xml` and run docker image  RESULT: logs format will be changed (if you set it as in the example, the time will have only hours and minutes)
