### ISSUE TITLE
Teams management access by folders

### ISSUE THREAD

**Issue by RaffiRaff** [dbeaver/cloudbeaver#1477]
Hi,
It would be really nice to make possible to manage access by folders.
For example: we have CNF, DEV and TST folders and inside of this folders other folders with the db connections. 
We need different teams to be able to access only CNF or DEV or TST and all included folders.

![image](https://user-images.githubusercontent.com/125563367/219357657-3e10a2bf-64c5-4cc1-a973-1c902d98e4ff.png)

Sorry, if this is already requested - I didn't find it in the issues :)

Thank you

**Comment by MarinaVorobeva21** [comment]
Hello @RaffiRaff,
we will think about the possibility to develop this functionality in CloudBeaver in the future. For now please look at the CloudBeaver Team Edition. There is a Project functionality that you can use to separate access for users in Team Edition. It can be more useful for you.
Thank you for your interest in CloudBeaver.

**Comment by LonwoLonwo** [comment]
Hello @RaffiRaff 

As my colleague said, you can find similar functionality in our Team Edition product.
You can read more about it here: https://dbeaver.com/dbeaver-team-edition/
In Team Edition, we have the support of different teams, users, and groups. 
And you can change access permissions for different projects. https://github.com/dbeaver/cloudbeaver/wiki/Teams
You can try it for free: https://dbeaver.com/trial/
