### ISSUE TITLE
Save connection error Field 'Host' can't be empty Driver SQLite

### ISSUE THREAD

**Issue by YuraKril** [dbeaver/cloudbeaver#1495]
**Describe the bug**
Update existing connection sqlite driver 

Can
**To Reproduce**
Create any Sqlite connection and try update

**Screenshots**
![image](https://user-images.githubusercontent.com/4184026/220684841-43be3a6c-ada8-4f56-9931-cf20db82f8d3.png)

**Comment by dariamarutkina** [comment]
Hello @YuraKril ,
this is a known issue. Thank you for the report. It will be fixed in the next milestone 23.0.0.
Thank you for your interest in CloudBeaver.
