### ISSUE TITLE
H2GIS 1.5  driver

### ISSUE THREAD

**Issue by ebocher** [dbeaver/cloudbeaver#15]
**Describe the solution you'd like**
It would be great if CloudBeaver could offer an H2GIS base in demonstration.
You will have an easy way to init a temporary spatial database.
Ready to collaborate.

**Comment by serge-rider** [comment]
We have it in plans. 
H2 and Derby drivers will be included in the next version (and in Demo server as well).

It is still questionable which exactly drivers to include by defaultL
- H2 or H2GIS
- Remote server or embedded database.
- What driver version exactly

**Comment by ebocher** [comment]
Excellent !

You can add both H2 and H2GIS. When H2GIS is selected the spatial functions must be initialized. 
Embedded database is enough. 
Is a new database created after each connection ?
We can prepare for you some demo data with spatial contents.
According the driver version, use the 1.5.0. 
We are working on 2.0 but it still in dev.
Best regards

**Comment by kseniiaguzeeva** [comment]
Sorry for the really long delay in response. Is implementing of H2GIS is still actual for you? H2 driver is included in Enterprise Edition, you can try it for free https://cloudbeaver.io/trial/.

**Comment by TatyanaSsau** [comment]
This feature is already implemented in EE version.
No updates for a six months. Closing.

Please, feel free to reopen the ticket if you have any questions.
