### ISSUE TITLE
How to fix http response status 431 error?

### ISSUE THREAD

**Issue by owenJiao** [dbeaver/cloudbeaver#1500]
Dear Teams:
When I accessed cloudbeaver  which was deployed in AKS,  Web browser threw 431 error, the detail error message is "Bad Message 431, reason : Request Header Fields Too Large". The server side log of  cloudbeaver is "org.eclipse.jetty.http.HttpParser - Header is too large 8193>8192". I haven't found any parameters  that can enlarge the size of http header. So could you provide some tips to fix this error?
Thanks very much.

**Comment by dariamarutkina** [comment]
Hello @owenJiao,
Please can you try clearing cookies, if that doesn't help, could you send Logs and a full Header, please?
Thank you for your interest in CloudBeaver.

**Comment by TatyanaSsau** [comment]
There is no updates for a long time. 
@owenJiao please, feel free to contact me to reopen the ticket if it's still actual.
