### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by Rainee-Davad** [dbeaver/cloudbeaver#1507]
I hope CB have the function of "Data Import". It has export .

Data Import to Database table like DBEAVER.

**Comment by dariamarutkina** [comment]
Hello @Rainee-Davad,
Thank you so much for the feature request, we will add it to the backlog.
Thank you for your interest in CloudBeaver.

**Comment by dariamarutkina** [comment]
Hello, @Rainee-Davad !
We added the ability to import data to the database from a CSV file.
Please take a look at the new version of CloudBeaver 24.0.2
Thank you for your interest in CloudBeaver!
