### ISSUE TITLE
authentication password with the api

### ISSUE THREAD

**Issue by Geronium** [dbeaver/cloudbeaver#1520]
Hello, apparently the password that is presented to cloudbeaver is encrypted (with a hash?). How can reproduce it? how do you switch from clear password to encrypted password? thanks

**Comment by Wroud** [comment]
Thank you for a question, you can find encryption mechanism used in the application [here](https://github.com/dbeaver/cloudbeaver/blob/29b4e816545729cb15daac8bf5bc395f225a2187/webapp/packages/core-authentication/src/AuthProviderService.ts#L66).

**Comment by Geronium** [comment]
it's perfect, juste a simple md5sum, i tried but without the -n , to have the right hash we have to make a 

echo -n "passord" | md5sum 

Thank you very much for your answer.
