### ISSUE TITLE
Typos on CloudBeaver License Management github page

### ISSUE THREAD

**Issue by BruceRMack** [dbeaver/cloudbeaver#1522]
**Describe the bug**
Two typos on license page
liucense.
https::/dbeaver.com

**To Reproduce**
Visit https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-License-Management

**Comment by dariamarutkina** [comment]
Hello @BruceRMack ,
Thank you very much for your comments, we have corrected these typos in the documentation.
Thank you for your interest in CloudBeaver.
