### ISSUE TITLE
Enter and Tab

### ISSUE THREAD

**Issue by R-i-c-h-B** [dbeaver/cloudbeaver#1525]
Hi all, loving CloudBeaver, except...

If I hit Enter I seem to get strange behaviours - eg triggers a save, doesn't add a new line, or adds a new line but doesn't move the cursor.

Tab also seems to behave oddly, in that it doesn't consistently move tabs, but seems to want to force a half tab or a mix of automatic tab and manual.

I am hoping someone can tell me how to configure this to be a simple NL/CR and TAB functionality, without any extras/autoformatting.

I am running latest chrome on fedora.

Note, this is also running quite literally on the other side of the world, so there may be some latency complicating matters.

**Comment by dariamarutkina** [comment]
Hello @R-i-c-h-B ,
Thank you for the issue. This will be fixed in future releases. Thank you for your interest in CloudBeaver.

**Comment by dariamarutkina** [comment]
Fixed in milestone 23.0.5
In the SQL editor, pressing Tab/Space followed by Enter now causes the cursor to move to a new line
Thank you for the interest in CloudBeaver.
