### ISSUE TITLE
PostgreSQL not showing all databases

### ISSUE THREAD

**Issue by renns** [dbeaver/cloudbeaver#1541]
**Describe the bug**
I upgraded from version 22.0 to 23.0. After the upgrade, although the PostgreSQL connection was configured to "Show all databases", only the database on the JDBC URL was visible in both the navigation pane on the left and in the dropdown in the SQL editor header bar.

Note, this issue only occurs when the connection is configured using "URL". It works properly when it is configured using "Manual".

**To Reproduce**
1. Create PostgreSQL connection to a PostgreSQL server with multiple databases (using URL)
2. Edit connection properties and check "Show all databases"
3. Connect to database
4. Expand list of databases
5. See that there is only a single database listed

**Screenshots**
Select PostgreSQL URL connection:
![image](https://user-images.githubusercontent.com/3082842/225022294-6bac45c3-df74-46bc-a19d-7e5768b774d0.png)

Make sure Show all databases is checked:
![image](https://user-images.githubusercontent.com/3082842/224813818-99d479e5-dda0-4e0f-b847-5553a85d5620.png)

Only a single database is shown under the connection:
![image](https://user-images.githubusercontent.com/3082842/224814131-6cf1a048-62cd-452d-ac8a-2bbeddcc9ab0.png)

**Desktop (please complete the following information):**
 - OS: Server running with docker on Ubuntu. Client is Windows 11.
 - Browser: Chrome
 - Version: 23.0

**Comment by dariamarutkina** [comment]
Hello @renns ,
Thank you for the issue. This will be fixed in future releases. Thank you for your interest in CloudBeaver.

**Comment by TatyanaSsau** [comment]
@renns Thanks! This is known issue. We are going to disable settings checkboxes under URL configuration type very soon - expected version is 23.0.3

**Comment by dariamarutkina** [comment]
Fixed in milestone 23.0.5
The URL configuration for PostgreSQL now correctly displays only a single database
Thank you for your interest in CloudBeaver.
