### ISSUE TITLE
When i auth by reverse proxy can i add Firstname and Lastname in to header ?

### ISSUE THREAD

**Issue by natamongkol** [dbeaver/cloudbeaver#1558]
When i Auth by reverse proxy i want to add Firstname and Lastname for user, Can i add Firstname and Lastname in to header ?

**Comment by dariamarutkina** [comment]
Hello @natamongkol ,
Thank you so much for the feature request, we will think about the possibility to develop this functionality in CloudBeaver in the future. 
Thank you for your interest in Cloud Beaver.

**Comment by EvgeniaBzzz** [comment]
Hi, @natamongkol 
Reverse Proxy authentication now includes the option to provide users' First name and Last name.
Added fields to the configuration file nginx.conf
```
proxy_set_header X-First-Name TestFirstName;
proxy_set_header X-Last-Name TestLastName;
```
Please, check CloudBeaver v.23.1.4.
