### ISSUE TITLE
build.sh returns "ERROR: There are no scenarios; must have at least one."

### ISSUE THREAD

**Issue by dchosnek** [dbeaver/cloudbeaver#158]
Please, describe your question in details.
I'm trying to install CloudBeaver in an Ubuntu 18.04 container. The build script runs for about 2 minutes and displays pages of messages, but it concludes with:

```
Copy server packages
Build static content
ERROR: There are no scenarios; must have at least one.
```

There seems to be an issue on line 46 of the build script as the `lib` directory does not exist at `/cloudbeaver/webapp/packages/product-default`

I see many WARNING messages during the build script, such as:

```
[WARNING] Some problems were encountered while building the effective model for io.cloudbeaver:drivers.clickhouse:jar:1.0.0
[WARNING] 'dependencies.dependency.version' for ru.yandex.clickhouse:clickhouse-jdbc:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 21, column 22
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/root/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[WARNING] JAR will be empty - no content was marked for inclusion!
```

Any guidance on how to proceed would be much appreciated.

**Comment by serge-rider** [comment]
Perhaps you have wrong version of Node. Please see https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy

You can also download recent [Docker image](https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container) or download [release build](https://github.com/dbeaver/cloudbeaver/releases)

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if the issue still actual for you.
