### ISSUE TITLE
Unable to add SAP HANA as custom jdbc driver to  cloudbeaver

### ISSUE THREAD

**Issue by Caleb-A** [dbeaver/cloudbeaver#1588]
I am trying to add in the SAP HANA jdbc driver to cloudbeaver, but it is not showing up in the UI using the the instructions below.

https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers

I beleive that I ran the instructions correct since the hana ngdbc driver was automatically downloaded in the target directory after the pom.xml file was created and the build.sh script was run. 

![image](https://user-images.githubusercontent.com/68909693/229933322-7bfa84aa-5f65-4865-82d3-fa279b6b230f.png)

1. HANA directory and pom.xml created in servers/drivers 

![image](https://user-images.githubusercontent.com/68909693/229933694-3033e33c-f1a6-4e8c-98d9-a0c8e7e47056.png)

2. Modules updated in server/drivers/pom/xml with hana

![image](https://user-images.githubusercontent.com/68909693/229934300-5b2fa71c-f7ff-45a0-906c-7c6df94f580c.png)

3. Sections updated in server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml

![image](https://user-images.githubusercontent.com/68909693/229934819-f30ef820-6291-4a1c-92cf-3f6f6fd0cb86.png)

4. Driver selections in UI 

![image](https://user-images.githubusercontent.com/68909693/229935644-08e2fd4d-3b8f-4257-a8da-b41c27c3ca9f.png)

![image](https://user-images.githubusercontent.com/68909693/229935757-650989ff-873d-43e0-9451-ed31e434ae67.png)

Can someone help me to check why the HANA driver is not showing up?

**Comment by TatyanaSsau** [comment]
@Caleb-A Unfortunately, I need more information to help you to solve your issue. Could you please provide the docker logs cloudbeaver files?

**Comment by Caleb-A** [comment]
@TatyanaSsau -  Thanks for looking into this. I am running cloudbeaver from source on a VM. Do you have path for the logs?

**Comment by alexander-skoblikov** [comment]
@Caleb-A Hi! did you create driver configuration in DBeaver?
https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#configuring-drivers-in-dbeaver

**Comment by Caleb-A** [comment]
@alexander-skoblikov  - Hello! From what I see DBeaver already comes with the HANA driver. 

[rocky@localhost plugins]$ pwd
/home/rocky/dbeaver/plugins

[rocky@localhost plugins]$ ll | grep -i hana
drwxr-xr-x. 7 rocky rocky  133 Apr  4 09:55 org.jkiss.dbeaver.ext.hana
drwxr-xr-x. 6 rocky rocky  119 Apr  4 08:40 org.jkiss.dbeaver.ext.hana.ui

![image](https://user-images.githubusercontent.com/68909693/231761624-e5edcf1c-38a5-4c7b-aecd-f7de4c5f17ce.png)

**Comment by alexander-skoblikov** [comment]
@Caleb-A 
if you want to use an already existing driver configuration you need to specify `<driver id="hana:sap_hana"/>` in  `server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml`

**Comment by Caleb-A** [comment]
Thanks for the assistance @alexander-skoblikov! With your help,  I was able to get things working on my end. I was even able to create a running docker container with the configurations. Thanks again!
