### ISSUE TITLE
Please support Db2

### ISSUE THREAD

**Issue by thuanvan** [dbeaver/cloudbeaver#159]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by friedmar** [comment]
I would like to support this request!
Tried to implement it myself but did not succeed. If you implement it, i volunteer as guinie pig!

**Comment by friedmar** [comment]
The description of how to add other databases to cloudbeaver is, from my point of view, totaly unclear. I tried to follow - but no success!

**Comment by serge-rider** [comment]
DB2 driver will be added in the next version

**Comment by kseniiaguzeeva** [comment]
DB2 driver support is implemented in 20.0.3 CE release.
