### ISSUE TITLE
Build and Deploy not working - Ubuntu 20.04 Docker

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/cloudbeaver#160]
Hi Serge,

I just tried to test your CloudBeaver, but I wasn't able to build it. There are always errors like:

![image](https://user-images.githubusercontent.com/38714600/94348986-fc8df200-0040-11eb-811d-9c46f62d64d4.png)

I used your installation guide at:
https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy

You can easily reproduce my problem when doing the following:

```
sudo docker pull ubuntu:20.04
sudo docker run -it --name cloudbeaver ubuntu:20.04
```
Now you are inside the Container and do:
```
apt update
apt install sudo
apt install git
apt install curl
apt install gnupg
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt update
sudo apt install openjdk-11-jdk
```
(Choose Geographic area: 8. Europe. and then 7. Berlin)
```
sudo apt install maven
sudo apt install yarn
sudo apt install nodejs
sudo apt install npm
```
(At this stage I get many "Depends:" Messages)
```
sudo npm install -g lerna
git clone https://github.com/dbeaver/cloudbeaver.git
cd cloudbeaver/deploy 
./build.sh
```

You get the error:
[INFO] org.jkiss.dbeaver.ext.postgresql 2.1.114-SNAPSHOT .. FAILURE [  0.902 s]

Can you guide me in the right direction?

Cheers,
James

**Comment by JamesInform** [comment]
Hi,

seems you have fixed this issue with one of you latest commits!

Now building inside docker works pretty well.

Thanks

**Comment by serge-rider** [comment]
Yep, `devel` branch becomes unstable sometimes :(

**Comment by miltonchirinos44** [comment]
A query when a new cloudbeaver docker image is generated in which folder the file is generated, could you help me with that information please
