### ISSUE TITLE
Query bug in Editor with semicolon

### ISSUE THREAD

**Issue by AmiasLi** [dbeaver/cloudbeaver#1604]
Every time when I want to execute the query with semicolon it will produce an error after I choose entire statement

Version: 23.0.0-23.0.2

For example 

The following statement will  be executed correctly when I choose the statement
```sql
select * from employees e
```

But this one will not if I choose all include semicolon
```sql
select * from employees e;
```

error:

Error executing query:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0, 200' at line 2

**Comment by dariamarutkina** [comment]
Hello @AmiasLi  ,
Thank you for the report. I've reproduced the bug. We will fix this in the future.
Thank you for your interest in Cloud Beaver.

**Comment by TatyanaSsau** [comment]
Fixed in 23.0.4

@AmiasLi, thank you, for your interest in CloudBeaver!
