### ISSUE TITLE
What this refresh button does

### ISSUE THREAD

**Issue by yjySun** [dbeaver/cloudbeaver#1617]
When is this button used and what is its function
![P$%QVW~_34@JKWOFBI V%%A](https://user-images.githubusercontent.com/54382029/233052908-900151ca-2680-42ae-813c-844f25b7f0b8.png)

**Comment by TatyanaSsau** [comment]
@yjySun thank you for interesting in CloudBeaver :)

You can find more information about menu - [DB Navigator toolbar](https://github.com/dbeaver/cloudbeaver/wiki/DB-Navigator-toolbar)

**Comment by yjySun** [comment]
> 
But why doesn't the new table appear in the navigation bar when you click the refresh button after creating a new table with an sql statement

**Comment by dariamarutkina** [comment]
Hello @yjySun  ,
this is a known issue. Thank you for the report. We will fix this in the future.
Thank you for your interest in CloudBeaver.

**Comment by LonwoLonwo** [comment]
Hello @yjySun 

It can be dangerous - to refresh all your connections in the navigator tree with the inside metadata. So, this button on the top only refreshes general connections info, not inside metadata.

![2024-03-11 20_17_23-Window](https://github.com/dbeaver/cloudbeaver/assets/45152336/c3e54d19-764d-47f4-93cc-411b252ea333)

So, if you want to refresh your database metadata, click on your connection in the database navigator and choose Refresh.
Additionally, you can click on your database, schema, and other nodes in the navigator tree.

**Comment by LonwoLonwo** [comment]
Resolution - this refresh button is for the connections list in the navigator tree (to synchronize with other server instances).
Not for refreshing all-all entities. Because it can be costly.
We have other refresh buttons on the connection level and below.
