### ISSUE TITLE
How use Cloudbeaver with https://sqlite.org/com/see.html

### ISSUE THREAD

**Issue by YuraKril** [dbeaver/cloudbeaver#1620]
We try to build see (https://sqlite.org/com/see.html) to shared library - libsqlite3.so and start cloudbeaver with

JAVA_OPTS -Dorg.sqlite.lib.path=/opt/cloudbeaver/lib -Dorg.sqlite.lib.name=libsqlite3.so

We get an error on connection to clean database: 
Error connecting to database:
Unexpected driver error occurred while connecting to the database

Are there options how to solve it?

**Comment by YuraKril** [comment]
Hi team.
The problem was solved by update sqlite-jdbc to 3.41.2 version. 
Is it possible to do this in the main repo?

Another question - how to prioritize those properties. We need for this key `textkey` run as first PRAGMA statement:
`PRAGMA textkey='somesectetvalue';`
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/4184026/234803599-941412c0-4871-492f-84ee-1891320e8068.png">

**Comment by TatyanaSsau** [comment]
@YuraKril I'm glad that the first issue isn't actual anymore :) but we are going to implement new update for sqllite driver after 23.1 release.

And one more question about properties - could you please give me more details about your case or the problem you are trying to solve?

**Comment by YuraKril** [comment]
Sqlite SEE support three different key formats: -key -hexkey -textkey. The -textkey format is recommended for new applications.
https://www.sqlite.org/see/doc/trunk/www/readme.wiki

I uses textkey for my databases, but sqlite-jdbc do not support that type of key. That's why i tried to set 'textkey' with driver properties. 
https://github.com/xerial/sqlite-jdbc/blob/043efd7ef3358247e4947d9b9e53a1dd378c6d36/src/main/java/org/sqlite/SQLiteConfig.java#L199

**Comment by TatyanaSsau** [comment]
We going to upgrade the driver for sqlite-jdbc to 3.41.2 version in 23.0.5 version

**Comment by dariamarutkina** [comment]
Fixed in milestone 23.0.5
We upgraded the sqlite-jdbc driver, version 3.41.2.
Thank you for the interest in CloudBeaver.
