### ISSUE TITLE
Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.1:compile

### ISSUE THREAD

**Issue by gboreczek** [dbeaver/cloudbeaver#1622]
**Describe the bug**
Dear Team, I build cloudbeaver with your cloudbeaver/deploy/build.sh script. Unfortunately the build ends up with BUILD FAILURE status and throws following:
Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.1:compile (default-compile) on project io.cloudbeaver.server: Compilation failure: Compilation failure: 
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[22] 
#23 302.4 [ERROR] 	import org.eclipse.jetty.websocket.server.JettyServerUpgradeRequest;
#23 302.4 [ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] The import org.eclipse.jetty.websocket.server cannot be resolved
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[23] 
#23 302.4 [ERROR] 	import org.eclipse.jetty.websocket.server.JettyServerUpgradeResponse;
#23 302.4 [ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] The import org.eclipse.jetty.websocket.server cannot be resolved
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[24] 
#23 302.4 [ERROR] 	import org.eclipse.jetty.websocket.server.JettyWebSocketCreator;
#23 302.4 [ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] The import org.eclipse.jetty.websocket.server cannot be resolved
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[36] 
#23 302.4 [ERROR] 	public class CBJettyWebSocketManager implements JettyWebSocketCreator {
#23 302.4 [ERROR] 	                                                ^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] JettyWebSocketCreator cannot be resolved to a type
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[47] 
#23 302.4 [ERROR] 	public Object createWebSocket(JettyServerUpgradeRequest request, JettyServerUpgradeResponse resp) {
#23 302.4 [ERROR] 	                              ^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] JettyServerUpgradeRequest cannot be resolved to a type
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[47] 
#23 302.4 [ERROR] 	public Object createWebSocket(JettyServerUpgradeRequest request, JettyServerUpgradeResponse resp) {
#23 302.4 [ERROR] 	                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] JettyServerUpgradeResponse cannot be resolved to a type
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[66] 
#23 302.4 [ERROR] 	private BaseWebSession resolveWebSession(JettyServerUpgradeRequest request) throws DBException {
#23 302.4 [ERROR] 	                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] JettyServerUpgradeRequest cannot be resolved to a type
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[72] 
#23 302.4 [ERROR] 	var webSession = webSessionManager.getSession(webSessionId);
#23 302.4 [ERROR] 	                                   ^^^^^^^^^^
#23 302.4 [ERROR] The method getSession(String) in the type WebSessionManager is not applicable for the arguments (Object)
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/websockets/CBJettyWebSocketManager.java:[74] 
#23 302.4 [ERROR] 	return webSession;
#23 302.4 [ERROR] 	       ^^^^^^^^^^
#23 302.4 [ERROR] Type mismatch: cannot convert from Object to BaseWebSession
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/jetty/CBJettyServer.java:[36] 
#23 302.4 [ERROR] 	import org.eclipse.jetty.websocket.server.config.JettyWebSocketServletContainerInitializer;
#23 302.4 [ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] The import org.eclipse.jetty.websocket.server cannot be resolved
#23 302.4 [ERROR] /cloudbeaver/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/jetty/CBJettyServer.java:[117] 
#23 302.4 [ERROR] 	JettyWebSocketServletContainerInitializer.configure(servletContextHandler,
#23 302.4 [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#23 302.4 [ERROR] JettyWebSocketServletContainerInitializer cannot be resolved
#23 302.4 [ERROR] 11 problems (11 errors)
#23 302.4 [ERROR] -> [Help 1]

**To Reproduce**
As you can see, I'm using the dockerfile to build it and unfortunately I cannot share its content.

**Desktop (please complete the following information):**
 - OS: adoptopenjdk/openjdk15:x86_64-ubuntu-jdk-15.0.2_7 image
 - Version 23.0.1

**Additional context**
Can you help me with this? Should I update the tycho version? I already tried installing the jetty with dockerfile commands just before running the build.sh: 
RUN wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.43.v20210629/jetty-distribution-9.4.43.v20210629.tar.gz && \
    tar -xzf jetty-distribution-9.4.43.v20210629.tar.gz && \
    mv jetty-distribution-9.4.43.v20210629 /opt/jetty && \
    rm jetty-distribution-9.4.43.v20210629.tar.gz
ENV JETTY_HOME /opt/jetty
ENV PATH $PATH:$JETTY_HOME/bin
But it didn't help.

Thanks in advance.

**Comment by TatyanaSsau** [comment]
@gboreczek thank you for reporting!
Could you please send a screenshot and web console details? It will help me to assess the issue and find a solution.

**Comment by gboreczek** [comment]
@TatyanaSsau sure, thanks for the reply :) Here are the screenshots from the console:
![image](https://user-images.githubusercontent.com/103647431/236125478-6dad841f-7e61-4334-9df4-2b45d0e8a40d.png)
![image](https://user-images.githubusercontent.com/103647431/236125965-181e202c-176f-40ff-b70c-81e0fe111e1a.png)

**Comment by alexander-skoblikov** [comment]
@gboreczek Hi, are you using the latest version?

**Comment by gboreczek** [comment]
Hi, I'm using v. 23.0.1

**Comment by alexander-skoblikov** [comment]
Can you update to the latest version? Your version uses dependencies that are no longer available

**Comment by gboreczek** [comment]
I used 23_0_4 and I think it helped a little, but unfortunately, there is another error :( :
![image](https://github.com/dbeaver/cloudbeaver/assets/103647431/afbe5a1f-2218-48d1-8022-37d18a539436)

**Comment by alexander-skoblikov** [comment]
@gboreczek, can you attach full build log?

**Comment by gboreczek** [comment]
[build_sh_log.txt](https://github.com/dbeaver/cloudbeaver/files/11463138/build_sh_log.txt)
Hi, sure, I can. But let me warn you - it's enormous.

**Comment by alexander-skoblikov** [comment]
@gboreczek Hi, have you modified the drivers? Please check that [h2_v2](https://github.com/dbeaver/cloudbeaver/tree/devel/server/drivers/h2_v2) driver included in your build

**Comment by AGlowczewska** [comment]
Hi, let me reply for the future reference.

Yes, we were adding drivers with @gboreczek , the problem was with ours .pom declarations . It changed between versions 22 and 23 and we needed to upgrade. The exact problem was with the file: drivers/pom.xml Once we copied the newest CloudBeaver version and added our delta, it started working :)

**Comment by TatyanaSsau** [comment]
I'm glad to hear that the issue isn't actual anymore.

@AGlowczewska @gboreczek thank you for your interest in CloudBeaver!
