### ISSUE TITLE
View bytea type data  decoded

### ISSUE THREAD

**Issue by diegopazosrego** [dbeaver/cloudbeaver#1642]
Hi,

I am using since some time the cloudbeaver solution and I have in a PostgreSQL database columns in tables with bytea data type. In the desktop application I have been able to change it to see the data in plain without being encoded but however in the cloudbeaver web version I can't change it to see the data decoded. 

Is there any option to change like in the desktop version to see the data without encoding?

I attach an image of how the data looks like. 

<img width="285" alt="image" src="https://user-images.githubusercontent.com/35931756/236434286-f81ca2aa-ec23-468b-b47e-fb0be6642c2c.png">

Thanks in advance

**Comment by TatyanaSsau** [comment]
Hello, @diegopazosrego thanks for the report!
Could you send both screenshots - from DBeaver and CloudBeaver? It helps me to reproduce the issue and find a solution.

**Comment by diegopazosrego** [comment]
Hi @TatyanaSsau ! 

In cloudbeaver I cannot find this option, but in DBeaver this is the option:

This options allow to us to view all bytea data in String, Hex or base64 . 

![image](https://github.com/dbeaver/cloudbeaver/assets/35931756/777cef37-30bb-4ccf-95b9-d8b2b65def92)

Many thanks in advance

**Comment by TatyanaSsau** [comment]
Thank you for the update! This is a new feature for CloudBeaver version.
But I just want to know the details - how it works in your case: how it looks in DBeaver when you use a different data format.

**Comment by diegopazosrego** [comment]
Thank you very much! In our case it works that if we have that option checked in the viewer for each column of a table we can see the data in hex, string or base64 without having to do some kind of query.

**Comment by jonasbenjaminsson** [comment]
Regardless of which database being used, it would be great to be able to change the view format on binary columns. In the DBeaver application you may right click on the column and change the binary view format to one of "string", "hex" and "base64".
Applied to a guid that is stored in binary format you will get the following in the view:
string - " y~ò à H ªÄ¥ìy U"
hex - "01797EF214E00A4892AAC4A5EC798D55"
base64 - "AXl+8hTgCkiSqsSl7HmNVQ=="

In some cases it really helps being able to copy the hex value, as in the case with guids as identifiers when you want to find that record in another table using the guid.

**Comment by TatyanaSsau** [comment]
@diegopazosrego @jonasbenjaminsson thank you for your suggestion - we are going to implement in the near future.

**Comment by dariamarutkina** [comment]
Hello, @diegopazosrego !
We added the ability to view decoded binary-type data in the Value panel. Please take a look at the new version of CloudBeaver 23.3.2.
Thank you for your interest in CloudBeaver!

**Comment by jonasbenjaminsson** [comment]
That's great and a step in the right direction, thank you.

It would still be useful to be able to choose how it is shown in the column, as in the DBeaver application.
E.g.
Given that the primary keys on all tables are guids.
I do a select and get a handful of records as a result, the id's of those I would like to use in some way, either to send to a collegue or use in another query.
Yes, you could argue that i could use a join a similar, but it is not allways possible.
So, seeing the guids in hex representation in the column of the data grid would make it possible to copy many ids instead of copying them one by one from the value-window.

**Comment by diegopazosrego** [comment]
Hi @dariamarutkina , @TatyanaSsau !

Thanks for the implementation ! I think despite that it would be interesting that in the connection manager itself or in some option ( some configuration value) that it would be allowed to show that BLOB value in all that database in the default type you choose without having to go one by one as it is very laborious.

Thank you very much

**Comment by diegopazosrego** [comment]
Hi @dariamarutkina @TatyanaSsau ,

Any news on this?

**Comment by LonwoLonwo** [comment]
Hello @diegopazosrego 

Please create a separate ticket for your request.
