### ISSUE TITLE
build cloudbeaver

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1650]
mvn clean verify -Dheadless-platform

Is this step necessary?
If i explanatory note this，is it can success

**Comment by TatyanaSsau** [comment]
@ccczhouxin Could you please add more details descriptions with steps to reproduce in the ticket content. And what CloudBeaver version do you use? Or which article? 
It will help me to assess the issue and find a better solution.

**Comment by ccczhouxin** [comment]
Because the database not in dbeaver,i add it in local dbeaver,when i use cloudbeaver and click "bulid,bat",it has error, the error is can not resolve maven by ourself database. The cloudbeaver version is the last version.

**Comment by ccczhouxin** [comment]
I use mvn clean verify is right
