### ISSUE TITLE
The ssh tunnel aliveInterval config is invalid. 

### ISSUE THREAD

**Issue by dlsaint** [dbeaver/cloudbeaver#1657]
**Describe the bug**
The ssh tunnel aliveInterval config is invalid. When I set it up, we didn't see heartbeat in tcpdump

**Screenshots**
![image](https://github.com/dbeaver/cloudbeaver/assets/7350452/b1ee577b-3eaf-4b88-b1c3-d0d81c08674b)
![image](https://github.com/dbeaver/cloudbeaver/assets/7350452/787b0bbf-b8b2-4d2f-a05e-a1e7cddc4bfc)

**Comment by TatyanaSsau** [comment]
@dlsaint thank you for the report! Please let me know -what CloudBeaver version do you use?

**Comment by dlsaint** [comment]
lastest version, dbeaver/cloudbeaver:23.0.4 , I deployed it through Docker. @TatyanaSsau 
![image](https://github.com/dbeaver/cloudbeaver/assets/7350452/d4800a80-8327-49fb-b806-da0f15b5e67d)

**Comment by dlsaint** [comment]
Do you have a scheduled time for fixing it? My server's SSH connection often drops due to no heartbeat, which requires me to manually reconnect to the database repeatedly.
@TatyanaSsau

**Comment by TatyanaSsau** [comment]
@dlsaint we added it to the backlog to provide a solution to this case.

**Comment by dariamarutkina** [comment]
Fixed in milestone 23.1.0
