### ISSUE TITLE
Compression on export - zip/tar support

### ISSUE THREAD

**Issue by anapoc** [dbeaver/cloudbeaver#1660]
**Is your feature request related to a problem? Please describe.**
When doing exports on large tables >1 mil record output file is large and takes time to download.

**Describe the solution you'd like**
Add compression, zip or tar.

**Comment by TatyanaSsau** [comment]
@anapoc Thank you for the feature request. We are going to implement it in the near future

**Comment by dariamarutkina** [comment]
The ability to compress files during export allows for faster download speeds, particularly for larger files. When exporting a file, the 'Compression' checkbox appears in the settings.
Thank you for your interest in CloudBeaver!
