### ISSUE TITLE
java.io.FileNotFoundException:**/cloudbeaver/web/index.html

### ISSUE THREAD

**Issue by liukekeke** [dbeaver/cloudbeaver#1662]
The prompt file does not exist, actually it does. After restarting the service, it will work normally

**Comment by TatyanaSsau** [comment]
@liukekeke thank you for the report! 
Please let me know - what CloudBeaver version do you use? Is it happen after updates?

**Comment by liukekeke** [comment]
22.2.2 
During use, there is a probability that this problem will occur, and once it occurs, there will be no problem restarting

**Comment by TatyanaSsau** [comment]
@liukekeke please, could you send me more detailed description with the steps to reproduce in the ticket content in order to assess the issue and help you to solve it.

**Comment by liukekeke** [comment]
![image](https://github.com/dbeaver/cloudbeaver/assets/32697210/a5bdef9e-69ca-4d56-8ed3-eb7119cebeb1)

**Comment by liukekeke** [comment]
<img width="901" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/32697210/1d05eafe-25df-4ac6-a06f-26380972765a">

**Comment by liukekeke** [comment]
<img width="1223" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/32697210/bb5ad387-4e72-4d68-aede-71030857706a">

**Comment by TatyanaSsau** [comment]
@liukekeke thank you for your suggestion - we are going to fix this behavior

**Comment by LonwoLonwo** [comment]
Hello @liukekeke 

We have many updates since last year. Is this issue still actual for you?

**Comment by LonwoLonwo** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by wangyabingjob** [comment]
> <img alt="image" width="1223" src="https://private-user-images.githubusercontent.com/32697210/240900995-bb5ad387-4e72-4d68-aede-71030857706a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc4NTg5NzIsIm5iZiI6MTczNzg1ODY3MiwicGF0aCI6Ii8zMjY5NzIxMC8yNDA5MDA5OTUtYmI1YWQzODctNGU3Mi00ZDY4LWFlZGUtNzEwMzA4NTc3MDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI2VDAyMzExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNGNjY2I4MzdiODFhZWM0MzgyYWM2MzAyMGQ3NDAwNjc3MDI0NzRjZWY0ZWMwYWJkNDhhMzhiMTRhOTk0ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lwt4hpXMDmSSPFvU-6ClQHSQ7H6iWbZ0RdLNarZTOLo">

Did you solve this error？

**Comment by wangyabingjob** [comment]
[https://github.com/dbeaver/cloudbeaver/issues/1662#issuecomment-1562754796](url)

Did you solve this error?
