### ISSUE TITLE
How can i import csv to sql table use cloudBeaver Community?

### ISSUE THREAD

**Issue by liuyu2013** [dbeaver/cloudbeaver#1668]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TatyanaSsau** [comment]
@liuyu2013 Thank you for the feature request. Unfortunately, we do not have an estimated time for this ticket now.

Closed as duplicate https://github.com/dbeaver/cloudbeaver/issues/1507
