### ISSUE TITLE
Commit Changes Option

### ISSUE THREAD

**Issue by bossdu15000** [dbeaver/cloudbeaver#1670]
Good morning,
the commit option was planned for 1.3 but you have moved from 1.2 to 21.3.
when is this option available?

Feature request: https://github.com/dbeaver/cloudbeaver/issues/129

Cordially

**Comment by TatyanaSsau** [comment]
@bossdu15000 sorry for really long time to response! 
It is not completely dropped, but this task is in the long-term plans for our team.

Thank you for your interest in CloudBeaver!

Close as duplicate https://github.com/dbeaver/cloudbeaver/issues/129
