### ISSUE TITLE
How download 23.0.4 veriosn

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1677]
How download 23.0.4 veriosn cloudbeaver

**Comment by TatyanaSsau** [comment]
@ccczhouxin hello! I hope that document will help you https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container
with different versions.

And https://hub.docker.com/r/dbeaver/cloudbeaver - Community Edition version
