### ISSUE TITLE
CloudBeaver startup will throw an error 

### ISSUE THREAD

**Issue by q2221407** [dbeaver/cloudbeaver#1679]
CloudBeaver startup will throw an error ERROR i.c.s.d.t.i.WebServiceDataTransfer - Error re-creating temporary folder java.nio.file.AccessDeniedException: D:\runtime-DBeaverWebServer.product\.work-data\data-transfer

**Comment by TatyanaSsau** [comment]
@q2221407 please, let me know - what CloudBeaver version do you use?
And please share all logs file.

**Comment by q2221407** [comment]
devel and release_23_0_4

**Comment by TatyanaSsau** [comment]
@q2221407 Are you using Docker or source files?
Please, could you send me a description with the steps to reproduce?

**Comment by TatyanaSsau** [comment]
@q2221407 I've noticed there is no updates for a long time. 
Please - feel free to contact me to reopen the ticket if it's still actual.
