### ISSUE TITLE
社区版支持oracle吗？ 

### ISSUE THREAD

**Issue by wukaiqiang520** [dbeaver/cloudbeaver#1682]
为什么我下载的社区版没有oracle的驱动
Why doesn't the community edition I downloaded come with the Oracle driver?

**Comment by TatyanaSsau** [comment]
@wukaiqiang520 thank you for the report!
You can use Oracle driver with Community Edition version. Please, look at this document about addition: https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-overview

**Comment by TatyanaSsau** [comment]
@wukaiqiang520 I've noticed there is no updates for a long time. 
Please - feel free to contact me to reopen the ticket if you have another question!
