### ISSUE TITLE
Disable update check

### ISSUE THREAD

**Issue by hbenali** [dbeaver/cloudbeaver#1689]
Is it possible to disable update checks? I'd like to manage upgrades throughout the docker tag change instead of WebUI. Thanks

**Comment by TatyanaSsau** [comment]
@hbenali, thank you for reporting!
Could you please provide an example? I want to clarify what the checks you are referring to.

**Comment by hbenali** [comment]
> @hbenali, thank you for reporting! Could you please provide an example? I want to clarify what the checks you are referring to.

Of course, taking the case of Cloudbeaver CE 23.0.4 (docker), when visiting the web interface, a pop-up appears asking for an upgrade (CE 23.0.5 was released). I want to manage the upgrade through the Docker image release, not through the web UI. Hope it's clear. Thanks!

**Comment by TatyanaSsau** [comment]
@hbenali thank you for your suggestion. we are going to implement a new config parameter to turn off notifications.

Additionally, could you please supply me with screenshots featuring this pop-up? This will help me clarify precisely what you are referring to.

**Comment by lancelotly** [comment]
<img width="1217" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/10369253/6b98e489-829a-4046-aebe-8618aa344160">
The update popup seems cannot be closed.

**Comment by webysther** [comment]
In this case I think the fastest and flexible is make available a ENV to disable or enable this warning, as example: `ENABLE_UPDATE_WARNING=true|false`, with this will be easy to every user change this behavior on docker or any other install method.

**Comment by dariamarutkina** [comment]
We added to refresh the page automatically instead of displaying dialog & notification
Thank you for your interest in CloudBeaver!
