### ISSUE TITLE
Q: Multi-DB-Connection

### ISSUE THREAD

**Issue by jonasbadstuebner** [dbeaver/cloudbeaver#1694]
Hello there,

I just upgraded from 22.3.5 to 23.0.5. Worked like a charm - with only one thing popping up: How do I tell DBeaver to show me all databases on the server? (Postgres)

In the changelog it reads `the URL-configuration for PostgreSQL now correctly displays only a single database`, is this related?
How do I "wildcard" the database-name, so I don't have to have one database connection per db, but credentials per host? Just leaving it empty does not work.

Thank you in advance!
BR

**Comment by jonasbadstuebner** [comment]
I know, that you cannot show the DB or it's contents before connecting to it, but I saw all the databases on the host listed in the web view before. Why is this gone now? And how could I bring it back, is the question. :)

**Comment by TatyanaSsau** [comment]
@DrBu7cher thank you for your interest in CloudBeaver!!! :)
![image](https://github.com/dbeaver/cloudbeaver/assets/79170253/dc26adfc-e4cc-4ec5-9d9e-4fe0a1205a4f)

To display all databases - you need to choose Configuration - > **Manual**
![image](https://github.com/dbeaver/cloudbeaver/assets/79170253/7d4a722f-e8a6-482a-aa80-0351c70a5d31)

And than Settings -> **Show all databases**

**Comment by jonasbadstuebner** [comment]
This worked, thank you very much! :)
