### ISSUE TITLE
[web] TypeError: t.extensions is undefined

### ISSUE THREAD

**Issue by jonasbadstuebner** [dbeaver/cloudbeaver#1695]
**Describe the bug**
When I restart the container, I see `TypeError: t.extensions is undefined` in the web frame.

**To Reproduce**
1. Upgrade from 22.3.5 to 23.05 (I recently updated, this might be related?)
2. (Log in in web) (I didn't witness this problem when not logged in, because I was logged in)
4. Restart container
5. Go to web
6. See error

**Screenshots**
![grafik](https://github.com/dbeaver/cloudbeaver/assets/18399895/4f458c45-35c2-4329-b536-dfc5b990b756)

**Desktop (please complete the following information):**
 - Browser Firefox (unrelated)
 - Version 113.0.1

**Additional context**
If I refresh with clearing the cache, it works again. But this is unexpected still.

**Comment by TatyanaSsau** [comment]
@DrBu7cher please - let me know - is that permanently reproduced?

**Comment by jonasbadstuebner** [comment]
I cannot reproduce it anymore. I completely reinstalled my cluster lately, the error is gone - I think it had something to do with the local cache. The same part that would intercept the 503 error on client side, if there is any (I saw this happen).
So I propose we keep it open, for a week or two, maybe someone else can reproduce/has the same the issue?
If not...we just look away :see_no_evil:

**Comment by TatyanaSsau** [comment]
@DrBu7cher I completely agree! 

And thank you again for your suggestion!!!

**Comment by TatyanaSsau** [comment]
We released version 23.1.1 and I think the error is completely gone.

**Comment by TatyanaSsau** [comment]
Closed as completed and Thank you for the interest in CloudBeaver!
