### ISSUE TITLE
Cursor jump

### ISSUE THREAD

**Issue by AmiasLi** [dbeaver/cloudbeaver#1700]
**Version: 23.0.5**

**Describe the bug**
The cursor still jumps randomly when selecting field from code prompts sometimes.

**To Reproduce**
Example 1:
1. Type the table alias with comma before from key word, and the code prompts display nomal
2. when I choose the third field in code prompt, and then the cursor will jump to the first field

![image](https://github.com/dbeaver/cloudbeaver/assets/121344381/3d4809c9-8ca6-46e0-98f6-c5f8e3eb45f6)

Example 2:
1. Complete the column name according to code hint
2. The cursor will jump to the above line

![image](https://github.com/dbeaver/cloudbeaver/assets/121344381/0d15458b-5806-4a1b-93e7-68140cf06af8)

**Desktop**
 - OS: Windows 10
 - Browser chrome
 - Version latest

**Comment by TatyanaSsau** [comment]
@AmiasLi sorry for the really long delay in response. We released version 23.1.0, which includes a new SQL Editor and several enhancements to the suggestion. I recommend giving it a try. And case 2 is already fixed.

**Comment by TatyanaSsau** [comment]
There is no updates for a long time.
@AmiasLi You are welcome to reach out to me if you want to reopen. Hopefully, the issue is no longer relevant at this time.
