### ISSUE TITLE
Max size of the uploaded SQL script file

### ISSUE THREAD

**Issue by ihor-lysukha** [dbeaver/cloudbeaver#1720]
Hello there,

I hope you can help me with clarifying the following point.

I use the CloudBeaver CE version 22.2.0 which is running as a Google Cloud Run service instance. When I try to upload a SQL script file for the current DB connection into CloudBeaver I get such a warning message:
`File size exceeds max size`
`Max size: 100KB`
`File size: XXXXKB`

I've looked through the official CloudBeaver documentation but unfortunately, I didn't find any section with an explanation of how the max size of the uploaded SQL script file is possible to configure for the CloudBeaver instance. I tried to increase the `resourceManagerFileSizeLimit` parameter in `resourceQuotas` but it didn't help.

I'd appreciate it if you could provide me with any information regarding the possibility to manage this `max size` parameter.

BR

**Comment by dariamarutkina** [comment]
Hello @ihor-lysukha,
Try to change the parameter in [this instruction](https://github.com/dbeaver/cloudbeaver/wiki/Product-settings-sql-editor) please
And please tell me later if it will help
Thank you for your interest in CloudBeaver.

**Comment by ihor-lysukha** [comment]
> Hello @ihor-lysukha, Try to change the parameter in [this instruction](https://github.com/dbeaver/cloudbeaver/wiki/Product-settings-sql-editor) please And please tell me later if it will help Thank you for your interest in CloudBeaver.

Hi @dariamarutkina , thank you for the reference, it seems that I've missed this. I will try to configure a parameter following the manual and let you know if it helps.

**Comment by ihor-lysukha** [comment]
> Hello @ihor-lysukha, Try to change the parameter in [this instruction](https://github.com/dbeaver/cloudbeaver/wiki/Product-settings-sql-editor) please And please tell me later if it will help Thank you for your interest in CloudBeaver.

Hello @dariamarutkina , it works as expected. Thanks for your assistance!

**Comment by dariamarutkina** [comment]
I'm glad that the issue isn't actual anymore. 
Thank you for the interest in Cloud Beaver!
