### ISSUE TITLE
Elements are limited to 1000 items and cannot be changed

### ISSUE THREAD

**Issue by HappinerWinnie** [dbeaver/cloudbeaver#1728]
![image](https://github.com/dbeaver/cloudbeaver/assets/31788525/324b5594-c2b5-49fd-9e67-98e9aa35f008)

![image](https://github.com/dbeaver/cloudbeaver/assets/31788525/38d0a0a7-4efe-42bd-8f90-323b0247382f)

![image](https://github.com/dbeaver/cloudbeaver/assets/31788525/b5b13c7c-4bee-4f8b-8ce1-18d794a76c38)

As shown in the picture, I found a prompt during using the software: "Elements are limited to 1000 items". I needed to be able to see more information, so I found the corresponding line of code and changed it to 2000 and posted it, but it didn't work

In addition, I found that the invisible data table cannot be searched in the search bar. I think there is a problem with this design. You can limit the number of displays, but it should not prevent me from searching it out. 
![image](https://github.com/dbeaver/cloudbeaver/assets/31788525/81910de7-7251-4934-9c23-d3719c9f3688)

**Comment by dariamarutkina** [comment]
Hello, @HappinerWinnie !
Please use these instructions and please tell me if it helped or not: https://github.com/dbeaver/cloudbeaver/wiki/Product-configuration-parameters and https://github.com/dbeaver/cloudbeaver/wiki/Product-settings-navigation-tree 
Thank you for the interest in Cloud Beaver!

**Comment by HappinerWinnie** [comment]
@dariamarutkina It works, thks
