### ISSUE TITLE
versions_load_fail after a few seconds

### ISSUE THREAD

**Issue by hmmftg** [dbeaver/cloudbeaver#1736]
**Describe the bug**
When we deploy app to environment which has no internet access, after a few seconds it keeps displaying **Resource Error** versions_load_fail and the retry key does nothing and we have to reload the page.

**To Reproduce**
1. Open app in a client with no internet access
2. Stay on any page for a few seconds
3. See error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [opera]
 - Version [99.0.4788.13]

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by TatyanaSsau** [comment]
@hmmftg thank you for reporting!
This is a known issue. We are going to fix it after 23.1.1

**Comment by ben-singlet** [comment]
Hi,

Any idea when the 23.1.1 version will be available ?
This bug is a real blocker...

Many thanks in advance ;)

**Comment by TatyanaSsau** [comment]
@ben-singlet the release 23.1.1 is scheduled for June 26th.

**Comment by dariamarutkina** [comment]
Fixed in 23.1.1
Thank you for your interest in CloudBeaver!
