### ISSUE TITLE
首页加载速度特别慢

### ISSUE THREAD

**Issue by cplinux98** [dbeaver/cloudbeaver#1749]
**Describe the bug**
第一次访问首页的时候，会很慢，通过浏览器的开发者工具发现，每次打开时会向：https://fonts.googleapis.com/css?family=Roboto:300,400,500,700 发起请求，导致延迟20s左右

**To Reproduce**

**Screenshots**
<img width="1987" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91673303/74100a0a-360a-462f-8bfb-a54ae7da08b7">

**Desktop (please complete the following information):**

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by TatyanaSsau** [comment]
@cplinux Could you please describe step by step what are you doing and what doesn't work? It will help me to assess the issue and find a solution.
Also I kindly ask you to write all information in English.

**Comment by cplinux98** [comment]
> @cplinux Could you please describe step by step what are you doing and what doesn't work? It will help me to assess the issue and find a solution. Also I kindly ask you to write all information in English.

When visiting the homepage for the first time, it will be very slow. Through the developer tool of the browser, it will be displayed to: https://fonts.googleapis.com/css?family=Roboto:300 400500700 initiated the request, resulting in a delay of about 20 seconds

**Comment by TatyanaSsau** [comment]
@cplinux thank you for your report!
We added it to the backlog to provide solution with this case.

**Comment by dariamarutkina** [comment]
We fixed this in version 23.1.5
Please, check CloudBeaver v.23.1.5
@cplinux , thank you for interesting in CloudBeaver!
