### ISSUE TITLE
How add a new database

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1752]
Dbeaver has our database，how to add it to cloudbeaver

**Comment by cnkidong** [comment]
You can refer to website below:
https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers
I added our own database according to the method.

**Comment by ccczhouxin** [comment]
> You can refer to website below: https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers I added our own database according to the method.

![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/c62cce13-f42b-4eab-b025-942313609deb)
are you set it generic

**Comment by TatyanaSsau** [comment]
@cnkidong @ccczhouxin also we added a new option to add new driver - here wiki page https://github.com/dbeaver/cloudbeaver/wiki/Drivers-Management

The option has been available since version 23.1. for EE version

**Comment by ccczhouxin** [comment]
> @cnkidong @ccczhouxin我们还添加了一个新选项来添加新驱动程序 - 这里是 wiki 页面https://github.com/dbeaver/cloudbeaver/wiki/Drivers-Management
> 
> 该选项自版本 23.1 起可用。

![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/6fa8b969-34e0-447d-b61f-82584756f74d)
I can not find the options to add new database

**Comment by TatyanaSsau** [comment]
@ccczhouxin you can find [Drivers Management](https://github.com/dbeaver/cloudbeaver/wiki/Drivers-Management) in EE version.
For CE version is better to choose [Adding new database](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers) article

**Comment by ccczhouxin** [comment]
> @ccczhouxin您可以在 EE 版本中找到[驱动程序管理。](https://github.com/dbeaver/cloudbeaver/wiki/Drivers-Management) 对于 CE 版本最好选择[Adding new database](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers)文章

I  choose the [Adding new database](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers) article，the dbeaver can use my database，but i follow the step of that article，when i start CE ，it has not my database。
this is my configuration，
![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/b78d4536-6674-4e2f-9c82-4b65188f8986)

![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/c9f50309-cdf1-4959-9585-2d7a7f76fb0c)

![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/c03b400a-2d2d-43e4-af7b-7ca49596f5bc)

I don not know where else is not configured

**Comment by ccczhouxin** [comment]
> @ccczhouxin您可以在 EE 版本中找到[驱动程序管理。](https://github.com/dbeaver/cloudbeaver/wiki/Drivers-Management) 对于 CE 版本最好选择[Adding new database](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers)文章

Can you help me
