### ISSUE TITLE
new database error

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1764]
I added a database on the home page and an error occurred when I clicked on the home page icon to view the details.
![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/fd9394cb-fcbb-4226-bc78-06373f261bf6)

[error.txt](https://github.com/dbeaver/cloudbeaver/files/11744168/error.txt)

**Comment by serge-rider** [comment]
Do you use a custom build of CloudBeaver? If so then do you use maven to build product?

I see a lot of errors which include plugins which mustn't be in server build.

**Comment by ccczhouxin** [comment]
> Do you use a custom build of CloudBeaver? If so then do you use maven to build product?
> 
> I see a lot of errors which include plugins which mustn't be in server build.

Yes i built with the steps. I use build.bat is ok.

**Comment by ccczhouxin** [comment]
> > Do you use a custom build of CloudBeaver? If so then do you use maven to build product?
> > I see a lot of errors which include plugins which mustn't be in server build.
> 
> Yes i built with the steps. I use build.bat is ok.

I  just add database in feature.xml。if not add，the cloudbeaver don not have my database。
