### ISSUE TITLE
cloudbeaver build error

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1770]
I add a new database has these erros。
![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/dcf98740-bf2c-44e5-97ea-75ab6b57dbdb)

**Comment by TatyanaSsau** [comment]
@ccczhouxin pleease - give me information about the version
and describe steps to reproduce.

**Comment by ccczhouxin** [comment]
> @ccczhouxin pleease - give me information about the version and describe steps to reproduce.

The version is 23.1.0，in dbeaver ，i can start my database，when i add my database in feature.xml.  Start cloudbeaver then has these errors。
![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/a32b8ac4-36a1-4bca-adeb-c86525299503)
