### ISSUE TITLE
Hive support

### ISSUE THREAD

**Issue by mencwelp** [dbeaver/cloudbeaver#178]
Please add Apache Hive support

**Comment by serge-rider** [comment]
This makes sence.
We need to decide what driver we can include. It must be OS and must be in the Maven Central.

Official one is https://mvnrepository.com/artifact/org.apache.hive/hive-jdbc
But it is too heavy (about 180Mb). And contains a lot of redundant artifacts.

Or, perhaps, we could make separate CB build for Hadoop based databases.

**Comment by mencwelp** [comment]
BTW - hive-jdbc-3.1.2-standalone.jar    is 68 MB
alternative hive-jdbc-uber-2.6.5.0-292.jar 17,6MB
Meby some kind of customizable build configuration, so ppl will enable these drivers that are needed?

**Comment by serge-rider** [comment]
At the moment we don't have plans to add Hive/Impala drivers in CloudBeaver CE (mostly because mess with drivers and huge distribution size).
But you could try to do it by yourself by configuring Hive drivers in CB, see https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers

**Comment by kseniiaguzeeva** [comment]
Hive driver is added to Enterprise Edition. You can try it for free https://cloudbeaver.io/try-it-now/.
