### ISSUE TITLE
Option for adding ODBC-connections

### ISSUE THREAD

**Issue by TobiasTDV** [dbeaver/cloudbeaver#1786]
Unfortunately, I don't see any way to add database connections based on the ODBC driver.
Is it possible to implement ODBC connections in the connection management of Cloudbeaver?
With DBeaver there seems to be this possibility:
https://dbeaver.com/docs/wiki/ODBC-JDBC-Driver/

**Comment by TatyanaSsau** [comment]
@TobiasTDV Thank you for the suggestion! 
We will add ODBC driver in EE version CloudBeaver.

**Comment by LonwoLonwo** [comment]
Hello @TobiasTDV 

Could you please provide more information about your request? What exactly driver do you want to use? And why? 
You can add it now in our EE version inside the docker configuration. However, you need to configure it on Linux and most ODBC drivers for Windows. 

The picture from the EE CloudBeaver version:

![2024-05-24 12_48_25-CloudBeaver Enterprise](https://github.com/dbeaver/cloudbeaver/assets/45152336/8adc90d0-545d-4bcb-bba8-fe9964f33b97)

**Comment by LonwoLonwo** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
