### ISSUE TITLE
After  import cloudbeaver into  Eclipse，I got this problem.

### ISSUE THREAD

**Issue by highgo-srk** [dbeaver/cloudbeaver#1793]
I followed the Develop in Eclipse guid https://github.com/dbeaver/cloudbeaver/wiki/Develop-in-Eclipse
but I get this problem 
how can I solve it ？
<img width="955" alt="issue" src="https://github.com/dbeaver/cloudbeaver/assets/62869157/9ce66369-b376-4bba-9ed4-50c08f7d5986">

**Comment by TatyanaSsau** [comment]
@Killer-srk Please, follow [these](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse) instructions to update the dependencies - it should resolve the issue. 
Additionally, please make sure you are using Eclipse ver.23.06 and Java ver.17

**Comment by TatyanaSsau** [comment]
@Killer-srk I've noticed there is no updates for a long time.
Please - feel free to contact me to reopen the ticket if it's still actual.
