### ISSUE TITLE
waffle-jna driver for sspi auth in postgres 

### ISSUE THREAD

**Issue by njesp** [dbeaver/cloudbeaver#18]
It would be nice, if the waffle-jna jars were included in the driversetup  for Postgres. 

This in order to have builtin support for SSPI auth against Postgres om Windows.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
Since 1.0.2 it is possible to put any extra jars in drivers/postgresql. They will be loaded automatically.
