### ISSUE TITLE
Support for major and minor release docker

### ISSUE THREAD

**Issue by webysther** [dbeaver/cloudbeaver#1802]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for `docker pull dbeaver/cloudbeaver:23` to update the image only with no-breaking changes

**Comment by TatyanaSsau** [comment]
@webysther we are going to fix it in 23.1.2 version. the known issue [here](https://github.com/dbeaver/cloudbeaver/issues/1689)

**Comment by webysther** [comment]
Hi @TatyanaSsau is related but not the same, look, https://hub.docker.com/_/postgres, in this project I can choose the major in docker, I think the warning about new version is more about UX and make available a ENV to disable.

![image](https://github.com/dbeaver/cloudbeaver/assets/750007/c534fd18-5ecd-4de3-a5c2-47bc9826323a)

**Comment by TatyanaSsau** [comment]
@webysther thank you for your suggestion!
It is a feature request for us and we added it to the backlog to provide solution with this case.

**Comment by webysther** [comment]
Hi @TatyanaSsau, here a sample of how this is made using github actions for ghcr and hub name: https://github.com/webysther/hoppscotch-docker/blob/main/.github/workflows/docker-container-publish.yml

**Comment by TatyanaSsau** [comment]
@webysther Thank you! This is helpful for us, and we are working on it now. I will inform you once we reach a decision.

**Comment by TatyanaSsau** [comment]
@webysther We have added several more tags for the ability to download the major version of CloudBeaver. You can now choose from the following Docker options for e.g.: 23 - yearly, 23.1 - seasonal, 23.1.4 - minor

**Comment by webysther** [comment]
Really great! thanks a lot!!!
