### ISSUE TITLE
Build Very Slowly

### ISSUE THREAD

**Issue by HappinerWinnie** [dbeaver/cloudbeaver#1808]
Please, describe your question in details.
[WARNING] [9622c996-9ccb-4d85-a5cd-f040adea987c][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.1] The digest algorithms (md5) used to verify osgi.bundle,org.jkiss.bundle.apache.poi,4.1.1 have severely compromised security. Please report this concern to the artifact provider.

[WARNING] [9622c996-9ccb-4d85-a5cd-f040adea987c][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.1] The digest algorithms (md5) used to verify osgi.bundle,com.jcraft.jsch,0.2.8 have severely compromised security. Please report this concern to the artifact provider.

[WARNING] [9622c996-9ccb-4d85-a5cd-f040adea987c][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.1] The digest algorithms (md5) used to verify osgi.bundle,org.jkiss.bundle.sshj,0.34.1 have severely compromised security. Please report this concern to the artifact provider.

[WARNING] [9622c996-9ccb-4d85-a5cd-f040adea987c][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.1] The digest algorithms (md5) used to verify osgi.bundle,org.jkiss.bundle.jetty.server,1.0.2 have severely compromised security. Please report this concern to the artifact provider.
[WARNING] [9622c996-9ccb-4d85-a5cd-f040adea987c][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.1] The digest algorithms (md5) used to verify osgi.bundle,org.jkiss.bundle.jetty.websocket,1.0.5 have severely compromised security. Please report this concern to the artifact provider.

Every time a prompt similar to the above appears, the program will be stuck for a long time before going down
Usually it takes 1 hour or more to build. Is there any good way?
The problem is mainly focused on the following packages：
![image](https://github.com/dbeaver/cloudbeaver/assets/31788525/9c31bcba-242a-4781-b2a8-081cf507e10c)

**Comment by TatyanaSsau** [comment]
@HappinerWinnie could you please provide the log file?

**Comment by HappinerWinnie** [comment]
@TatyanaSsau 
sure，
[build.zip](https://github.com/dbeaver/cloudbeaver/files/12156624/build.zip)


![image](https://github.com/dbeaver/cloudbeaver/assets/31788525/122374fd-435f-4b48-adf9-52d802a15efa)

**Comment by alexander-skoblikov** [comment]
It's supposed to be a network issue. Most likely you download the dependencies for too long. Unfortunately, we cannot solve this issue from our side.

**Comment by EvgeniaBzzz** [comment]
It’s been a while since an update here. Please contact me if you have any further questions.
