### ISSUE TITLE
How start cloudbeaver\webapp web server?

### ISSUE THREAD

**Issue by jswanglink** [dbeaver/cloudbeaver#1819]
Run the local server as described in the [Build and deploy](https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy) section
Execute
cd webapp/
yarn lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=localhost:8978
to run Webpack dev server

Open localhost:3100 in web browser

Error reported after starting according to the above steps：

Error occurred while trying to proxy: 127.0.0.1:3100/api/gql
GQL Error: Error occurred while trying to proxy: 127.0.0.1:3100/api/gql

How to solve it

**Comment by TatyanaSsau** [comment]
@jswanglink please provide me all steps like [here](https://github.com/dbeaver/cloudbeaver/issues/1200) - it will help me understand where exactly the problem occurred.

Additionally, please make sure you are using Eclipse ver.23.06 and Java ver.17

**Comment by jswanglink** [comment]
I have compared other issues and found that there are no issues with the Java version and front-end dependency version

How can I start the front-end 3100 port correctly to see the page? The back-end server.bat has started normally and can access localhost: 8978 ok, but accessing localhost: 3100 reports the following error

Error occurred while trying to proxy: localhost: 3100/api/gql

GQL Error: Error occurred while trying to proxy: localhost: 3100/api/gql

**Comment by teunlao** [comment]
@jswanglink Hi,

From your description, it seems that the problem might be related to the `--stream` flag. When `--stream` is used, the output from the subprocesses are all logged to the console together, which can sometimes cause conflicts or issues.

As a workaround, you could try running dev server without the `--stream` flag. Like so:
```
yarn lerna run dev --scope=@cloudbeaver/product-default -- -- --env server=localhost:8978
```

If this doesn't solve your problem, another workaround would be to run the dev server locally from within the package without `lerna`:
```bash
cd packages/product-default
yarn run dev -- --env server=http://localhost:8978
```

**Comment by jswanglink** [comment]
The problem still exists and is not caused by the -- stream

**Comment by jswanglink** [comment]
http://localhost:3100/webpack-dev-server  This address allows you to see the front-end resources. Can you determine if it's not a front-end issue

**Comment by teunlao** [comment]
Have you tried running the dev server without Lerna?

**Comment by jswanglink** [comment]
yes I tried to start without Lerna, but the result was still a similar error;

Error occurred while trying to proxy: localhost: 3100/api/gql

GQL Error: Error occurred while trying to proxy: localhost: 3100/api/gql

Are there any front-end startup steps for the first time I come into contact with CloudBeaver? I follow the official documentation, but there are always errors. I need to verify each step again until it starts normally

**Comment by teunlao** [comment]
It seems that the problem is quite specific and usually no additional steps are required to start the frontend.

You have a problem with proxying requests to the local server.

Are you sure the local server is running on port 8978?
What opens up when you navigate to localhost:8978 in your browser?

I also suggest checking the following option:
In `packages/core-cli/configs/webpack.product.dev.config.js`, hardcode the server value to http://localhost:8978/, possibly there's a problem with the server argument being passed.

<img width="534" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/75555523/56d643e2-c70a-4ddb-9dd0-72c1fbd2ed53">

**Comment by jswanglink** [comment]
Open local localhost: 8978, as shown in the figure, I don't know what problem the agent has
![1](https://github.com/dbeaver/cloudbeaver/assets/42864079/ac6eebf0-f7fb-4ab4-9831-bb45bdf438e7)
![2](https://github.com/dbeaver/cloudbeaver/assets/42864079/cc152647-a203-4761-bc46-e6af1130e1a5)

**Comment by TatyanaSsau** [comment]
@jswanglink I've noticed there is no updates for a long time.
Please, contact me - if it's still actual.

**Comment by jswanglink** [comment]
I have re cloned the old version and modified the dev configuration, which is now ready`'/api/gql': {
          target: 'http://localhost:8978/api/gql',
        },`，

**Comment by abhi40308** [comment]
I am facing the exact same issue.

i tried adding below to proxy config as @jswanglink  mentioned but didn't seem to fix it
```
'/api/gql': { 
          target: 'http://localhost:8978/api/gql',
        },
```

running without learna worked, thanks @teunlao  for the workaround
```
cd packages/product-default
server=http://localhost:8978 yarn run dev
```
