### ISSUE TITLE
adding Dremio Driver (arrow-flight-sql-jdbc-driver)

### ISSUE THREAD

**Issue by YuriyGavrilov** [dbeaver/cloudbeaver#1858]
**Is your feature request related to a problem? Please describe.**
Currently we can't connect to the Dremio EE or Dremio OSS Version without this driver.

**Describe the solution you'd like**
Just need to install this driver https://docs.dremio.com/current/sonar/client-applications/drivers/arrow-flight-sql-jdbc-driver
https://www.dremio.com/drivers/jdbc/

**Comment by TatyanaSsau** [comment]
@YuriyGavrilov thank you for your suggestion - we are going to implement in the near future.

**Comment by bigleka** [comment]
+1

**Comment by LonwoLonwo** [comment]
Hello @YuriyGavrilov 

DBeaver already supports the Dremio driver. And CloudBeaver is based on DBeaver.
So, you can already add the Dremio driver. Please follow this instruction: https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers 

And answer me if this solution works for you.
Thanks.

**Comment by LonwoLonwo** [comment]
It's been a while since there has been an update here. Please let me know if the request is still present and provide additional information.
