### ISSUE TITLE
SQL Editor drag and drop functionality ( from table objects , table, view, column to the editor )

### ISSUE THREAD

**Issue by mencwelp** [dbeaver/cloudbeaver#187]
SQL editor -  Autofill of code
-  user  productivity features: syntax highlighting
-  automated field selection during SQL typing 
-  drag and drop functionality ( from  table objects , table, view, column to the editor )

**Comment by serge-rider** [comment]
Thanks for suggestions.

Syntax highlighting is already there, as well as auto-completion (use <kbd>ctrl+space</kbd>).

Drag-n-drop would be a handy frature 👍

**Comment by kseniiaguzeeva** [comment]
The feature is available in the latest release 22.0.2.
