### ISSUE TITLE
Provide an option to disable data export for any user.

### ISSUE THREAD

**Issue by kyle-joiner** [dbeaver/cloudbeaver#1878]
**Is your feature request related to a problem? Please describe.**
Please provide a security option to disable the export button for any user type other than the administrator.

**Describe the solution you'd like**
A option when defining a user to disable the ability to export data.

**Comment by TatyanaSsau** [comment]
@kyle-joiner Thank you for the suggestion!
We will add in the backlog.

**Comment by TatyanaSsau** [comment]
We have moved the ticket to the backlog, and it will be closed as a duplicate.
