### ISSUE TITLE
WebUI not showing OpenStreetMap layer with default coordinate system ESPG 4326 (aka WG84)

### ISSUE THREAD

**Issue by aleksandaratanasov** [dbeaver/cloudbeaver#1882]
**Describe the bug**
In a PostgreSQL DB with PostGIS extension the OpenStreetMap layer in the map view (used to preview geometry data entries) is not showing when using Simple or WG84. Any other coordinate system available (3395, 3857 and 900913) shows the layer (of course the geometry is shifted accordingly due to the affect a different coordinate system has on the coordinates in a geometry data entry).

**To Reproduce**
1. Create (if not available) and connect to a PostGIS DB that contains a table with one or multiple geometries (in my case a polygon, polyline and multipoint entries)
2. Run a SELECT query
3. Go to table view, where also the map view is available
4. Select entry/entries
5. Observe the entries appearing in the map view but without the OpenStreetMap layer

**Screenshots**
![Working map view (here using EPSG900913)](https://github.com/dbeaver/cloudbeaver/assets/3254568/d971225a-204b-4e04-8249-ced6024acd7d)

![Not working map view (here using default WG84](https://github.com/dbeaver/cloudbeaver/assets/3254568/16ffe991-0e7f-421d-9c7e-803a843a77a1)

**Desktop:**
 - OS: Ubuntu Server 22.04 with microk8s deployment, CloudBeaver running in a pod, using `dbeaver/cloudbeaver:latest`
 - Browser Firefox
 - Version 115.0.2 (as of time of writing latest snap version for Ubuntu Server 22.04)

**Additional context**
The OpenStreetMap layer has no problem showing in the desktop version of DBeaver incl. the above mentioned problematic coordinate systems. I recall reading about this issue here somewhere but cannot find it. It appears that it's a reoccurring problem.

**Comment by dariamarutkina** [comment]
@aleksandaratanasov, thank you for the bug reporting!
We are going to fix it in the near future.

**Comment by aleksandaratanasov** [comment]
@dariamarutkina I think that part of the error is probably the CRS itself. The desktop version also supports manually selecting one of the tens or hundreds of CRSs. If I'm not mistaken, it also uses Leaflet for the rendering so this should not be coming from that JS library.

**Comment by dariamarutkina** [comment]
Hi @aleksandaratanasov !
We added the ability to display the OpenStreetMap layer with the default coordinate system ESPG 4326. The Simple mode will also be displayed without a map. Please take a look at the new version of CloudBeaver 23.3.4.
Thank you for your interest in CloudBeaver!
