### ISSUE TITLE
How to import and development configuration?

### ISSUE THREAD

**Issue by rzandonai** [dbeaver/cloudbeaver#189]
Can share a documentation how to import this project on intellij or eclipse 
to development?

**Comment by serge-rider** [comment]
Project consists of two parts: backend and frontend.

Backend is based on dbeaver headless component. It is Java + OSGI + Eclipse runtime.
See our wiki: especially https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse

Front-end is in TypeScript. You could use VSCode or some other TS IDE.
