### ISSUE TITLE
cloudbeaver Whether the passed parameter is supported

### ISSUE THREAD

**Issue by mingmingqiang** [dbeaver/cloudbeaver#1907]
Please, describe your question in details.
I don't want to create users through the interface, delete user configuration database connections, etc., whether these operations can be solved by passing in connections

**Comment by TatyanaSsau** [comment]
@mingmingqiang thank you for reporting!

we already have several configurations that can be set up via https://github.com/dbeaver/cloudbeaver/wiki/Configuring-server-datasources;
also access permissions that can be specified for pre-configured connections via the configuration file
https://github.com/dbeaver/cloudbeaver/wiki/Pre%E2%80%90configured-permissions-for-connections

**Comment by EvgeniaBzzz** [comment]
Hi @mingmingqiang 
I hope everything worked out for you. Please contact me if you have any further questions.
