### ISSUE TITLE
Array fields in Clickhouse cause a crash

### ISSUE THREAD

**Issue by AviSarmani** [dbeaver/cloudbeaver#1951]
Hi,
Started at 23.1.5, doesn't happen in 23.1.4.
When we try to display data that has an array column in Clickhouse, we get an error:

```
The field at path '/result/results[0]/resultSet/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'SQLResultSet'
```
or:
```
Cannot invoke "org.jkiss.dbeaver.ext.clickhouse.ClickhouseDataTypesParser$AnyTypeContext.getText()" because the return value of "org.jkiss.dbeaver.ext.clickhouse.ClickhouseDataTypesParser$ArrayTypeContext.anyType()" is null
```

**To Reproduce**
```
create table test(
  `test` Array(Int64)
  )
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192
```

Try to navigate to the data tab
**Screenshots**
![image](https://github.com/dbeaver/cloudbeaver/assets/49937628/5930efc4-5b13-453a-96cc-09299d975988)
![image](https://github.com/dbeaver/cloudbeaver/assets/49937628/e366239c-cae6-40ea-8f5c-4e52205816d8)
![image](https://github.com/dbeaver/cloudbeaver/assets/49937628/1b6c04a5-c764-4bd8-92ad-bd4cb9539cef)

**Comment by ShadelessFox** [comment]
Hello @AviSarmani,

Can you please provide information about the database version and the driver version?

**Comment by AviSarmani** [comment]
Hi @ShadelessFox,
Thanks for the reply.
DB version is 23.7.1.2470
Driver version I can see in enabledDrivers is "clickhouse:yandex_clickhouse" which looks to be Legacy.
What should I put in enabledDrivers if I want to test with the newest driver?
Thanks.

**Comment by ShadelessFox** [comment]
Yes, this is a legacy one. You should use `clickhouse:com_clickhouse` instead.

**Comment by AviSarmani** [comment]
Thanks for that, happens with the new driver as well.
The log is:

line 1:5 mismatched input '<EOF>' expecting '('                                                                                                                                                                                    │                              │
│ 24-08-2023 15:40:07.699 [DBeaver: Read data from container database://com_clickhouse-18a282afbe8-15ff2c6e5a39b2f/datricks/org.jkiss.dbeaver.ext.generic.model.GenericTable/test] ERROR o.j.d.m.impl.jdbc.struct.JDBCTable - Error  │                              │
│ java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.clickhouse.ClickhouseDataTypesParser$AnyTypeContext.getText()" because the return value of "org.jkiss.dbeaver.ext.clickhouse.ClickhouseDataTypesParser$ArrayT │                              │
│     at org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser.getArrayType(ClickhouseTypeParser.java:130)                                                                                                                           │                              │
│     at org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser.getType(ClickhouseTypeParser.java:116)                                                                                                                                │                              │
│     at org.jkiss.dbeaver.ext.clickhouse.model.ClickhouseDataSource.resolveDataType(ClickhouseDataSource.java:156)                                                                                                                  │                              │
│     at org.jkiss.dbeaver.model.DBUtils.resolveDataType(DBUtils.java:1589)                                                                                                                                                          │                              │
│     at org.jkiss.dbeaver.model.impl.data.transformers.ArrayAttributeTransformer.transformAttribute(ArrayAttributeTransformer.java:47)                                                                                              │                              │
│     at org.jkiss.dbeaver.model.data.DBDAttributeBinding.lateBinding(DBDAttributeBinding.java:331)                                                                                                                                  │                              │
│     at org.jkiss.dbeaver.model.data.DBDAttributeBindingMeta.lateBinding(DBDAttributeBindingMeta.java:265)                                                                                                                          │                              │
│     at org.jkiss.dbeaver.model.exec.DBExecUtils.bindAttributes(DBExecUtils.java:897)                                                                                                                                               │                              │
│     at io.cloudbeaver.service.sql.WebSQLQueryDataReceiver.fetchEnd(WebSQLQueryDataReceiver.java:104)                                                                                                                               │                              │
│     at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:216)                                                                                                                                             │                              │
│     at io.cloudbeaver.service.sql.WebSQLProcessor.lambda$2(WebSQLProcessor.java:259)                                                                                                                                               │                              │
│     at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)                                                                                                                                            │                              │
│     at io.cloudbeaver.service.sql.WebSQLProcessor.readDataFromContainer(WebSQLProcessor.java:256)                                                                                                                                  │                              │
│     at io.cloudbeaver.service.sql.impl.WebServiceSQL$2.run(WebServiceSQL.java:403)                                                                                                                                                 │                              │
│     at io.cloudbeaver.model.session.WebSession$1.run(WebSession.java:672)                                                                                                                                                          │                              │
│     at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)                                                                                                                                                       │                              │
│     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ShadelessFox** [comment]
It looks like the database reports the column's type as `Array`, not `Array(Int64)`.
