### ISSUE TITLE
Password for H2 database

### ISSUE THREAD

**Issue by Vormillion** [dbeaver/cloudbeaver#1987]
Hi,

I'd like to debug some things related to cloudbeaver and I copied h2 database file to open it with jar which can handle h2 files.
What's the default username/password which is used in this database?

When I open it without user/pass I can see only PUBLIC schema.
I tried to use my initial admin credentials (I'm able to login using it in UI) but it's not working. I tried to use various user combinations and password from .data/.database-credentials.dat but also no luck.

**Comment by alexander-skoblikov** [comment]
Hi, the default username is `cb-data` , a password is generated randomly and stored in  `.data/.database-credentials.dat `

**Comment by EvgeniaBzzz** [comment]
Hi @Vormillion 
I hope everything worked out for you. Please contact me if you have any further questions.
