### ISSUE TITLE
Looks like a memory leak

### ISSUE THREAD

**Issue by chrisleell** [dbeaver/cloudbeaver#1991]
**Describe the bug**
After the system is up and running and in use for some time. I found the memory usage is high. Take the heap dump and analyze, One instance of "java.util.HashMap" occupies 80% which is referenced by "io.cloudbeaver.service.session.WebSessionManager".
/
**To Reproduce**
/
1. Repeat the following steps several times: 1. Clear cookies. 2. Login. 3. Logout. Or refresh the browser several times without logging in.
2. Memory usage increases.
3. The log contains only the information about creating web sessions.
4. Take the heap dump. There are many objects (io.cloudbeaver.model.session.WebSession) that are not cleared.

**Screenshots**
![image](https://github.com/dbeaver/cloudbeaver/assets/37203635/220bf17c-0172-4009-aa66-d90dc38449ee)
![image](https://github.com/dbeaver/cloudbeaver/assets/37203635/94b726dc-14c8-4878-a944-2a4fd1c27bf6)
![image](https://github.com/dbeaver/cloudbeaver/assets/37203635/a6a117f8-d9e3-41cc-98a0-ff497c7682aa)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 23.1.0

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by alexander-skoblikov** [comment]
Hi! Described above seems to be the expected behavior.
This data is cleared in the WebSessionMonitorJob, but only expired sessions will be deleted. You can manage session lifetime in the Administration page.
<img width="444" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/23139328/9a344bc4-5f13-4e12-9ce1-9660a5fed190">

**Comment by EvgeniaBzzz** [comment]
It's been a while since the last update here. I hope this solution worked for you. Please let me know if you have any futher questions.
