### ISSUE TITLE
+ dropdown missing from UI

### ISSUE THREAD

**Issue by wrabit** [dbeaver/cloudbeaver#2004]
<img width="911" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/5918271/a70ff7dd-15bb-4d89-9107-6a732fc2b66a">

(community version) I have tried removing image and re-running to no avail

**Comment by dariamarutkina** [comment]
Hello, @wrabit !
Could you answer the questions, please, by 'dropdown', do you mean dropdown with connections? Have you logged into the app? Do you have access to the admin panel?

**Comment by wrabit** [comment]
When I first spun up the containers, i had to register and I once saw the connections and created one. Next time I spin up, it's gone and I don't see any. I also tried removing images / containers, rebuilding but does not present me any login screen.

**Comment by dariamarutkina** [comment]
Thanks for the answer!
![image](https://github.com/dbeaver/cloudbeaver/assets/125263541/cf9b0230-df19-4597-af64-ee78771e0d77)
Can you please log in to the app this way?

**Comment by Bovive** [comment]
I have the same problem. Fresh install on Unraid. I am logged in as admin. I have postgres and mysql connection templates made and they test fine. Nothing shows up on my panel. I tried creating another user and assigned access for those connections, but that user also does not see them. Version is 23.2.0.

**Comment by EvgeniaBzzz** [comment]
@Bovive hi
Please, make sure that option 'Enable private connections' in Administration panel is enabled. It affects visibility of the connection dropdown on the main page

**Comment by EvgeniaBzzz** [comment]
Hi! It’s been a while since an update here. I hope everything worked out for you. Please contact me if you have any further questions.
