### ISSUE TITLE
Create a DB

### ISSUE THREAD

**Issue by xSkeletor** [dbeaver/cloudbeaver#2005]
Hi folks, so far Cloudbeaver looks like a really good product, but I've been trying to find information on how I can create an actual DB within my Postgres instance. All of my results have just shown how to add the actual database instance (i.e. Postgres connection), but I can't create any actual databases in it. I can view the current ones and delete them, but I can't seem to figure out how to add them. Does this functionally exist within Cloudbeaver?

**Comment by dariamarutkina** [comment]
Hello, @xSkeletor !
 You can only do this through a query in the [SQL editor](https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-overview#execute-sql-query) in CloudBeaver 
Please let me know if you succeeded or not, thank you for your interest in ClodBeaver!

**Comment by EvgeniaBzzz** [comment]
It's been a while since the last update here. Please let us know if you have any futher questions.
