### ISSUE TITLE
When will support for informix databases be added?

### ISSUE THREAD

**Issue by wjyijun** [dbeaver/cloudbeaver#2007]
When will support for informix databases be added?

**Comment by dariamarutkina** [comment]
Hello, @wjyijun !
CloudBeaver[ Enterprise](https://dbeaver.com/cloudbeaver-enterprise/) already supports Informix.

You can try it for free https://cloudbeaver.io/trial/
You can also add the driver manually https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#adding-drivers-in-cloudbeaver

**Comment by wjyijun** [comment]
Cannot modify the data in the data editor after manually adding the informix driver

**Comment by EvgeniaBzzz** [comment]
@wjyijun hi!
It's rather complicated to help you as it depends on your DB configurations.
We made some tests and everything works well for manually added Informix driver.
Could you please provide us with your table ddl?

**Comment by EvgeniaBzzz** [comment]
Hi! It’s been a while since an update here. Please contact me if you have any further questions.
