### ISSUE TITLE
Eclipse import Cloudbeaver launch configuration, choose. / server/product/web - server path, do not display CloudbeaverServer.product.launch

### ISSUE THREAD

**Issue by Lili-Nthan** [dbeaver/cloudbeaver#2053]
![Dingtalk_20231010110240](https://github.com/dbeaver/cloudbeaver/assets/93107372/affb53b2-043d-4c3d-a361-647ba60d43a8)

**Comment by alexander-skoblikov** [comment]
<img width="1294" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/23139328/b94bd33c-e7df-426a-8b9d-f7db24e538c7">

You can open `cloudbeaver/server/product/web-server/CloudbeaverServer.product` file in Eclipse and press `Launch as Eclipse applicaton`

**Comment by EvgeniaBzzz** [comment]
Hi @Lili-Nthan 
I hope everything worked out for you.
Please contact me if you have any further questions.
