### ISSUE TITLE
Impossible to use connection templates with anonymous access

### ISSUE THREAD

**Issue by Pinozerg** [dbeaver/cloudbeaver#2058]
**Describe the bug**
In older versions, for example 22.1.0 it was possible to use connection templates that I predefined in initial-data-sources.conf
having no login enabled - so as anonymous user:
anonymousAccessEnabled: true,
"enabledAuthProviders": [],
and
supportsCustomConnections": true

currently, since 23.x.x it is impossible to use connection templates with anonymous user(the option doesn't appear). Only "New Connection" is available.

**To Reproduce**
On fresh clean cloudbeaver image with no params,
enable private connections,
disable Local auth,
Logout from admin user,
Try to create connection from template - no option available

**Screenshots**
setup:
![obraz](https://github.com/dbeaver/cloudbeaver/assets/35170678/f413fded-c4b5-4a31-a8d4-2636348e875f)
![obraz](https://github.com/dbeaver/cloudbeaver/assets/35170678/5ee5ba99-b8fc-48fa-9f68-6f55e2147e80)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 23

**Comment by EvgeniaBzzz** [comment]
Hi @Pinozerg 
You should grant permission to the templates via default team "User".
1. Open Administration->Access management
2. Open Team tab
3. Open team User
4. Open Connections tab
5. Select templates which you want to share with anonymous users
6. Press Save button
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/fc39b99b-b717-4789-9e4a-8aac8fbbcf41)

We've changed the permission logic to make templates and connections more secure.
We will add some descriptions to make it clearer.
Thanks for your support of CloudBeaver!

**Comment by dariamarutkina** [comment]
We added some descriptions to make it clearer
@Pinozerg, Please, check CloudBeaver v.23.1.5
Thank you for your interest in CloudBeaver!
