### ISSUE TITLE
Apache proxy configuration

### ISSUE THREAD

**Issue by albenard** [dbeaver/cloudbeaver#2086]
Hi, in documentation i find information for nginx :

location / {
    proxy_pass       http://localhost:8978;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
I have installed docker and cloudbeaver and ran 'docker run ... -p8080:8978 ...' like in documentation and i can access http://myserver:8080 to work with cloudbeaver but in my production environment the 8080 port is not enable so i would like to use my apache server with an alias like http://myserver/cloudbeaver. I use configuration like 
    <Location /cloudbeaver>
        ProxyPassReverse /
        RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{HTTP:X-Forwarded-For}s
    RequestHeader set Host %{HTTP_HOST}s
    RequestHeader set Upgrade %{HTTP_UPGRADE}s
    RequestHeader set Connection "Upgrade"
        Order allow,deny
        Allow from all
    </Location>

ProxyPass /cloudbeaver  http://localhost:8080
ProxyPassReverse /cloudbeaver  http://localhost:8080
And i have error message with http://192.16.20.140/cloudbeaver 👍 
![image](https://github.com/dbeaver/cloudbeaver/assets/60139239/afac1703-0ad6-4c75-a592-d56b64d5f09c)
Have any body success configure an apache with proxy for access to cloudbeaver? Thanks or your help. I think this solution coul be in the documentation (if there is a solution).

**Comment by EvgeniaBzzz** [comment]
Hi, @albenard!
You can use any port in your environment, not only 8080.
Please, try to change port in `docker run`. 
Let us know if that solution works for you.

**Comment by albenard** [comment]
It's not important the port; it could be 8090, 35 or other. The principe is cloudbeaver is on docker on port 8978 but this port port is not visible from the host so ti's necessary to publish this port (isn't??). So I publish this port on port 8080 or 8090 from the host. The host is a web server (apache) who has just port 80 open for external access - so i want to proxify with mod_proxy but i don't know if my configuration is bad or if necessary other thing but it's not ok. I search a person who have proxify (with apache) an application under docker.

**Comment by alexander-skoblikov** [comment]
@albenard Most likely, the problem is in your prefix `/cloudbeaver`, by default the application uses `/` as the root.
You can remove  `/cloudbeaver` from apache configuration or update `rootURI` [parameter in cloudbeaver.conf](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration). You will need to change the file inside the image/make a custom build/copy all default configuration files and map it to your volume (we will add more convenient configuration ways in the future)

**Comment by EvgeniaBzzz** [comment]
It’s been a while since an update here. Please feel free to ask to reopen the ticket if it is still actual for you.
