### ISSUE TITLE
how do i create users with different roles from inside dbeaver docker container

### ISSUE THREAD

**Issue by chiziproxy** [dbeaver/cloudbeaver#2092]
Please, describe your question in details.
I want to build a dbeaver image that creates 15 users with different permissions by modifying a dockerfile. however in the dbeaver image I do not know what file to edit or how to edit the file that will create the users with their different permissions. I have tried modifying the initial.data.conf file to include several users. its either my syntax is not correct or that is not the right way to do cause it is not working and i do not wish to do this via the graphical user interface.

**Comment by EvgeniaBzzz** [comment]
Hi, @chiziproxy!
Unfortunately, we do not yet have the ability to pre-create users. And we are not going to add it in near future.
You can use [Reverse proxy](https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication) authentication, as Proxy users are created automatically.
Thank you for your interest in CloudBeaver!

**Comment by EvgeniaBzzz** [comment]
We have not heard from you for a while, so this ticket was closed.
