### ISSUE TITLE
Is it possible to set dbeaver configurations?

### ISSUE THREAD

**Issue by bennettmsherman** [dbeaver/cloudbeaver#2098]
Hello!

I'm looking to disable automatic insertion of table aliases in the SQL editor. 

The [dbeaver docs](https://dbeaver.com/docs/dbeaver/Admin-Manage-Preferences/23.2/) state that there's a configuration for this: `sql.proposals.insert.table.alias`. 

I created `.metadata/.plugins/org.eclipse.core.runtime/.settings/org.jkiss.dbeaver.core.prefs` and populated it with `sql.proposals.insert.table.alias=NONE` per the dbeaver instructions, but it didn't seem to take effect.

Is there a way to change this setting (and possible other dbeaver settings) in cloudbeaver?

Thanks!

**Comment by EvgeniaBzzz** [comment]
Hi @bennettmsherman!
There is currently no way to disable this feature. But we are going to implement it approximately in the first quater of the next year.

**Comment by bennettmsherman** [comment]
Thanks for the clarification!

**Comment by EvgeniaBzzz** [comment]
Hi @bennettmsherman! 
The alias autocomplete option now can be disabled. Please, check it out in version 23.3.5
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/7fce10a5-1a50-4d2c-a8fe-abf403948368)

**Comment by bennettmsherman** [comment]
I'll do an update later today and check it out, thank you!
