### ISSUE TITLE
Would you please upgrade commons-compress to 1.21 or higher?

### ISSUE THREAD

**Issue by Jeffrey778** [dbeaver/cloudbeaver#2099]
Since cb introduces commons-compress 1.18, which is detected HIGH Vulnerability about 
GHSA-crv7-7245-f45f - https://github.com/advisories/GHSA-crv7-7245-f45f
GHSA-mc84-pj99-q6hh - https://github.com/advisories/GHSA-mc84-pj99-q6hh
GHSA-53x6-4x5p-rrvv - https://github.com/advisories/GHSA-53x6-4x5p-rrvv
GHSA-xqfj-vm6h-2x34 - https://github.com/advisories/GHSA-xqfj-vm6h-2x34
GHSA-7hfm-57qf-j43q - https://github.com/advisories/GHSA-7hfm-57qf-j43q

Please upgrade to 1.21 or higher. Thanks~

**Comment by EvgeniaBzzz** [comment]
Hi @Jeffrey778!
This is a known issue, we will update Apache POI in the near future.
We really appreciate your attention, thank you!

**Comment by Jeffrey778** [comment]
@EvgeniaBzzz sure, thanks!

**Comment by EvgeniaBzzz** [comment]
Hi @Jeffrey778 
We have updated Apache POI.
Thank you for being with CloudBeaver!

**Comment by Jeffrey778** [comment]
Cool! Thanks @EvgeniaBzzz.
