### ISSUE TITLE
Running Script without being in PWD doesn't work

### ISSUE THREAD

**Issue by FreeSoftwareServers** [dbeaver/cloudbeaver#21]
**Describe the bug**

When I launch the script like so, it fails, but I am able to run by using `./run-server.sh` when CD in folder.

`/opt/cloudbeaver/cloudbeaver/deploy/cloudbeaver/run-server.sh`

**Comment by serge-rider** [comment]
Yeah. You have to be in server root folder.
Workaround: you can set environment variable `CLOUDBEAVER_HOME` to the server root. And then run server from any directory.

I'll add this into instructions.
