### ISSUE TITLE
Disable autocomplete feature for inserting aliases

### ISSUE THREAD

**Issue by mgite** [dbeaver/cloudbeaver#2102]
Every single time i run some query and use suggestion of table names and choose one of them it autocompletes and adds alias for table name. It's so frustrating how shell i disable this functionality?

example:
here are suggestions
![2023-10-31_17_31_42_061941370](https://github.com/dbeaver/cloudbeaver/assets/134310004/3f853699-128f-4675-88ef-d224dded6879)

after hitting enter
![2023-10-31_17_31_50_436321287](https://github.com/dbeaver/cloudbeaver/assets/134310004/5f46a684-59f6-4386-be08-0fafbe23b8cc)

Found this issue in dbeaver also but they have option to disable it. https://github.com/dbeaver/dbeaver/issues/8283

**Comment by EvgeniaBzzz** [comment]
Hi @mgite!
Currently we don't have alias disable option in CloudBeaver. But we are going to implement it in one of the future releases.
Same issue [here](https://github.com/dbeaver/cloudbeaver/issues/2098)
