### ISSUE TITLE
Can not edit rows info in data viewer for Greenplum

### ISSUE THREAD

**Issue by ChrisYuan** [dbeaver/cloudbeaver#2105]
Hi Team,

I create a connection for Greenplum 6.x using PostgreSQL connection type, and I want to edit data in [data viewer] but its not. I tried this way in sqlserver, it is ok, please help~

Is it a bug or misunderstandarding for Cloudbeaver? Can I edit data for Greenplum after some configs? 

Thx,
Chris

**Comment by EvgeniaBzzz** [comment]
Hi, @ChrisYuan!
This is a known bug, we are going to fix it in the nearest release.
Thank you for reporting!

**Comment by ChrisYuan** [comment]
> Hi, @ChrisYuan!
> 
> This is a known bug, we are going to fix it in the nearest release.
> 
> Thank you for reporting!

OK, looking forward, thx~

**Comment by EvgeniaBzzz** [comment]
@ChrisYuan hi!
Fixed in Milestone 23.2.5, please try.
Let us know if you have any further questions.
