### ISSUE TITLE
Can not connect to SQL Server 2008, ERROR of TLS v1

### ISSUE THREAD

**Issue by ChrisYuan** [dbeaver/cloudbeaver#2112]
**Describe the bug**
There is an issue about SQL Server 2008, I tried to connect it and report an error of TLS. I find a way to solve it in stackoverflow, see below:
1. docker exec -it cloudbeaver-docker-name bash
2. change the file '/opt/java/openjdk/conf/security/java.security', remove 'TLSv1, TLSv1.1' from [jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA]
3. restart docker 

For Cloudbeaver version 23.2.4 and 23.2.0

**Comment by EvgeniaBzzz** [comment]
Hi, @ChrisYuan!
Thank you for bringing this to our attention. We will develop a solution in one of the future releases.

**Comment by EvgeniaBzzz** [comment]
Hi, @ChrisYuan!
Please, try to enable 'Trust Server Certificate' or/and select desired TLS in Driver properties
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/02a257c7-4e6e-487d-8fc0-e7b71cb60b83)
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/ba86fed7-6259-4257-a0b5-57c911e0e46a)

**Comment by LonwoLonwo** [comment]
Hello @ChrisYuan 

Please check the latest CloudBeaver version. We changed our Java version. Maybe it will help.
Or take a look at this comment to solve your issue: https://github.com/dbeaver/cloudbeaver/issues/2112#issuecomment-1808282456

**Comment by LonwoLonwo** [comment]
Hello @ChrisYuan 

Does this issue still exist for you?

**Comment by ChrisYuan** [comment]
Let me check, I don't know if
It exists now

**Comment by LonwoLonwo** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by RealfuRyZ** [comment]
Apologies for replying to this issue so late. I want to point out that this problem is still not resolved. When deploying via Docker, I have to configure the container during initialization to remove certain outdated encryption methods from` jdk.tls.disabledAlgorithms` in order to successfully connect to some SQL Server 2008 databases.
