### ISSUE TITLE
Please add query function like navicat query 

### ISSUE THREAD

**Issue by fufeiii** [dbeaver/cloudbeaver#213]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Sometimes, we log into a database server not only want to query the data, but also want to modify or delete the data

**Comment by serge-rider** [comment]
CloudBeaver supports data edit. In both table data viewer and SQL query results viewer. Just double click on a cell value.

Note: you may need to use fully qualified table name in your query in order to enable edit support.
