### ISSUE TITLE
Please add sql query alert function

### ISSUE THREAD

**Issue by xuanyuanaosheng** [dbeaver/cloudbeaver#214]
we need to exec the sql on database and  send the query result to different team by email? 
Could you please add this function?

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. You can do it using Export option (available in the bottom toolbar of the ResultSet)
![EK4wmtZdPN](https://user-images.githubusercontent.com/51405061/104562942-125c0d00-565a-11eb-8a4b-a2e173276c1a.png)

**Comment by xuanyuanaosheng** [comment]
@kseniiaguzeeva   Thanks, I will do some test.

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen, if you need some additional questions about the export.
