### ISSUE TITLE
Inconsistent mobile rendering; UI elements often missing

### ISSUE THREAD

**Issue by bennettmsherman** [dbeaver/cloudbeaver#2142]
**Describe the bug**
When visiting CloudBeaver on my tablet (Kindle Fire 11 using either Brave or Amazon's default Silk browser), the UI doesn't consistently load properly. On some loads, rendering is fine. On others, either the top bar is missing, the bottom bar in the data editor page is missing, or both are missing (and possibly others that I haven't noticed).

On occasion, zooming into the page and moving around causes the bars to reappear.

**To Reproduce**
1. Go to cloudbeaver
2. Click on a table's data edit page
3. Data edit bar not present
4. Refresh page
5. Top bar missing
6. 2-finger zoom into the page and move around; bars may reappear.

There are variations on what's missing. Sometimes it's the top bar, some times it's the data edit bar, sometimes it's both.

**Screenshots**

****Missing edit bar****
![Screenshot_20231119-093405](https://github.com/dbeaver/cloudbeaver/assets/5759079/da6a49eb-ba6b-4f0b-b224-c71877d3898a)

****Missing top bar and edit bar****
![Screenshot_20231119-093418](https://github.com/dbeaver/cloudbeaver/assets/5759079/56fd12b1-f9e9-45d7-beec-1f37fcdfce58)

**Desktop (please complete the following information):**
 - OS: Fire OS (Android 11-based)
 - Browser: Brave (1.60.118; Chromium 119.0.6045.163)
 - Version: Backend version - `23.2.4.202311061434`; Frontend version: `23.2.4.202311061440`

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by EvgeniaBzzz** [comment]
@bennettmsherman hi!
We will try to fix the rendering for older models. Thank you for the report and for the detailed description of the problem.

**Comment by EvgeniaBzzz** [comment]
@bennettmsherman 
For now please try this workarounds: 
- zoom out to minimum and then zoom in
- use as PWA

**Comment by bennettmsherman** [comment]
Kindle devices don't support PWAs, but I can give the zoom option a shot. 

I'll also note that the issue is present on my Pixel 6 (Android 14; same brave version), but the PWA seems to work properly.

Thank you for the quick reply!

**Comment by dariamarutkina** [comment]
Hello @bennettmsherman ! 
We have fixed the display of the elements.
Please take a look at the new version of CloudBeaver 23.3.2.
Thank you for your interest in CloudBeaver!
