### ISSUE TITLE
Cloudbeaver mongo drivers installation for AKS deployment

### ISSUE THREAD

**Issue by rashapudenko** [dbeaver/cloudbeaver#2144]
Hi,

So I've followed these 2 wiki pages for mongo driver addition:
[https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy](https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy)
[https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#Drivers-and-bundles](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#Drivers-and-bundles)

I am trying to build deployment pipeline in Azure Devops for deploying cloudbeaver as Helm chart into AKS.
Pipeline build agent tool versions are the following:
### /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu120.04, mixed mode, sharing)
### mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
### Found tool in cache: yarn 1.22.21 x64

Build succeeded, build logs can be found in attached file 
[build_logs.txt](https://github.com/dbeaver/cloudbeaver/files/13412854/build_logs.txt)

In this files following commands were executed after checking out https://github.com/dbeaver/cloudbeaver @ devel:

cat ./server/drivers/pom.xml <- verification
cat ./server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml <- verification
cat ./server/drivers/mongodb/pom.xml <- verification
cd ./deploy
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 <- multimple JDK are installed, so I set this var for this step in particular
./build.sh
sed -i '/java.security/d' /path/to/cloudbeaver/deploy/docker/Dockerfile <- our custom build agents doesn't have this dir, so I simply dropped this instruction for now

Followed by Docker image build: 
[docker-build-logs.txt](https://github.com/dbeaver/cloudbeaver/files/13412879/docker-build-logs.txt)
Issued docker command here: /usr/bin/docker build -f /path/to/cloudbeaver/deploy/docker/Dockerfile --alotofdefaultlabels -t ***.azurecr.io/cloudbeaver:626331 /path/to/cloudbeaver/deploy

Also succeeded.

After that, Helm deploy also succeeded, where I have (I'll mention only important things IMO):
1) Configmap with 2 following connections (alongside with others, but mongo connections are failing):
`            "mongo-test": {
                "provider": "mongodb",
                "driver": "mongodb-jdbc",
                "name": "mongo-test",
                "save-password": false,
                "show-system-objects": false,
                "read-only": true,
                "template": true,
                "configuration": {
                    "host": "***.mongo.cosmos.azure.com",
                    "port": "10255",
                    "url": "***",
                    "type": "dev",
                    "provider-properties": {
                        "@dbeaver-show-non-default-db@": "false"
                    }
                }
            },
            "mongo-test-2": {
                "provider": "mongodb",
                "driver": "mongodb-jdbc",
                "name": "mongo-test-2",
                "save-password": false,
                "show-system-objects": false,
                "read-only": true,
                "template": true,
                "configuration": {
                    "host": "***.mongo.cosmos.azure.com",
                    "port": "10255",
                    "url": "***",
                    "type": "dev",
                    "provider-properties": {
                        "@dbeaver-show-non-default-db@": "false"
                    }
                }
            }`
Configmap with these mounts to /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
2) Deployment manifest:
[deployment.txt](https://github.com/dbeaver/cloudbeaver/files/13415493/deployment.txt)

With image we've built previously Helm deployment succeeds, but pod logs shows the following error:
"17-11-2023 21:36:44.632 [qtp1024240671-28] DEBUG o.j.d.r.DataSourceSerializerModern - Can't find datasource provider mongodb for datasource 'mongo-test'
17-11-2023 21:36:44.632 [qtp1024240671-28] DEBUG o.j.d.r.DataSourceSerializerModern - Can't find driver mongodb-jdbc in datasource provider mongodb for datasource 'mongo-test'. Create new driver"

Would appreciate any help, if more info required - LMK.

Thanks!

**Comment by EvgeniaBzzz** [comment]
Hi @pavel-rudenko! 
Even if you will add Mongo as a custom image it won't work properly. Full support for Mongo is provided by CloudBeaver [Enterprise](https://dbeaver.com/cloudbeaver-enterprise/).
If you still want to try, please provide us with datasources.json and full server start log.

**Comment by rashapudenko** [comment]
Full pods logs: 
[full-pods-logs.txt](https://github.com/dbeaver/cloudbeaver/files/13459654/full-pods-logs.txt)


Not a great news because you have wiki page for that matter :(

**Comment by EvgeniaBzzz** [comment]
Technically, you can add any driver. However, due to the specifics of noSQL drivers, we guarantee their support and proper functioning only in CloudBeaver [Enterprise](https://dbeaver.com/cloudbeaver-enterprise/) and PRO versions of DBeaver. You can explore any product in the [2-week trial version](https://dbeaver.com/download/). Using a self-added MongoDB will not meet your expectations.

**Comment by rashapudenko** [comment]
So there is nothing you can assist with based on provided logs, right?

**Comment by EvgeniaBzzz** [comment]
Hi @pavel-rudenko 
It seems that your driver is configured incorrectly, a non-existent provider is specified in the datasource config.

**Comment by rashapudenko** [comment]
I have seen that, thanks.
Any pointers on _why_ this is incorrect, based on all the files I've provided alongside with used Wiki?

In original message there are log files with all the modification, I can resend them here separetly (not within [build_logs.txt](https://github.com/dbeaver/cloudbeaver/files/13412854/build_logs.txt)):

./server/drivers/pom.xml -> [server_drivers_pom_xml.txt](https://github.com/dbeaver/cloudbeaver/files/13460651/server_drivers_pom_xml.txt)

./server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml -> 
[_server_bundles_io_cloudbeaver_resources_drivers_base_plugin_xml.txt](https://github.com/dbeaver/cloudbeaver/files/13460662/_server_bundles_io_cloudbeaver_resources_drivers_base_plugin_xml.txt)
Here I also tried `<driver id="mongodb:mongodb-jdbc"/>` - gives same result

./server/drivers/mongodb/pom.xml -> 
[_server_drivers_mongodb_pom_xml.txt](https://github.com/dbeaver/cloudbeaver/files/13460667/_server_drivers_mongodb_pom_xml.txt)

**Comment by serge-rider** [comment]
Most likely you specified wrong provider in data-sources.json.
Can you attach your `data-sources.json` to the ticket? (just delete all non-public data from it)

**Comment by rashapudenko** [comment]
I've sent a snippet in my original message, it looks like this:
```
		"mongo-test": {
			"provider": "mongodb",
			"driver": "mongodb-jdbc",
			"name": "mongo-test",
			"save-password": false,
			"show-system-objects": false,
			"read-only": true,
			"template": true,
			"folder": "***",
			"configuration": {
				"host": "***.mongo.cosmos.azure.com",
				"port": "10255",
				"url": connstringfromservice",
				"provider-properties": {
					"@dbeaver-show-non-default-db@": "false"
				}
			}
		}
```

**Comment by serge-rider** [comment]
I think provider must be set to `generic`

**Comment by rashapudenko** [comment]
Tried that as well.
Here are logs for multiple different combinations:
```
28-11-2023 16:40:10.392 [qtp1458152564-33] DEBUG o.j.d.r.DataSourceSerializerModern - Can't find driver mongodb-jdbc in datasource provider generic for datasource 'mongo-test'. Create new driver
28-11-2023 16:40:10.393 [qtp1458152564-33] DEBUG o.j.d.r.DataSourceSerializerModern - Can't find datasource provider mongodb for datasource 'mongo-test-2'
28-11-2023 16:40:10.393 [qtp1458152564-33] DEBUG o.j.d.r.DataSourceSerializerModern - Can't find driver mongodb-jdbc in datasource provider mongodb for datasource 'mongo-test-2'. Create new driver
28-11-2023 16:40:10.393 [qtp1458152564-33] DEBUG o.j.d.r.DataSourceSerializerModern - Can't find driver mongodb in datasource provider mongodb for datasource 'mongo-test-3'. Create new driver
28-11-2023 16:40:10.394 [qtp1458152564-33] DEBUG o.j.d.r.DataSourceSerializerModern - Can't find driver mongodb in datasource provider generic for datasource 'mongo-test-4'. Create new driver
```

Maybe it will make sense to prebuild additional driver into dbeaver (that gets built in cloudbevaer build process) somehow?
I'm kinda lost here :(

**Comment by serge-rider** [comment]
It is not clear how exactly you added the driver.
You need to add it by editing plugin.xml of `generic` plugin (https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#configuring-drivers-in-dbeaver). 
Because mongoddb driver declaration is missing in the community dbeaver repository.

Could you send examply of your plugin.xml? And pom.xml with new driver dependency.

**Comment by rashapudenko** [comment]
I used https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#adding-drivers-in-cloudbeaver rather then https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#configuring-drivers-in-dbeaver

As per your message I can make a conclusion that both of these steps (not only cloudbeaver related one) should be performed in order to add plugin, right?

I will try to add them to dbeaver (as I've suggested earlier) and will keep u posted.

**Comment by rashapudenko** [comment]
Please check if this additional driver looks ok in dbeaver/plugins/org.jkiss.dbeaver.ext.generic/plugin.xml file in datasource/drivers/driver path:
```
                <driver
                    id="mongodb"
                    label="MongoDB"
                    icon="icons/mongodb_icon.png"
                    iconBig="icons/mongodb_icon_big.png"
                    category="MongoDB"
                    class="org.mongodb.mongodb-jdbc"
                    sampleURL="mongodb://{database}:{password}@{database}.mongo.cosmos.azure.com:10255/"
                    webURL="https://www.mongodb.com/"
                    description="MongoDB driver"
                    supportedConfigurationTypes="MANUAL,URL"
                    categories="nosql">
                    <file type="jar" path="maven:/org.mongodb:mongodb-jdbc:RELEASE[2.0.3]" bundle="!drivers.mongodb"/>
                    <file type="jar" path="drivers/mongodb" bundle="drivers.mongodb"/>
                </driver>
```

I'll try to rebuild it locally.

**Comment by rashapudenko** [comment]
Still nothing.
Both setups produce jars within cloudbeaver/deploy/cloudbeaver/drivers/mongodb directory:
![image](https://github.com/dbeaver/cloudbeaver/assets/76470702/d4cb85a6-9c4d-4640-b513-65893752beb2)

With addition to dbeaver/plugins/org.jkiss.dbeaver.ext.generic/plugin.xml I get the same errors in logs, and in UI I now can get this error:
```
Error connecting to database:
Connection failed:
Can't create driver instance
java.lang.NoSuchMethodException: java.sql.Driver.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.createDriverInstance(DriverDescriptor.java:740)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1254)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1179)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:719)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:717)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createDriverInstance(JDBCDataSource.java:282)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:198)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:155)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:120)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1288)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1125)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at io.cloudbeaver.service.core.impl.WebServiceCore.testConnection(WebServiceCore.java:677)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

Maybe some other modifications to dbeaver within dbeaver/plugins/org.jkiss.dbeaver.ext.generic/plugin.xml is required.

**Comment by serge-rider** [comment]
You have wrong class name in driver descriptor.
"org.mongodb.mongodb-jdbc" is definitely not a class name.

**Comment by EvgeniaBzzz** [comment]
It has been some time since our last communication on this matter.
Please let us know if you have any further questions.
