### ISSUE TITLE
Can't switch from default connected DB when connecting to Microsoft SQL Server

### ISSUE THREAD

**Issue by rashapudenko** [dbeaver/cloudbeaver#2149]
**Describe the bug**
Can't switch from default connected DB when connecting to Microsoft SQL Server

**To Reproduce**
Made a Helm chart with use of [dbeaver/cloudbeaver](https://hub.docker.com/r/dbeaver/cloudbeaver/tags): 23.2.1 image
Added the following connections with use of configmap mounted to /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json containing following connection details (this is typical MS SQL configuration on our side, Postgres connections works just fine):
```
            "***": {
                "provider": "sqlserver",
                "driver": "microsoft",
                "name": "***",
                "description": "***",
                "save-password": true,
                "lockPassword": "***",
                "show-system-objects": true,
                "read-only": false,
                "folder": "***",
                "configuration": {
                    "user": "***",
                    "password": "***",
                    "host": "***.database.windows.net",
                    "port": "1433",
                    "database": "defaultdbnamehere",
                    "type": "dev",
                    "provider-properties": {
                        "@dbeaver-show-non-default-db@": "true"
                    },
                    "auth-model": "native"
                }
            },
```

After that I can only browse freely from UI within *defaultdbnamehere* database, trying to switch to any other db results in following error:
![image](https://github.com/dbeaver/cloudbeaver/assets/76470702/23b56238-6499-4b1d-a58c-8fffaedb9fd8)
Full text: 
[stacktrace.txt](https://github.com/dbeaver/cloudbeaver/files/13417643/stacktrace.txt)

Connection details:
```
Client version: Microsoft JDBC Driver 8.2 for SQL Server 8.2.0.0
Server version: Microsoft SQL Server 12.00.5349
Microsoft SQL Azure (RTM) - 12.0.2000.8
Oct 8 2023 18:40:28
Copyright (C) 2022 Microsoft Corporation
```

**Desktop:**
 - Windows 10 Enterprise
 - Chrome Version 119.0.6045.160 (Official Build) (64-bit)

**Additional context**
I saw multiple pages on this or adjacent matter:
[https://github.com/dbeaver/dbeaver/issues/19241](https://github.com/dbeaver/dbeaver/issues/19241)
[https://github.com/dbeaver/dbeaver/issues/5258](https://github.com/dbeaver/dbeaver/issues/5258)
[https://github.com/dbeaver/dbeaver/issues/20803](https://github.com/dbeaver/dbeaver/issues/20803)
[https://github.com/dbeaver/dbeaver/issues/17263](https://github.com/dbeaver/dbeaver/issues/17263)

But none of them addresses my issue, I think.
I understand that we can create a separate connection for each database within each server, but this will get out of hands like really quick :)
Is there/will there be some solution to this one?

P.S.: sorry for issue spam :)

**Comment by EvgeniaBzzz** [comment]
Hi @pavel-rudenko!
This is MS SQL Azure issue. It will be fixed here  https://github.com/dbeaver/dbeaver/issues/17263, you found the right ticket.
For now, the only workaround is to create separate connections for different databases.

**Comment by rashapudenko** [comment]
Understood, thanks.

**Comment by EvgeniaBzzz** [comment]
Thank you for reporting!
I will close this ticket because the fix will be implemented in https://github.com/dbeaver/dbeaver/issues/17263
