### ISSUE TITLE
Adding Drivers to Custom Dockerfile

### ISSUE THREAD

**Issue by jefflester** [dbeaver/cloudbeaver#215]
I am trying to add a driver to the CloudBeaver Docker container and am running into some issues. I believe this is similar to issue #208. Reading the [Wiki](https://github.com/dbeaver/cloudbeaver/wiki/Driver-managements), this was how I expected things would work from a Dockerfile perspective:

Dockerfile:

```
FROM dbeaver/cloudbeaver:1.2.0

ADD ./pom.xml server/drivers/prestosql/
ADD ./plugin.xml server/bundles/io.cloudbeaver.resources.drivers.base/
```

Driver `pom.xml`:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>drivers.prestosql</artifactId>
    <version>1.0.0</version>
    <parent>
        <groupId>io.cloudbeaver</groupId>
        <artifactId>drivers</artifactId>
        <version>1.0.0</version>
        <relativePath>../</relativePath>
    </parent>
    <properties>
        <deps.output.dir>prestosql</deps.output.dir>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.prestosql</groupId>
            <artifactId>presto-jdbc</artifactId>
            <version>338</version>
        </dependency>
    </dependencies>
</project>
```

Plugin XML:

<?xml version="1.0" encoding="UTF-8"?>
<plugin>
    
    <extension point="org.jkiss.dbeaver.resources">
        <resource name="drivers/clickhouse"/>
        <resource name="drivers/derby"/>
        <resource name="drivers/jaybird"/>
        <resource name="drivers/h2"/>
        <resource name="drivers/mysql/mysql8"/>
        <resource name="drivers/mariadb"/>
        <resource name="drivers/postgresql"/>
        <resource name="drivers/prestosql"/>
        <resource name="drivers/sqlite/xerial"/>
    </extension>

    
    <extension point="org.jkiss.dbeaver.product.bundles">
        <bundle id="drivers.clickhouse" label="Clickhouse drivers"/>
        <bundle id="drivers.derby" label="Derby drivers"/>
        <bundle id="drivers.firebird" label="Firebird drivers"/>
        <bundle id="drivers.h2" label="H2 drivers"/>
        <bundle id="drivers.mysql" label="MySQL drivers"/>
        <bundle id="drivers.mariadb" label="MariaDB drivers"/>
        <bundle id="drivers.postgresql" label="PostgreSQL drivers"/>
        <bundle id="drivers.prestosql" label="PrestoSQL drivers"/>
        <bundle id="drivers.sqlite.xerial" label="SQLite drivers"/>
    </extension>

    
    <extension point="io.cloudbeaver.driver">
        <driver id="generic:yandex_clickhouse"/>
        <driver id="generic:derby_server"/>
        <driver id="jaybird:jaybird"/>
        <driver id="generic:h2_embedded"/>
        <driver id="mysql:mysql8"/>
        <driver id="mysql:mariaDB"/>
        <driver id="postgresql:postgres-jdbc"/>
        <driver id="generic:prestosql_jdbc"/>
        <driver id="generic:sqlite_jdbc"/>
    </extension>
</plugin>
```

However, it appears these instructions expect the user to be building from source with the `build.sh` script _after_ the relevant files have been updated/added. Going off that, it looks like the `cloudbeaver` source is added to the Docker image after the `build.sh` script is run, per the [Dockerfile](https://github.com/dbeaver/cloudbeaver/blob/devel/deploy/docker/Dockerfile#L6).

Is there an interim Maven command I need to add to the image entrypoint to get this to work? The default entrypoint `ENTRYPOINT ["./run-server.sh"]` does not register the added drivers since no build commands are executed.

Thanks for any and all clarification, and I am very excited to start using this! I'm happy to create a doc PR to update the instructions for adding drivers to a custom Dockerfile if that would be helpful as well.

**Comment by jefflester** [comment]
I confirmed that the `COPY cloudbeaver /opt/cloudbeaver` Dockerfile instruction is grabbing the build artifacts resulting from `build.sh` script. So it does in fact appear that the only way to add drivers to your Dockerized CloudBeaver is to design your own Dockerfile and to copy over your own built distribution. 

If I'm wrong and there's an easier way to do this, please let me know.

**Comment by serge-rider** [comment]
You don't need to change Dockerfile in order to add drivers. Dockerfile copies all drivers configured in pom.xml and pluginx.xml.
We plan to add Presto as pre-configured driver in the next version (1.3).

**Comment by jefflester** [comment]
Thanks for confirming, @serge-rider. A couple of quick followup questions:

1. Do you plan to add PrestoSQL, PrestoDB, or both drivers in the 1.3 release?
2. If you don't need to change/make your own Dockerfile, how do you actually add drivers to a container? I'm probably misunderstanding (if this is possible), but it looks like you need to clone the CloudBeaver source, add the new driver resources, build it, and then add the built distro to your own Dockerfile.

Thank you again! We're really excited to start using this. :)

**Comment by darint00** [comment]
Yes, please explain how to add a driver to the container.  I have an Informix driver I'd like to add.  And the only thing, as mentioned above, I can think of is ..
1.  Create your own image with a dockerfile that adds the specific driver you want.
If there is another way, easier way, please let us know.

**Comment by mskyttner** [comment]
I too would like to add a driver but didn't figure it out. 

This is a draft multi-stage Dockerfile that builds in the first step and then moves build results in the second step (probably some things are moved which doesn't need to be moved, I'm a bit unfamiliar with the build tools).

But where would I add my jdbc driver?

```Dockerfile
FROM adoptopenjdk/openjdk11:x86_64-ubuntu-jdk-11.0.7_10

RUN apt-get update -y && apt-get install -y \
	nano \
	git \
	maven

RUN apt-get install -y gnupg && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - 

RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
	apt-get update -y && apt-get install -y --no-install-recommends \
	yarn

# build server
RUN mkdir conf workspace web
RUN git clone --depth=1 https://github.com/dbeaver/cloudbeaver.git
RUN git clone --depth=1 https://github.com/dbeaver/dbeaver.git

WORKDIR /cloudbeaver

RUN cd server/product/aggregate && \
	mvn clean package -Dheadless-platform

RUN cp -rp server/product/web-server/target/products/io.cloudbeaver.product/all/all/all/* server && \
	cp -p deploy/scripts/* .

RUN mkdir -p deploy/cloudbeaver/samples/db deploy/cloudbeaver/conf && \
	cp -rp samples/sample-databases/db deploy/cloudbeaver/samples/ && \
	cp -rp samples/sample-databases/GlobalConfiguration/.dbeaver/data-sources.json deploy/cloudbeaver/conf/initial-data-sources.conf && \
	cp -p samples/sample-databases/*.conf deploy/cloudbeaver/conf/ && \
	mv server/drivers deploy/cloudbeaver

# build frontend

RUN curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && \
	chmod +x ./nodesource_setup.sh && ./nodesource_setup.sh && \
	apt-get install -y nodejs

RUN cd webapp && yarn && \
	yarn add -W lerna --dev && \
	npm install --global lerna && \
	lerna run build --stream --scope=@cloudbeaver/product-default -- -- --mode=production

RUN mkdir -p deploy/cloudbeaver/web && \
	cp -rp webapp/packages/product-default/lib/* deploy/cloudbeaver/web

RUN mv /cloudbeaver /opt/cloudbeaver

FROM adoptopenjdk/openjdk11:alpine-slim

COPY --from=0 /opt/cloudbeaver /opt/cloudbeaver

RUN apk --update --no-cache add tini bash

WORKDIR /opt/cloudbeaver

EXPOSE 8978
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/opt/cloudbeaver/run-server.sh"]
```

**Comment by momiji** [comment]
does it help #259 ?

**Comment by jefflester** [comment]
> does it help #259 ?

@momiji It adds some clarity––it looks like your flow involves cloning both DBeaver and Cloudbeaver, making adjustments to each repository, and then building them with the changes. Please correct me if I'm wrong.

I'm interested in using the provided Docker image and extending it through my own Dockerfile without the need to modify and build both the DBeaver and CloudBeaver repositories. If that's the required flow, I'll probably wait until release 1.3 comes out for native support of Presto JDBC drivers. Speaking of which, @serge-rider do you know if you're adding the [Trino](https://github.com/trinodb/trino) (formerly PrestoSQL) or the PrestoDB drivers?

In terms of adding new drivers to the Docker image, this is how I'd envision it working:

```
FROM dbeaver/cloudbeaver:1.2.0

ADD ./pom.xml server/drivers/prestosql/
ADD ./plugin.xml server/bundles/io.cloudbeaver.resources.drivers.base/
```

Or by simply mounting the files to the base CloudBeaver image without modifying it through a Dockefile at all.

Thanks again, everyone!

**Comment by momiji** [comment]
Hi,

> @momiji It adds some clarity––it looks like your flow involves cloning both DBeaver and Cloudbeaver, making adjustments to each repository, and then building them with the changes. Please correct me if I'm wrong.

Absolutely, you're right.

Concerning your idea ti build from docker image, what you're proposing cannot work, because adding the pom.xml is not for the single purpose of adding a new file on the filesystem, but to add a new sub-project in the project building process (which uses maven, which uses pom.xml...).

So my understanding is you definitely need to rebuild the project... Then, rebuilding one or two, no difference especially as the build.sh script rebuilds both...

Regards.

**Comment by serge-rider** [comment]
Please see instruction how to add new drivers: https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if you have some additional questions.
