### ISSUE TITLE
The value panel could only show 4k characters.

### ISSUE THREAD

**Issue by ImagineBrain** [dbeaver/cloudbeaver#2156]
**Describe the bug**
We're using DBeaver to manage the MySQL database, there is a table includes a text column. When I query a record and view this text column's value via the value panel, only the first 4k characters was showed. Then I try to export this text column's value into txt, I can find it contains 8045 characters. I don't know this is a bug in the value panel, or it's by design.

**To Reproduce**
1. Find a column value which contains more than 4k characters.
2. Click on 'value' panel to view the value.
3. Only the first 4k characters was showed.

**Screenshots**
![Screenshot_2023-11-22_at_14_10_02](https://github.com/dbeaver/cloudbeaver/assets/11919568/a057f033-fff5-402e-acc3-b300079f069b)
<img width="688" alt="Screenshot_2023-11-22_at_14_11_23" src="https://github.com/dbeaver/cloudbeaver/assets/11919568/c684dca3-94c9-430a-8ac3-21772a6b4554">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Chrome]
 - Version
![image](https://github.com/dbeaver/cloudbeaver/assets/11919568/004ddb45-bf98-4b69-926c-9a27d880d2b7)

**Comment by EvgeniaBzzz** [comment]
Hi @ImagineBrain!
It's not a bug, this is a set limit. You can change parameter for visible text in [sqlTextPreviewMaxLength](https://dbeaver.com/docs/cloudbeaver/Server-configuration/#resource-quotas).
We will increase default limit for text visability. Thank you for your report!

**Comment by Jeffrey778** [comment]
Hi @EvgeniaBzzz, I tried update sqlTextPreviewMaxLength to 65535 but not work, would you please take a look?

**Comment by EvgeniaBzzz** [comment]
Hi @Jeffrey778 
Let's check steps:
1. `.cloudbeaver.runtime.conf` in your workspace (or `.cloudbeaver.conf`, but it has lower priority)
2. Updated `sqlTextPreviewMaxLength` in `app.resourceQuotas`
3. Server was restarted if it was running

I just tried again and it works as expected

**Comment by EvgeniaBzzz** [comment]
Hi @ImagineBrain!
We added a button to load full content for string data types in the Value panel. Please, check it out in 23.3.3
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/f54e74af-39db-4191-bc48-c9ec6e6f72bf)

**Comment by ImagineBrain** [comment]
@EvgeniaBzzz 

Seems it doesn't work. I've upgrade it to 23.3.3, the `
VIEW FULL TEXT` button is not showed up. The `DOWNLOAD` button disappeared even for some records.

![Screenshot 2024-01-23 at 15 04 59](https://github.com/dbeaver/cloudbeaver/assets/11919568/4318e40a-e457-475c-89b6-b82ec4efbbca)
![Screenshot_2024-01-23_at_15_04_05](https://github.com/dbeaver/cloudbeaver/assets/11919568/a4d3b62d-f046-4691-86fa-a9313a22d3e6)
![Screenshot_2024-01-23_at_15_04_46](https://github.com/dbeaver/cloudbeaver/assets/11919568/6308c11d-9ac5-41da-b90b-28139dac15ee)

**Comment by EvgeniaBzzz** [comment]
Hi @ImagineBrain 
'View full text' button appears only in the case when the content is truncated. 
Can you see the whole text in the value panel now?
Didn't you increase the limit?

**Comment by ImagineBrain** [comment]
Hi @EvgeniaBzzz,

When the text is over than 4k, the `Download` button will be showed, which is matched with the logic you mentioned above. But I still don't find the `View Full Text` button, any settings needs to enable?

**Comment by EvgeniaBzzz** [comment]
@ImagineBrain 
Please, make `sqlBinaryPreviewMaxLength` and `sqlTextPreviewMaxLength` equal ( in `.cloudbeaver.runtime.conf`)
We will make an improvement for that :) Thank you for bringing this to our attention.

And we are also going to add a wrap button for value panel in the next release. So you will not have to scroll that far anymore :)

**Comment by ImagineBrain** [comment]
@EvgeniaBzzz

It works after I made these changes. Now I can view the full text in the value panel, this feature is very helpful!

> @ImagineBrain Please, make `sqlBinaryPreviewMaxLength` and `sqlTextPreviewMaxLength` equal ( in `.cloudbeaver.runtime.conf`) We will make an improvement for that :) Thank you for bringing this to our attention.
> 
> And we are also going to add a wrap button for value panel in the next release. So you will not have to scroll that far anymore :)

**Comment by Syrnnik** [comment]
@EvgeniaBzzz 
Got same problem on `25.0.5` version.
I couldn't edit json columns because of limits and updating them using sql scripts isn't convenient..

Tried to set `CLOUDBEAVER_RESOURCE_QUOTA_SQL_BINARY_PREVIEW_MAX_LENGTH` and `CLOUDBEAVER_RESOURCE_QUOTA_SQL_TEXT_PREVIEW_MAX_LENGTH` in env file as described in docs (https://dbeaver.com/docs/cloudbeaver/Server-configuration/#resource-quotas) but nothing changed. Also tried to set directly in docker compose file in container `environment` param and also nothing.
Then I changed `sqlTextPreviewMaxLength` in `.cloudbeaver.runtime.conf` and it's finally solved :)

It'll be so good if you can somehow fix this in future releases
Thank you in advance :)
