### ISSUE TITLE
Server resource and security questions about self hosting

### ISSUE THREAD

**Issue by abhi40308** [dbeaver/cloudbeaver#2157]
Hi folks, thanks for amazing work on cloudbeaver! We were looking into self deployment options (using docker), and wanted to know some server stats on:
1. how many concurrent connections could a single instance handle reliably
2. what is the instance size, etc.

Questions like:
1. If we had 1000 users each with the cloudbeaver open and actively working with the DB UI, how much might we be spending on server resources

If you could give some ballpark estimates on resource consumption vs number of active users, from your experience of hosting the demo server at https://demo.cloudbeaver.io/#/, that would be amazing 

We are also considering disabling the user login, so users will only be able to connect anonymously. Wanted to know if there could be some specific security considerations we should take. 

Thanks in advance!

**Comment by EvgeniaBzzz** [comment]
Hi @abhi40308!
Thank you for being with CloudBeaver! 
Could you please send your questions to [support@dbeaver.com](mailto:support@dbeaver.com)

**Comment by abhi40308** [comment]
Sure @EvgeniaBzzz  i've emailed the questions, thanks!

**Comment by EvgeniaBzzz** [comment]
If there are any specific questions, please let us know.

**Comment by abhi40308** [comment]
Hi @EvgeniaBzzz , thanks for looking into the issue so quickly. I haven't got any reply to the support email yet. Please note that we are evaluating cloudbeaver for our use case and these are important metrics for us to know, and the questions are specifically about hosting cloudbeaver ce / ee images and not dbeaver in general (the support email seems like general dbeaver support). 

If we can make this process faster that would be awesome for us, if possible could you please tag someone who has experience with this or with hosting the demo server on https://demo.cloudbeaver.io/#/ , maybe tag here itself or please check the emails from abhijeet@hasura.io to [support@dbeaver.com](mailto:support@dbeaver.com)

**Comment by EvgeniaBzzz** [comment]
@abhi40308 
I will ask support team to prioritize your questions
