### ISSUE TITLE
Allow server listen address to be specified, and allow unix socket file path instead of port

### ISSUE THREAD

**Issue by toddpfaff** [dbeaver/cloudbeaver#216]
In addition to being able to specify serverPort in cloudbeaver.conf, I'd like to be able to also specify the IP addresses to listen on.  In most cases this would be localhost only, for cloudbeaver running behind a web server such as nginx or apache.  Once that is possible, I would recommend that localhost should be the default unless overriden in cloudbeaver.conf, for additional security.

I would also like to be able to have cloudbeaver listen on a unix socket file path instead of a port.  Is this already possible perhaps by specifying an absolute file path instead of a port number for serverPort?

Thanks!

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion and sorry for the long answer.

**Comment by zach-withcoherence** [comment]
Hi! Is there any workaround to listen to a socket file path instead of a port, as suggested above? Thanks...

**Comment by kseniiaguzeeva** [comment]
@zach-withcoherence we don't support a socket file path. Hovewer we are going to add possibility to listen IP addresses.

**Comment by serge-rider** [comment]
Parameter `serverHost` was added to server configuration.
Server config docs were updated: https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration

This feature will be added in the next CB release.

**Comment by kseniiaguzeeva** [comment]
The latest version is available.
