### ISSUE TITLE
Possibility to Inject user db credentials programatically (how to update credentials-config.json)

### ISSUE THREAD

**Issue by Fran-Rg** [dbeaver/cloudbeaver#2165]
Hi,

I'm working on some automation around db management and I'm interested in providing the users with private connections programatically. I found the relevant files to update are:
* user-projects/USER/.dbeaver/data-sources.json
* user-projects/USER/.dbeaver/credentials-config.json

While the first one is simple to understand, the second one is encoded. What's the way to decode in order to update it?

I see that this is partially repeated on https://github.com/dbeaver/cloudbeaver/wiki/User-credentials-storage
But it doesn't point to where and what the encryptions are.

PS: amazing job on this tool

**Comment by EvgeniaBzzz** [comment]
Hi @Fran-Rg!
We do not have API for saving encrypted user/password for private connections. Only UI allows to save encrypt data in this case. 

As a workaround you can add user/password to `data-sources.json`.
```
"auth-properties" : {
	"user": "username",
	"password": "connection_password"
	}
```
But keep in mind that your passwords will be stored as _plain text_. **Use this method only if you are absolutely sure that nobody can gain access to your data!**

**Comment by Fran-Rg** [comment]
Thanks

That worked and if anyone is interested it is in:
```
{
"connections":{
  "CONNECTION_ID":{
  ...
    "configuration: {
      ...
     
	  "auth-properties": {
	  	  "user": "DBUSER",
	 	  "password": "DBPASS"
	  },
