### ISSUE TITLE
"Save Credentials" missing from admin connection template creation

### ISSUE THREAD

**Issue by daledude** [dbeaver/cloudbeaver#2179]
**Describe the bug**
https://github.com/dbeaver/cloudbeaver/wiki/Connection-Templates-Management
The above wiki page states on #5:

> As an administrator, you can set and save these authentication parameters by checking the Save Credentials checkbox in the Authentication section. Doing so will allow any user with access to the template to connect without needing to enter their credentials.

But there isn't a "Save Credentials" button.

EDIT: I have "Save credentials" and "Save user credentials" enabled under "Server Configuration".

**To Reproduce**
1. Go to /#/admin/connections
2. Click on "+Add"
3. Pick database driver
4. See Authentication section

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 1.61.83

**Comment by EvgeniaBzzz** [comment]
Hi @daledude!
We have changed te way of creating templates for security reasons - now creds are never saved. User should enter creds when creating a connection from the template.
And we missed these changes in the article :) Sorry for the inconvenience. Thank you for bringing this to our attention!

**Comment by EvgeniaBzzz** [comment]
We have edited wiki article, it is actual now. Thank you again!
