### ISSUE TITLE
Cursor disappears from UI and doesn't write anything

### ISSUE THREAD

**Issue by EysaN** [dbeaver/cloudbeaver#2183]
**Description**
After authenticating to cloudbeaver CE with Username/Password, I can work normally for few minutes, then the cursor disappears.
After that, I cannot input any characters and I cannot see the cursor, until I reload the page completely. 

I believe the issue is related to the fact that I am working on MySQL 5.7 database.
And in [23.2.5 release](https://github.com/dbeaver/dbeaver/releases/tag/23.2.5), `Legacy MySQL 5.x driver was deprecated and replaced with MySQL 8 driver` so my database is facing this issue.

How could I support backward compatibility for my MySQL 5.7 connections.

**To Reproduce**
1. log in to CloudBeaver CE latest version. 23.2.5
2. work for a while about (10 mins)
3. wait for the issue to happen
4. under the browser's console, you can see websocket errors.

**Browsers**
 Chrome, Firefox, Edge.

**Comment by EvgeniaBzzz** [comment]
Hi @EysaN!
Have you encountered the issue of the cursor disappearing in the SQL editor after a while, am I right?
If yes, then this is a known bug in 23.2.5, it's not your database issue. It will be fixed in 23.3.0 (next week).
Thank you for the report! Sorry for the inconvenience.

**Comment by EysaN** [comment]
yes @EvgeniaBzzz, you are right, it happens in the SQL editor after a while from opening it.
is there any known workarounds for this until next week?
thank you for the quick answer.

**Comment by EvgeniaBzzz** [comment]
@EysaN the only workaround you have already found - it's page reload. Or close script tab and open the script again from resource manager.
The problem occurs when the browser tab is inactive for about 6 minutes.

**Comment by dariamarutkina** [comment]
We fixed this in version 23.3.0
@EysaN  , Please, check CloudBeaver v.23.3.0
Thank you for your interest in CloudBeaver!
