### ISSUE TITLE
How to configure Postgres connection for this use case?

### ISSUE THREAD

**Issue by toddpfaff** [dbeaver/cloudbeaver#219]
I am beginning to test CloudBeaver as a tool to provide a consistent web interface to users of our various database services, including MySQL, MariaDB, Postgres,and MS-SQL.

My current goal is to allow anonymous connections to CloudBeaver and, from there, users would create a new connection to their database using one of the templates we provide.  They would provide their database username and password, establish an authenticated connection to the DB server, and be presented with a list of database for which their authenticated credentials have access.

This is exactly how our MySQL / MariaDB database users are accustomed to working with phpMyAdmin.

This is working as expected for a MySQL connection, using the MySQL driver provided with CloudBeaver.

Unfortunately this is not working similarly for Postgres.  In the Postgres case, regardless of the Postgres user credentials provided, a connection is being established but only the "postgres" database is visible.

Can anyone tell me if it's possible to have a CloudBeaver Postgres connection behave similarly in this respect to a CloudBeaver MySQL connection, and to phpMyAdmin?

Thanks.

**Comment by kseniiaguzeeva** [comment]
We are going to implement this option in the future. While you can use 2 workarounds:
- create a separate connection for every database
- set parameter @dbeaver-show-non-default-db@": "true" in JSON file for PostgreSQLhttps://github.com/dbeaver/cloudbeaver/wiki/Configuring-server-datasources

**Comment by kseniiaguzeeva** [comment]
PostgreSQL specific settings were added to the latest CE version 20.0.3. You can set **Show all databases** parameter now.
![chrome_R5ZXmvtITf](https://user-images.githubusercontent.com/51405061/107628104-37e83080-6c71-11eb-85f4-9f78d14833cd.png)
