### ISSUE TITLE
Table list not expanding

### ISSUE THREAD

**Issue by Vormillion** [dbeaver/cloudbeaver#2197]
Version: Cloudbeaver EE 23.2.0

We have an issue with one db schema which is not showing tables on navigation panel, all other schemas under this connection are working fine. We can select from this schema using SQL editor without any issues and also "SHOW TABLES" query works fine.

I checked graphql call and it's not returning tables list:

`{
  "data": {
    "navNodeChildren": [],
    "navNodeInfo": {
      "id": "database://mysql8-18a45b55543-a469f1beda31274/org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog/XX/org.jkiss.dbeaver.ext.mysql.model.MySQLTable",
      "name": "Tables",
      "plainName": null,
      "hasChildren": true,
      "nodeType": "Tables",
      "icon": "platform:/plugin/org.jkiss.dbeaver.model/icons/tree/folder_table.png",
      "folder": true,
      "inline": false,
      "navigable": true,
      "filtered": true,
      "features": [
        "container",
        "shared"
      ],
      "projectId": "g_GlobalConfiguration",
      "object": {
        "features": []
      }
    }
  }
}`

![image](https://github.com/dbeaver/cloudbeaver/assets/10175362/9338c2bc-b3b1-49f5-9384-da895f771386)

**Comment by EvgeniaBzzz** [comment]
Hi @Vormillion!
It seems you have enabled a filter.
Open context menu of the Tables folder, navigate to Filters and choose Reset filter
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/cd4f4d46-d481-4034-af88-a6863daff89a)

**Comment by Vormillion** [comment]
Hi,

You were right! Thank you very much.
