### ISSUE TITLE
Connection templates list is empty

### ISSUE THREAD

**Issue by Vormillion** [dbeaver/cloudbeaver#2198]
Version: Cloudbeaver EE 23.2.0

Connection template list is empty when checking it as an administrator. I can see that file with connection details is present, all the connections are loaded and I can edit them from navigation panel but as an administrator I can't modify them globaly.

I can see that graphql is properly returning templates, so it's just UI not showing them.

![image](https://github.com/dbeaver/cloudbeaver/assets/10175362/ffb26863-8144-45f4-9f48-54d630a49c82)

**Comment by EvgeniaBzzz** [comment]
Hi @Vormillion!
Are you sure that you have created any templates? This GraphQL request returns both existing connections and templates. 

Connections in the navigation tree and [connection templates](https://github.com/dbeaver/cloudbeaver/wiki/Connection-Templates-Management) are two different things. A template is a pre-configured connection that can be used for quickly creating connections with all the necessary permissions.

In Connection templates tab of the Administration menu you will not see any existing connections from the navigation tree.

**Comment by Vormillion** [comment]
Hi,

That's correct. For sure I've created templates in the past, bacause I used them to grant proper permissions per connection template. Then based on those templates connections in navigation tree appeared (based on user permission).

Now I can't see those templates anymore.

**Comment by EvgeniaBzzz** [comment]
If I understood you correctly, we are still discussing different things. 

Connection - a specific instance for database access, and you can find them in the navigation tree. 

Connection template - a template that allows you to create many copies of connections. You can create a specific instance via the Tools menu on the main page.

![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/30250551-f43d-4433-9390-90c0a89d5074)

You can still change permissions for shared connections on the main page. All your changes will affect other users.

![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/c8ef35c1-5ab2-4f5b-bab9-2076078b0f68)

We have removed the list of existing connections from the Administration section in [23.2.0](https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-23.2.0--2023-09-04).

We'll add some information to our wiki article to make this clearer.
