### ISSUE TITLE
CloudBeaver connection to MS SQL Server Express?

### ISSUE THREAD

**Issue by toddpfaff** [dbeaver/cloudbeaver#220]
Anyone have experience connecting CloudBeaver to MS SQL Server?

**Comment by serge-rider** [comment]
We will add SQL Server drivers in version 1.3 (release in December).

**Comment by serge-rider** [comment]
SQL Server driver was added in the version 1.3 (aka 20.0)

**Comment by tigerbones24** [comment]
> SQL Server driver was added in the version 1.3 (aka 20.0)

Hi, 
I don't see it added, I have just installed it via docker is this version not released for docker yet?

kr

**Comment by serge-rider** [comment]
@tigerbones24 Indeed, SQL Server config was broken. Now fixed.
New docker version will be published on the next week.
