### ISSUE TITLE
can i close auto commit

### ISSUE THREAD

**Issue by dennymou** [dbeaver/cloudbeaver#2221]
how can i use clouddbeaver with transaction manual commit default

auto commit off

**Comment by EvgeniaBzzz** [comment]
Hi @dennymou!
Unfortunately, we don't have options to configure commits via UI. But we are going to implement it in the future (the same request [here](https://github.com/dbeaver/cloudbeaver/issues/129)).
For now you can make it manually according to your DB syntax - `begin transaction` and then `commit/rollback`.

**Comment by dennymou** [comment]
thank u so much

**Comment by EvgeniaBzzz** [comment]
Hi @dennymou!
[Manual commit mode](https://github.com/dbeaver/cloudbeaver/wiki/SQL-Editor#auto-and-manual-commit) was added in 24.0.1

**Comment by dennymou** [comment]
> Hi @dennymou! [Manual commit mode](https://github.com/dbeaver/cloudbeaver/wiki/SQL-Editor#auto-and-manual-commit) was added in 24.0.1
so great
