### ISSUE TITLE
can i use stored procedure debug on UI with opengauss?

### ISSUE THREAD

**Issue by dennymou** [dbeaver/cloudbeaver#2226]
can i use stored procedure debug on UI with opengauss?

**Comment by EvgeniaBzzz** [comment]
Hi @dennymou!
CloudBeaver do not have any debugger now and not going to implement it in near future.

But there is console output log as a little help 
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/6cf03fe5-bf4f-4ac7-9925-9c2d1f05f2fc)

**Comment by dennymou** [comment]
> Hi @dennymou! CloudBeaver do not have any debugger now and not going to implement it in near future.
> 
> But there is console output log as a little help ![image](https://private-user-images.githubusercontent.com/139753579/290493258-6cf03fe5-bf4f-4ac7-9925-9c2d1f05f2fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDU4MDYsIm5iZiI6MTcwMzE0NTUwNiwicGF0aCI6Ii8xMzk3NTM1NzkvMjkwNDkzMjU4LTZjZjAzZmU1LWJmNGYtNGFjNy05OTI1LTljMmQxZjA1ZjJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNzU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmYwMGRjOWNkNWUwMTg1ZDA3NjNkM2NhNzJmNzM3MzMzZTBlYTFjM2E1ZjU5NDg5NjFlMTMwMmMzNmY4ZGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E6VD260e54CY2_whJv4VG6xWVoGcj9ik24ks3Ra321s)

ok , ths!
