### ISSUE TITLE
Eclipse start has some problem

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#2233]
When i build the cloudbeaver，the floder don not have that start file。

![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/67361d2e-5782-4751-9300-9bb922efc9f1)
![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/69a2956c-9832-4a23-b0a3-57daa51ec448)

**Comment by ccczhouxin** [comment]
When i start the cloudbeaver has this error.
![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/87979cde-eee5-45ff-99a8-5178c958b5ef)

**Comment by EvgeniaBzzz** [comment]
Hi @ccczhouxin!
Deployment has been changed a little bit.
You can open `cloudbeaver/server/product/web-server/CloudbeaverServer.product` file in Eclipse and press `Launch as Eclipse applicaton`.

We will update the wiki, sorry for the inconvenience.

![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/0cfeba47-d6b8-4c0d-8a3f-77de9c5be04d)

**Comment by ccczhouxin** [comment]
> Hi @ccczhouxin! Deployment has been changed a little bit. You can open `cloudbeaver/server/product/web-server/CloudbeaverServer.product` file in Eclipse and press `Launch as Eclipse applicaton`.
> 
> We will update the wiki, sorry for the inconvenience.
> 
> ![image](https://private-user-images.githubusercontent.com/139753579/290792979-0cfeba47-d6b8-4c0d-8a3f-77de9c5be04d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODMyNjgsIm5iZiI6MTcwMjg4Mjk2OCwicGF0aCI6Ii8xMzk3NTM1NzkvMjkwNzkyOTc5LTBjZmViYTQ3LWQ2YjgtNGMwZC04YTNmLTc3ZGU5YzViZTA0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNzAyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZThlZDJjYmE0NDA0N2Q5MWY1ODUyM2M5OTU0NWU2ZTM4YzJmNzUzYjFmYTA2NGM2ODVkNDg0ZjhlM2ZiM2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ObSAInw-sgMTn1DA1Hya_dpPbBh7uL_uM63rCfyFnXI)

ok

**Comment by EvgeniaBzzz** [comment]
Thank you for bringing this to our attention! Please contact us if you have any further questions.
