### ISSUE TITLE
A Tool for Adding Cloudbeaver Database Drivers

### ISSUE THREAD

**Issue by Danst-bjtu** [dbeaver/cloudbeaver#2239]
I have developed a tool for automatically expanding database drivers, which is more efficient than changing configuration files. Specific information can be accessed https://github.com/danst-bjtu/cloudbeavertool. Hope to help more people.

**Comment by EvgeniaBzzz** [comment]
Hi @Danst-bjtu!
Thank you for your interest in our product and for contributing to the community!

Also we would like to remind that this method is not official and is not supported by the CloudBeaver development team. Explore the [official method](https://github.com/dbeaver/cloudbeaver/wiki/Drivers-Management) of adding drivers in the [Enterprise Edition](https://dbeaver.com/cloudbeaver-enterprise/).
