### ISSUE TITLE
[Docker Image] Switch to Alpine & support more archs

### ISSUE THREAD

**Issue by the-hotmann** [dbeaver/cloudbeaver#2253]
Currently there is just one official Docker Image. It is based on Ubuntu and supported just the `amd64` architecture.

This was common +5 years ago. These days specially the official Images are provided, based on Alpine Linux and for at least:
- `amd64`/`х86_64`
- `arm64`/`aarch64` (supported since `22.3.3`)

better would be additionaly:
- `riscv64`
- `armv7`
- `armv6`
- `armhf`
- `ppc64le`
- `s390x`
- `x86`

Most Docker Images I re-dockerized from Ubuntu to Alpine has come down about 80% of the Imagesize (which is already compressed!) and typically are just in general slimmer, more secure and better performing.

It might be worth it, also I dont see any dependencies which Alpine is not able to provide

Specially when we are talking about security issues popping up with automatic scanns, Alpine shows to be one of the best as it is the most up-to-date.

I would be happy to assist if there is a Dockerfile.

Best regards,
Martin

**Comment by EvgeniaBzzz** [comment]
Hi @the-hotmann!
Thank you for your request! 
Actually, we are working on Alpine right now :) So it will be implemented in the near future.

**Comment by the-hotmann** [comment]
Is there any info about this, or an early mockup etc.?
Would be happy to have some info about this.

**Comment by EvgeniaBzzz** [comment]
Unfortunately, I can't give you any details as it is in development now.
But the work will be finished till mid-January I suppose.

**Comment by the-hotmann** [comment]
Mid January is over - is there any news on this?

Only thing I noticed was:

Docker-Image size went up a bit, but not hint of Alpine images, or more archs.

**Comment by EvgeniaBzzz** [comment]
Hi @the-hotmann 
We had to change plans. For now we still have Ubuntu (23.10).
Alpine uses the primary C library - `musl`, while we primarily use libraries compatible with `glibc`. Some database drivers lack compatibility unfortunately.
We will look for other ways.
