### ISSUE TITLE
Pre-defined database connection issue using os env var with latest docker image (23.3.1)

### ISSUE THREAD

**Issue by kjee87** [dbeaver/cloudbeaver#2276]
Hello 

I just found out the new release on cloudbeaver and I am having issues with pre-defined database connection, which was fine with previous version (23.2.0). 
I am using this `initial-data-sources.conf` and it errored with a message that it cannot make connection to this database url "${hostname}:8080", which sounds like it does not support os env var anymore...? or Am I missing something here?

`{
	"folders": {},
	"connections": {
        "trino_connection": {
            "provider": "generic",
            "driver": "trino_jdbc",
            "name": "trino_connection",
            "save-password": true,
            "show-system-objects": false,
            "read-only": true,
            "template": false,
            "configuration": {
                "user": "${username}",
                "password": "${password}",
                "host": "${hostname}",
                "port": "8080",
                "url": "jdbc:trino://${hostname}:8080",
                "type": "dev",
                "provider-properties": {
                    "@dbeaver-show-non-default-db@": "False"
                }
            }
        }
	}
}`

**Comment by dariamarutkina** [comment]
Hello, @kjee87 !
We have turned off some settings for security reasons, but we will add a parameter to the server settings to allow us to do as it worked before.
Thank you for your interest in our product and for contributing to the community!

**Comment by LonwoLonwo** [comment]
Hello @kjee87 

As my colleague said - we removed this env variable for security reasons. 
We can return this ability to use this parameter as an option only for connections, not for the server side. And we will probably add it only with the ability to add it in configuration directly, not via UI.

Would such a decision suit you? If not, then please describe, more precisely - why not.

**Comment by dariamarutkina** [comment]
Hello, @kjee87 
We implemented support for utilizing environment variables within connection configurations;
A new parameter was added to the ‘app’ part, you can change the value in the [.cloudbeaver.runtime](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration)

> systemVariablesResolvingEnabled: "true"

Please take a look at the new version of CloudBeaver 24.0.2
Thank you for your interest in CloudBeaver!
