### ISSUE TITLE
Cloudbeaver Community in Docker supports DuckDB ?

### ISSUE THREAD

**Issue by frankvent** [dbeaver/cloudbeaver#2283]
Thank you very much to the whole team for the great work you do. I've been testing Cloudbeaver Community in Docker for a long time. Is it possible to incorporate the Duckdb driver?

**Comment by dariamarutkina** [comment]
Hello, @frankvent !
Currently, the DuckDB driver is available in the PRO version of the CloudBeaver Enterprise Edition. We plan to add it to the CloudBeaver Community Edition product.
Thank you for your interest in our product and for contributing to the community!

**Comment by EvgeniaBzzz** [comment]
Hi @frankvent!
DuckDB support has been added in 23.3.3, please, check it out

**Comment by frankvent** [comment]
Great!!! 👌

**Comment by EvgeniaBzzz** [comment]
@frankvent keep in mind, that DuckDB is an embedded driver, so it is disabled by default. You can enable it in the Server configuration before creating a connection.

**Comment by frankvent** [comment]
I saw it and it works perfectly!!!  Good Job 👌⭐
