### ISSUE TITLE
SQLite driver missing in latest container image

### ISSUE THREAD

**Issue by jokob-sk** [dbeaver/cloudbeaver#2291]
### Description

The SQLite driver seems to be missing in the latest image:

![image](https://github.com/dbeaver/dbeaver/assets/96159884/ee7519d2-3ba6-4b78-b93a-03718a1950b6)

![image](https://github.com/dbeaver/dbeaver/assets/96159884/39c12cdb-b6fe-46c2-992a-f02c7b48dd43)

### DBeaver Version

Community 23.3.2

### Operating System

Docker x86

**Comment by E1izabeth** [comment]
Hi, @jokob-sk. I'll move your issue to the Cloudbeaver issues.

**Comment by dariamarutkina** [comment]
Hello, @jokob-sk !
For security reasons, we have disabled embedded drivers by default; you can enable this driver in the admin settings. Please check this and let us know if you have succeeded.

**Comment by jokob-sk** [comment]
Thanks for the tip - found it after a while. For anyone searching:

1. You need to login
2. Navigate to Settings > Administration 
3. Server configuration
4. Disabled Drivers -> Remove SQLite 

You can close this as resolved.

**Comment by dariamarutkina** [comment]
@jokob-sk Thank you for your interest in our product and for contributing to the community!
