### ISSUE TITLE
Settings and Display Name parameters appear grayed out

### ISSUE THREAD

**Issue by jeayalar** [dbeaver/cloudbeaver#2297]
Hello, 

I am not able to modify the parameters of the Settings page, please see screenshot below:

![image](https://github.com/dbeaver/cloudbeaver/assets/133604687/99dbd19f-7cce-47d0-9f31-8d9ffa538742)

Additionally, the Display Name parameter appears to be grayed out (see image below), is this intended?

![image](https://github.com/dbeaver/cloudbeaver/assets/133604687/4e6f098d-b997-4e3e-85a1-e5374bc3ca31)

**Comment by EvgeniaBzzz** [comment]
Hi @jeayalar!
For now these parameters are read-only.
Global server settings you can change in [cloudbeaver.conf](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#main-server-configuration).
Username could be changed by admin in [Access management](https://github.com/dbeaver/cloudbeaver/wiki/Users).

**Comment by jeayalar** [comment]
Hi @EvgeniaBzzz, thanks for the clarification! I managed to change the settings using the cloudbeaver.conf documentation you sent. Sorry I missed that on the docs!

**Comment by EvgeniaBzzz** [comment]
It's ok. I suppose we will add some clarifications.
Thank you for being with CloudBeaver!
