### ISSUE TITLE
data-sources not working

### ISSUE THREAD

**Issue by FreeSoftwareServers** [dbeaver/cloudbeaver#23]
Please, describe your question in details.
I'm trying to setup pre-defined data-sources. I installed dbeaver and created a connection, copied the config and tried my best to get it to work but I continue to get the following error:

Can anybody give me an example/see what I'm doing wrong? Thanks!

![DB_error](https://user-images.githubusercontent.com/16218200/80445511-58552300-88c9-11ea-81e8-a6423441b2ab.png)

`Exception while fetching data (/navGetStructContainers) : null`
```
PWD=/opt/cloudbeaver/cloudbeaver/deploy/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/
cd $PWD
cat << 'EOF' >data-sources-postgresql.json
{
        "folders": {},
        "connections": {
                "postgres-jdbc-171bee20d7c-272dcd5ad2bbe925": {
                        "provider": "postgresql",
                        "driver": "postgres-jdbc",
                        "name": "PostgreSQL - postgres",
                        "save-password": false,
                        "show-system-objects": false,
                        "read-only": false,
                        "configuration": {
                                "host": "127.0.0.1",
                                "port": "5432",
                                "database": "postgres",
                                "url": "jdbc:postgresql://localhost:5432/",
                                "type": "prod",
                                "properties": {
                                        "connectTimeout": "20",
                                        "loginTimeout": "20"
                                },
                                "auth-model": "native",
                                "handlers": {}
                        }
                }
        },
        "connection-types": {
                "prod": {
                        "name": "Production",
                        "color": "247,159,129",
                        "description": "Production database",
                        "auto-commit": false,
                        "confirm-execute": true,
                        "confirm-data-change": true
                }
        }
}
EOF
systemctl restart cloudbeaver
```

**Comment by Wroud** [comment]
it's a known issue, we work on it, it's not related with configuration

**Comment by serge-rider** [comment]
@FreeSoftwareServers could you check server log? 
Steps to reproduce in UI would be helpful too.

**Comment by FreeSoftwareServers** [comment]
@serge-rider I don't know where to find logs just yet, would help me with debugging, but seems @Wroud says it's a bug/known issue atm. (Though I didn't see a issue tracker created). Basically to reproduce, setup a PostgreSQL DB on localhost that you can connect to and then create the `data-sources*.json* and restart the CB server. It should auto load the data-source and in my case gave the above error. Does that make sense? The goal is to pre-define the connections I want so I don't have to add them each time.

**Comment by FreeSoftwareServers** [comment]
@Wroud  I noticed the `driver` field was blank, perhaps that is related? (In the UI behind the error)

**Comment by Wroud** [comment]
it's can be helpful if you can find this request (`query navGetStruct Containers`) and send which variables are sent to the backend
![image](https://user-images.githubusercontent.com/811729/80539053-772de500-89af-11ea-9f83-93852abb38b0.png)

also, it's probably related with empty driver field like you said

**Comment by serge-rider** [comment]
@FreeSoftwareServers well, default server run script doesn't dump logs anywhere, just flushed everything into stdout (we are working on proper logging configuration). If you start server from console you can see logs on screen.

**Comment by Wroud** [comment]
I'm pushed a fix for object tabs, so request leading to the error now sends only for SQL-editor, probably error will still occur for SQL-editor

**Comment by FreeSoftwareServers** [comment]
@serge-rider I forgot, I actually had trouble getting it to run "silently" lol, used systemd and `&`, but I'll start it manually for debugging next time and post logs.

**Comment by allenyu6** [comment]
was this fixed? can we try out postgres and mysql? can someone post an example here if we have those done and working? Thanks!

**Comment by serge-rider** [comment]
@allenyu6 There are several different and unrelated issues in this ticket. So I'm not quite sure what exactly are you asking about

Datasources configuration was fixed, now it supports folders and all other options.
If it still doesn't work for you - please create separate ticket.
