### ISSUE TITLE
Seeking Advice for Efficient Development and Testing

### ISSUE THREAD

**Issue by tryantdb** [dbeaver/cloudbeaver#2303]
Hello CloudBeaver Team and Community,
recently I'm learning code of Dbeaver and Cloudbeaver. And I did some changes to the cloudbeaver code.
Here is how I test my code works:
	1. Implement code changes.
	2. run deploy/build.bat.
	3. execute deploy/cloudbeaver/run-server.bat in debug mode.
	4. Use idea remote JVM debug to test the code.
My questions are:
It always takes serveral mininutes to run the build.bat after a code change which is disturbing and time-consuming.
In light of this, I'm reaching out to seek your insights and recommendations. I'm curious to learn about the approaches and strategies you employ for developing and testing CloudBeaver. Are there more efficient methods or best practices that you follow within your team? Any tips or tools that could expedite the build and test process would be immensely helpful.
Thank you for your time and for the incredible work you do with DBeaver. I look forward to any suggestions or advice you might have.

**Comment by EvgeniaBzzz** [comment]
Hi @tryantdb!
We will share our debug tips, but it will take some time to prepare.
Thank you for you request!

**Comment by tryantdb** [comment]
> Hi @tryantdb! We will share our debug tips, but it will take some time to prepare. Thank you for you request!

Thank you for your response! Eagerly awaiting your valuable tips.

**Comment by serge-rider** [comment]
We moved IDEA config generator in open source (https://github.com/dbeaver/idea-rcp-launch-config-generator).

Now you can try to build/debug from IDEA using this instruction: https://github.com/dbeaver/cloudbeaver/wiki/Develop-in-IDEA

**Comment by Amor7527** [comment]
Can you synchronize the startup method of dbeaver here? Is it similar to the cloudbeaver startup method provided above?
