### ISSUE TITLE
Friendly competitor invitation

### ISSUE THREAD

**Issue by WebDB-App** [dbeaver/cloudbeaver#2317]
Hello Guys,

First, thanks you for everything you did to the open source community
I just want to invite people to take a look at a new competitor, if possible give feedbacks and even to participate -> webdb.app

Have a great day and happy new year =)
I sincerely hope you doesn't consider this as a awkward move, I just want to help open source community

**Comment by EvgeniaBzzz** [comment]
Hi @WebDB-App 
We wish you all the best. Be brave and wisdom! :)

**Comment by WebDB-App** [comment]
Thanks =)
Wish you the best
