### ISSUE TITLE
Disbale Export option based on User Roles

### ISSUE THREAD

**Issue by anthoniraj** [dbeaver/cloudbeaver#2373]
Kindly provide an option to enable or disable editor export option according to user roles.
![Screenshot 2024-02-09 142238](https://github.com/dbeaver/cloudbeaver/assets/965210/40db2c5a-dc2a-4fbf-b7c5-8121259580ba)

**Comment by dariamarutkina** [comment]
Hi @anthoniraj !
You can set the parameter ['data-export': {disabled: true}](https://github.com/dbeaver/cloudbeaver/wiki/Product-settings-data-export) in [.product.runtime.conf](https://github.com/dbeaver/cloudbeaver/wiki/Product-configuration-parameters). This will mean that the Export will not be available to the User role, while the Export will be available to the Administrator.

**Comment by anthoniraj** [comment]
:~$ sudo docker run --name cloudbeaver --rm -ti -p 8080:8978 -v /opt/cloudbeaver/workspace dbeaver/cloudbeaver:latest
Starting Cloudbeaver Server
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
09-02-2024 06:30:47.921 [main] DEBUG i.c.model.app.BaseWebApplication - Loading configuration from /opt/cloudbeaver/conf/cloudbeaver.conf
09-02-2024 06:30:47.922 [main] DEBUG io.cloudbeaver.server.CBApplication - Using configuration [/opt/cloudbeaver/conf/cloudbeaver.conf]
09-02-2024 06:30:47.922 [main] DEBUG io.cloudbeaver.server.CBApplication - Read configuration [/opt/cloudbeaver/conf/cloudbeaver.conf]
09-02-2024 06:30:47.952 [main] DEBUG io.cloudbeaver.server.CBApplication - Load product configuration from '/opt/cloudbeaver/conf/product.conf'
09-02-2024 06:30:47.956 [main] DEBUG io.cloudbeaver.server.CBApplication - CloudBeaver CE Server 23.3.4.202402051107 is starting
09-02-2024 06:30:47.957 [main] DEBUG io.cloudbeaver.server.CBApplication -      OS: Linux 5.15.0-94-generic (amd64)
09-02-2024 06:30:47.957 [main] DEBUG io.cloudbeaver.server.CBApplication -      Java version: 17.0.10 by Eclipse Adoptium (64bit)
09-02-2024 06:30:47.957 [main] DEBUG io.cloudbeaver.server.CBApplication -      Install path: '/opt/cloudbeaver/server'
09-02-2024 06:30:47.959 [main] DEBUG io.cloudbeaver.server.CBApplication -      Global workspace: 'file:/opt/cloudbeaver/workspace/'
09-02-2024 06:30:47.962 [main] DEBUG io.cloudbeaver.server.CBApplication -      Memory available 128Mb/1986Mb

these files are loaded when server started. when i shutdown the server cloudbeaver folder removed from /opt folder. can you please guide me how to add this config in .product.runtime.conf

**Comment by EvgeniaBzzz** [comment]
You can find and change export parameter in `workspace/.data/.product.runtime.conf`
More info on our [web-site ](https://dbeaver.com/docs/cloudbeaver/Server-configuration/)

**Comment by anthoniraj** [comment]
> /opt/cloudbeaver$ cat workspace/.data/.product.runtime.conf
> {
>         plugin.data-export.disabled: true
> }
Thanks for your guidance, i have created` .product.runtime.conf` file under` /opt/cloudbeaver/workspace/.data/` and added `plugin.data-export.disabled: true`. Now the export option was disabled in editor.

**Comment by anthoniraj** [comment]
> Hi @anthoniraj ! You can set the parameter ['data-export': {disabled: true}](https://github.com/dbeaver/cloudbeaver/wiki/Product-settings-data-export) in [.product.runtime.conf](https://github.com/dbeaver/cloudbeaver/wiki/Product-configuration-parameters). This will mean that the Export will not be available to the User role, while the Export will be available to the Administrator.

Thanks for your comment. it was helped me to analysis the issue.

**Comment by EvgeniaBzzz** [comment]
Enjoy your no-export CloudBeaver! :)
