### ISSUE TITLE
OAuth - ExternalAuthentication on Trino Database Connection

### ISSUE THREAD

**Issue by alaturqua** [dbeaver/cloudbeaver#2375]
**Is your feature request related to a problem? Please describe.**
For example if using jdbc connection to Trino and oauth/externalauthentication is enabled on additional properties.
It should open a new tab or at least show the url to click for authentication.

User can set additional property to "PRINT" and it writes currently into debug logs.

**Describe the solution you'd like**
Ideally a pop up should appear and user can click on the link to authenticate to his database connection via OAUTH, SSO etc.

**Comment by EvgeniaBzzz** [comment]
Hi @alaturqua!
Thank you for your desire to improve CloudBeaver!
But additional authentication methods are beyond the scope of Community edition.
