### ISSUE TITLE
Add configuration for group delimiter from auth proxy

### ISSUE THREAD

**Issue by enimaloc** [dbeaver/cloudbeaver#2376]
**Is your feature request related to a problem? Please describe.**

I use authelia as proxy auth and the delimiter for group header is `,` so I can't use it with cloudbeaver.

**Describe the solution you'd like**

Add an option to configure the delimiter of `Groups` header.

**Comment by EvgeniaBzzz** [comment]
Hi @enimaloc!
Sure, we'll add it in one of the nearest releases. Thank your for your request!

**Comment by dariamarutkina** [comment]
Hello, @enimaloc !
The delimiter symbol for the reverse proxy team headers is configurable now, details can be found in the [instructions](https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication) 
Please take a look at the new version of CloudBeaver 24.0.0.
Thank you for your interest in CloudBeaver!
