### ISSUE TITLE
Can empty x-role ignored if it is empty when using header authentication?

### ISSUE THREAD

**Issue by abelmferreira** [dbeaver/cloudbeaver#2379]
**Is your feature request related to a problem? Please describe.**
We configured header authentication using just x-user header for login, and it is working correctly. But the roles manually configured via admin interface  are removed if x-role is empty or not sended by the proxy.

**Describe the solution you'd like**
We don't have role controls in proxy side, it will be great if we can manually create a new user and set his roles, and use just x-user for authentication, keeping roles configurations unchanged.

Maybe just ignore x-role header if is empty or not exist, or maybe a enable/disable swtich for keep roles sended from proxy or ignore it.

**Comment by EvgeniaBzzz** [comment]
Hi @abelmferreira!
We will fix it in one of the nearest releases. Thank you for your report!

**Comment by dariamarutkina** [comment]
Hello, @abelmferreira !
We have fixed this problem
Please take a look at the new version of CloudBeaver 24.0.0.
Thank you for your interest in CloudBeaver!

**Comment by abelmferreira** [comment]
Worked perfectly! Thanks
