### ISSUE TITLE
Okta integration error: No security manager auth id specified

### ISSUE THREAD

**Issue by garruti9** [dbeaver/cloudbeaver#2384]
**Describe the bug**
When following all the steps outlined in the documentation (https://github.com/dbeaver/cloudbeaver/wiki/Okta-OpenID-Authentication) to set it the okta integration, it fails with the following error: 
```hcl
13-02-2024 15:50:15.682 [Test datasource connection] ERROR i.c.s.o.s.AbstractOpenIdServlet - null
io.cloudbeaver.DBWebException: No security manager auth id specified
```
Additionally, attempting to configure it using aws-opened yields the same error experienced with OKTA, as described above.

**To Reproduce**
Configure an Okta integration following the documentation: https://github.com/dbeaver/cloudbeaver/wiki/Okta-OpenID-Authentication

**Screenshots**
![image](https://github.com/dbeaver/cloudbeaver/assets/45664765/ed9551ef-068c-40a5-ab22-62f28cc68faf)

**Additional context**
Additionally, I've included the error trace from the Docker on the EC2 instance:
[cloudbeaver_trace_error_okta_integration.txt](https://github.com/dbeaver/cloudbeaver/files/14296034/cloudbeaver_trace_error_okta_integration.txt)

**Comment by EvgeniaBzzz** [comment]
You are trying to configure Okta (which is available only for pro CB versions) for http, am I right?
If so, it is expected behavior for now.

We are going to add Okta http support in 24.0.0 (which will be released in two weeks). As a workaround you can use https.

**Comment by EvgeniaBzzz** [comment]
Please, try version 24.0.0, there were made some improvements.
If the issue is still happening, please let us know and provide additional information.
