### ISSUE TITLE
Update wiki - build documentation

### ISSUE THREAD

**Issue by michalkahle** [dbeaver/cloudbeaver#2392]
**Describe the bug**
Wiki build instructions do not work for clean build and are outdated. 

https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy

Some prerequisites need higher versions:
- node.js (20+)
- Apache Maven (3.9+)

You need to build `dbeaver` before attempting to build `cloudbeaver`. This is because the build process expects `dbeaver-common` to be present. This is only cloned when building `dbeaver`.

**Comment by EvgeniaBzzz** [comment]
Hi @michalkahle!
We recently changed our repository, so `dbeaver-common` is now missing in the build script. We'll update it soon. Here is [the same issue](https://github.com/dbeaver/cloudbeaver/issues/2393).
Prerequisites have been updated on the [wiki](https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy).
Thank you for bringing this to our attention! ❤️

**Comment by michalkahle** [comment]
@EvgeniaBzzz thank you for updating the prerequisites versions. I think this issue can be closed when `dbeaver-common` is added to the `cloudbeaver` build script or an instruction is added to the wiki to build `dbeaver` first.

**Comment by EvgeniaBzzz** [comment]
Fix with updated build script has been merged into `devel` branch

**Comment by michalkahle** [comment]
Great. Thank you very much!
