### ISSUE TITLE
Maven build fails for P2 repo

### ISSUE THREAD

**Issue by TomCat80-code** [dbeaver/cloudbeaver#2393]
### Description

Building CloudBeaver results in missing metadata for dbeaver.

![image](https://github.com/dbeaver/dbeaver/assets/157839684/182717bf-47a3-4fd3-a60f-834afd0e76fc)

### DBeaver Version

Latest

### Operating System

Windows Server 2022

### Steps to reproduce

Instructions followed https://dbeaver.com/docs/cloudbeaver/Build-and-deploy/
Running either build.sh or build.bat cause issues retrieving metadata using the pom file.

**Comment by EvgeniaBzzz** [comment]
Hi @TomCat80-code!
`dbeaver-common` is missing
We will update build script in the nearest future. Thank you for your report!
As a workaround, please, clone to the same place https://github.com/dbeaver/dbeaver-common. So you will have `cloudbeaver`, `dbeaver` and `dbeaver-common` folders.

**Comment by EvgeniaBzzz** [comment]
@TomCat80-code 
Fix with updated build script has been merged into `devel` branch
