### ISSUE TITLE
Can you package cloudbeaver with Docker and Docker compose?

### ISSUE THREAD

**Issue by snowdream** [dbeaver/cloudbeaver#24]
**Is your feature request related to a problem? Please describe.**

Can you package cloudbeaver with Docker and Docker compose?

**Describe the solution you'd like**
Please package cloudbeaver with Docker and Docker compose

**Comment by FreeSoftwareServers** [comment]
This is already under request w/ Issue #13, I just hit a "thumbs up" to show my desire/support for the ticket, perhaps do the same?>

https://github.com/dbeaver/cloudbeaver/issues/13

**Comment by serge-rider** [comment]
Yep. Duplicate of #13
