### ISSUE TITLE
How to modify http://ip:port/#/ to http://ip:port/cloudbeaver/

### ISSUE THREAD

**Issue by 48929645** [dbeaver/cloudbeaver#240]
I know needs to modify cloudbeaver.conf file  rooturi:'/' to rooturi:'/cloudbeaver', but 404 error is reported

**Comment by serge-rider** [comment]
Parameter `rootURI` in `cloudbeaver.conf` config file is responsible for that.
It is `/` by default.
BTW you can use nginx (or any other web server) in front of cloudbeaver.

**Comment by 48929645** [comment]
ok,thanks!!
