### ISSUE TITLE
On the Cloudbeaver Community add the same driver support like the java client

### ISSUE THREAD

**Issue by bigleka** [dbeaver/cloudbeaver#2415]
It's possible add on the CloudBeaver Community edition the same amount of drivers as the DBeaver Java?
Or add the same support to add new drivers that exists on EE to CE, because on the wiki page only show how to add a new driver to EE not on CE.

**Comment by EvgeniaBzzz** [comment]
Hi @bigleka 
Here is instruction [how to add drivers](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers)

**Comment by bigleka** [comment]
> Hi @bigleka Here is instruction [how to add drivers](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers)
HI @EvganiaBzzz I saw that link, but you try? The directory don't exists, the files locations don't exists, even creating the same structure and reload the cloudbeaver the driver don't appear.

**Comment by EvgeniaBzzz** [comment]
Could you, please, give us more information.
What driver are you trying to add?
Describe your steps. Which directory and file location does not exist?

**Comment by EvgeniaBzzz** [comment]
If the issue is still actual, please let us know and provide additional information.
