### ISSUE TITLE
control+space to expand all columns in the query script section

### ISSUE THREAD

**Issue by kjee87** [dbeaver/cloudbeaver#2434]
Hello 

I was wondering if this feature already available in the cloudbeaver community version? This was so much helpful function when writing queries.

**Comment by EvgeniaBzzz** [comment]
Hi @kjee87!
CloudBeaver Community edition has SQL assist feature.
But first you should specify a table, so that the assistant understands which columns to show
 
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/d7d8a8e7-8c35-4bef-b50c-3279bbe7ef8c)

**Comment by kjee87** [comment]
Oh!! I worked for me using `ctrl+shift+space` in the cloudbeaver (which was a bit different from dbeaver, `ctrl+space`). Thank you!
