### ISSUE TITLE
View Resource Manager for Anonymous/Not logged in Users

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#2441]
Hi, is there a way to have Anonymous/Not logged in Users also view and create sql scripts in the shared folders (Resource Manager)?

CB version 23.3.5
i.e. Enable the below which currently shows up ONLY for logged in users.
![image](https://github.com/dbeaver/cloudbeaver/assets/57646596/95304867-a40f-42d6-a3f3-5eca519f21df)

I have an external auth system so would love to have a workaround to enable this.

Thanks!

**Comment by EvgeniaBzzz** [comment]
Hi @metalshanked!
For now CloudBeaver doesn't have functionality that allows anonymous to use shared scripts.

As a workaround you can configure [Reverse proxy](https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication) and specify a team with access to shared connections. Users will be created automatically.

**Comment by EvgeniaBzzz** [comment]
I hope this worked out for you. Please, let us know if you have any futher questions.
