### ISSUE TITLE
Set simple view as a default one doesn't work

### ISSUE THREAD

**Issue by wieczorslawo** [dbeaver/cloudbeaver#2467]
Trying to set a simple view as a default one, but it seems to not work. 
https://dbeaver.com/docs/cloudbeaver/Server-configuration/#navigator-settings

![image](https://github.com/dbeaver/cloudbeaver/assets/26138717/a80a9b93-a97a-408c-99ca-08402901f1fb)
Is there something I do wrong?

Used version:
Backend version
23.3.4.202402051107
Frontend version
23.3.4.202402051112

Thanks

**Comment by EvgeniaBzzz** [comment]
Hi @wieczorslawo!
Config looks right.
What config are you changing exactly? For initial start or for existing workspace?
`.cloudbeaver.runtime.conf` in the workspace has more power than `.cloudbeaver.conf`.

Also you always can change view via UI. Navigate Administration - Server configuration - Navigator simple view

**Comment by wieczorslawo** [comment]
I enter it to the cloudbeaver.conf json file: app.defaultNavigatorSettings

**Comment by EvgeniaBzzz** [comment]
Please, try to add it to `.cloudbeaver.runtime.conf`

**Comment by wieczorslawo** [comment]
added it also to /opt/cloudbeaver/workspace/.data/.cloudbeaver.runtime.conf file and unfortunately still no effect:
![image](https://github.com/dbeaver/cloudbeaver/assets/26138717/024492e6-c454-41cc-b86d-a8a8c24c83b7)

**Comment by EvgeniaBzzz** [comment]
Are you trying to change existing connections?

Simple/advanced view affects only new connections. This setting is applied to a connect only at the moment of creation.

So if you want to change view for existing connections, then change the same three parameters in `/opt/cloudbeaver/workspace/GlobalConfiguration/data-sources.conf`.
Or change it via UI
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/4684a72b-04f1-4ccc-81ca-70b84b69bee0)

**Comment by wieczorslawo** [comment]
That clarified everything, thank you very much :)
