### ISSUE TITLE
Add support for SAP HANA DB

### ISSUE THREAD

**Issue by ckyong** [dbeaver/cloudbeaver#2476]
Are there any plans to include support for SAP HANA DB in the near future ?

Would be great if support for SAP HANA is included soon.

Thank you.

Regards,
Chee Keong

**Comment by EvgeniaBzzz** [comment]
Hi @ckyong!
SAP HANA is available in CloudBeaver Enterprise. You can try [2-week trial version](https://dbeaver.com/cloudbeaver-enterprise/).
Or [you can add it](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers) yourself to the Community edition.

**Comment by ckyong** [comment]
@EvgeniaBzzz . 
 Thank you very much for the info.
