### ISSUE TITLE
oracle11g default driver properties

### ISSUE THREAD

**Issue by iwanghc** [dbeaver/cloudbeaver#2482]
Hello, this  question about cloudbeaver22.2. 
Why is this configuration enabled by default? How to set it to be off by default?
![image](https://github.com/dbeaver/cloudbeaver/assets/83113746/110a6108-adf6-41b5-a34b-7a871f666b6e)
![image](https://github.com/dbeaver/cloudbeaver/assets/83113746/0dd602bd-98d0-4154-b5cb-1d6ddaeb7ac5)
It seems that oracle11g does not support this option

**Comment by LonwoLonwo** [comment]
Hello @iwanghc 

DBeaver/CloudBeaver just shows you available driver properties. If a property value is not bold - it is the default value from the server.
Did you try to change it manually? Did it help?

![2024-03-20 10_47_01-Window](https://github.com/dbeaver/cloudbeaver/assets/45152336/16aab059-1f4b-4bbc-8984-15cc257fcb31)

**Comment by iwanghc** [comment]
@LonwoLonwo Manual modification is successful, but I create the connection through cloudbeaver api every time.  this error only appears in oracle11g，should you create different driver attribute default values ​​for 11g and 12c?

**Comment by LonwoLonwo** [comment]
Do you have only 11 Oracle instances? Or other server versions, too?

**Comment by LonwoLonwo** [comment]
You can try to decrease your Oracle driver version.
For this, you need to create a new driver in your config: https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers
Or you can try our [Enterprise version](https://dbeaver.com/cloudbeaver-enterprise/), which has native support for driver library adding.

**Comment by iwanghc** [comment]
thanks！

**Comment by LonwoLonwo** [comment]
Thanks for the update
