### ISSUE TITLE
Is Azure AD based Authentication available in cloudbeaver Community edition ?

### ISSUE THREAD

**Issue by Afsalmc** [dbeaver/cloudbeaver#2500]
I was not able to find settings for the same in the docker latest image of cloudbeaver CE
![image](https://github.com/dbeaver/cloudbeaver/assets/48438931/2a231211-69de-4ef5-8e03-5478245e3e2b)

**Comment by EvgeniaBzzz** [comment]
Hi @Afsalmc!
Azure AD based auth and other additional authentication methods are beyond the scope of Community edition.
Azure servises are available in Enterprise edition. You can try it in [2-week free trial](https://dbeaver.com/download/enterprise/).
