### ISSUE TITLE
Explorer script save allows only admin users to add

### ISSUE THREAD

**Issue by Phoebus888** [dbeaver/cloudbeaver#2501]
Please, describe your question in details.
![image](https://github.com/dbeaver/cloudbeaver/assets/45359605/4abbfbec-d756-4411-ba71-05c97a283274)

How to enable ordinary users to add scripts and set permissions to be private or shared

**Comment by EvgeniaBzzz** [comment]
Hi @Phoebus888!
Scripts inherit permissions of the connections.
Ordinary users (non-admin) can't save or edit shared scripts, only use them. But users still can add and edit private scripts (for private and shared connections).

Could you describe your use case, please?

**Comment by Phoebus888** [comment]
is that the average user doesn't have a button to save the script.   Administrators have.
![image](https://github.com/dbeaver/cloudbeaver/assets/45359605/0e175edb-9530-43b1-b368-581d710c3542)

**Comment by EvgeniaBzzz** [comment]
Do you mean that an ordinary user is an anonymous user who is not logged in at all?
Anonymous users can't save scripts.

**Comment by Phoebus888** [comment]
I'm saying regular users are already logged in. My version is 23.3.1.

**Comment by EvgeniaBzzz** [comment]
Have you disabled private connections? In this case standart users can't save scripts, since they do not have private space for them.

Could you describe how do you want to work with connections and scripts? What is your use case?

**Comment by Phoebus888** [comment]
I disabled private connections.
