### ISSUE TITLE
Issue after upgrade from 23.2.x to 23.3.0 dbeaver not get the data-source.json file and saml integration

### ISSUE THREAD

**Issue by rogeriarodrigues** [dbeaver/cloudbeaver#2511]
Please, describe your question in details:

Hi All,
After upgrade from 23.2.x to 23.3.0 dbeaver not get the data-source.json file and saml integration. We did the backup /opt/workspace but the application not is running with the configuration files.

Any idea what is going on?

Follow the process we did:
`sudo docker stop a819ca456ca2
sudo docker rm a819ca456ca2
sudo docker pull dbeaver/cloudbeaver-aws:23.3.0
sudo docker run -d --restart unless-stopped -p 8978:8978 -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver-aws:23.3.0`

Troubleshooting checked:
docker inspect
`        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/3d3a78d459309edbb1ab818a91ee1bdb4f33155c91d3f3ef210035df65aec34f-init/diff:/var/lib/docker/overlay2/1bea8619e2cd603e12393bfdaf81b89537df38f993db62c707ef28f793054053/diff:/var/lib/docker/overlay2/c75d128ae2231ee76a56564fe7ffaafb7d79ea7351f9079b46026b686077f4c9/diff:/var/lib/docker/overlay2/a739c0cd7e6b065f1c44bf6bf54d4448f0fe0945fcee4f51b195e8b6ae8ce675/diff:/var/lib/docker/overlay2/83ef6b9029ca2dabec18cf9e85dad3c807ccd47d157ec0aed21ea3e7c50ebc6e/diff:/var/lib/docker/overlay2/a22a2f160dd4c94531cf0f1046493b149bda1121bf1c96de81307a31f4e7a9b0/diff:/var/lib/docker/overlay2/38f108e2683b97247113f20214bbde0507f3836abd9bd5f817190a5fcd26931e/diff:/var/lib/docker/overlay2/5d7841da6d22f4069ad23ff7d0a88532d8bd0db08ca8ab68ce7fd66ba3e0ebe1/diff:/var/lib/docker/overlay2/2ea6b795dac5597c4895793544e4a2358d7b8f2714c9e519b9b2f4636913422a/diff:/var/lib/docker/overlay2/a24c413d961ce124cf129b5822a63ddcd30ff2a3563a1e4b4a169d504e75c560/diff",
                "MergedDir": "/var/lib/docker/overlay2/3d3a78d459309edbb1ab818a91ee1bdb4f33155c91d3f3ef210035df65aec34f/merged",
                "UpperDir": "/var/lib/docker/overlay2/3d3a78d459309edbb1ab818a91ee1bdb4f33155c91d3f3ef210035df65aec34f/diff",
                "WorkDir": "/var/lib/docker/overlay2/3d3a78d459309edbb1ab818a91ee1bdb4f33155c91d3f3ef210035df65aec34f/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/cloudbeaver/workspace",
                "Destination": "/opt/cloudbeaver/workspace",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],`
        
     `     "Cmd": null,
            "Image": "dbeaver/cloudbeaver-aws:23.3.0",
            "Volumes": null,
            "WorkingDir": "/opt/cloudbeaver",
            "Entrypoint": [
                "./run-server.sh"
            ],`

<img width="1429" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/141668902/b2505780-9be8-4b98-99ff-dbd497104afd">

**Comment by LonwoLonwo** [comment]
Hello @rogeriarodrigues 

If I understood correctly, you also created the same ticket for our Online Support Team. So, I hope they will get back to you soon. 
For now, I'm closing this issue, then.

**Comment by renderson-silva** [comment]
By the way, we have already managed to solve the problem, you can close the ticket
