### ISSUE TITLE
Unable to see the connection templates in Administration page 

### ISSUE THREAD

**Issue by rohithkumarpusarla** [dbeaver/cloudbeaver#2523]
**Describe the bug**
Not able to see the list Connection templates in the Administration page. But there were some connections created and able to see the response of gql request. Attached the screenshot for your reference. This issue i was able to see in the version 23.x onwards.

**To Reproduce**
1. Go to Administration page 
2. Click on the Connection templates tab on left side menu
3. You will not able to see the connection templates on right side 

**Screenshots**
<img width="960" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/138758710/4389ac2e-ef81-4728-ab72-79303114469b">

Backend request using Developer tools

<img width="960" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/138758710/bacde281-43be-4adf-bf7f-48c3fc67ac6e">
<img width="959" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/138758710/54e609cf-7597-462e-8144-c5f3a8659cb1">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 24.0.1

**Comment by EvgeniaBzzz** [comment]
Hi @rohithkumarpusarla 
Up to version 23.2.0, the Templates tab included both templates and existing connections. After this version, the tab only contains templates for connections (that are created on the same tab of admin panel). 
You can see all your existing connections in the navigator on the main page of the application.

**Comment by EvgeniaBzzz** [comment]
Please let us known if you have any futher questions
