### ISSUE TITLE
Default corelation between team and connection

### ISSUE THREAD

**Issue by wieczorslawo** [dbeaver/cloudbeaver#2530]
Hi team.
Can a default connection be set between the initial team and the initial data source? I'm thinking about the initial-data.conf and the initial-data-sources.conf files. It would be helpful for our needs

KR
Slawo

**Comment by EvgeniaBzzz** [comment]
Hi @wieczorslawo 
Could you give more information - what do you want to do? Grant the team access to the connection initially?

**Comment by wieczorslawo** [comment]
Yes, exactly. If not possible by the conf files please add a hint on how one could do it by direct db access or a graphql usage

**Comment by EvgeniaBzzz** [comment]
You can set permissions in `${WORKSPACE}/GlobalConfiguration/.dbeaver/data-sources-permissions.json`
Here is an [instruction](https://github.com/dbeaver/cloudbeaver/wiki/Pre%E2%80%90configured-permissions-for-connections).
Does this solution suit you?

**Comment by wieczorslawo** [comment]
Sounds good, thank you. What if one would like to use the GraphQL endpoint or a direct db connection (from a sidecar project for example)?

**Comment by EvgeniaBzzz** [comment]
You can use gql with admin permission
