### ISSUE TITLE
It's possible to bind sql parameters?

### ISSUE THREAD

**Issue by douglascachoeira** [dbeaver/cloudbeaver#2534]
There is some way to use bind parameters on sql script execution?
I tried with : and '?', but it doesn't work.

![image](https://github.com/dbeaver/cloudbeaver/assets/7831478/85ce8a39-4640-415a-8579-e732b7929625)

**Comment by EvgeniaBzzz** [comment]
Hi @douglascachoeira 
CloudBeaver doesn't have that functionality yet. Let it be feature request, thank you.
You can use desktop version if you need binding

**Comment by douglascachoeira** [comment]
Hi @EvgeniaBzzz ,
ok, thanks!
