### ISSUE TITLE
Feature Request: Add support for Turso/libsql

### ISSUE THREAD

**Issue by jylin** [dbeaver/cloudbeaver#2550]
Libsql is a fork of SQLite that works over the network. It would be great if cloudbeaver added support for it.
https://github.com/tursodatabase/libsql

**Comment by LonwoLonwo** [comment]
Hello @jylin 

Does the Libsql have a jdbc driver? 
Can you connect to Libsql using SQLite driver (and connection)? 

![image](https://github.com/dbeaver/cloudbeaver/assets/45152336/62b99315-c85c-43b5-bccc-5043603835de)

**Comment by jylin** [comment]
Not that I know of. I don't think you can just use a SQLite driver since I believe the protocol is over HTTP.

**Comment by LonwoLonwo** [comment]
But how do we add it to our product without a driver? We do not support databases without drivers.

**Comment by EvgeniaBzzz** [comment]
Unfortunately, we can't integrate any database without JDBC driver.

**Comment by serge-rider** [comment]
We will implement it here: https://github.com/dbeaver/dbeaver/issues/23361
And then add to CloudBeaver

**Comment by dariamarutkina** [comment]
Hello @jylin !
We have added LibSQL support, you can find it in v.24.3.0 💙
Thank you for being with CloudBeaver!
