### ISSUE TITLE
[Feature Request]: Ability to collapse the range

### ISSUE THREAD

**Issue by gudge25** [dbeaver/cloudbeaver#2553]
![image](https://github.com/dbeaver/cloudbeaver/assets/2346208/796f60f6-f5e9-4e2c-ab80-c9a0438bb3ce)
there is no way I can collapse the range starting from [

**Comment by EvgeniaBzzz** [comment]
Hi @gudge25!
Could you provide us with your json example, please, to see the full structure? 
As CloudBeaver has the ability to collapse arrays.
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/988054a4-ec49-4201-b9f2-197f564d3976)

**Comment by EvgeniaBzzz** [comment]
It's been some time since last update on this issue.
If the issue is still happening, please let us know and provide additional information.
