### ISSUE TITLE
Highlight the row where any field is currently selected

### ISSUE THREAD

**Issue by DVLP** [dbeaver/cloudbeaver#2562]
I click on an item in a row and one field is selected, then I scroll horizontally to check another value in the row but easily lose track of which row it was.

After clicking once on any item in a row I want the whole row to be left slightly highlited just like when it's hovered over

**Comment by EvgeniaBzzz** [comment]
Hi @DVLP!
You can highlight the row by clicking on the row numbering column header.
Or do you need to leave the cell selected and scroll horizontally?
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/1d6d39ee-1ba7-45aa-82d3-dd1e77e82cdb)

**Comment by DVLP** [comment]
Thanks. This is helpful but highlighting the row if any field is selected would be more intuitive.

**Comment by EvgeniaBzzz** [comment]
We will add highlighting in one of the futher releases. Thank you for your request! ❤️

**Comment by DVLP** [comment]
Great, I'm looking forward to it

**Comment by dariamarutkina** [comment]
Hello @DVLP !
In the new version v.24.2.3, we have improved the Data editor. Rows with focused cells are specially marked to make it easier to locate a position in large tables
Thank you for your request! ❤️
