### ISSUE TITLE
Execute the selected SQL，just like the dbeaver

### ISSUE THREAD

**Issue by dennymou** [dbeaver/cloudbeaver#2581]
can u give a button or other way : just execute the **selected sql**  instead of all SQL in the label , like dbeaver. 
Execute all sql may take a critical mistake,ths
![image](https://github.com/dbeaver/cloudbeaver/assets/7556854/5be7afa8-8a5c-489c-8942-e75dbbbeaf7f)

**Comment by EvgeniaBzzz** [comment]
Hi @dennymou!
You can use the first button to execute only selected statements
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/5b004a60-2494-4761-888b-48efabe50333)

**Comment by dennymou** [comment]
> Hi @dennymou! You can use the first button to execute only selected statements ![image](https://private-user-images.githubusercontent.com/139753579/326390946-5b004a60-2494-4761-888b-48efabe50333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODM1OTgsIm5iZiI6MTcxNDM4MzI5OCwicGF0aCI6Ii8xMzk3NTM1NzkvMzI2MzkwOTQ2LTViMDA0YTYwLTI0OTQtNDc2MS04ODhiLTQ4ZWZhYmU1MDMzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwOTM0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mzc0NjgzYjQ0Y2IzMWNhMTNiNzdlMjdjNDMwYTVmNjU3YzkyZTQzOWYzZWM0NzliYmRhZDVjZTY5Yjg3MDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v6RHF9DGCy5QeTNRyI08cCXM6JRVIWxZ9oJnM-ZZ3Kk)

ths for u reply,  i want to select mutiple sql, then execute.

i used 24.02, but report me error : "Multiple sql must use query mode to execute"

**Comment by EvgeniaBzzz** [comment]
What database do you use?

**Comment by dennymou** [comment]
> What database do you use?

open gauss

**Comment by EvgeniaBzzz** [comment]
@dennymou and what exact driver do you use?

If you use PostgreSQL driver it should work properly with multi statements 🤔 
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/1f9ad510-cdfe-495a-82b6-c7e2437b1556)

**Comment by dennymou** [comment]
> @dennymou and what exact driver do you use?
> 
> If you use PostgreSQL driver it should work properly with multi statements 🤔 ![image](https://private-user-images.githubusercontent.com/139753579/326847688-1f9ad510-cdfe-495a-82b6-c7e2437b1556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTIyMTIsIm5iZiI6MTcxNTA1MTkxMiwicGF0aCI6Ii8xMzk3NTM1NzkvMzI2ODQ3Njg4LTFmOWFkNTEwLWNkZmUtNDk1YS04MmI2LWM3ZTI0MzdiMTU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMzE4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGE4N2Q4YWI3NDdkNjY3YzU1NzI5YmI5ZjA3ODBkNTg0ZTg0MTNlMDAxMzFjZmQ4YmU0OWVhMDMyZmYyZDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DeNRZsLpwsiGaYZ5TAuZ7LGEvcj9-XeMiANOeh_hUd0)

yeah
