### ISSUE TITLE
Reopening a closed connection does not ask for login/password anymore

### ISSUE THREAD

**Issue by momiji** [dbeaver/cloudbeaver#260]
**Describe the bug**

Disconnect closes the connection but does not forget associated credentials.

**To Reproduce**

Open a new connection for a database (like mssqlserver, but this will do the same for all), which requires credentials to be entered.
Go to SQL ot whatever, and then close it (Disconnect all from menu).
Then if you open again the connection, it will not ask for credentials.

**Solution**

I guess this is related to closeAndDeleteConnection() method that does not call webSession.removeConnection(connectionInfo);

https://github.com/dbeaver/cloudbeaver/blob/ec6eaf4899db7d28277bd4b637c32c4093d75d1e/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/service/core/impl/WebServiceCore.java#L389-L392

The fix seems to move the `webSession.removeConnection(connectionInfo);` out of the condition:

```java
 if (forceDelete) { 
     webSession.getSingletonProject().getDataSourceRegistry().removeDataSource(dataSourceContainer); 
 }

 // Remove connection to forget stored credentials
 webSession.removeConnection(connectionInfo); 
```

Regards,
Christian

**Comment by kseniiaguzeeva** [comment]
Can **Save credentials** option be enabled when you entered credentials?
![chrome_Tb3JYL3L5l](https://user-images.githubusercontent.com/51405061/104187514-f32a6900-5428-11eb-91fb-9c691532c334.png)

**Comment by momiji** [comment]
Not sure to understand the question here.
Do you mean that "save credentials" purpouse is to keep credentials even after disconnecting all?

If so I totally didn't mis-understand it :)

**Comment by kseniiaguzeeva** [comment]
Yes, Save credentials option allows you to open the database without entering credentials after disconnect or re-login.

**Comment by momiji** [comment]
My bad... In that case does it make sens to add a new feature to forget all credentials?

**Comment by kseniiaguzeeva** [comment]
I see you have already created the feature request for it. It can be implemented in the future.
As a workaround you can clear passwords in JSON file now. 

Please ask to reopen the ticket, if you have some additional questions about it.
