### ISSUE TITLE
Can support the Apache IoTDB driver better ？

### ISSUE THREAD

**Issue by sunquan819** [dbeaver/cloudbeaver#2601]
After installing the Apache IoTDB driver using Dbeaver, most SQL can be executed,
BUT after installing the Apache IoTDB driver using CloudBeaver, most SQL cannot be executed
Some errors like the following:
SQL Error [700] [Error occurred while parsing SQL to physical plan: line 1:61 token recognition error at: '']: 700: Error occurred while parsing SQL to physical plan: line 1:61 token recognition error at: ''
SQL Error [700] [Error occurred while parsing SQL to physical plan: line 1:61 token recognition error at: '']: 700: Error occurred while parsing SQL to physical plan: line 1:61 token recognition error at: ''

Error details：
Org. jkiss. dbeaver. model. SQL DBSQLException: SQL Error [700] [Error occurred while parsing SQL to physical plan: line 1:61 token recognition error at: '']: 700: Error occurred while parsing SQL to physical plan: line 1:61 token recognition error at: ''
At org.jkiss.beaver.model. impl.jdbc. exec JDBCStatementImpl. executeStatement (JDBCStatementImpl. java: 133)
At org.jkiss.beaver.model. impl.jdbc. structure JDBCTable. readData (JDBCTable. Java: 192)
At io. cloudbeaver. service. SQL WebSQLProcessor. lambda $2 (WebSQLProcessor. java: 293)
At org.jkiss.beaver.modeL.exec DBExecUtils. tryExecuteRecover (DBExecUtils. java: 194)
At io. cloudbeaver. service. SQL WebSQLProcessor. readDataFromContainer (WebSQLProcessor. java: 290)
At io. cloudbeaver. service. SQL. impl WebServiceSQL $2. run (WebServiceSQL. Java: 439)
At io. cloudbeaver. model. session WebSession $1. run (WebSession. java: 742)
At org. jkiss. beaver. model. runtime AbstractJob. run (AbstractJob. java: 115)
At org. eclipse. core. internal. Jacobs Worker. run (Worker. java: 63)
Caused by: org. apache. iotdb. jdbc IoTDBSQLException: 700: Error occurred while parsing SQL to physical plan: line 1:61 token recognition error at: ''
At org. apache. iotdb. jdbc IoTDBStatement. executeSQL (IoTDBStatement. java: 265)
At org. apache. iotdb. jdbc IoTDBStatement. execute (IoTDBStatement. java: 219)
At org.jkiss.beaver.model. impl.jdbc. exec JDBCStatementImpl. execute (JDBCStatementImpl. java: 330)
At org.jkiss.beaver.model. impl.jdbc. exec JDBCStatementImpl. executeStatement (JDBCStatementImpl. java: 131)
... 8 more

**Comment by LonwoLonwo** [comment]
Hello @sunquan819 

Could you please provide footage of your SQL execution? Which tabs do you use? Do you highlight the query text or not? Are you using the same driver in both products? 
These details will be beneficial.

**Comment by LonwoLonwo** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by david20200211** [comment]
it happen again in DBeaver 24.2.2 , driver is iotdb-jdbc-1.3.2-jar-with-dependencies.jar
it show same error  when click view table 
![1728984196986](https://github.com/user-attachments/assets/9115c755-5d14-4f05-aff8-0b92d1523f3e)

@LonwoLonwo  I hope I'm not bothering you, but could you help me with this?

**Comment by LonwoLonwo** [comment]
Hello
DBeaver and CloudBeaver do not have official support for the Apache IoTDB database.
I see that IoTDB has specific commands: https://github.com/apache/iotdb?tab=readme-ov-file#basic-commands-for-iotdb
and they are also not supported.
For now, it is better to use SQL Editor and execute all queries there with specific syntax.

You can create a ticket about Apache IoTDB support here: https://github.com/dbeaver/dbeaver/issues. Please add more details about the database and driver.
