### ISSUE TITLE
Add a configuration item to prevent saving credentials, in memory as well as on disk

### ISSUE THREAD

**Issue by momiji** [dbeaver/cloudbeaver#261]
**Describe the solution you'd like**
To prevent leakage of credentials, we would like to have a configuration item to prevent saving crendetials to disk as well as in memory.

**Ugly solution**
To achieve this, without enough knwoledge on how to add configuration items, we changed a few lines in code to prevent this.
This is totally ugly, and is based on the assumption that encrypt argument is only used for credentials (and not for projects).

cloudbeaver/.../WebServiceCore.java:

```java
    @Override
    public WebConnectionInfo initConnection(WebSession webSession, String connectionId, Map<String, Object> authProperties, Boolean saveCredentials) throws DBWebException {
        // Begin Hack
        saveCredentials = false;
        // End Hack
...
    @Override
    public WebConnectionInfo createConnection(WebSession webSession, WebConnectionConfig connectionConfig) throws DBWebException {
        // Begin Hack
        connectionConfig.setSaveCredentials(false);
        // End Hack
```

cloudbeaver/.../WebServiceAdmin.java:

```java
    @Override
    public WebConnectionInfo createConnectionConfiguration(@NotNull WebSession webSession, @NotNull WebConnectionConfig config) throws DBWebException {
        // Begin Hack
        config.setSaveCredentials(false);
        // End Hack
...
    @Override
    public WebConnectionInfo updateConnectionConfiguration(@NotNull WebSession webSession, @NotNull String id, @NotNull WebConnectionConfig config) throws DBWebException {
        // Begin Hack
        config.setSaveCredentials(false);
        // End Hack
```

dbeaver/.../DataSourceSerializerModern.java:

```java
    private void saveConfigFile(File configFile, String contents, boolean teamPrivate, boolean encrypt) {
        // Begin Hack
        if (encrypt) return;
        // End Hack
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by kseniiaguzeeva** [comment]
Security section was added to Server configuration of Administration menu.
![chrome_YGoRA6aJZM](https://user-images.githubusercontent.com/51405061/107624883-8c3ce180-6c6c-11eb-829e-bb767a0a441a.png)
Now admin can enable/disable credentilal saving to all roles or to user roles only.
