### ISSUE TITLE
Cannot see vertica in cloudbeaver ce UI

### ISSUE THREAD

**Issue by deepaksinghkhetwal** [dbeaver/cloudbeaver#2611]
**Describe the bug**
I am trying to add vertica driver in cloudbeaver CE using doc https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers. But cannot see the driver added in the UI

**To Reproduce**
1. Created pom.xml at server/drivers/vertica/

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>drivers.vertica</artifactId>
    <version>1.0.0</version>
    <parent>
        <groupId>io.cloudbeaver</groupId>
        <artifactId>drivers</artifactId>
        <version>1.0.0</version>
        <relativePath>../</relativePath>
    </parent>

    <properties>
        <deps.output.dir>vertica</deps.output.dir>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.vertica.jdbc</groupId>
            <artifactId>vertica-jdbc</artifactId>
            <version>10.0.1-0</version>
        </dependency>
    </dependencies>

</project>

```
2. added the below to modules section in server/drivers/pom.xml

`<module>vertica</module>`

3. Added in the server configuration at server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml

Resource mappings 
`<resource name="drivers/vertica"/>`

Bundles
`<bundle id="drivers.vertica" label="Vertica drivers"/>`

Enabled Drivers

`<driver id="generic:vertica"/>`

4. Build the app

5 Created docker container and deployed it. But I do not see the driver in cloudbeaver UI

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by LonwoLonwo** [comment]
Hello @deepaksinghkhetwal 

Could you please try `<driver id=vertica:vertica-jdbc-8"/>`

This is the working one:
https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.vertica/plugin.xml#L117

**Comment by deepaksinghkhetwal** [comment]
Thank you, @LonwoLonwo. This configuration works
