### ISSUE TITLE
Backup private/shared connections

### ISSUE THREAD

**Issue by MatthiasSchnoeke** [dbeaver/cloudbeaver#2666]
Hi, we are running CB on Kubernetes. What is the recommended way to backup (and restore) all DB connection configurations?
The configuration DB (Maria) does not seem to be involved here. Why not actually?

Thanks

**Comment by LonwoLonwo** [comment]
Hello @MatthiasSchnoeke 

Did you check the options from this wiki-page? https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-Workspace-Backup

**Comment by MatthiasSchnoeke** [comment]
Yes, I want to avoid doing anything on the work node side. Creating a backup inside a pod/container ends up with a denied permission. 
The best would be to export/backup all configurations via CB UI.

**Comment by MatthiasSchnoeke** [comment]
I have found an easy way. Copy workspace folder to my local disk by "oc cp -n <namespace> <pod_name>:workspace workspace" .
