### ISSUE TITLE
If SP debug is supported?

### ISSUE THREAD

**Issue by zhaonaiy** [dbeaver/cloudbeaver#2680]
Hello, 
     I have noted PG stored procedure debug mode is enabled in destop version of DBeaver, however I can't find it in cloudeaver. If I missed anything? 
     Thanks. 

NaiYan

**Comment by EvgeniaBzzz** [comment]
Hi @zhaonaiy 
CloudBeaver do not have debug mode.

There is server output log which can give you some extra information.
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/7e59756b-218a-4bdb-8a76-0bcb92c8a27e)
