### ISSUE TITLE
The saved credentials is not effective when connect db

### ISSUE THREAD

**Issue by seepine** [dbeaver/cloudbeaver#2702]
**Describe the bug**
The saved voucher is not effective when connect db.
I have to input form every time, although check it in a timely manner

**Screenshots**
<img width="684" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/93666053/7c42c01c-f038-478e-a1fa-549e7d761445">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [EDGE]
 - Version [docker dbeaver/cloudbeaver:24.1]

**Comment by EvgeniaBzzz** [comment]
Hi @seepine 
Actually, it's not a bug. It's a frustrating name for a check-box 😞 We are going to make it clearer, I'll prioritize this task.

Here's how it works: When you check 'Save credentials' in the authentication dialog, you save the credentials _**only for the current user and only for the current session**_. After logging out, you will have to input the credentials again.

Credentials can be saved only in the connection form. 
- For a private connection (if this option is enabled in the admin panel), it can be done by the current user. 
- For a shared connection, it can be done by any admin user. Then all users who have access to that connection can use it without needing to re-enter credentials. So it's like the credentials are saved and shared.
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/f1350eb1-e245-4554-8620-0378375bc90d)

**Comment by seepine** [comment]
This is too difficult to understand. 😱

**Comment by EvgeniaBzzz** [comment]
Hi @seepine 
We've updated the desctiptions for credential saving in all forms.
I hope everything is clear now. 
![Снимок экрана 2024-07-08 115457](https://github.com/dbeaver/cloudbeaver/assets/139753579/c78a0829-86c7-4a11-9bb5-d538d0dd4623)
