### ISSUE TITLE
Unauthorized to access cloudbeaver after idle session

### ISSUE THREAD

**Issue by deepaksinghkhetwal** [dbeaver/cloudbeaver#2720]
**Describe the bug**
I have configured access to cloudbeaver using reverse proxy(apache web server) adding ldap authentication. I can login to the cloudbeaver successfully. But after some time I am getting below error. I can login to incognito properly though

GQL Error: 401 Unauthorized
GQL Error: 401 Unauthorized
    at CustomGraphQLClient.overrideRequest (<removed the url>)
    at async NetworkStateService.sessionExpiredInterceptor (<removed the url>)
    at async SessionExpireService.sessionExpiredInterceptor (<removed the url>)
    at async SessionResource.loader (<removed the url>)
    at async SessionResource.loadingTask (<removed the url>)
    at async SessionResource.taskWrapper (<removed the url>)
    at async Task.task (<removed the url>)

I have to remove cache and can login again

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
On checking logs in the pod, 

20-06-2024 07:46:21.211 [qtp182254297-41] ERROR i.c.service.WebServiceBindingBase - Unexpected error during gql request
io.cloudbeaver.DBWebException: User authentication failed:
Authentication parameter 'user' is missing

Below is the header configuration in httpd.conf
        RequestHeader add X-User %{AUTHENTICATE_SAMACCOUNTNAME}e
        RequestHeader add X-Role user
        RequestHeader add X-First-name %{AUTHENTICATE_GIVENNAME}e
        RequestHeader add X-Last-name  %{AUTHENTICATE_SN}e

**Comment by EvgeniaBzzz** [comment]
Hi @deepaksinghkhetwal 
Could you please show your proxy server config

**Comment by deepaksinghkhetwal** [comment]
Hello @EvgeniaBzzz 

Please find my proxy server config

```
<VirtualHost *:80>
    <Location / >
        ProxyPass  http://localhost:8978/
        ProxyPassReverse  http://localhost:8978/
        AuthType Basic
        AuthName "Enter LDAP credentials"
        AuthBasicProvider ldap
        AuthLDAPGroupAttribute memberOf
        AuthLDAPSubGroupClass group
        AuthLDAPGroupAttributeIsDN On
        AuthLDAPURL removed
        AuthLDAPBindDN removed
        AuthLDAPBindPassword removed
        require valid-user
        RequestHeader add X-User %{AUTHENTICATE_SAMACCOUNTNAME}e
        RequestHeader add X-Role user
        RequestHeader add X-Team db-access
        RequestHeader add X-First-name %{AUTHENTICATE_GIVENNAME}e
        RequestHeader add X-Last-name  %{AUTHENTICATE_SN}e
     </Location>
</VirtualHost>

**Comment by EvgeniaBzzz** [comment]
The X-User header stops coming at some point. Possibly due to the end of the LDAP session.
Could you also check if there is any errors in apache logs?

**Comment by deepaksinghkhetwal** [comment]
All the logs show 401 status code

Removed IP Address - - [24/Jun/2024:16:01:17 +0000] "HEAD / HTTP/1.1" 401 -
Removed IP Address - - [24/Jun/2024:16:01:18 +0000] "POST /api/gql HTTP/1.1" 401 381
Removed IP Address - - [24/Jun/2024:16:01:19 +0000] "GET /api/ws HTTP/1.1" 401 381
Removed IP Address - - [24/Jun/2024:16:01:19 +0000] "POST /api/gql HTTP/1.1" 401 381
Removed IP Address - - [24/Jun/2024:16:01:20 +0000] "GET /service-worker.js HTTP/1.1" 401 381
Removed IP Address - - [24/Jun/2024:16:01:21 +0000] "GET /api/ws HTTP/1.1" 401 381

Logs when logged in from incognito

Removed IP Address - deepak [24/Jun/2024:16:02:24 +0000] "HEAD / HTTP/1.1" 200 -
Removed IP Address - deepak [24/Jun/2024:16:02:55 +0000] "HEAD / HTTP/1.1" 200 -
Removed IP Address - deepak [24/Jun/2024:16:02:56 +0000] "POST /api/gql HTTP/1.1" 200 4894
Removed IP Address - deepak [24/Jun/2024:16:02:56 +0000] "POST /api/gql HTTP/1.1" 200 270

**Comment by EvgeniaBzzz** [comment]
At the moment we don't have solution on our side.
As a workaround, you could add cache clearing to your apache config.
```
Header set Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0" 
Header set Pragma "no-cache"
Header set Expires "0"
```

**Comment by EvgeniaBzzz** [comment]
Hi @deepaksinghkhetwal 
Any news here?

**Comment by deepaksinghkhetwal** [comment]
Hello @EvgeniaBzzz thanks for reminder

I tried setting this up in apache pod, but could not resolve the issue

**Comment by LonwoLonwo** [comment]
Hello @deepaksinghkhetwal 

Sorry for the late response. 
We can't reproduce your issue.
Please update the project version to the last one and check again.

**Comment by LonwoLonwo** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
