### ISSUE TITLE
Data edit

### ISSUE THREAD

**Issue by MatthiasSchnoeke** [dbeaver/cloudbeaver#2723]
Hello, 
What could be the reason that I can not edit data directly in Oracle tables? 
The baseline only shows the following options.

![image](https://github.com/dbeaver/cloudbeaver/assets/23337668/6f9e05a3-8c69-4a24-bc7a-11b17fdfaf5d)

Thank you very much
MS

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke 
According to your tooltip line it is a read-only table.
Please, check that:
- Oracle user has permissions for editing
- current table has primary key
- (if you logged in as CB non-admin user) administration - preferences - 'Disable edit' is not checked

**Comment by MatthiasSchnoeke** [comment]
Many thanks for the quick reply. A missing PK was the reason.

**Comment by EvgeniaBzzz** [comment]
You're very welcome! Happy developing!
