### ISSUE TITLE
Global default setting for commit behavior

### ISSUE THREAD

**Issue by MatthiasSchnoeke** [dbeaver/cloudbeaver#2728]
Can you estimate when we can change the default to "manual commit"? 
Currently, every new DB connection is set back to "AutoCommit". Unfortunately, this can easily be overlooked/forgotten in day-to-day business.

Many Thanks!

Best regards
Matthias Schnöke

**Comment by EvgeniaBzzz** [comment]
We are going to add a setting in the next version.
As the first step, it will be available in each connect form. And global setting is the next step.

**Comment by MatthiasSchnoeke** [comment]
Top!

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke 
We've added commit mode setting to the connection form. You can find it in Expert settings. By default auto commit is on.
Please check out v24.1.2.
We're grateful for your support and engagement with our project! 🦫 
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/4a1742c5-2206-4097-b28c-8b7fa3d5e20a)
