### ISSUE TITLE
Planned feature set

### ISSUE THREAD

**Issue by pikausp** [dbeaver/cloudbeaver#273]
Hello,

I love DBeaver and the set of features it offers. Is it a goal of CloudBeaver to reach feature parity with the desktop application at some point? That or significant overlap "at least".

Secondly, have you considered sharing the project's roadmap?

Thanks!

**Comment by tati-kru** [comment]
Hello @pikausp 

Thank you for your warm feedback. CloudBeaver is not going to be a copy or a replacement for DBeaver. Of course, it will have the same base functions but it is more focused on the data visualisation and integration with third-party services. 

This moment we are not ready to share the CloudBeaver roadmap, but perhaps we will do this in future.

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if you have further questions.
