### ISSUE TITLE
shared connections

### ISSUE THREAD

**Issue by MatthiasSchnoeke** [dbeaver/cloudbeaver#2749]
How to allow users to create shared connections? Currently, a user cannot change the parameter from a private to a shared connection. 
Only with admin rights is it possible. But we dont want to give admin rights for normal CB users.

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke 
There is no option to grant permission for common users to create/edit connections in Shared project.
They can create connections only in Private project (if it is enabled in settings).

Only [Team edition](https://dbeaver.com/dbeaver-team-edition/) provides the opportunity for flexible role setup (there are 5 diffrernt roles and an unlimited number of shareable projects).
