### ISSUE TITLE
UUID type trino - no icon

### ISSUE THREAD

**Issue by raphaelauv** [dbeaver/cloudbeaver#2757]
![image](https://github.com/dbeaver/cloudbeaver/assets/10202690/a3ba3d06-4a5a-4d9c-8e1b-e2bafd176a02)

dbeavercloud do not have an icon for the UUID type of trino , it show a `?`

thanks all

**Comment by EvgeniaBzzz** [comment]
Thanks for the report! We'll fix it in on of the future releases

**Comment by EvgeniaBzzz** [comment]
Icon fixed in v.24.2.1 🪄
