### ISSUE TITLE
Allow filtering Query manager based on fields

### ISSUE THREAD

**Issue by Vormillion** [dbeaver/cloudbeaver#2763]
Currently in the newest Cloudbeaver EE 24.1.0 the new catalog field is added in query manager. Unfortunatelly it's not possible to setup search filters to use this field.

**Comment by LonwoLonwo** [comment]
Hello @Vormillion 

Thanks for the future request. 
We will implement it in our feature releases.

**Comment by LonwoLonwo** [comment]
Hello @Vormillion 

We implemented the ability to search by catalogs and schemas in the Query Manager. 

![изображение](https://github.com/user-attachments/assets/8d066016-1dd3-4dfd-981e-5b47b8d98527)

This feature will be available in the next major release, 24.3

Or you can download and try it in our Early Access version by `ea` tag.

**Comment by EvgeniaBzzz** [comment]
Hi @Vormillion 
New version 24.3 has been released.
Thank you for your request, any futher suggestions are welcome 🦫
