### ISSUE TITLE
CloudBeaver container with TimescaleDB

### ISSUE THREAD

**Issue by AlexiaArtemis** [dbeaver/cloudbeaver#2783]
Hello,

I am using the dbeaver/cloudbeaver image, and when I open CloudBeaver on localhost, I am unable to find how to connect to TimescaleDB.

Could you please provide guidance on how to configure the connection to TimescaleDB?

Thank you!

**Comment by EvgeniaBzzz** [comment]
Hi @AlexiaArtemis,

TimescaleDB is not supported by CloudBeaver Community Edition by default. You can add it using [this instruction](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers).

You can also try the Enterprise Edition ([2-week free trial](https://dbeaver.com/trial/)), which includes a [much wider range](https://github.com/dbeaver/cloudbeaver/wiki/Supported-databases) of preconfigured drivers.

Additionally, if you don't need any specific features (e.g., hypertables, continuous aggregates), you can connect using the PostgreSQL driver.

**Comment by EvgeniaBzzz** [comment]
HI @AlexiaArtemis!
Did you manage to connect to TimescaleDB?

**Comment by EvgeniaBzzz** [comment]
I hope one of the solutions suits you.
If you have any further questions, please don't hesitate to ask 🦫
