### ISSUE TITLE
Editing rootURI breaks docker.cloudbeaver

### ISSUE THREAD

**Issue by GabrieleFrau** [dbeaver/cloudbeaver#279]
**Describe the bug**
Editing .data/.cloudbeaver.runtime.conf breaks cloudbeaver

**To Reproduce**
1. Edit .data/.cloudbeaver.runtime.conf
```
{
  "server": {
    "serverName": "Cloudbeaver",
    "expireSessionAfterPeriod": 1800000,
    "rootURI": "/cloudbeaver",
    "serviceURI": "/cloudbeaver/api/"
  },
  "app": {
    "anonymousAccessEnabled": false,
    "authenticationEnabled": true,
    "supportsCustomConnections": false
  }
}
```
2. `/usr/bin/docker run --name cloudbeaverd --rm -p 8081:8978 --network host -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:latest`
3. Browse 127.0.0.1:8978 or 127.0.0.1:8978/cloudbeaver/

**Runtime**
CloudBeaver CE Server 20.0.1.202012301222
OS: Linux 5.4.0-37-generic (amd64)
Java version: 11.0.7 by AdoptOpenJDK (64bit)
Install path: '/opt/cloudbeaver/server'
Global workspace: 'file:/opt/cloudbeaver/workspace/'
Memory available 188Mb/2990Mb

**Comment by serge-rider** [comment]
Thanks for the bug report.

**Comment by Wroud** [comment]
Thanks for the bug report, unfortunately, we not test this possibility yet so it can don't work properly. I will reply as soon as I will be sure that all works correctly.

**Comment by euanmacinnes** [comment]
Any progress on this, as we need it to be able to host it properly on a subfolder through a reverse proxy, e.g.:

/business/development/dbvr

We can do rewrites to handle the majority of it, but the API insists on being on /api/ instead, and /icons/icons, and we won't be able to run multiple cloudbeavers side by side (for e.g. development and production database access for different apps).

**Comment by meb21uk** [comment]
Been struggling with this issue as well, in that I can operate behind nginx reverse proxy using only the / URL. Within CBStaticServlet.class, the static servlet is fixed to "@WebServlet(urlPatterns = {"/"})" . I am not very familiar with Java, but is it possible to create a variable potentially as URL_Pattern or BaseURL  within cloudbeaver.conf file and dictates the @WebServlet URL.

**Comment by yoavo-datricks** [comment]
Hi. This is not working for me either. I'm getting 404 when trying to access it in a "/cloud" even after setting the rootURI.
Also, I see in the index.html hard-coded access to /api/pgsql so I'm guessing setting serviceURI doesn't work as well.

**Comment by vliska** [comment]
Same problem here. We have to run cloudbeaver on a separate domain to mitigate this (which is unfortunate, we have all other monitoring items under single domain).

**Comment by meb21uk** [comment]
While issue gets fixed, following works with NGINX for non root URI for any one interested.

Replace cloudbeaver as required.

   location = /cloubeaver {
        return 302 /cloudbeaver/;
    }

    location = /api/gql {
        return 307 https://<needs URL>/cloudbeaver$request_uri;
    }

    location /icons/ {
        return 307 https://<needs URL>/cloudbeaver$request_uri;
    }

    location /cloudbeaver/ {
        proxy_pass  http://<needs pass request>/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

**Comment by Wroud** [comment]
we fixed this issue in 21.0.4
documentation was updated: https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration

if you want to change the path you only need to change `rootURI`, so the configuration will be looks like:

```JSON
{
  "server": {
    "serverName": "Cloudbeaver",
    "expireSessionAfterPeriod": 1800000,
    "rootURI": "/cloudbeaver",
    "serviceURI": "/api/"
  },
  "app": {
    "anonymousAccessEnabled": false,
    "authenticationEnabled": true,
    "supportsCustomConnections": false
  }
}
```

please check for any issues

**Comment by meb21uk** [comment]
Hi Wroud,

All sorted, thanks. Location block for NGINX if anyone is interested. Log below from testing.

    location /cloudbeaver {
        set $db dbeaver:8978;
        proxy_pass  http://$db;
        include /etc/nginx/common-loc.conf;
    }

<img width="1397" alt="Screenshot 2021-07-02 at 14 17 07" src="https://user-images.githubusercontent.com/69455950/124280306-71e2a200-db40-11eb-843f-6d9fad5a0e4d.png">

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen, if the issue still can be reproduced.

**Comment by yankee14** [comment]
> Hi Wroud,
> 
> All sorted, thanks. Location block for NGINX if anyone is interested. Log below from testing.
> 
> ```
> location /cloudbeaver {
>     set $db dbeaver:8978;
>     proxy_pass  http://$db;
>     include /etc/nginx/common-loc.conf;
> }
>```

@meb21uk On the first line inside your location block, where did the hostname `dbeaver` come from? Is that your container name or network name?
On the 3rd line, what is the contents of your file `/etc/nginx/common-loc.conf`?

Sorry for the obvious questions, but I'm having trouble getting this to work through my reverse proxy.

**Comment by YuraKril** [comment]
Hi team,
After save any configuration from UI - "rootURI" key removed from - workspace/.data/.cloudbeaver.runtime.conf
Restart container without rm volume  =  404.
