### ISSUE TITLE
Add configuration for full-name parameter from auth proxy

### ISSUE THREAD

**Issue by brunnels** [dbeaver/cloudbeaver#2791]
Right now there is `first-name` and `last-name` but I need `full-name` and maybe `full-name-delimiter`.  I'm using authelia via ingress-nginx in k8s and it has this annotation:

`nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email`

Authelia only provides those headers: https://www.authelia.com/integration/trusted-header-sso/introduction/#response-headers

Here's my current authConfig params:
```
            parameters: {
              first-name-header: "X-First-name",
              user-header: "Remote-User",
              team-header: "Remote-Groups",
              team-delimiter: ",",
              logout-url: "https://auth.${SECRET_DOMAIN}/logout?rd\u003dhttps://cloudbeaver.${SECRET_DOMAIN}",
              last-name-header: "X-Last-name"
            }
```

Here's my flux Kustomization for reference https://github.com/brunnels/talos-cluster/tree/main/kubernetes/apps/databases/cloudbeaver

**Comment by EvgeniaBzzz** [comment]
Hi @brunnels 
Thank you for your request! 🦫 
We will add parameter in one of the future releases

**Comment by brunnels** [comment]
Great, thank you.  I'm happy to test once you're ready.

**Comment by dariamarutkina** [comment]
Hello @brunnels !
We have added a [parameter](https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication#configuring-default-http-header-fields) `X-Full-name` to authConfig.
Please check out v24.1.4.
We're grateful for your support and engagement with our project!

**Comment by brunnels** [comment]
@dariamarutkina So there's config for `full-name-header` now?

So my authConfig should be:
```python
            parameters: {
              full-name-header: "Remote-Name",
              user-header: "Remote-User",
              team-header: "Remote-Groups",
              team-delimiter: ",",
              logout-url: "https://auth.${SECRET_DOMAIN}/logout?rd\u003dhttps://cloudbeaver.${SECRET_DOMAIN}"
            }
```

**Comment by brunnels** [comment]
answer my own question, yes:  https://github.com/dbeaver/cloudbeaver/blob/devel/server/bundles/io.cloudbeaver.service.auth/src/io/cloudbeaver/service/auth/RPConstants.java#L25

Thank you for the added configuration!
