### ISSUE TITLE
Support for multiple LDAP hosts

### ISSUE THREAD

**Issue by stephanonepoint** [dbeaver/cloudbeaver#2796]
It would be convenient to have the possibility to pass to the ldap host a list of hosts or the various hosts to be given in a string with a comma separated hosts in the **cloudbeaver.conf**.

Currently the configuration file only allow one string host to be given as follow : 
`authConfigurations: [
                    {
                        "id": "ldap",
                        "provider": "ldap",
                        "displayName": "LDAP",
                        "disabled": false,
                        "iconURL": "",
                        "description": "",
                        "parameters": {
                            "ldap-host": "{{ ldap_host }}",
                            "ldap-port": "636",
                            "ldap-dn": "{{ ldap_dn }}"
                        }
                    }
`
                    
(For the Community Edition)

**Comment by EvgeniaBzzz** [comment]
Hi @stephanonepoint 
How many hosts do you actually need?

For now, as a workaround you can add several LDAP entries:
```
    "authConfigurations": [
      {
        "id": "ldap",
        "provider": "ldap",
        "displayName": "LDAP",
        "disabled": false,
        "iconURL": "",
        "description": "",
        "parameters": {
          "ldap-host": "host_name",
          "ldap-port": "389",
          "ldap-dn": "ou=ou_name,dc=dc_name,dc=dc2_name"
        }
      },
        {
        "id": "ldap2",
        "provider": "ldap",
        "displayName": "LDAP2",
        "disabled": false,
        "iconURL": "",
        "description": "",
        "parameters": {
          "ldap-host": "host_name",
          "ldap-port": "389",
          "ldap-dn": "ou=ou_name,dc=dc_name,dc=dc2_name"
        }
      }
    ]
```
Each tab will be associated with its own host.
![Снимок экрана 2024-07-22 181319](https://github.com/user-attachments/assets/094a9a71-3780-4f2e-9829-d443e99b60bd)

**Comment by EvgeniaBzzz** [comment]
Hi @stephanonepoint 
Is the solution with adding multiple LDAP providers suitable for you?

**Comment by EvgeniaBzzz** [comment]
We are not planning to add the ability to specify hosts in a string in the near future. 
For known use cases, creating several separate entries is sufficient. 
However, thank you for your suggestion, we'll keep it in mind.
