### ISSUE TITLE
Install let's encrypt certificate on my cloudbeaver

### ISSUE THREAD

**Issue by huhtml** [dbeaver/cloudbeaver#280]
Dear,
I have deployed cloudbeaver on my infrastructure. I am running it with http://mydomain:8978
How can install let's encrypt certificate on my cloudbeaver ?
Thank you very much for your help!
Best regards.

**Comment by serge-rider** [comment]
Generally you should use some other web server in front of Cloudbeaver - nginx or apache. 
And configure SSL, cache and other stuff there.

Here is a brief instruction how to configure CloudBeaver Nginx proxy: https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-and-Nginx

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if you have any questions.
