### ISSUE TITLE
HTTP ERROR 403 Forbidden

### ISSUE THREAD

**Issue by Etoakor** [dbeaver/cloudbeaver#2807]
启动后浏览器报403错误
![1](https://github.com/user-attachments/assets/6d339192-22cc-44f8-a02e-6069af222053)

**Comment by EvgeniaBzzz** [comment]
Hi @Etoakor 
We need more information about deploy. How do you start server? Did you change any config files?

**Comment by Etoakor** [comment]
> 你好@Etoakor 我们需要有关部署的更多信息。您如何启动服务器？您是否更改了任何配置文件？

hi,我没有更改任何文件，我实在windows系统中安装了wsl，在这里面启动就出现这个问题了

**Comment by LonwoLonwo** [comment]
Please use the English language.

Do you have any custom permissions on the docker image?

**Comment by GeoffryAbiFarah** [comment]
Hey, I am facing the same issue.
I cloned the cloudbeaver repository and ran:
./build.sh
./make-docker-container.sh
./run-docker-container.sh

without changing anything, and I'm getting the following when accessing http://localhost:8978
`09-08-2024 07:57:24.556 [qtp1651318806-76] DEBUG i.c.model.session.WebUserContext - refresh permissions null a872d211-ef1d-41a4-8f3b-db6d15d9f69e`
![image](https://github.com/user-attachments/assets/0311874c-116e-4935-a6e1-81fb30d8eb47)

is this expected? and what can be done to fix it?

**Comment by EvgeniaBzzz** [comment]
@GeoffryAbiFarah could you, please, provide us with `build.sh` log? Still can't reproduce

**Comment by LonwoLonwo** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
