### ISSUE TITLE
Export TXT replaces newline character

### ISSUE THREAD

**Issue by tlegrave** [dbeaver/cloudbeaver#2811]
Hello there,

**Describe the bug**
When I make a txt export from the UI with utf-8 encoding, newline characters are not respected.

**To Reproduce**
1. Connect Trino data source
2. Enter the following query `SELECT concat('Hello', CHR(10), 'world') AS result;`
3. Click export, choose txt and set all field to false
4. Choose utf-8 encoding and download the file 

**Screenshots**
![Capture d’écran 2024-07-30 à 10 08 21](https://github.com/user-attachments/assets/c430890a-4229-4953-88c1-01e69ef49f8a)

Value in the bottom-right panel looks good but after download the file contains:

```txt
Hello¶world
```

**Desktop (please complete the following information):**
 - OS: OS X 12.7.3
 - Browser Firefox
 - Version 128.0.3

**Additional information**
- Other ascii code points seem to be respected (e.g. space)
- Other non ascii code points seem to be respected (e.g. `à`)
- Zero width chars (e.g. combining characters) work and are not modified by the export function

Is this a bug or a desired behavior? If this is wanted, is there any plan to add a "raw" export feature?

Thanks

**Comment by dariamarutkina** [comment]
@tlegrave thank you for bug reporting!
We are going to fix it in the near future.

**Comment by LonwoLonwo** [comment]
Hello @tlegrave 

We reviewed your request again, and we have a question now.
Why do you need a new line inside a value in the result text? Our TXT export format is designed to have all values from the row in a single string. A new line character will break this behavior. Maybe you can just use the \n symbol instead of the CHR(10)? In this case, you can copy content from your .txt file with a new line inside.

**Comment by tlegrave** [comment]
Hello @LonwoLonwo,

Sorry for the late reply. The usecase was a bit tricky, I wanted to format the output of the query to make it compatible with SRT subtitle files (the tables stores transcriptions of videos).

Using a `\n` instead of `CHR(10)` does not solves the problem as it prints a raw `\n` in the export. For example:

```txt
Hello\nworld
```

I didn't know that txt export was designed to handle all values on a single line. I understood it more like a "raw" export of the data (doesn't matter linebreaks or other stuffs).

**Comment by LonwoLonwo** [comment]
I am not sure what we can do inside our one-line .txt export.
Did you try to use the XLSX export? And rework the .xlsx file in the required format?

**Comment by LonwoLonwo** [comment]
It's been a while since there has been an update here. If the issue is still present, please let me know and provide additional information.
