### ISSUE TITLE
Unable to add cockroachdb-driver in cloudbeaver-ce

### ISSUE THREAD

**Issue by AllardKrings** [dbeaver/cloudbeaver#2817]
Hello,

I am trying to add the cockroachdb-driver to cloudbeaver-ce. Whatever I try, it does not show up in the UI

Here is my configuration:

added directory cockroachdb in server/drivers
added pom.xml inside the directory:

[<project](url) xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>driver-cockroachdb</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>

    <parent>
        <groupId>io.nosqlbench</groupId>
        <artifactId>mvn-defaults</artifactId>
        <version>4.15.102</version>
        <relativePath>../mvn-defaults</relativePath>
    </parent>

    <properties>
        <deps.output.dir>cockroachdb</deps.output.dir>
    </properties>

    <description>
        A CockroachDB ActivityType driver for http://nosqlbench.io/
    </description>

    <dependencies>
        <dependency>
            <groupId>io.nosqlbench</groupId>
            <artifactId>driver-jdbc</artifactId>
            <version>4.15.102</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.3.3</version>
        </dependency>
    </dependencies>

</project>

Then I added the lines in plugin.xml:

 cat ~/cloudbeaver/server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml 
<?xml version="1.0" encoding="UTF-8"?>
<plugin>
    
    <extension point="org.jkiss.dbeaver.resources">
        <resource name="drivers/cockroachdb"/>
        <resource name="drivers/db2"/>
        <resource name="drivers/db2-jt400"/>
        <resource name="drivers/duckdb"/>
        <resource name="drivers/mysql/mysql8"/>
        <resource name="drivers/mariadb"/>
        <resource name="drivers/oracle"/>
        <resource name="drivers/postgresql"/>
        <resource name="drivers/clickhouse"/>
        <resource name="drivers/clickhouse_com"/>
        <resource name="drivers/jaybird"/>
        <resource name="drivers/h2"/>
        <resource name="drivers/h2_v2"/>
        <resource name="drivers/sqlite/xerial"/>
        <resource name="drivers/mssql/new"/>
        <resource name="drivers/trino"/>
        <resource name="drivers/kyuubi"/>
    </extension>

    
    <extension point="org.jkiss.dbeaver.product.bundles">
        <bundle id="drivers.cockroachdb" label="CockroachDB drivers"/>
        <bundle id="drivers.db2" label="DB2 drivers"/>
        <bundle id="drivers.duckdb" label="DuckDB drivers"/>
        <bundle id="drivers.jt400" label="DB2 iSeries drivers"/>
        <bundle id="drivers.mysql" label="MySQL drivers"/>
        <bundle id="drivers.mariadb" label="MariaDB drivers"/>
        <bundle id="drivers.oracle" label="Oracle drivers"/>
        <bundle id="drivers.postgresql" label="PostgreSQL drivers"/>
        <bundle id="drivers.clickhouse" label="Clickhouse (legacy) drivers"/>
        <bundle id="drivers.clickhouse_com" label="Clickhouse drivers"/>
        <bundle id="drivers.firebird" label="Firebird drivers"/>
        <bundle id="drivers.h2" label="H2 drivers"/>
        <bundle id="drivers.h2_v2" label="H2 v2 drivers"/>
        <bundle id="drivers.sqlite.xerial" label="SQLite drivers"/>
        <bundle id="drivers.mssql.new" label="SQL Server drivers"/>
        <bundle id="drivers.trino" label="Trino drivers"/>
        <bundle id="drivers.kyuubi" label="Apache Kyuubi drivers"/>
    </extension>

    
    <extension point="io.cloudbeaver.driver">
        <driver id="db2:db2"/>
        <driver id="db2_i:db2_iseries"/>
        <driver id="mysql:mysql8"/>
        <driver id="mysql:mariaDB"/>
        <driver id="oracle:oracle_thin"/>
        <driver id="postgresql:postgres-jdbc"/>
        <driver id="jaybird:jaybird"/>
        <driver id="clickhouse:yandex_clickhouse"/>
        <driver id="clickhouse:com_clickhouse"/>
        <driver id="h2:h2_embedded"/>
        <driver id="h2:h2_embedded_v2"/>
        <driver id="sqlite:sqlite_jdbc"/>
        <driver id="sqlserver:microsoft"/>
        <driver id="generic:trino_jdbc"/>
        <driver id="generic:duckdb_jdbc"/>
        <driver id="generic:kyuubi_hive"/>
        <driver id="generic:cockroachdb"/>
    </extension>
</plugin>

Then i ran ~/cloudbeaver/deploy/build.sh

I can see that server/drivers/cockroacddb/target contains the jar file.

However the driver does not show up in de UI

What am I missing?

**Comment by dariamarutkina** [comment]
Hello @AllardKrings !
Have you [added a driver](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers#configuring-drivers-in-dbeaver) to plugin.xml?

**Comment by AllardKrings** [comment]
as I understand I have to do this in the dbeaver-code and not in the cloudbeaver-code? 

Does building cloudbeaver clone dbeaver asswell and overwrite my changes in the plugin.xml?

**Comment by dariamarutkina** [comment]
> as I understand I have to do this in the dbeaver-code and not in the cloudbeaver-code?

Yes, in the dbeaver-code

> Does building cloudbeaver clone dbeaver asswell and overwrite my changes in the plugin.xml?

No, it's not like that

**Comment by dariamarutkina** [comment]
Hello @AllardKrings!
Is there any news, have you been able to add a driver?

**Comment by AllardKrings** [comment]
No,

I can use the postgres driver to adress cockroachdb

Thanks for your help

Op ma 12 aug 2024 om 10:03 schreef Daria Marutkina ***@***.***
