### ISSUE TITLE
Configure system objects visibility for connections

### ISSUE THREAD

**Issue by EricPE69** [dbeaver/cloudbeaver#285]
**Describe the bug**
I access a mysql database (8.0.19) with the root user. i only see the sys database; I do not see mysql, performance_schema and information_schema even if I set it in database parameter.

**To Reproduce**
Access a mysql database (v8) with root user.

**Screenshots**
![2021-02-10 17_26_45-CloudBeaver](https://user-images.githubusercontent.com/39956814/107539852-aa9bd200-6bc5-11eb-96a1-9ef4f304e2f7.png)
![2021-02-10 17_25_51-CloudBeaver](https://user-images.githubusercontent.com/39956814/107539882-b5566700-6bc5-11eb-97be-f3224c5a78da.png)

**Desktop (please complete the following information):**
 - docker image 20.0.3
 - Browser : chrome
 - Version 87

**Comment by kseniiaguzeeva** [comment]
Unfortunately I cannot reproduce it. Do you enter a schema in the connection settings? 
![chrome_bWAm6nodkF](https://user-images.githubusercontent.com/51405061/107942608-86ad0780-6f9c-11eb-8b8d-b9122a46db89.png)


Can you see other schemas when use other clients (e.g. DBeaver https://dbeaver.io/download/)?

**Comment by EricPE69** [comment]
No, I do not enter schema in the connection settings.
Yes, with adminer or dbeaver I see all the schemas (see screenshot)
![2021-02-15 13_37_24-Window](https://user-images.githubusercontent.com/39956814/107947684-03d37f00-6f93-11eb-8626-4f984df19047.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the additional info. Looking for steps to reproduce.

**Comment by kseniiaguzeeva** [comment]
Can you login as admin? If yes, please go to Administration menu>Server configuration and check whether Navigator simple view is enabled. 
![Screenshot 2021-02-16 at 12 49 11](https://user-images.githubusercontent.com/51405061/108046973-4e69ff80-7056-11eb-88d4-da99c3902a68.png)

If yes, disable it and recreate the connection.

**Comment by EricPE69** [comment]
No, Navigator simple view is not enabled.
![2021-02-16 11_14_13-Window](https://user-images.githubusercontent.com/39956814/108049297-5e7ae280-7048-11eb-87cb-475a7528ff2c.png)

**Comment by serge-rider** [comment]
By default you system objects are hidden in CloudBeaver. 
We plan add this configuration option in one of the next versions (in DBeaver it is shown as "Show system objects" setting on connection settings page).

Workaround: you can change connection config manually by editing file `data-sources.json` file. It can be found in CloudBeaver workspace folder in `GlobalConfiguration/.dbeaver` or `user-projects/USER/.dbeaver`.
Find you connection config there and add elemnt `"show-system-objects": true`  somewhere after "name": "...".
Restart CloudBeaver server - now you can see system objects.

**Comment by EricPE69** [comment]
I add a connection with "show-system-objects": true in data-sources.json file (see joined file).
For information to see this connection in the GUI I had to connect with the admin user, otherwise I do not see it.
But with this connection it does not change anything: I still only see the sys database.

[data-sources.json.txt](https://github.com/dbeaver/cloudbeaver/files/6003512/data-sources.json.txt)

**Comment by kseniiaguzeeva** [comment]
Thank you for the additional details. We will add the option to see system objects to the next release.

**Comment by EricPE69** [comment]
Ok,

Thank you.

**Comment by Wroud** [comment]
Hello. great news we released 20.0.6, where we implemented this feature!
![image](https://user-images.githubusercontent.com/811729/113263454-777ae280-92da-11eb-88bb-318f372dcc05.png)

**Comment by EricPE69** [comment]
Hello,

It works,
Thank you
