### ISSUE TITLE
how to pre-load queries from disk

### ISSUE THREAD

**Issue by parisni** [dbeaver/cloudbeaver#2882]
dbeaver AFAIK saves queries on disk. So it's trivial to export them, or preload queries.

Now cloud beaver apparently saves queries within the db or something. So it's kind of complex to pre-load queries for users. 

Let's say I want to give users an connection with demonstration queries, now I have to backup the workspace ?
https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-Workspace-Backup

**Comment by EvgeniaBzzz** [comment]
Hi @parisni 
Scripts for shared connections you can find in `workspace/GlobalConfiguration` (`.sql` files). 
So you are right - you have to configure a connection and scripts once, and then use that workspace backup for demo.

**Comment by parisni** [comment]
thanks for your answer. I am not sure to get what you mean by `.sql` files. I can't find any sql files in `workspace/GlobalConfiguration`. Also if I add manually sql file there, they don't appear in the ui.

**Comment by EvgeniaBzzz** [comment]
If you have any scripts for shared connections then you will see in GlobalConfiguration folder smth like: 
```
.dbeaver
.project
script-name-1.sql
script-name-2.sql
```
Scripts for private connections are stored in .dbeaver folder in separated named folders (for each user).

Are you sure that you're trying to add `.sql` to /cloudbeaver/workspace/GlobalConfiguration for current server? Please, check that you are running and editing the same workspace.

**Comment by webketje** [comment]
Don't forget you need to restart Cloudbeaver to take these into account

**Comment by EvgeniaBzzz** [comment]
@webketje Scripts are synchronized, as shared scripts could be edited by several users at the same time. So no server restart needed. 
But thanks for your comment, it's an important step for changing other server-side settings.

**Comment by parisni** [comment]
> Are you sure that you're trying to add .sql to /cloudbeaver/workspace/GlobalConfiguration for current server? Please, check that you are running and editing the same workspace.

Yes I did. AFter adding the sql files, no one appears in the UI. BTW when I create new scripts from the UI, no sql file can be found in that directory either. Sounds like the scripts are store either in the database, or in the client side, within some firebase .

**Comment by EvgeniaBzzz** [comment]
@parisni 
Check that 'Enable Resource Manager' is enabled in Administration UI part. 
Also scripts are not created automatically, you should press 'Save as script' button in SQL editor for the first time ([SQL editor article](https://github.com/dbeaver/cloudbeaver/wiki/Resource-Manager#saving-a-script)).

Could you, please, provide us with a video of creating script in UI.
And also server log on the moment of saving script. Open SQL editor - press 'Save as script'

**Comment by parisni** [comment]
> Check that 'Enable Resource Manager' is enabled in Administration UI part

If not enabled by default then i didn't turn it on. Will try thanks

**Comment by parisni** [comment]
Got it : I was using anonymous user, and disabled auth. In this way the file support is not enabled.


To solve the issue I fall back using reverse proxy auth and got same user experience including file sharing feature.

Thanks for your patience.

Sep 13, 2024 12:56:00 Nicolas Paris ***@***.***>:

>> Check that 'Enable Resource Manager' is enabled in Administration UI part
> 
> If not enabled by default then i didn't turn it on. Will try thanks

**Comment by LonwoLonwo** [comment]
Thanks for your investigation @parisni
