### ISSUE TITLE
Cloudbeaver offline deployment experience improved

### ISSUE THREAD

**Issue by Kingong** [dbeaver/cloudbeaver#2904]
**Is your feature request related to a problem? Please describe.**

When I deploy cloudbeaver on an offline environment( (in an internet-free environment) ) , i use administrator cbadmin account to manage configuration and user. The CE will access the `https://dbeaver.com/product/cloudbeaver-ce-version.json` resource which is located in network dbeaver.com site.
By analysis, the `cloudbeaver-ce-version.json` request is triggered in `io.cloudbeaver.product.ce` plugin.
![image](https://github.com/user-attachments/assets/0305ca71-21e1-4e2d-a44d-510b82b445fd)

**Describe the solution you'd like**

I hope CE can extract this configuration(the version resource absolute path, eg: http: //test.com/cloudbeaver-ce-version. json) into a configuration file. Then I can extract `cloudbeaver-ce-version. json` file in the static resource server(offline environment).

**Comment by EvgeniaBzzz** [comment]
Hi @Kingong 
Could you, please, translate your issue into English to avoid misunderstanding.

**Comment by Kingong** [comment]
> Hi @Kingong Could you, please, translate your issue into English to avoid misunderstanding.
Sorry, I have translate the issue to English. Thanks.

**Comment by Kingong** [comment]
> > Hi @Kingong Could you, please, translate your issue into English to avoid misunderstanding.
> > Sorry, I have translate the issue to English. Thanks.

just now, i misclick close issue. sorry

**Comment by EvgeniaBzzz** [comment]
@Kingong actually that's a bug, as application should work in offline-mode.
Thank you for your report!

**Comment by Kingong** [comment]
Okay，Hope you support the offline-mode perfectly. Thanks.

**Comment by LonwoLonwo** [comment]
Hello @Kingong 

We fixed this issue and re-released our product on Docker. 
Could you please recheck it? Is this issue still relevant?

**Comment by Kingong** [comment]
> Hello @Kingong
> 
> We fixed this issue and re-released our product on Docker. Could you please recheck it? Is this issue still relevant?

yes, I use the 24.2.0 tag docker image to deploy yesterday. It's now correctly work in offline mode and won't tip error. Thanks.

**Comment by EvgeniaBzzz** [comment]
Thank you for being with CloudBeaver! 🦫
