### ISSUE TITLE
Now in "Offline mode"

### ISSUE THREAD

**Issue by tyuhasbio5** [dbeaver/cloudbeaver#2909]
I'd set up CloudBeaver Community 24.1.5 for our lab.  I'm using the Docker container running on an AWS Linux 2 instance with CC configured to connect to a postgresql RDS instance.  It had been running fine for the past few weeks.  I just went in to check on things this morning and an "Offline mode" message has popped up.  The db connections work and I can run queries so I'm not sure what is offline.  

I did just upgrade to 24.2.0 after seeing the message thinking that would clear "offline mode" but the message is still there.

**Comment by LonwoLonwo** [comment]
Hello @tyuhasbio5 
Thanks for the report.

We just fixed this issue and re-released our product on Docker.
Could you please recheck it? Is this issue still relevant?

**Comment by tyuhasbio5** [comment]
Hi @LonwoLonwo, 
The message is now gone.
Thanks for the quick turnaround!!

**Comment by LonwoLonwo** [comment]
Thanks for the quick reply!
