### ISSUE TITLE
Regarding Issue 2728 - autocommit

### ISSUE THREAD

**Issue by rlauti1980** [dbeaver/cloudbeaver#2921]
I've tried to set the autocommit to false, for all our data connections, by adding the autocommit parameter to every connection, in the configuration/bootstrap section of data-sources.json.

"configuration": {
  ...
      "bootstrap": {
            "autocommit": false
      }
}

This was what i noticed that changed, after deactivating it using the GUI. But it seems not all that needs to be done, because the autocommit is still active.
What else needs to be done?

Thank you!
René

**Comment by EvgeniaBzzz** [comment]
Hi @rlauti1980 
That's enough to disable autocommit mode. 
What exactly did you do to ensure that autocommit mode is still on?
 
If autocommit is disabled in connection settings, you'll see 3 buttons when open sql editor.
![image](https://github.com/user-attachments/assets/7ec61a24-0077-4fb3-bd81-e32bc2e1d37c)

**Comment by rlauti1980** [comment]
Hi Evgenia,

sorry for my late answer. I hadn't any time to go after this. Let me double check, what i have done in the config file and come back to you.

Thank you for your fast response!

**Comment by EvgeniaBzzz** [comment]
@rlauti1980 
Also you can set commit mode in the connection settings via UI.
Expand Expert settings on the connection form and unmark 'Auto commit'.
![image](https://github.com/user-attachments/assets/0dd56451-a42c-4c15-824c-13f687a6f88c)

**Comment by rlauti1980** [comment]
I'm aware of that. When i unset the checkbox manually, this is actually working. But no one wants to do it for that many connections. 
Following is an example of a connection in the script generated json file and it's end.
![image](https://github.com/user-attachments/assets/94ad5bf7-8ec4-496e-a452-b489d79f2646)

But the checkbox is still set in the GUI after deployment.

![image](https://github.com/user-attachments/assets/284ec8b8-6520-49d4-83ec-615d4733ecab)

What am i missing?

**Comment by EvgeniaBzzz** [comment]
Please, use lower case for `autocommit`.

**Comment by rlauti1980** [comment]
Awsome! That was my mistake. Works now as expected. 
Thank you very much!

**Comment by EvgeniaBzzz** [comment]
Great, thanks for the update 🦫
