### ISSUE TITLE
Accessing an existing database connection via a link does not work

### ISSUE THREAD

**Issue by ikril** [dbeaver/cloudbeaver#2938]
**Describe the bug**
Accessing an existing database connection via a link does not work

**To Reproduce**
1. Go to https://demo.cloudbeaver.io/open?id=cql-19097a9e12d-6bb1ce6d78afd2f0 and you will get 404
2. See error

**Screenshots**
![Screenshot 2024-09-26 at 16 04 58](https://github.com/user-attachments/assets/530a8047-efe4-4aba-94a0-02dcb53ff1d2)

**Comment by EvgeniaBzzz** [comment]
Hi @ikril 
Thank you for your report!
How did you plan to use the link? What is your use case?

**Comment by ikril** [comment]
I have a large number of databases, so I opened them using this url

**Comment by dariamarutkina** [comment]
Hello @ikril !
You can find a fix in v.24.2.3 💙
Thank you for being with CloudBeaver!
