### ISSUE TITLE
Connection structure not visible on login when using folders

### ISSUE THREAD

**Issue by martins-072** [dbeaver/cloudbeaver#294]
**Describe the bug**
When connection is placed under folder, database folder structure is not displayed on connect.

**To Reproduce**
1. Create connection such as:
`{
	"folders": {
		"Folder": {}
	},
	"connections": {
		"oracle_thin-<hash>": {
			"provider": "oracle",
			"driver": "oracle_thin",
			"name": "test",
			"save-password": true,
			"show-system-objects": true,
			"read-only": false,
			"folder": "Folder",
			"configuration": {
				"host": "<IP>",
				"port": "<port>",
				"database": "<service>",
				"url": "jdbc:oracle:thin:@//<IP>:<port>/<service>",
				"type": "dev",
				"provider-properties": {
					"@dbeaver-sid-service@": "SERVICE"
				},
				"auth-model": "oracle_native",
				"handlers": {}
			}
		}
	},
	"connection-types": {
		"dev": {
			"name": "Development",
			"color": "255,255,255",
			"description": "Regular development database",
			"auto-commit": true,
			"confirm-execute": false,
			"confirm-data-change": false
		}
	}
}`
2. Click on connection in order to connect to database
3. Database is connected, connection tree structure is not displayed. Click on connection again - nothing is happening.
4. Refresh page
5. Try to expand connection - it is working

**Screenshots**
On login:
![image](https://user-images.githubusercontent.com/79421708/108638015-78278a00-748d-11eb-9c3e-2e1c2a4846f1.png)
After refresh:
![image](https://user-images.githubusercontent.com/79421708/108638033-8ecde100-748d-11eb-9552-72882bd409ef.png)

**Desktop (please complete the following information):**
 - OS: Windows Desktop, container running on CentOS 7.5
 - Browser: chrome, edge
 - container version is latest

**Comment by serge-rider** [comment]
Thank you for the bug report

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it for now. Could you please try the latest release version?

**Comment by martins-072** [comment]
It seems to be fixed in latest version. thanks.

**Comment by kseniiaguzeeva** [comment]
Nice to hear!
