### ISSUE TITLE
GrantConnectionsAccessToAnonymousTeam flag incorrect behaviour 

### ISSUE THREAD

**Issue by MikeAmputer** [dbeaver/cloudbeaver#2943]
I setup CloudBeaver via docker compose for a dev environment. I'm trying to achieve anonymous access with a predefined server connection list. I mounted `.../workspace/GlobalConfiguration/.dbeaver/data-sources.json`, and connections are visible for authorized users, but not for anonymous.

Here's a part of my `.../workspace/.data/.cloudbeaver.runtime.conf`:
```json
"server": {
  "serverName": "CloudBeaver",
  ...
},
"app": {
  "anonymousAccessEnabled": true,
  "supportsCustomConnections": true,
  "publicCredentialsSaveEnabled": true,
  "adminCredentialsSaveEnabled": true,
  "grantConnectionsAccessToAnonymousTeam": true,
  ...
}
```

I expected the `"grantConnectionsAccessToAnonymousTeam": true` to make predefined connections visible to anonymous users, as it's description states: "Provides access to the predefined shared connections for the "User" team". While anonymous users belong to the "User" team.

Mounting the following `.../workspace/GlobalConfiguration/.dbeaver/data-sources-permissions.json` didn't help either:
```json
{
    "my_data_source": ["user", "admin"]
}
```

The only thing that solved the issue was granting "admin" permission for the "User" team via `/opt/cloudbeaver/conf/initial-data.conf`:
```
{
    teams: [
        {
            subjectId: "admin",
            teamName: "Admin",
            description: "Administrative access. Has all permissions.",
            permissions: [ "admin" ]
        },
        {
            subjectId: "user",
            teamName: "User",
            description: "All users, including anonymous.",
            permissions: [ "admin" ]
        }
    ]
}
```

So, it seems like the `grantConnectionsAccessToAnonymousTeam` is behaving incorrectly. Additionally, `data-sources-permissions.json` might also be behaving incorrectly.

**Desktop (please complete the following information):**
 - OS: Debian WSL
 - Browser: chrome
 - Version: 24.2.1

**Comment by AndLut** [comment]
+1

**Comment by EvgeniaBzzz** [comment]
Hi @MikeAmputer 
Path to the config is broken. We'll fix it in one of the nearest releases.
Thank you for the report! 🦫

**Comment by EvgeniaBzzz** [comment]
Hi @MikeAmputer @AndLut 
Granting access to anonymous users was fixed in v.24.2.2, please take a look.

Now it works as expected:
1. To add access to a specific connection for a user role (including anonymous by default) - create a file `data-sources-permissions.json` in `cloudbeaver/workspace/GlobalConfiguration/.dbeaver`:

````
{
    "datasource-123": ["admin", "user"]
}
````

where `datasource-123` is the name of an existing connection in `data-sources.json`.

2. To add access to all shared connections for anonymous users, modify `cloudbeaver.runtime.conf`:

````
"grantConnectionsAccessToAnonymousTeam": "${CLOUDBEAVER_APP_GRANT_CONNECTIONS_ACCESS_TO_ANONYMOUS_TEAM:true}"
````

3. To change the default anonymous group, update `cloudbeaver.conf`:

````
anonymousUserRole: "user"
````
