### ISSUE TITLE
Service exception: Too many open files

### ISSUE THREAD

**Issue by chrisleell** [dbeaver/cloudbeaver#2947]
Service can not be used normally. The log shows exception: "Too many open files". The process opened 1,048,628 files and most of these files are from the directory /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver. This makes me very confused.
![image](https://github.com/user-attachments/assets/2c3114ca-5742-4fdd-af33-2080615f61f9)
![image](https://github.com/user-attachments/assets/6b15e4a8-96ec-417b-849e-e86a21e713b0)
![image](https://github.com/user-attachments/assets/675845b8-1834-4c94-bf64-c6f8a7f8de76)

**Comment by EvgeniaBzzz** [comment]
Hi @chrisleell 
Please update CloudBeaver version, this problem was fixed in 24.0.2

**Comment by chrisleell** [comment]
Hi @EvgeniaBzzz 
I have updated the version to 24.0.3. But when I open the connection. The number of open files increases. Even if I close all the connections and wait for a while. The number of open files is still high. I wonder when these open files will be closed.

**Comment by EvgeniaBzzz** [comment]
Hi @chrisleell 
It is expected that the number of files increases after connection. Service files will close after some time following a disconnection.
I just checked your case on the current version of CB and looks like everything works fine. In a minute after disconnection number of files is reduced to the previous value.

How big is the file growth after each connection? I mean the gap between 'before' states.
You can try to update to a major version (24.2.0).

**Comment by chrisleell** [comment]
Hi @EvgeniaBzzz 
I tried to update to the latest version (24.2.2) and the problem did not occur again.
Thank you for your reply.

**Comment by EvgeniaBzzz** [comment]
Great! 🦫 
Thanks for the update
