### ISSUE TITLE
 No application id has been found.

### ISSUE THREAD

**Issue by sunboyzoey** [dbeaver/cloudbeaver#2949]
in eclipse,dbeaver is debug running ok,but cloudbeaver failed( No application id has been found.)
![image](https://github.com/user-attachments/assets/87608315-4ba0-4643-8d9e-23a072a5400c)

how to fix this

**Comment by EvgeniaBzzz** [comment]
Hi @sunboyzoey 
Please, try [this workaround](https://stackoverflow.com/questions/13575695/eclipse-rcp-no-application-id-has-been-found):

> What you need to do is go to your Run Configurations (Run -> Run Configurations). Select the Plug-ins tab and then hit Add Required Plug-ins. Apply, then Run, and it should work now.

**Comment by EvgeniaBzzz** [comment]
[Developing in Eclipse](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse) article may also be helpful

**Comment by EvgeniaBzzz** [comment]
Hi @sunboyzoey 
Did this work for you?
