### ISSUE TITLE
It is not possible to create provided connections

### ISSUE THREAD

**Issue by opendatakraken** [dbeaver/cloudbeaver#295]
Hello, I'm testing Cloudbeaver 20.0.3 and would like to create provided connections.

However, this wiki page looks no more valid as I tried to insert connection in both
${WORKSPACE}/GlobalConfiguration/.dbeaver/provided-connections.json
and
${WORKSPACE}/GlobalConfiguration/.dbeaver/data-sources.json
and they don't appear in the connection list.

I also noticed that, if I create connection during the initial configuration they are entered in data-sources.json but further created connection are not stored there.

How can I create provided connections?

**Comment by serge-rider** [comment]
In new CloudBeaver versions we added admin panel where you can manage "provided" connections in web UI.

I've update documentation: https://github.com/dbeaver/cloudbeaver/wiki/Connection-configuration

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if you have any questions.
