### ISSUE TITLE
Unable to filter DB2 z/OS schemas

### ISSUE THREAD

**Issue by Ko2nel** [dbeaver/cloudbeaver#2954]
**Describe the bug**
There is a bug in the user interface when filtering resources in the DB2 for z/OS database. This bug occurs only at the highest level of resources (root node), which is the schema level. DB2 z/OS is a specific database where schemas are the highest level of resources, and this aspect may not have been accounted for in the filtering mechanism.

**To Reproduce**
1. Configure a connection to the DB2 for z/OS database.
2. Add a filter at the connection level (it is worth noting that there is an attempt to filter the resource named “DB2 for z/OS,” which corresponds to the database connection name).
3. Enter the schema name in the filtering window – `XXX1`.
4. Accept the configured filter.

**Screenshots**
DB2 for zOS connection structure
![image](https://github.com/user-attachments/assets/2dc49fcf-0246-49e7-bbeb-0b25657ddccd)
Filtering at root level
![image](https://github.com/user-attachments/assets/d3745508-3c69-4462-be02-b98234b9b8fc)
Applying filter
![image](https://github.com/user-attachments/assets/051fff2f-9b3e-4be3-82e8-550434c53779)

For comparison, I added a correctly behaving DB2 for LUW database.
DB2 for LUW connection structure
![image](https://github.com/user-attachments/assets/7eb7f8b3-3519-4cef-ba8e-552d6871594e)
Schema resource filtering working properly
![image](https://github.com/user-attachments/assets/77cd61c4-b434-4cb4-98f9-996f4d1e6bfd)

**Desktop:**
 - OS: Win11
 - Browser Google Chrome Version 129.0.6668.60 (Official Build) (64-bit)
 - Version based on CloudBeaver CE Server 24.2.0

**Additional info**
DBeaver handles filtering of DB2 for z/OS schemas properly.

Could you please fix it ;) ?

**Comment by dariamarutkina** [comment]
@Ko2nel  thank you for the report!
We've reproduced the bug. We will fix this in the future.
Thank you for your interest in CloudBeaver!

**Comment by dariamarutkina** [comment]
Hello @Ko2nel!
You can find a fix in v.24.2.4 💙
Thank you for being with CloudBeaver!

**Comment by Ko2nel** [comment]
Everything works great. thank you 🦫 team!
