### ISSUE TITLE
Localization setting in embedded Cloudbeaver

### ISSUE THREAD

**Issue by wieczorslawo** [dbeaver/cloudbeaver#2979]
Hi team.
We embed the Cloudbeaver in our UI with an iframe (we use a reverse proxy authorization). Is it possible to set a session language with a query param to see ad hoc results? Or could you recommend another approach?

**Comment by LonwoLonwo** [comment]
Hello @wieczorslawo 

Do you want to change the language to one existing on our list?
https://github.com/dbeaver/cloudbeaver/wiki/Local-Preferences#interface

**Comment by wieczorslawo** [comment]
Hi @LonwoLonwo 
Yes, to one that already exists. We might add some translations in the future.
But we want to set the language for the current session. Can we do it via a query parameter or something like a header? We need something that could take effect in the iframe.
Something like this:
cloudbeaver.example.com?lang=de would provide Cloudbeaver UI translated to German.
or this:
X-Lang reverse proxy auth header would set the session

**Comment by LonwoLonwo** [comment]
```java
public WebSession(
        @NotNull WebHttpRequestInfo requestInfo,
        @NotNull WebAuthApplication application,
        @NotNull Map<String, DBWSessionHandler> sessionHandlers
) throws DBException {
        this(requestInfo.getId(),
            CommonUtils.toString(requestInfo.getLocale()),
            application,
            sessionHandlers
        );
        updateSessionParameters(requestInfo);
}
```

` request.getAttribute("locale");`

Maybe this is what you are looking for. 
Or I need more details about your case.

**Comment by LonwoLonwo** [comment]
But it is better to change your default config 
_core.localization.localization: 'en'_

**Comment by wieczorslawo** [comment]
Okay the api/gql call to set lang did the trick, thank you

**Comment by LonwoLonwo** [comment]
Thanks for the update @wieczorslawo!

> We might add some translations in the future.

We will wait 🦫
