### ISSUE TITLE
Add Database Template error,tips Project is not found

### ISSUE THREAD

**Issue by sunboyzoey** [dbeaver/cloudbeaver#2983]
git clone project,local build and start,but Add Database Template error! tips "Project is not found"
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/0f0162ea-778c-481f-9e61-8c757e96529c">

start logs:

09-10-2024 17:11:02.612 [main] DEBUG i.c.model.app.BaseWebApplication - Loading configuration from /Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/conf/cloudbeaver.conf
09-10-2024 17:11:02.613 [main] DEBUG i.c.s.CBServerConfigurationController - Using configuration [/Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/conf/cloudbeaver.conf]
09-10-2024 17:11:02.613 [main] DEBUG i.c.s.CBServerConfigurationController - Read configuration [/Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/conf/cloudbeaver.conf]
09-10-2024 17:11:02.642 [main] INFO  io.cloudbeaver.server.CBPlatform - Initialize web platform...: 
09-10-2024 17:11:02.770 [main] DEBUG o.j.d.runtime.SecurityProviderUtils - BounceCastle bundle found. Use JCE provider BC
09-10-2024 17:11:02.805 [main] DEBUG o.j.d.registry.BasePlatformImpl - Initialize base platform...
09-10-2024 17:11:02.961 [main] DEBUG o.j.d.r.DataSourceProviderRegistry - Total database drivers: 119 (119)
09-10-2024 17:11:02.966 [main] ERROR io.cloudbeaver.server.CBPlatform -         Driver 'yandex_clickhouse' is missing library 'ru.yandex.clickhouse:clickhouse-jdbc:RELEASE'
09-10-2024 17:11:02.968 [main] INFO  io.cloudbeaver.server.CBPlatform - Available drivers: ClickHouse,Db2 for LUW,Db2 for IBM i,Firebird,DuckDB,Hadoop / Apache Kyuubi,Trino,H2 Embedded,H2 Embedded V.2,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite
09-10-2024 17:11:02.973 [main] INFO  io.cloudbeaver.server.CBPlatform - Web platform initialized (331ms)
09-10-2024 17:11:03.004 [main] INFO  i.c.m.a.BaseServerConfigurationController - Workspace path initialized: /Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/workspace
09-10-2024 17:11:03.004 [main] DEBUG i.c.s.CBServerConfigurationController - Runtime configuration [/Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/workspace/.data/.cloudbeaver.runtime.conf]
09-10-2024 17:11:03.004 [main] DEBUG i.c.s.CBServerConfigurationController - Read configuration [/Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/workspace/.data/.cloudbeaver.runtime.conf]
09-10-2024 17:11:03.013 [main] DEBUG io.cloudbeaver.server.CBApplication - CloudBeaver CE Server 24.2.3.202410090747 is starting
09-10-2024 17:11:03.013 [main] DEBUG io.cloudbeaver.server.CBApplication -      OS: Mac OS X 11.4 (x86_64)
09-10-2024 17:11:03.013 [main] DEBUG io.cloudbeaver.server.CBApplication -      Java version: 18.0.2.1 by Oracle Corporation (64bit)
09-10-2024 17:11:03.014 [main] DEBUG io.cloudbeaver.server.CBApplication -      Install path: '/Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/server'
09-10-2024 17:11:03.014 [main] DEBUG io.cloudbeaver.server.CBApplication -      Global workspace: 'file:/Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/workspace/'
09-10-2024 17:11:03.016 [main] DEBUG io.cloudbeaver.server.CBApplication -      Memory available 130Mb/2048Mb
09-10-2024 17:11:03.016 [main] DEBUG io.cloudbeaver.server.CBApplication -      Content root: /Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/web
09-10-2024 17:11:03.017 [main] DEBUG io.cloudbeaver.server.CBApplication -      Drivers storage: /Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/drivers
09-10-2024 17:11:03.019 [main] DEBUG io.cloudbeaver.server.CBApplication -      Listen port: 8978 on all interfaces
09-10-2024 17:11:03.019 [main] DEBUG io.cloudbeaver.server.CBApplication -      Base URI: /api/
09-10-2024 17:11:03.019 [main] DEBUG io.cloudbeaver.server.CBApplication -      Production mode
09-10-2024 17:11:03.025 [main] DEBUG io.cloudbeaver.server.CBApplication -      Local host addresses:
09-10-2024 17:11:03.026 [main] DEBUG io.cloudbeaver.server.CBApplication -              192.168.30.40 (192.168.30.40)
09-10-2024 17:11:03.027 [main] DEBUG io.cloudbeaver.server.CBApplication -              192.168.99.140 (192.168.99.140)
09-10-2024 17:11:03.028 [main] DEBUG io.cloudbeaver.server.CBApplication -              0:0:0:0:0:0:0:1%lo0 (localhost)
09-10-2024 17:11:03.076 [main] DEBUG i.c.s.auth.ReverseProxyConfigurator - Reverse proxy provider disabled, migration not needed
09-10-2024 17:11:03.092 [main] DEBUG i.c.service.security.db.CBDatabase - Initiate management database
09-10-2024 17:11:03.115 [main] DEBUG i.c.service.security.db.CBDatabase -       Initiate connection pool with management database (H2 Embedded V.2; jdbc:h2:/Users/**/Downloads/cloudbeaver/deploy/cloudbeaver/workspace/.data/cb.h2v2.dat)
09-10-2024 17:11:03.419 [main] DEBUG i.c.service.security.db.CBDatabase -       Connected to H2 2.1.214 (2022-06-13)
09-10-2024 17:11:03.496 [main] DEBUG i.c.service.security.db.CBDatabase -       Management database connection established
09-10-2024 17:11:03.508 [main] DEBUG io.cloudbeaver.server.CBApplication - Starting Jetty server (8978 on all interfaces) 
09-10-2024 17:11:03.862 [main] DEBUG i.c.server.graphql.GraphQLEndpoint - Schema extensions loaded: WebServiceBindingCore,WebServiceBindingNavigator,WebServiceBindingSQL,WebServiceBindingAdmin,WebServiceBindingAuth,WebServiceBindingDataTransfer,WebServiceBindingFS,WebServiceBindingMetadata,WebServiceBindingRM
09-10-2024 17:11:04.195 [main] DEBUG i.c.server.jetty.CBJettyServer - Max http session idle time: 1800s
09-10-2024 17:11:04.202 [main] DEBUG i.c.server.jetty.CBJettyServer - Active servlets:
09-10-2024 17:11:04.202 [main] DEBUG i.c.server.jetty.CBJettyServer -   static: [/]
09-10-2024 17:11:04.202 [main] DEBUG i.c.server.jetty.CBJettyServer -   images: [/api/images/*]
09-10-2024 17:11:04.202 [main] DEBUG i.c.server.jetty.CBJettyServer -   status: [/status]
09-10-2024 17:11:04.202 [main] DEBUG i.c.server.jetty.CBJettyServer -   graphql: [/api/gql/*]
09-10-2024 17:11:04.202 [main] DEBUG i.c.server.jetty.CBJettyServer -   sqlResultValueViewer: [/api/sql-result-value/*]
09-10-2024 17:11:04.202 [main] DEBUG i.c.server.jetty.CBJettyServer -   sqlUploadFile: [/api/resultset/blob/*]
09-10-2024 17:11:04.203 [main] DEBUG i.c.server.jetty.CBJettyServer -   adminLogs: [/api/logs/*]
09-10-2024 17:11:04.203 [main] DEBUG i.c.server.jetty.CBJettyServer -   dataTransfer: [/api/data/*]
09-10-2024 17:11:04.203 [main] DEBUG i.c.server.jetty.CBJettyServer -   dataTransferImport: [/api/data/import/*]
09-10-2024 17:11:04.203 [main] DEBUG i.c.server.jetty.CBJettyServer -   fileSystems: [/api/fs-data/*]
09-10-2024 17:11:04.203 [main] DEBUG i.c.server.jetty.CBJettyServer - Active websocket mappings:
09-10-2024 17:11:04.203 [main] INFO  i.c.server.jetty.CBJettyServer - Refreshing Jetty configuration

**Comment by EvgeniaBzzz** [comment]
Hi @sunboyzoey 
We can't reproduce it on the same version. Did you change something in the configuration files?
The error could be caused by the fact that you have no active projects. In other words, the current user does not have permission to create new connections on the main page.

**Comment by EvgeniaBzzz** [comment]
Also it could be a cache problem. Please, try to clear cache or open CB in incognito brawser tab.

**Comment by sunboyzoey** [comment]
> Also it could be a cache problem. Please, try to clear cache or open CB in incognito brawser tab.

I open CB in chrome,but alse have this question

![image](https://github.com/user-attachments/assets/f545331e-58df-4fe8-8a69-f00feb61cd7f)

![image](https://github.com/user-attachments/assets/e4b8fb99-196e-4315-82e0-bd5451f6d5f5)

how can i do

**Comment by sunboyzoey** [comment]
> Also it could be a cache problem. Please, try to clear cache or open CB in incognito brawser tab.

thanks for you! i rebuild this and no change init user name,everthing is ok. init is not allow change user name

**Comment by EvgeniaBzzz** [comment]
Thanks for the update 🦫

**Comment by sunboyzoey** [comment]
> Thanks for the update 🦫

sorry! i find when i run in eclipse,have this proble,but when i run run-server.sh no this prolem, is that true?
