### ISSUE TITLE
new user no connection 

### ISSUE THREAD

**Issue by sunboyzoey** [dbeaver/cloudbeaver#2988]
git clone project and build this, then to run run-server.sh

i use admin user create mysql connection templates,and access user new user 'zhangsan'
![image](https://github.com/user-attachments/assets/03daabb0-1c2c-4d77-92c3-6d1df7efa7dd)

but when i login with zhangsan user,in console not show mysql connection
![image](https://github.com/user-attachments/assets/b8be04ce-78da-424e-9c01-a4d224f6b6b5)

how can i do fix this

**Comment by LonwoLonwo** [comment]
Hello @sunboyzoey 

You created a template in the Connection Template section, not a real connection. You can use your template to create a new connection. Or create a new connection from the main page.

![image](https://github.com/user-attachments/assets/91bf06df-3a90-4d4e-94b5-38e741167b1a)

**Comment by sunboyzoey** [comment]
> 你好@sunboyzoey
> 
> 您在“连接模板”部分创建了一个模板，而不是真正的连接。您可以使用模板创建新连接。或者从主页创建新连接。
> 
> ![图像](https://private-user-images.githubusercontent.com/45152336/375284064-91bf06df-3a90-4d4e-94b5-38e741167b1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTM2NTUsIm5iZiI6MTcyODU1MzM1NSwicGF0aCI6Ii80NTE1MjMzNi8zNzUyODQwNjQtOTFiZjA2ZGYtM2E5MC00ZDRlLTk0YjUtMzhlNzQxMTY3YjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA5NDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMDc1OWRlY2NlZTNmMWQzN2ZhMDdhYzliNWY0Y2FiMzlkY2EzMzdjNzI5OWFmOTgwZDcyNjcwNjYxZGY2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lIe_-AXwhJZE5NHGIGZ1koyQwbj-WD-WGlj8aGht6TE)

ok! Thank you so much for helping me solve this problem
