### ISSUE TITLE
Enhance Logging of SQL Commands

### ISSUE THREAD

**Issue by jrhickey** [dbeaver/cloudbeaver#302]
**Is your feature request related to a problem? Please describe.**
In order to use the tool in a larger enterprise that will grant users access to production resources we need to be able to track who/what/when/where.

**Describe the solution you'd like**
A simple feature would be to have a flag that can be enabled at the user level to enable audit logs.  
The audit log should contain:
Date of the action 
Who they are (username)
Database/connection they ran against
What they ran (DELETE * FROM SOME_COOL_TABLE)

Example

02-03-2021 13:43:23.003 some_username COOL_PROD_Database - DELETE * FROM SOME_COOL_TABLE
02-03-2021 13:45:23.003 some_developer COOL_DEV_Database - DELETE * FROM ANOTHER_COOL_TABLE

An option to output in JSON might be handy or long term auditing

**Comment by serge-rider** [comment]
This makes great sense.

CloudBeaver EE (which will be released soon) keeps all query execution history in the internal embedded database. Just like DBeaver EE does.
We'll add query manager view for query tracking.

**Comment by kseniiaguzeeva** [comment]
The new Query manager has been implemented in the latest Cloudbeaver EE.
