### ISSUE TITLE
Unclear how to turn off / set console logging levels for docker

### ISSUE THREAD

**Issue by AndLut** [dbeaver/cloudbeaver#3020]
With cloudbeaver running as a service in my docker-compose stack, it prints out lots of debug and info statements during runtime. 

As written [here](https://github.com/dbeaver/cloudbeaver/issues/1469) there should now be a config accessible to support a custom logging configuration. 

How would one configure this? I couldn't find documentation regarding this topic anywhere.

**Comment by LonwoLonwo** [comment]
Hello @AndLut 

Yeah, we didn't add it in the documentation, but now we will.

I added a comment in the original issue: https://github.com/dbeaver/cloudbeaver/issues/1469#issuecomment-2431324601

Is it helpful for you?

**Comment by AndLut** [comment]
Yes, perfect!
I was just wondering how it works with the logback.xml, if I can mount it and where.
But as you wrote, just putting it alongside the cloudbeaver.conf solves the problem!
