### ISSUE TITLE
After modifying the Java code and restarting CloudBeaver, the code does not take effect

### ISSUE THREAD

**Issue by cecyLDY** [dbeaver/cloudbeaver#3037]
After modifying the Java code and restarting CloudBeaver, the code does not take effect

How can we make the modified Java code take effect, only by re executing mvn clean verify $MAVEN-COMMON_OPTS Headless platform?

**Comment by EvgeniaBzzz** [comment]
Hi @cecyLDY 
After modifying Java code you should rebuild application.
If you run IDEA/Eclipse you can just build it in the IDE.
Or you can build image using `build.sh`.

**Comment by cecyLDY** [comment]
Thank you

**Comment by cecyLDY** [comment]
Another quession,how to config route?

**Comment by EvgeniaBzzz** [comment]
@cecyLDY Which route do you mean?

**Comment by cecyLDY** [comment]
@EvgeniaBzzz Hello, may I ask how to modify the front-end routing and page? Do you have any examples or materials to refer to

**Comment by EvgeniaBzzz** [comment]
@cecyLDY 
You can set this with `server.rootURI` variable in config file.
Here is [example configuration](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#main-server-configuration).
