### ISSUE TITLE
trino - nanosecond are truncate to millisecond

### ISSUE THREAD

**Issue by raphaelauv** [dbeaver/cloudbeaver#3066]
with trino ( version 462 ) and cloudbeaver ( version 24.2.4 ) 

```sql
select timestamp '2024-11-11 19:40:03.166968'
```

give

![image](https://github.com/user-attachments/assets/43c5f3bd-9de8-4a29-9e14-f43b9269f1c3)

**Comment by EvgeniaBzzz** [comment]
Hi @raphaelauv 
It's a known issue. CloudBeaver can show only 3 digits in milliseconds.
We will add data formats preferences.
Here is the initial request https://github.com/dbeaver/cloudbeaver/issues/2764
