### ISSUE TITLE
Permission denied on Docker run

### ISSUE THREAD

**Issue by tnatssb** [dbeaver/cloudbeaver#308]
Am I missing something basic here?
myusername@azure-demo cloudbeaver]$ sudo docker run --name cloudbeaver --rm -ti -p 8081:8978 -v /home/myusername/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/clo
udbeaver:latest

Starting Cloudbeaver Server
mkdir: cannot create directory ‘workspace/GlobalConfiguration’: Permission denied
An error has occurred. See the log file
/opt/cloudbeaver/server/configuration/1615125180319.log.

[myusername@azure-demo cloudbeaver]$ cat /opt/cloudbeaver/server/configuration/1615125180319.log
cat: /opt/cloudbeaver/server/configuration/1615125180319.log: No such file or directory

**Comment by serge-rider** [comment]
It looks like problem with docker permissions. It can't create shared resource linked with local folder `/home/myusername/cloudbeaver/workspace`. 
Can you create this folder manually?

**Comment by kseniiaguzeeva** [comment]
Here is no responce for a long time. Could you please ask to reopen the ticket if it is stiil actual for you?
