### ISSUE TITLE
Cannot find module？

### ISSUE THREAD

**Issue by cecyLDY** [dbeaver/cloudbeaver#3082]
When I added a plugin directory and recompiled, I got an error: error TS2307: Cannot find module '@cloudbeaver/plugin-new' or its corresponding type declarations.How to add a plugin directory to implement functions？

**Comment by devnaumov** [comment]
Hi @cecyLDY! 

1. Create a `plugin-new` folder inside the `webapp/packages` directory.  
2. Ensure the plugin structure is correct. You will need a `manifest.ts` file to define your plugin. Use an existing plugin as a reference to understand the structure, but remember to update the name in the `package.json` file to match your plugin's name.  
3. Implement the plugin logic. To handle tasks like registering buttons or panels, extend the `Bootstrap` class and implement the `register` method.  
4. Add your plugin to the product by locating the `product-default` folder and including your plugin in the `index.ts` file.  
5. Update the TypeScript references by running the "Update TS References CE" command from the workspace.  
6. Verify that the `register` method is triggered during the product's initialization. This confirms that your plugin is registered correctly.  

If you have any further questions, feel free to ask

**Comment by cecyLDY** [comment]
I have completed the first 4 steps, but the fifth step, Update TS References CE, is not a command. Executing the yarn run bundle command still produces an error message: Cannot find module '@ cloudbeamer/plugin new'. What should I do?

**Comment by devnaumov** [comment]
@cecyLDY Do you have a `.vscode` folder in your project? What code editor you using? If it’s VS Code, try this: **Cmd + Shift + P** → **Tasks: Run Task** or just run `yarn run update-ts-references` from `webapp` directory.

**Comment by cecyLDY** [comment]
@devnaumov Thank you for your reply. I followed the above steps to add plugin new and executed `yarn run update-ts- references`. The information is as follows: 
![err1](https://github.com/user-attachments/assets/6e2c63de-0658-4574-be58-be490b2bf0c8)
![err2](https://github.com/user-attachments/assets/c84012b5-3198-450e-91bc-7b0996c4fd4d)


I don't know where else needs to be configured. If you have any ideas, please reply to me. Thank you

**Comment by devnaumov** [comment]
Can you share a screenshot of your plugin structure and the package.json file?

**Comment by cecyLDY** [comment]
plugin-new is a very simple structure, with the following structure and file content:

**Comment by cecyLDY** [comment]
plugin-new is a very simple structure, with the following structure and file content:
![err3](https://github.com/user-attachments/assets/4db59295-1c28-4cb0-8e3f-5fce6980336a)
![err4](https://github.com/user-attachments/assets/f17155cb-ad54-49b4-8646-961558f636be)
![err5](https://github.com/user-attachments/assets/d7e00dc4-0709-4c4b-890b-fea252bfdea1)
![err6](https://github.com/user-attachments/assets/3ca9121d-9cb4-41ad-b70b-d35380ba704f)
![err7](https://github.com/user-attachments/assets/0a769324-7b24-4040-b013-a2a41f93f2cf)
![err8](https://github.com/user-attachments/assets/a44f075a-fb0b-4c13-873c-8f434fa543e0)
![err9](https://github.com/user-attachments/assets/2a59421a-5dab-4378-80d0-aa59577c0371)
![err10](https://github.com/user-attachments/assets/2c413737-436a-49be-b9ea-2044eb54b554)
![err11](https://github.com/user-attachments/assets/4f772b40-53a4-49bc-906a-fb6c6ab7dcc2)

**Comment by devnaumov** [comment]
@cecyLDY 

Please try adding the following field to your `product-default/src/tsconfig.json` file (references array):

```json
{
    "path": "../plugin-new/tsconfig.json"
}
```

If it doesn't help, try running the `yarn` command inside the `/webapp` directory, and then run `yarn run update-ts-references` again.

**Comment by devnaumov** [comment]
I have written a mini wiki on how to add custom plugins and extend app functionality. Feel free to take a look
https://github.com/dbeaver/cloudbeaver/wiki/Custom-plugin

**Comment by cecyLDY** [comment]
Thanks a lot
