### ISSUE TITLE
Mac reverse selection through keyboard in editor broken

### ISSUE THREAD

**Issue by khludenevav** [dbeaver/cloudbeaver#3083]
**Describe the bug**
On Mac 15.1 (and v14 at least) reverse selection was broken.

**To Reproduce**
Reproduce - write query, press opt+shift+leftArrow is not selecting more than one word. It worked 3 months ago.
opt+shift+rightArrow works fine

**Screenshots**
On video I'm pressing opt+shift+leftArrow and then opt+shift+rightArrow
https://github.com/user-attachments/assets/b5848b03-e360-4d5b-be23-c47eec7a57f2

**Desktop (please complete the following information):**
 - OS: MacOs 15.1
 - Browser chrome
 - Version v130.0

**Additional context**
We updated to 24.2 version and problem still exists.

It is really annoying and brakes all user experience in editing queries.

**Comment by EvgeniaBzzz** [comment]
Hi @khludenevav 
It's a known issue, we're going to fix it in one of the nearest releases.
Thank you for the report!
Sorry for the inconvenience ❤️

**Comment by dariamarutkina** [comment]
Hello @khludenevav  !
You can find a fix in v.24.3.0 💙
We would be grateful if you could share any other issues or concerns that might be bothering you.
Thank you for being with CloudBeaver!
