### ISSUE TITLE
I hope to get the dependency library of cloudbeaver 23.1.0 version

### ISSUE THREAD

**Issue by wangqian-49** [dbeaver/cloudbeaver#3103]
I use dbeaver 23.1.1 and cloudbeaver 23.1.0. When building, I get an error, as shown below. I found that the content in the dependent library (https://p2.dev.dbeaver.com/eclipse-repo) has changed. Can you provide the corresponding version of the dependent library?Thank you very much!
![b6c362f5ee16b2b18da9792c2a08d4df](https://github.com/user-attachments/assets/e61ac2e9-4f70-4e8b-88a9-9acd4ae74fb5)

**Comment by LonwoLonwo** [comment]
Hello @wangqian-49 

Do you have any specific reasons not to update all projects to the latest version and do not have problems with dependencies?

**Comment by wangqian-49** [comment]
Hello @LonwoLonwo
Because I added some specific features, I can't update to the latest version.

**Comment by LonwoLonwo** [comment]
We have the archive of previous versions here: https://dbeaver.io/files/
You can try to find the Jfree bundle in the zip files. 
But it can have other dependencies, and I can't tell you the correct versions.

The better way is to upgrade your code version with your specific features. These two years, we have also added many great features to our products.

**Comment by wangqian-49** [comment]
Ok, I have solved this problem, and Thanks for your help!

**Comment by LonwoLonwo** [comment]
Thank you for your feedback and for your interest in CloudBeaver.
