### ISSUE TITLE
Demo server link in WIKI documentation is broken

### ISSUE THREAD

**Issue by shruti-santosh** [dbeaver/cloudbeaver#3105]
**Describe the bug**
When trying to access the demo server through https://github.com/dbeaver/cloudbeaver/wiki/Demo-Server#demo-server, it gives a bad gateway error

**To Reproduce**
1. Go to Wiki: https://github.com/dbeaver/cloudbeaver/wiki/Demo-Server#demo-server
2. Click the link: https://demo.cloudbeaver.io/

**Screenshots**
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/822753d6-0ea5-4cc9-beb3-53c2f5a113b2">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge
 - Version: 131.0.2903.70

**Comment by dariamarutkina** [comment]
Hello @shruti-santosh !
Thank you very much for the report, we are investigating this issue 💙

**Comment by dariamarutkina** [comment]
@shruti-santosh We fixed the issue 
Thank you for being with CloudBeaver! 💙
