### ISSUE TITLE
<SDK Jetty WebSocket>

### ISSUE THREAD

**Issue by AmorMantra** [dbeaver/cloudbeaver#3135]
I am using the 23-3-1 version of cloudbeaver, and dbeaver is the same version, but now I cannot compile and the build.sh script fails to execute. I can confirm that it can be executed successfully around September 2024, and no local code modifications have been made subsequently. But now I cannot build successfully.
I have troubleshooted the problem and found that it is caused by the jetty socket version.
In this directory: \maven\repository\.cache\tycho, there is a jetty version related to 12.0.12, but my project should use a version related to 11.0.18.

How should I modify the corresponding version information to adjust to the corresponding version

![image](https://github.com/user-attachments/assets/dfa0ffdc-632d-4a51-9fe5-7fe2163f7af3)

![image](https://github.com/user-attachments/assets/33bfd2fe-c2df-4bc6-bad3-2af62cd7e56b)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] dbeaver 1.0.0-SNAPSHOT ............................. SUCCESS [ 0.120 s]
[INFO] bundles 1.0.0-SNAPSHOT ............................. SUCCESS [ 0.009 s]
[INFO] org.jkiss.utils 2.1.204-SNAPSHOT ................... SUCCESS [ 23.568 s]
[INFO] org.jkiss.wmi 2.0.214-SNAPSHOT ..................... SUCCESS [ 2.565 s]
[INFO] plugins 1.0.0-SNAPSHOT ............................. SUCCESS [ 0.160 s]
[INFO] org.jkiss.dbeaver.model 1.1.14-SNAPSHOT ............ SUCCESS [ 20.985 s]
[INFO] org.jkiss.dbeaver.dpi.model 1.0.11-SNAPSHOT ........ SUCCESS [ 3.044 s]
[INFO] org.jkiss.dbeaver.registry 1.0.115-SNAPSHOT ........ SUCCESS [ 6.212 s]
[INFO] org.jkiss.dbeaver.model.ai 1.0.23-SNAPSHOT ......... SUCCESS [ 3.037 s]
[INFO] org.jkiss.dbeaver.model.sm 1.0.28-SNAPSHOT ......... SUCCESS [ 1.713 s]
[INFO] org.jkiss.dbeaver.model.event 1.0.25-SNAPSHOT ...... SUCCESS [ 2.959 s]
[INFO] org.jkiss.dbeaver.model.jdbc 1.0.14-SNAPSHOT ....... SUCCESS [ 3.837 s]
[INFO] org.jkiss.dbeaver.model.nio 1.0.5-SNAPSHOT ......... SUCCESS [ 1.304 s]
[INFO] org.jkiss.dbeaver.model.lsm 1.0.16-SNAPSHOT ........ SUCCESS [ 6.897 s]
[INFO] org.jkiss.dbeaver.model.sql 1.0.111-SNAPSHOT ....... SUCCESS [ 3.373 s]
[INFO] org.jkiss.dbeaver.dpi.app 1.0.11-SNAPSHOT .......... SUCCESS [ 2.431 s]
[INFO] org.jkiss.dbeaver.cmp.simple 6.0.117-SNAPSHOT ...... SUCCESS [ 1.475 s]
[INFO] org.jkiss.dbeaver.erd.model 1.0.81-SNAPSHOT ........ SUCCESS [ 1.796 s]
[INFO] org.jkiss.dbeaver.ext.generic 2.3.207-SNAPSHOT ..... SUCCESS [ 3.212 s]
[INFO] org.jkiss.dbeaver.ext.clickhouse 1.0.126-SNAPSHOT .. SUCCESS [ 2.482 s]
[INFO] org.jkiss.dbeaver.ext.h2 1.0.176-SNAPSHOT .......... SUCCESS [ 1.363 s]
[INFO] org.jkiss.dbeaver.ext.mssql 1.0.215-SNAPSHOT ....... SUCCESS [ 3.372 s]
[INFO] org.jkiss.dbeaver.data.gis 1.0.145-SNAPSHOT ........ SUCCESS [ 1.448 s]
[INFO] org.jkiss.dbeaver.tasks.native 1.0.99-SNAPSHOT ..... SUCCESS [ 1.410 s]
[INFO] org.jkiss.dbeaver.ext.mysql 2.1.206-SNAPSHOT ....... SUCCESS [ 3.785 s]
[INFO] org.jkiss.dbeaver.ext.oracle 2.1.206-SNAPSHOT ...... SUCCESS [ 3.849 s]
[INFO] org.jkiss.dbeaver.ext.postgresql 2.1.194-SNAPSHOT .. SUCCESS [ 5.315 s]
[INFO] org.jkiss.dbeaver.data.transfer 2.0.105-SNAPSHOT ... SUCCESS [ 2.707 s]
[INFO] org.jkiss.dbeaver.data.office 1.1.159-SNAPSHOT ..... SUCCESS [ 1.778 s]
[INFO] org.jkiss.dbeaver.net.ssh 1.0.142-SNAPSHOT ......... SUCCESS [ 1.422 s]
[INFO] org.jkiss.dbeaver.net.ssh.jsch 1.1.131-SNAPSHOT .... SUCCESS [ 1.610 s]
[INFO] org.jkiss.dbeaver.net.ssh.sshj 1.0.142-SNAPSHOT .... SUCCESS [ 1.433 s]
[INFO] org.jkiss.dbeaver.slf4j 2.0.91-SNAPSHOT ............ SUCCESS [ 1.024 s]
[INFO] org.jkiss.dbeaver.team.git 1.0.109-SNAPSHOT ........ SUCCESS [ 0.870 s]
[INFO] org.jkiss.dbeaver.headless 1.0.54-SNAPSHOT ......... SUCCESS [ 1.145 s]
[INFO] org.jkiss.dbeaver.runtime.feature 23.3.1-SNAPSHOT .. SUCCESS [ 1.537 s]
[INFO] org.jkiss.dbeaver.db.feature 1.0.112-SNAPSHOT ...... SUCCESS [ 0.557 s]
[INFO] features 1.0.0-SNAPSHOT ............................ SUCCESS [ 0.005 s]
[INFO] Cloudbeaver 1.0.0-SNAPSHOT ......................... SUCCESS [ 0.012 s]
[INFO] bundles 1.0.0-SNAPSHOT ............................. SUCCESS [ 0.013 s]
[INFO] io.cloudbeaver.model 1.0.43-SNAPSHOT ............... SUCCESS [ 2.609 s]
[INFO] io.cloudbeaver.service.security 1.0.43-SNAPSHOT .... SUCCESS [ 2.143 s]
[INFO] io.cloudbeaver.server 23.3.1-SNAPSHOT .............. FAILURE [ 3.278 s]
[INFO] io.cloudbeaver.slf4j 1.0.3-SNAPSHOT ................ SKIPPED
[INFO] io.cloudbeaver.service.admin 1.0.87-SNAPSHOT ....... SKIPPED
[INFO] io.cloudbeaver.service.auth 1.0.87-SNAPSHOT ........ SKIPPED
[INFO] io.cloudbeaver.service.metadata 1.0.91-SNAPSHOT .... SKIPPED
[INFO] io.cloudbeaver.service.fs 1.0.5-SNAPSHOT ........... SKIPPED
[INFO] io.cloudbeaver.service.rm 1.0.40-SNAPSHOT .......... SKIPPED
[INFO] io.cloudbeaver.service.rm.nio 1.0.5-SNAPSHOT ....... SKIPPED
[INFO] io.cloudbeaver.service.data.transfer 1.0.88-SNAPSHOT SKIPPED
[INFO] io.cloudbeaver.resources.drivers.base 1.0.88-SNAPSHOT SKIPPED
[INFO] io.cloudbeaver.product.ce 23.3.1-SNAPSHOT .......... SKIPPED
[INFO] features 1.0.0-SNAPSHOT ............................ SKIPPED
[INFO] io.cloudbeaver.ws.feature 1.0.41-SNAPSHOT .......... SKIPPED
[INFO] io.cloudbeaver.server.feature 23.3.1-SNAPSHOT ...... SKIPPED
[INFO] io.cloudbeaver.ce.drivers.feature 1.0.111-SNAPSHOT . SKIPPED
[INFO] io.cloudbeaver.product.ce.feature 23.3.1-SNAPSHOT .. SKIPPED
[INFO] drivers 1.0.0 ...................................... SKIPPED
[INFO] drivers.h2 1.0.0 ................................... SKIPPED
[INFO] drivers.h2_v2 1.0.0 ................................ SKIPPED
[INFO] drivers.mysql 1.0.0 ................................ SKIPPED
[INFO] drivers.mariadb 1.0.0 .............................. SKIPPED
[INFO] drivers.oracle 1.0.0 ............................... SKIPPED
[INFO] drivers.postgresql 1.0.0 ........................... SKIPPED
[INFO] drivers.sqlite 1.0.0 ............................... SKIPPED
[INFO] drivers.sqlserver 1.0.0 ............................ SKIPPED
[INFO] drivers.antdb-t-jdbc 1.0.0 ......................... SKIPPED
[INFO] drivers.antdb-m-jdbc 1.0.0 ......................... SKIPPED
[INFO] tests 1.0.0-SNAPSHOT ............................... SKIPPED
[INFO] io.cloudbeaver.test.platform 1.0.0-SNAPSHOT ........ SKIPPED
[INFO] Cloudbeaver Server Product 23.3.1-SNAPSHOT ......... SKIPPED
[INFO] product 1.0.0-SNAPSHOT ............................. SKIPPED
[INFO] CloudBeaver CE Aggregate 1.0.0-SNAPSHOT ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:29 min
[INFO] Finished at: 2024-12-12T11:21:28+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.4:compile (default-compile) on project io.cloudbeaver.server: Compilation failure: Compilation failure:
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\websockets\CBAbstractWebSocket.java:[20]
[ERROR] import org.eclipse.jetty.websocket.api.WebSocketAdapter;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.websocket.api.WebSocketAdapter cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\websockets\CBAbstractWebSocket.java:[27]
[ERROR] public class CBAbstractWebSocket extends WebSocketAdapter {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] WebSocketAdapter cannot be resolved to a type
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\websockets\CBAbstractWebSocket.java:[32]
[ERROR] if (isNotConnected()) {
[ERROR] ^^^^^^^^^^^^^^
[ERROR] The method isNotConnected() is undefined for the type CBAbstractWebSocket
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\websockets\CBAbstractWebSocket.java:[36]
[ERROR] getRemote().sendString(gson.toJson(event));
[ERROR] ^^^^^^^^^
[ERROR] The method getRemote() is undefined for the type CBAbstractWebSocket
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\websockets\CBAbstractWebSocket.java:[47]
[ERROR] var session = getSession();
[ERROR] ^^^^^^^^^^
[ERROR] The method getSession() is undefined for the type CBAbstractWebSocket
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\websockets\CBAbstractWebSocket.java:[50]
[ERROR] getSession().close();
[ERROR] ^^^^^^^^^^
[ERROR] The method getSession() is undefined for the type CBAbstractWebSocket
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[28]
[ERROR] import org.eclipse.jetty.server.session.DefaultSessionCache;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.server.session cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[29]
[ERROR] import org.eclipse.jetty.server.session.DefaultSessionIdManager;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.server.session cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[30]
[ERROR] import org.eclipse.jetty.server.session.FileSessionDataStore;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.server.session cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[31]
[ERROR] import org.eclipse.jetty.server.session.SessionHandler;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.server.session cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[32]
[ERROR] import org.eclipse.jetty.servlet.ErrorPageErrorHandler;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.servlet cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[33]
[ERROR] import org.eclipse.jetty.servlet.ServletContextHandler;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.servlet cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[34]
[ERROR] import org.eclipse.jetty.servlet.ServletHolder;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.servlet cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[35]
[ERROR] import org.eclipse.jetty.servlet.ServletMapping;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.servlet cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[37]
[ERROR] import org.eclipse.jetty.websocket.server.config.JettyWebSocketServletContainerInitializer;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.websocket.server.config cannot be resolved
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[81]
[ERROR] XmlConfiguration sslConfiguration = new XmlConfiguration(new PathResource(sslPath));
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The constructor PathResource(Path) is not visible
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[99]
[ERROR] ServletContextHandler servletContextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);
[ERROR] ^^^^^^^^^^^^^^^^^^^^^
[ERROR] ServletContextHandler cannot be resolved to a type
[ERROR] E:\Project\dbeaver\cloudbeaver-release-dev-02\cloudbeaver\server\bundles\io.cloudbeaver.server\src\io\cloudbeaver\server\jetty\CBJettyServer.java:[99]
[ERROR] ServletContextHandler servletContextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);
[ERROR] ^^^^^^^^^^^^^^^^^^^^^

**Comment by AmorMantra** [comment]
![image](https://github.com/user-attachments/assets/fc8a67ce-a0ea-420d-ad82-35636e3d0277)

According to the configuration of SDK_Jetty_WebSocket.xml, we can see that there is version 11.0.18, but it does not seem to be used when executing the build.sh script.

<component name="libraryTable">
<library name="SDK Jetty WebSocket">
<CLASSES>
<root url="file://$ECLIPSE_PATH$/plugins/org.jkiss.bundle.jetty.websocket_2.0.0/lib" />
</CLASSES>
<JAVADOC />
<SOURCES />
<jarDirectory url="file://$ECLIPSE_PATH$/plugins/org.jkiss.bundle.jetty.websocket_2.0.0/lib" recursive="false" />
</library>
</component>

**Comment by AmorMantra** [comment]
![image](https://github.com/user-attachments/assets/a197a8fa-c680-4130-83b1-60a1aef1c8f5)

I saw the mvn log printed during compilation indicated that I loaded the 12.x version, but I need to change to the 11.x version, how should I do it

**Comment by AmorMantra** [comment]
I have to use this version, please don't tell me to upgrade to the latest version of CloudBeaver or something.

**Comment by EvgeniaBzzz** [comment]
Hi @AmorMantra 
The behavior you described is expected.

You can try to change all p2 links from https://p2.dev.dbeaver.com/eclipse-repo/ to these https://p2.dev.dbeaver.com/eclipse-repo/23.3.0/

**Comment by AmorMantra** [comment]
OK, thank you. I replaced the p2 related download address and solved the problem.

![image](https://github.com/user-attachments/assets/ab313d02-2745-42c1-acc5-d1f246d22483)

**Comment by EvgeniaBzzz** [comment]
Great! Thank you for the update 🦫
