### ISSUE TITLE
Cloudbeaver Community - SAML ?

### ISSUE THREAD

**Issue by dng19059** [dbeaver/cloudbeaver#3147]
Hello

Does Cloudbeaver Community support SAMLv2?
If not, would Cloudbeaver EA version support SAML?

**Comment by EvgeniaBzzz** [comment]
Hi @dng19059 
What is you use case? Do you use any provider?

There is no SAML support in CloudBeaver Community version. But you can try Enterprise version (with [2-week free trial](https://dbeaver.com/download/cloudbeaver/))

**Comment by dng19059** [comment]
my use case is for plug to another idp over samlv2, but ok your answer seems to be clear

**Comment by dng19059** [comment]
thanks @EvgeniaBzzz
