### ISSUE TITLE
No support for HANA DB?

### ISSUE THREAD

**Issue by santosh-hegde** [dbeaver/cloudbeaver#319]
I don't see SAP HANA DB in database list. Its available in desktop client DBeaver.

**Comment by kseniiaguzeeva** [comment]
We are going to add SAP HANA driver to CloudBeaver EE.
While you can do it yourself using this instruction https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers

**Comment by alumni** [comment]
Actually SAP's HANA web ui seems to be based on CloudBeaver, and they have debugging support and everything, it would be nice to see some of those extra features in DBeaver/CloudBeaver too.

**Comment by Akshay-Thakare** [comment]
+1 for this feature

**Comment by kseniiaguzeeva** [comment]
Thank you for the voting. We are going to add SAP HANA support in 21.1.4 release in the beginning of September.

**Comment by kseniiaguzeeva** [comment]
SAP HANA driver has been added to CloudBeaver Enterprise in the latest 21.2.0 release.
