### ISSUE TITLE
Can't edit existing connection details

### ISSUE THREAD

**Issue by ariestikto** [dbeaver/cloudbeaver#326]
How do I edit DB connection once its created? The user interface doesn't allow me to, all inputs are readonly, am I being dumb here?

![image](https://user-images.githubusercontent.com/8805813/113123744-c0fcfc00-920c-11eb-9c01-2cb12576bd02.png)

**Comment by kseniiaguzeeva** [comment]
**Edit connection** allows to edit connections which are created on **the main page** (Connection>Manual/From Template).
![chrome_KdAJfXDh1d](https://user-images.githubusercontent.com/51405061/113124857-a5025600-921e-11eb-9832-f888165df9ea.png)

Connections settings are available in read-only mode for connections, created in **Easy-configuration** or **Administration** menu

**Comment by ariestikto** [comment]
Ah I see, thanks!

Additional question, how to delete those readonly connections? is it not possible via web UI?

**Comment by kseniiaguzeeva** [comment]
You can do it in Settings>Administration>Connection Management.
![chrome_fzCEIOs5QO](https://user-images.githubusercontent.com/51405061/113129283-64590b80-9223-11eb-91c0-464ce5a13d9d.png)

Administration menu is available only for users with **admin** role (It is a user who set CloudBeaver in Easy Configuration or another user who was given admin rights).

**Comment by ariestikto** [comment]
Ah right perfect, thanks!
