### ISSUE TITLE
installed with docker no oracle driver support?

### ISSUE THREAD

**Issue by robinhe87** [dbeaver/cloudbeaver#327]
hello:
I'am first use cloudbeaver,and deploy with some problem. so I intsall use docker now.but that haven't oracle and sql server. the follow image shows my installed driver support! 
![image](https://user-images.githubusercontent.com/37928952/113125192-f0c9f500-9248-11eb-862d-484ecf4f6529.png)

hope your help, thank you!

**Comment by Wroud** [comment]
Hello, we released a new 20.0.6 version, can you try it?

**Comment by robinhe87** [comment]
@Wroud 20.0.6 version can work now,thank you!
