### ISSUE TITLE
run cloudbeaver in eclipse appear error

### ISSUE THREAD

**Issue by robinhe87** [dbeaver/cloudbeaver#331]
I can compile cloudbeaver in eclipse now,but when I run the application the errors has appear follow:

![image](https://user-images.githubusercontent.com/37928952/113291532-beda9080-9325-11eb-9f74-dbfca8658d05.png)

![image](https://user-images.githubusercontent.com/37928952/113291627-df0a4f80-9325-11eb-8524-3881e429161d.png)

now, what can i do to solve the problem?

**Comment by robinhe87** [comment]
this is my cloudbeaver.conf content:

{
    server: {
        serverPort: 8978,

        workspaceLocation: "workspace",
        contentRoot: "web",
        driversLocation: "drivers",

        rootURI: "/",
        serviceURI: "/api/",

        productConfiguration: "conf/product.conf",

        expireSessionAfterPeriod: 1800000,

        develMode: false,

        database: {
            driver="h2_embedded",
            url: "jdbc:h2:${workspace}/.data/cb.h2.dat",

            createDatabase: true,

            initialDataConfiguration: "conf/initial-data.conf",

            pool: {
                minIdleConnections: 4,
                maxIdleConnections: 10,
                maxConnections: 100,
                validationQuery: "SELECT 1"
            }
        }

    },
    app: {
        anonymousAccessEnabled: true,
        authenticationEnabled: true,
        anonymousUserRole: "user",
        supportsCustomConnections: false,

        publicCredentialsSaveEnabled: true,
        adminCredentialsSaveEnabled: true

        /*
        enabledDrivers: [
            "postgresql:postgres-jdbc",
            "mysql:mysql8",
            "mysql:mariaDB",
            "generic:sqlite_jdbc",
            "generic:derby_server",
            "generic:h2_embedded",
            "jaybird:jaybird",
        ]
        */

    }

}

**Comment by serge-rider** [comment]
@robinhe87 it happens because CloudBeaver can't find H2 driver. Which is used as embedded database. It searches for driver in the same location where it searches other database drivers. It can be explicitly defined in property "driversLocation".

The simplest way to solve this problem is to
1. Build CloudBeaver with maven.
2. Copy folder `deploy/drivers` into your Eclipse folder (on the same level where `plugins` folder is).

Thus CloudBeaver will be able to find it.

**Comment by robinhe87** [comment]
@serge-rider I build with errors look like this:
![image](https://user-images.githubusercontent.com/37928952/113374841-b6736b80-93a0-11eb-94ab-c46e45e6aa46.png)
![image](https://user-images.githubusercontent.com/37928952/113374880-c7bc7800-93a0-11eb-92a0-9e2647031a20.png)

My Step Build & Deploy is:
1.install jdk11
2.install maven 3.6.3
3.nodejs、yran、lerna and so on
4. cd cloudbeaver/deploy
5. run build.bat

hope your help!

**Comment by robinhe87** [comment]
@serge-rider now i build now.then copy drivers like below:
![image](https://user-images.githubusercontent.com/37928952/113398701-99a35c00-93d1-11eb-95d0-032e095e02c7.png)
![image](https://user-images.githubusercontent.com/37928952/113398751-a922a500-93d1-11eb-8c33-e8cec370e6f7.png)
but i dosn't work too.
![image](https://user-images.githubusercontent.com/37928952/113398831-cbb4be00-93d1-11eb-8ff0-e4d483586029.png)
