### ISSUE TITLE
Prevent elastic scrolling of whole application on macOS

### ISSUE THREAD

**Issue by pixelspark** [dbeaver/cloudbeaver#345]
**Describe the bug**
On macOS (at least in Edge and Safari) the whole application scrolls when scrolling using the mouse wheel outside a table (e.g. in the tree when it has no scroll bar).

This is easily disabled by setting `overflow: hidden;` on `body` in CSS.

**To Reproduce**
1. Go to the demo instance on a mac
2. Scroll using the mouse wheel in a non-scrollable area

**Screenshots**

![cdb_scroll](https://user-images.githubusercontent.com/181337/114368291-93557280-9b7d-11eb-83f7-f56c698e6f4f.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Edge, Safari
 - Version Edge 89.0.774.63, Safari Versie 14.0.3 (16610.4.3.1.7)

**Additional context**

Love this project!

**Comment by pixelspark** [comment]
Should probably be added here: https://github.com/dbeaver/cloudbeaver/blob/b1911d646fe12807e1300a6eeb0ae5d5e8d80a5d/webapp/packages/core-app/src/Body.tsx#L27

**Comment by kseniiaguzeeva** [comment]
Thank you for the report and the solution. We will try to fix it in some of future releases.

**Comment by kseniiaguzeeva** [comment]
The bug has been fixed in the latest 21.1.1 CB version.
