### ISSUE TITLE
Ability to run SQL Scripts

### ISSUE THREAD

**Issue by marty-streamsets** [dbeaver/cloudbeaver#347]
**Is your feature request related to a problem? Please describe.**
I need to be able to execute a sql script like I can in the client version (alt-x).  I can only see where I can run a single sql command at a time...

**Describe the solution you'd like**
Provide the execute script ability that exists in the client version (alt-x).  I want to highlight the lines of sql I want to execute and then alt-x to run them (or click a button).

**Comment by kseniiaguzeeva** [comment]
Thank you for the feature request. We will think when the function can be implemented

**Comment by ajkq** [comment]
It would be great if functions can be executed from the GUI as well, i.e. when selecting a function, show:
- A text box for every input parameter
- An execute button
- Show function output

Adminer does that quite nicely, including only showing functions the user has execute privileges on.

Database is PostgreSQL 13

**Comment by kseniiaguzeeva** [comment]
Could I ask you to create a new ticket for this feature request? Thank you for the suggestion.

**Comment by kseniiaguzeeva** [comment]
The ability is implemented in 21.1.2 release. We are also going to improve SQL parsing for script execution.
