### ISSUE TITLE
ClickHouse support

### ISSUE THREAD

**Issue by blinkov** [dbeaver/cloudbeaver#36]
**Is your feature request related to a problem? Please describe.**
Unlike desktop dbeaver, the cloud version doesn't support [ClickHouse](https://clickhouse.tech) yet.

**Describe the solution you'd like**
ClickHouse is supported on par with other databases.

**Comment by serge-rider** [comment]
Yeah, I think we should include Clickhouse. Being an open-source database it fits CloudBeaver perfectly.

**Comment by serge-rider** [comment]
Done
