### ISSUE TITLE
Add a button "Change Password" for users

### ISSUE THREAD

**Issue by KyoshinSan** [dbeaver/cloudbeaver#361]
Hello ! Here is my problem. I hope this feature will add soon.

**Is your feature request related to a problem? Please describe.**
If a user want to change his password, he have to call an admin to modify his password. Moreover, the admin will know the user's password...

**Describe the solution you'd like**
Add a button "Change password" in Settings menu to permit users to change their password themself.

**Comment by tati-kru** [comment]
We are going to add this feature in the next major release.

**Comment by padas2** [comment]
Hello.

I also need this feature as I am using cloudbeaver in our production setup.
If nobody is working on this feature currently, I would like to work on this.

Let me know what you think.

**Comment by tati-kru** [comment]
This feature is in development now. It will be available in the version 21.1.0 (release in the middle of July).

**Comment by Wroud** [comment]
the feature has been available since 21.0.4

**Comment by kseniiaguzeeva** [comment]
Implemented.
![chrome_tFT2QQc1Vf](https://user-images.githubusercontent.com/51405061/124468795-3cd58a00-dda2-11eb-9bc4-912d41661b4f.png)
