### ISSUE TITLE
Environment variables and connection setup for Docker?

### ISSUE THREAD

**Issue by robertsearle** [dbeaver/cloudbeaver#366]
I am running `FROM dbeaver/cloudbeaver:21.0.1`

Q1)  How do I bypass "INITIAL SERVER CONFIGURATION" while running in Docker?  I want to specify the cbadmin user name (nice to have) and password (**critical**) as an environment variable or command line setting.   Something like `CB_ADMIN_NAME=cbadmin` and **`CB_ADMIN_PASSWORD=password`**.   If I provide this information, I hope it will **stop the setup wizard and go directly to the main / data explorer page.**

Q2) What does `adminCredentialsSaveEnabled` do within `conf/cloudbeaver.conf` [https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration)

Q3)  Where can I find a list of all Cloud Beaver environment variables? Is there a way to set `supportsCustomConnections` other than inside `conf/cloudbeaver.conf`

Q4) I believe I need to copy two files to force connection setup.  Is there a better way to setup connections automatically within docker? [https://github.com/dbeaver/cloudbeaver/wiki/Configuring-server-datasources](https://github.com/dbeaver/cloudbeaver/wiki/Configuring-server-datasources)
1. `/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/credentials-config.json` Saved user name and password from wizards setup?  _Anyway to pass with environment variables or command line settings?_
2. `/opt/cloudbeaver/conf/initial-data-sources.conf` driver and host setup _without password_

**Comment by yoavo-datricks** [comment]
Hi. Anything new on this? We are also interested in deploying the product in a k8s environment and the things asked/requested above are critical for us.

**Comment by kseniiaguzeeva** [comment]
Q2) it allows to save a password for a connection in the connection settings or when you connect to it in DB Navigator. If you disable this option, you have to enter database credentials when you connect to a database

I will give you an answer for other questions a little later.

**Comment by robertsearle** [comment]
@kseniiaguzeeva Any update?

**Comment by serge-rider** [comment]
All runtime settings can be specified in the file `workspace/.data/.cloudbeaver.runtime.conf`. 
It resides in the workspace (which can be a shared docker volume).
This file has the same structure as `cloudbeaver.conf` file.
We've updated article about supported configuration parameter.

If parameter `serverName` is set in config file then server configuration wizard won't be shown.

Q1. We don't support admin user credentials pre-configuration yet. Please create a feature request for this.

Q2 We've added description of this parameter in https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration

Q3 See answer above

Q4 Yes, just copy configuration files in the `.dbeaver` folder. This config file can be created in DBeaver desktop app or manually.
credentials-config.json keeps passwords in encrypted form. But you can save name/password in plain form directly in `data-sources.json` file (fields "user" and "password" in connection configuration section + field "save-password" must be set to true.

**Comment by OJFord** [comment]
It would be much nicer for K8s & Docker use if a connection could be configured via environment variables.

e.g.:
```
# docker-compose.yml
services:
  app:
    # ...
    environment:
      DATABASE_URL: postgres://local:hunter2@postgres/app

  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: app

  cloudbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - 8978:8978
    environment:
      # if only
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the feature request. We will implement it after 22.+ release

**Comment by kseniiaguzeeva** [comment]
Variables can be set in CloudBeaver configuration files. The description is available in the article [Using environment variables](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#using-environment-variable). 
Please feel free to contact me, if you have any additional questions.

**Comment by chardskarth** [comment]
Hi @kseniiaguzeeva. 

(it may be missing something but...) **I can't understand how configurations (aka `.conf` files) are supposed to read from environment variables**?

I have this `Dockerfile`.

![image](https://github.com/dbeaver/cloudbeaver/assets/26249511/a3878326-6126-4cfb-b2d8-a42842ae864b)

Which is built given this `compose.yml`

![image](https://github.com/dbeaver/cloudbeaver/assets/26249511/8c0cf775-162a-46a0-b225-a1d13842b1b3)

where my `cloudbeaver.conf` file contains this:

![image](https://github.com/dbeaver/cloudbeaver/assets/26249511/41cb25f0-62fe-43ba-8bcb-d56ae52912b2)



But it shows this error when running `docker compose up --build dbeaver)`

![image](https://github.com/dbeaver/cloudbeaver/assets/26249511/a9c4b3f3-0484-4515-b9b9-be043b02e65f)

**Comment by marcospgp** [comment]
just got here from google - indeed also trying to configure cloudbeaver with env vars in my docker compose file so that it would know how to connect to my db on first startup, without needing to go through manual setup. any updates here appreciated as it has been > 3 years since the last comment
