### ISSUE TITLE
How to view Entity Diagrams?

### ISSUE THREAD

**Issue by riccardomessineo** [dbeaver/cloudbeaver#367]
Hello,
  I am struggling to find the entity diagrams visualization.

On the docs, it's pretty straight-forward:
1. Navigate to your connection and open some table or schema
2. Select tab "Diagram" (if the tab is not presented then the object doesn't support diagram presentation)

Unfortunately, I can't view any ER not even on the demo page (https://demo.cloudbeaver.io/#/).
Am I the only one?

**Comment by tati-kru** [comment]
@riccardomessineo ERD is available in CloudBeaver Enterprise version only.

**Comment by riccardomessineo** [comment]
Oh... I see, ok. 
It's a bit odd to me that the only place where it's written (at least, that I found) it's on the homepage.

Thanks for the support @tati-kru

**Comment by tati-kru** [comment]
Perhaps, we need to improve documentation. Thank you for letting us know.

**Comment by marcellodesales** [comment]
Same problem here... It would be awesome if it were available in the open-source verison

**Comment by eduardomrj** [comment]
Alguma possibilidade disso existir um dia?
