### ISSUE TITLE
new JDBC driver addition / drivers directory

### ISSUE THREAD

**Issue by ghost** [dbeaver/cloudbeaver#37]
1. Please clarify what is the purpose of drivers directory?
Because it looks like "plug-and-play" addition of JDBC drivers (like in DBeaver desktop version) is not supported. I've tried to put oracle JDBC under drivers directory and restart cloudbeaver server, but it won't appear in web UI. 

2. By the way, is there a plan to add Oracle support?

**Comment by serge-rider** [comment]
We are working on better driver management, there is a plan to implement this before issue #36 resolve.
Drivers directory is supposed to hold JDBC driver jars after that.

In regards to Oracle - we do not plan to include any commercial/non open-source databases support in the community version.

However we are going to release Enterprise version which, besides extra drivers, will support a set of enterprise-ish features. It is planned on this Summer.

**Comment by allenyu6** [comment]
Can we add a custom jdbc driver? if yes, how?

**Comment by allenyu6** [comment]
I am trying to add a new jdbc data source and it is not currently on the driver list here
![image](https://user-images.githubusercontent.com/43618477/82903392-df300680-9f2e-11ea-8054-5f6957a80e6a.png)

**Comment by allenyu6** [comment]
wondering if anyone has an example?

**Comment by RajanVillalobos** [comment]
I also tried to add a JDBC driver but didn't appear on UI

**Comment by allenyu6** [comment]
could you share your steps about how to do it?

**Comment by allenyu6** [comment]
Do I need to modify the POM and rebuild?

**Comment by serge-rider** [comment]
We will write instruction on drivers configuration in wiki. At the moment this procedure is still under development.
Generally you will need to make a custom server product to add extra drivers.

**Comment by allenyu6** [comment]
any updates on this?

**Comment by serge-rider** [comment]
Please check this article: https://github.com/dbeaver/cloudbeaver/wiki/Driver-managements

**Comment by qianxuanyon** [comment]
Whether to support oracle jdbc driver

**Comment by k-paz** [comment]
> Please check this article: https://github.com/dbeaver/cloudbeaver/wiki/Driver-managements

Hi, I've tried to follow that instruction for adding IBM Db2 (db2jcc4.jar), but it still won't show up in GUI.

**Comment by mencwelp** [comment]
> > Please check this article: https://github.com/dbeaver/cloudbeaver/wiki/Driver-managements
> 
> Hi, I've tried to follow that instruction for adding IBM Db2 (db2jcc4.jar), but it still won't show up in GUI.

I have tried to  add hive driver, 
folder  cloudbeaver/server/drivers/hive/
pom.xml:
<project 
   <modelVersion 4.0.0</modelVersion>
    <artifactId drivers.hive</artifactId>
    <version 1.0.0</version>
    <parent 
        <groupId>io.cloudbeaver</groupId>
        <artifactId>drivers</artifactId>
        <version>1.0.0</version>
        <relativePath>../</relativePath>
    </parent>

    <properties>
        <deps.output.dir>hive</deps.output.dir>
    </properties>

    <dependencies>
        <dependency>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-jdbc</artifactId>
          <classifier>standalone</classifier>
          <version>RELEASE</version>
        </dependency>
    </dependencies>
</project>

and also without any success 
I can compile  everything but I don't have clue what is the  driver ID  
and description like :
/cloudbeaver/server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml   

   <plugin>

    <extension point="org.jkiss.dbeaver.resources">
        <resource name="drivers/clickhouse"/>
        **<resource name="drivers/hive"/>**
        <resource name="drivers/derby"/>
        <resource name="drivers/jaybird"/>
        <resource name="drivers/h2"/>
        <resource name="drivers/mysql/mysql8"/>
        <resource name="drivers/mariadb"/>
        <resource name="drivers/postgresql"/>
        <resource name="drivers/sqlite/xerial"/>
    </extension>

    
    <extension point="org.jkiss.dbeaver.product.bundles">
        **<bundle id="drivers.hive"/>**
        <bundle id="drivers.clickhouse" label="Clickhouse drivers"/>
        <bundle id="drivers.derby" label="Derby drivers"/>
        <bundle id="drivers.firebird" label="Firebird drivers"/>
        <bundle id="drivers.h2" label="H2 drivers"/>
        <bundle id="drivers.mysql" label="MySQL drivers"/>
        <bundle id="drivers.mariadb" label="MariaDB drivers"/>
        <bundle id="drivers.postgresql" label="PostgreSQL drivers"/>
        <bundle id="drivers.sqlite.xerial" label="SQLite drivers"/>

    </extension>

    
    <extension point="io.cloudbeaver.driver">
        <driver id="generic:yandex_clickhouse"/>
        <driver id="generic:derby_server"/>
        <driver id="jaybird:jaybird"/>
        <driver id="generic:h2_embedded"/>
        <driver id="mysql:mysql8"/>
        <driver id="mysql:mariaDB"/>
        <driver id="postgresql:postgres-jdbc"/>
        <driver id="generic:sqlite_jdbc"/>
        **<driver id="hive"/>**
    </extension>
</plugin>

[INFO] io.cloudbeaver.server 1.4.0-SNAPSHOT ............... SUCCESS [  1.010 s]
[INFO] io.cloudbeaver.service.admin 1.0.11-SNAPSHOT ....... SUCCESS [  0.320 s]
[INFO] io.cloudbeaver.service.auth 1.0.11-SNAPSHOT ........ SUCCESS [  0.317 s]
[INFO] io.cloudbeaver.service.metadata 1.0.15-SNAPSHOT .... SUCCESS [  0.210 s]
[INFO] io.cloudbeaver.service.data.transfer 1.0.12-SNAPSHOT SUCCESS [  0.297 s]
[INFO] io.cloudbeaver.resources.drivers.base 1.0.12-SNAPSHOT SUCCESS [  0.068 s]
[INFO] io.cloudbeaver.connect.provider.sample 1.0.15-SNAPSHOT SUCCESS [  0.185 s]
[INFO] io.cloudbeaver.product.ce 1.4.0-SNAPSHOT ........... SUCCESS [  0.163 s]
[INFO] features 1.0.0-SNAPSHOT ............................ SUCCESS [  0.013 s]
[INFO] io.cloudbeaver.server.feature 1.4.0-SNAPSHOT ....... SUCCESS [  0.392 s]
[INFO] io.cloudbeaver.ce.drivers.feature 1.0.35-SNAPSHOT .. SUCCESS [  0.106 s]
[INFO] io.cloudbeaver.sample.feature 1.0.15-SNAPSHOT ...... SUCCESS [  0.097 s]
[INFO] io.cloudbeaver.product.ce.feature 1.4.0-SNAPSHOT ... SUCCESS [  0.215 s]
[INFO] drivers 1.0.0 ...................................... SUCCESS [  0.848 s]
**[INFO] drivers.hive 1.0.0 ................................. SUCCESS [  5.339 s]**
[INFO] drivers.clickhouse 1.0.0 ........................... SUCCESS [  0.612 s]
[INFO] drivers.derby 1.0.0 ................................ SUCCESS [  0.282 s]
[INFO] drivers.h2 1.0.0 ................................... SUCCESS [  0.084 s]
[INFO] drivers.firebird 1.0.0 ............................. SUCCESS [  0.109 s]
[INFO] drivers.mysql 1.0.0 ................................ SUCCESS [  0.093 s]
[INFO] drivers.mariadb 1.0.0 .............................. SUCCESS [  0.070 s]
[INFO] drivers.postgresql 1.0.0 ........................... SUCCESS [  0.505 s]
[INFO] drivers.sqlite 1.0.0 ............................... SUCCESS [  0.127 s]
[INFO] Cloudbeaver Server Product 1.4.0-SNAPSHOT .......... SUCCESS [  7.859 s]
[INFO] Cloudbeaver Provided Sample Product 1.4.0-SNAPSHOT . SUCCESS [  5.408 s]
[INFO] product 1.0.0-SNAPSHOT ............................. SUCCESS [  0.015 s]
[INFO] CloudBeaver CE Aggregate 1.0.0-SNAPSHOT ............ SUCCESS [  0.003 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:32 min
[INFO] Finished at: 2020-10-14T15:10:00Z
[INFO] ------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/33003715/96009677-db971080-0e38-11eb-9c1e-5e000dac7d93.png)

So maybe there is anyone that actually know how to add driver and can help us?

**Comment by sahil30** [comment]
Anyone have added the successful custom driver yet?

**Comment by momiji** [comment]
does it help #259

**Comment by serge-rider** [comment]
See our new article about this: https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers

If something is not clear in it - please ask.
