### ISSUE TITLE
Show output of RAISE statement in Postgresql function

### ISSUE THREAD

**Issue by ajkq** [dbeaver/cloudbeaver#372]
Is it possible to show the output of RAISE statements when executing a Postgresql function?

DBeaver opens the output tab in the top right corner showing the output of RAISE WARNING.

Can the same be added to Cloudbeaver?

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We will implement it.

**Comment by EvgeniaBzzz** [comment]
The Output tab has been implemented in 23.2.1. 
It can be found in the left toolbar of the SQL editor. Open Output tab before execution.
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/3d85d2b4-04c5-47d1-ba4c-471612d0163b)
