### ISSUE TITLE
Support of AWS federated role

### ISSUE THREAD

**Issue by djingoule** [dbeaver/cloudbeaver#377]
Hello ! Here is my problem. I hope this feature will be added soon.

**Is your feature request related to a problem? Please describe.**
I am using AWS adapted CloudBeaver version available in AWS Marketplace. It has promising features that we want to make available for many users in the company. But the login process supports IAM users only through AWS access and secret keys. For security reasons, those credentials are not used in our company. We rather use federated IAM roles based on company Active Directory. 

**Describe the solution you'd like**
Add the possibility for administrator and other users to login through their federated IAM roles. 
I saw that those roles can be used for Dbeaver running locally on a computer. https://dbeaver.com/docs/wiki/AWS-Credentials/

Thanks in advance

**Comment by serge-rider** [comment]
This is one of our primary goals for CB 21.2 version.
We already added AWS SSO and federated authentication in DBeaver EE and now working on the web integration in CloudBeaver.

**Comment by djingoule** [comment]
Thanks for your quick reply. Do you have an approximate release date of that version ? It is a blocking point in the adoption of CloudBeaver EE for AWS.

**Comment by kseniiaguzeeva** [comment]
Federated Authentication for Single Sign-On access is implemented to CloudBeaver Enterprise in the latest 21.2.0 release.
