### ISSUE TITLE
Cannot update not-null array

### ISSUE THREAD

**Issue by ajkq** [dbeaver/cloudbeaver#378]
**Describe the bug**
A not-null array of domain cannot be updated.
When the field is NULL, values can be entered (e.g., `{a,b}`).
After saving the change, the field can no longer be updated unless a different client is used to set it to NULL again.

**To Reproduce**
1.
```
CREATE SCHEMA app;

CREATE DOMAIN app.test AS text;

CREATE TABLE app.tt (
  id integer PRIMARY KEY,
  test app.test ARRAY NULL
);

INSERT INTO app.tt (id, test) VALUES(1, NULL);
```
2. Use cloudbeaver to update field to `{a,b}`
3. Cloudbeaver no longer allows to change field

**Desktop:**
 - OS: macOS 11.4
 - Browser Chrome
 - Version 91

**Desktop:**
 - OS: Windows 10 21H1
 - Browser Edge chromium

**Additional context**
Database: PostgreSQL 13

**Comment by kseniiaguzeeva** [comment]
I cannot create the table from your example. Could you check its DDL?

**Comment by ajkq** [comment]
Cloudbeaver shows the following DDL:
```
-- Drop table

-- DROP TABLE app.tt;

CREATE TABLE app.tt (
	id int4 NOT NULL,
	"test" app."_test" NULL,
	CONSTRAINT tt_pkey PRIMARY KEY (id)
);
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. We will add an option to edit arrays.

**Comment by kseniiaguzeeva** [comment]
Arrays can be edited in [the latest release 21.3.3](https://github.com/dbeaver/cloudbeaver) .
