### ISSUE TITLE
Detect session expiration on data entry

### ISSUE THREAD

**Issue by ajkq** [dbeaver/cloudbeaver#379]
Detect session expiration on data entry, instead of when clicking save.

Currently, if the session expired a user can enter data which then is lost when clicking save triggers the session expired dialog.
Instead it would be great if when clicking a field the software would check the session and dump to expired dialog before the user can enter data.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We will implement it.

**Comment by kseniiaguzeeva** [comment]
The new notification way of  session expiration is available in the latest 21.1.1 CB release. I hope it will cover your needs.
