### ISSUE TITLE
Add dropdown for booleans

### ISSUE THREAD

**Issue by ajkq** [dbeaver/cloudbeaver#381]
Add a dropdown for boolean fields to choose true/false.

Currently it is quite cumbersome to change from false to true for instance, as the entire word needs to be deleted and entered.

**Comment by kseniiaguzeeva** [comment]
Thank you for suggestion. We will make boolean editing easier

**Comment by kseniiaguzeeva** [comment]
Implemented in 21.1.0 release (published 15.07.21).
