### ISSUE TITLE
Add insert/delete

### ISSUE THREAD

**Issue by ajkq** [dbeaver/cloudbeaver#382]
Can we have the ability to add/remove rows?

**Comment by kseniiaguzeeva** [comment]
The option will be added.

**Comment by luchees** [comment]
Can you provide a timeline for when it will be added? 
Is it possible that I can implement this feature myself? 

Would be awesome if that feature is added!

**Comment by kseniiaguzeeva** [comment]
We are going to implement it in 21.1.3 milestone at the end of August. 
Regarding your suggestion, thank you for being ready to help. We are glad to receive pull-requests that will make CloudBeaver more useful tool.

**Comment by kseniiaguzeeva** [comment]
The feature is available in the latest release https://github.com/dbeaver/cloudbeaver/.
