### ISSUE TITLE
Data filtering and sorting does not work in data view for PostgreSQL when field names have upper cased letters

### ISSUE THREAD

**Issue by paudan** [dbeaver/cloudbeaver#386]
I tried to use PostgreSQL connection to a database that contains tables with columns that have field names with uppercase letters (proper case, camel case, etc.). The connection works smoothly but when I try to use data filtering and sorting functionality for the table, an exception is thrown, like: 

```
SQL Error [42703]: ERROR: column "eventdate" does not exist
  Hint: Perhaps you meant to reference the column "tbl.EventDate".
  Position: 48
```

which clearly indicates that column names with upper case letters cannot be handled. This functionality is working properly in DBeaver CE.

**Steps to reproduce the behavior:**
1. Create a PostgreSQL table with columns that have upper-case letters, like:
```
CREATE TABLE"Test" (
	"EventDate" timestamp,
	"User" uuid NULL,
	"NumEntries" int4 NULL,
);
```
2. Open Data view.
3. Try to use filtering on the column "EventDate" (entering a condition, like "EventDate" > '2021-01-01') or just try to perform sorting on one of the columns.
4. See an error, similar to the one described above.

I used a recent version of Docker image pulled from the official repository.

**Comment by kseniiaguzeeva** [comment]
The filter/sorting works correctly in my case. But the issue happens to me when I enter an upper case column name to the filter field and don't add quotes to its name. Could you please send a video or screenshot? It will help me to assess the issue.

**Comment by paudan** [comment]
Actually, I tried to add quotes to filter condition (which worked perfectly all the for the DBeaver CE that I have been using), but it fails on this version of CloudBeaver. The preview is as follows; here I tried to use sorting on the EventDate column, but the same can be observed when entering filter condition, even with double quotes

![Screenshot_20210610_125519](https://user-images.githubusercontent.com/12464974/121505408-7a393880-c9eb-11eb-92ca-564380c7f87f.png)

I'm running Backend version 21.0.2.202105200722 and Frontend version 21.0.2.202105200723, according to Product information.

**Comment by kseniiaguzeeva** [comment]
Could you please upgrade to [the latest release 21.0.3](https://cloudbeaver.io/try-it-now/)? I can reproduce the bug in 21.0.2 but filters work correctly in 21.0.3.
We've added the option to sort and filter data via a table context menu.

Feel free to ask to reopen the ticket if the issue still persists.
![chrome_rkZzNRZHrB](https://user-images.githubusercontent.com/51405061/121680216-f56d1e00-cac1-11eb-838b-956ccdb47b65.png)

**Comment by paudan** [comment]
Great, I can also confirm that it works now 21.0.3
