### ISSUE TITLE
Only 500 tables are shown in navigation tree/table view

### ISSUE THREAD

**Issue by vliska** [dbeaver/cloudbeaver#387]
**Describe the bug**
Connect to database (MSSQL connection), expand it in navigation tree, expand schema - only ~500 tables are shown in the tree (we have > 800)
 and our main tables starts are at the end of an alphabet, so these are not shown at all.

**To Reproduce**
1. Create MSSQL Schema database with > 600 tables
2. Go to 'Navigation tree'
3. Click on 'Database Connection (MSSQL)' & expand the schema with > 500 tables
4. See error - only ~500 tables are shown
5. Doubleclick the schema
6. Switch to "Table" from "Info"
7. See another error - also only ~500 tables are shown in the table

**Screenshots**
![cloudbeaver-bug-screen1](https://user-images.githubusercontent.com/23450695/121497577-e14ef100-c9db-11eb-895d-d35b3e841f0f.png)
![cloudbeaver-bug-screen-2](https://user-images.githubusercontent.com/23450695/121497582-e1e78780-c9db-11eb-9c5f-70d623f95790.png)
![cloudbeaver-bug-screen-3](https://user-images.githubusercontent.com/23450695/121497584-e1e78780-c9db-11eb-9722-77967bfd3138.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, Ubuntu Linux 21.04
 - Browser firefox, chromium, chrome, edge (does not matter)
 - Version firefox 87.0 (32bit), 89.0, chromium 91.0.4472.77 (also does not seem to matter)

**Comment by vliska** [comment]
I found 
cloudbeaver/webapp/packages/core-app/src/CoreSettingsService.ts:18:  'app.navigationTree.childrenLimit': 500
so this seems configurable.

**Comment by vliska** [comment]
product.conf:
`  
    // Product configuration. Customized web application behavior
    // It is in JSONC format
    {
        // Global properties
        core: {
            app: {
                navigationTree: {
                    childrenLimit: 1000
                }
            }
`
... can be configured, closing issue.

**Comment by kseniiaguzeeva** [comment]
It's an expected behaviour for now. DB Navigator has a limit of 500 first objects. It's made to prevent the application from freezing. All tables can be seen in Metadata Editor. 
Please feel free to ask any questions.
