### ISSUE TITLE
can't add a new device to cloudbeaver

### ISSUE THREAD

**Issue by dbms007** [dbeaver/cloudbeaver#391]
as you mentioned in the cloudbeaver setup sequence, 
I try to add my new dbms driver to dbeaver by ui, and get drivers.xml..
and copy the <driver part of drivers.xml into dbeaver/plugins/org.jkiss.dbeaver.ext.generic/plugin.xml

and finally 
build DBeaver desktop app (run mvn clean package in the root folder)

and have errors as follows

[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jkiss.dbeaver:dbeaver:1.0.0-SNAPSHOT (/root/dbeaver/pom.xml) has 1 error 
[ERROR]     Invalid artifact repository: Guice provision errors:
[ERROR]
[ERROR]     1) Error in custom provider, java.lang.TypeNotPresentException: Type org.eclipse.tycho.core.p2.P2ArtifactRepositoryLayout not present 
[ERROR]     at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:2.0.0, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[ERROR]     at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:2.0.0, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[ERROR]     while locating org.apache.maven.artifact.repository.layout.ArtifactRepositoryLayout annotated with @com.google.inject.name.Named(value=p2)
[ERROR]
[ERROR]     1 error: org/eclipse/tycho/core/p2/P2ArtifactRepositoryLayout has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

whoever know this problem,, please guide me asap.. 
thanks for your concern..

**Comment by uslss** [comment]
you can learn [here](https://github.com/dbeaver/cloudbeaver/wiki/Driver-managements) how to add new driver

**Comment by dbms007** [comment]
p{margin-top:0;margin-bottom:0}
    


    oh thanks a lot.. i already solved that problem..
thanks again.. 

--------- 원본 메일 ---------

    
        보낸사람: Dziyana ***@***.***>
        받는사람: dbeaver/cloudbeaver ***@***.***>
        
            참조: dbms007 ***@***.***>, Author ***@***.***>
        
        날짜: 21.06.24 21:10 GMT +0900
        제목: Re: [dbeaver/cloudbeaver] can't add a new device to cloudbeaver (#391)
        
        
    
    
        
you can learn here how to add new driver

**Comment by kseniiaguzeeva** [comment]
Feel free to ask to reopen the ticket if the issue becomes actual for you again.

**Comment by dbms007** [comment]
p{margin-top:0;margin-bottom:0}
    


    thanks Kseniia..
I'v already solved that problem here .. 
thanks again.. 

--------- 원본 메일 ---------

    
        보낸사람: Kseniia ***@***.***>
        받는사람: dbeaver/cloudbeaver ***@***.***>
        
            참조: dbms007 ***@***.***>, Author ***@***.***>
        
        날짜: 21.07.05 22:10 GMT +0900
        제목: Re: [dbeaver/cloudbeaver] can't add a new device to cloudbeaver (#391)
        
        
    
    
        
Closed #391.
