### ISSUE TITLE
SQL Server different auth modes

### ISSUE THREAD

**Issue by hpolonskaya** [dbeaver/cloudbeaver#392]
Hi, I'm trying to connect Cloudbeaver to SQL server with sql server authentication . it's working with DBeaver,
but how to get it work with cloudbeaver. 
Here is snippet what i'm talking about 

<img width="401" alt="Screen Shot 2021-06-16 at 12 10 57 PM" src="https://user-images.githubusercontent.com/12278631/122256095-b9a8ce80-ce9c-11eb-849c-1d40db460a23.png">

**Comment by hpolonskaya** [comment]
any updates?

**Comment by uslss** [comment]
if I understand you right, you can connect to SQL server using SQL Server Authentication by filling in username and password in Authentication block in Connection settings. Could you check it and write back if it works for you.
![image](https://user-images.githubusercontent.com/31996417/122781302-57930380-d2b8-11eb-8273-778902a281ac.png)

Sorry for the late response.

**Comment by hpolonskaya** [comment]
Unfortunately it's not working I'm trying to connect with the  same credentials using DBeaver ,select from authentication dropdown list  -> sql server authentication > connect sucessfull
But clouldbeaver  does not have the same  dropdown  just user/psw
and  as result 
Error connecting to database:
Connection failed:
The connection to the host emdc2sqm102.media.global.loc, named instance db102 failed. Error: "java.net.UnknownHostException: emdc2sqm102.media.global.loc". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
---------

<img width="1208" alt="Screen Shot 2021-06-21 at 11 59 10 AM" src="https://user-images.githubusercontent.com/12278631/122792510-3dd9c800-d288-11eb-802e-4e2566538f03.png">


and Here is dbeaver connection test

<img width="436" alt="Screen Shot 2021-06-21 at 12 01 48 PM" src="https://user-images.githubusercontent.com/12278631/122792846-872a1780-d288-11eb-84fb-16edfe8fabd5.png">

**Comment by hpolonskaya** [comment]
Hi any updates . Look like it's bug in Cloudbeaver UI for MS SQL connection.

**Comment by hpolonskaya** [comment]
any updates on this issue

**Comment by serge-rider** [comment]
It looks like your SQL Server instance is not accessible from the machine where CloudBeaver was deployed (UnknownHostException). Host name cannot be resolved.

You need to consult with your network administrator.

**Comment by hpolonskaya** [comment]
Thank you Serge . it's working one more question.
what about Windows auth mode and the rest which dbeaver is supporting

**Comment by kseniiaguzeeva** [comment]
Regarding your last comment I change your ticket status on a feature request.

**Comment by kseniiaguzeeva** [comment]
SQL Server and NTLM authentication are available in the latest 22.1.0 release.
