### ISSUE TITLE
Language selector doesn't work

### ISSUE THREAD

**Issue by riccardomessineo** [dbeaver/cloudbeaver#404]
**Describe the bug**
Language selector doesn't work

**To Reproduce**
1. Go to the demo page (https://demo.cloudbeaver.io/#/)
2. Click on the gear on top right, than "Language" and pick any

**Additional context**
The interface will refresh, but the language will always be english

**Comment by Wroud** [comment]
only English and Russian languages is supported for UI

**Comment by riccardomessineo** [comment]
Hello,
  any news?

**Comment by kseniiaguzeeva** [comment]
As @Wroud answered above, CloudBeaver supports UI for English and Russian languages for now. When you select another language from the list, English is set by default. Could you please tell what language do you select? Can it be your case?

We will support other languages in the future too.

**Comment by riccardomessineo** [comment]
![image](https://user-images.githubusercontent.com/10194398/124898107-2d8f5000-dfdf-11eb-954b-e03380179fd0.png)

How can you support only Russian and English and the UI shows so many languages? 
I'm trying to set Italian by the way.

**Comment by kseniiaguzeeva** [comment]
I'm sorry, now I see the bug. Metadata objects are not translated in Italian, French and Korean. The issue is actual for DBeaver too. We will fix it. Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
After a little investigation I see that few drivers support Italian translation, such as Derby Server, H2, an old PostgreSQL driver. 
![Screenshot 2021-07-09 at 13 30 46](https://user-images.githubusercontent.com/51405061/125064967-e45ffe80-e0b9-11eb-9879-4c4356650300.png)

The same situation is in DBeaver too. These drivers support Italian, because they are open-source and community members helped us with their translation. We really appreciate their help. 
I will be really glad if someone can help us with translation of other drivers. While the ticket is changed on a feature request.
I hope you will be able to continue to use CloudBeaver and find it useful. Feel free to ask any questions and suggestions.

**Comment by riccardomessineo** [comment]
So.... the language is only connected to the DB drivers?
The "basic" UI is always in English or is it missing the translations? 
I mean labels as "User Connections", "Properties", "Diagram", ...

**Comment by kseniiaguzeeva** [comment]
It is in our plans, but it is difficult to say you an estimated time for it.

**Comment by riccardomessineo** [comment]
Is it possible to help with the Italian translation? How?

**Comment by kseniiaguzeeva** [comment]
It will be really great to receive any help with it. We will prepare an article with a description how to add translation. I will write you as soon as it will be ready. It shouldn't take a lot of time.

**Comment by kseniiaguzeeva** [comment]
We prepared the instruction https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-localization. It describes how to  translate UI items and create pull-requests.
Do not hesitate to ask any questions.

Thank you in advance.

**Comment by riccardomessineo** [comment]
Thanks!
Me or my teammates will surely make a PR soon :)

**Comment by kseniiaguzeeva** [comment]
Looking forward to it).

**Comment by riccardomessineo** [comment]
Here we go :)

**Comment by kseniiaguzeeva** [comment]
Great! Our developers will look into it.

**Comment by kseniiaguzeeva** [comment]
Thank you for your help! The translation will be available in 21.1.3 release 26.08.21
![Screenshot 2021-08-20 at 09 51 24](https://user-images.githubusercontent.com/51405061/130192555-6cffa525-c92c-440e-adf0-dbe7d0bc9c00.png)

**Comment by riccardomessineo** [comment]
Thank you! Can't wait to see it live :)

**Comment by kseniiaguzeeva** [comment]
We finally published 21.1.3 release https://github.com/dbeaver/cloudbeaver/. Thank you one more time.
