### ISSUE TITLE
Admin user and password config using environment variables

### ISSUE THREAD

**Issue by yoavo-datricks** [dbeaver/cloudbeaver#416]
We are working on designing a k8s deployment for cloudbeaver. We are in the process of writing a helm chart to build a proper k8s deployment including options to setup server configuration, add data sources via config maps and secrets, ingress, etc.
However, the basic functionality of configuring the admin user is currently impossible to develop.

What we are about to develop is having the server configured for no authentication and have only data source level authentication. This is fairly secured, however not optimal.

What we wished for is the ability to configure *just* the admin user via environment variables.
For example CD_ADMIN_USER and CB_ADMIN_PASS. This way will be able to initialize the user name and password via a k8s secret and have a secured login process to the product.

WE PLAN TO SHARE THE HELM CHART ONCE COMPLETED.

Thanks,
Yoav

**Comment by kseniiaguzeeva** [comment]
Thank you for your suggestion. We will help you with it.

**Comment by serge-rider** [comment]
@yoavo-datricks Please read this https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#automatic-server-configuration

These parameters can be specified in environment variables or in special config file.

Note: this feature will be included in the next CB release (21.1.1). Or you can build it from sources.

**Comment by yoavo-datricks** [comment]
Great news. looking forward to the version release.
Thanks!

**Comment by kseniiaguzeeva** [comment]
21.1.1 CB release is available.
