### ISSUE TITLE
MySQL 8 document store compatibility?

### ISSUE THREAD

**Issue by binaryfire** [dbeaver/cloudbeaver#423]
Hi guys,

Does Cloudbeaver work with the MySQL 8 document store?

https://www.mysql.com/products/enterprise/document_store.html

Thanks

**Comment by kseniiaguzeeva** [comment]
Thank you for your interest in CloudBeaver. We do not support this driver for now. But CloudBeaver Enterprise Edition has other different no-SQL databases and includes JSON data viewer. You can [get a trial license](https://cloudbeaver.io/trial/) and try it for free.

**Comment by binaryfire** [comment]
@kseniiaguzeeva Thanks Kseniia. Unfortunately changing databases isn't an option for us.

Does the MySQL driver support the standard JSON data type columns? https://dev.mysql.com/doc/refman/8.0/en/json.html

They've been available in MySQL since v5.7

**Comment by kseniiaguzeeva** [comment]
Yes, it is available in CE version too. You can edit JSON value directly in a cell or in the Value panel.

![chrome_AOUlaODsh5](https://user-images.githubusercontent.com/51405061/126746589-b8d1d184-ef4c-478a-a1df-6c377687f856.png)

Don't hesitate to ask any other questions.

**Comment by kseniiaguzeeva** [comment]
There is no update in the ticket during the long time. Please feel free to ask to reopen the ticket if it is still actual for you.
