### ISSUE TITLE
Not able to add connection to ClickHouse in 21.1.0

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/cloudbeaver#424]
ClickHouse is missing from the driver list, because it's disabled by default. `driverId` below is `clickhouse:yandex_clickhouse` but it should be `generic:yandex_clickhouse` according to [this](../blob/cb_release_21_1_0/server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml#L43):
https://github.com/dbeaver/cloudbeaver/blob/7141494dbe20a5e19d975099972e7fe9ad601ebf/server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/registry/WebDriverRegistry.java#L66

As a workaround, I replaced `generic` to `clickhouse`:
https://github.com/dbeaver/cloudbeaver/blob/7141494dbe20a5e19d975099972e7fe9ad601ebf/server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml#L43

**Comment by serge-rider** [comment]
Thank you for the fix. Configuration was broken after we added Clickhouse extension in DBeaver platform (this extension replaces generic driver).
