### ISSUE TITLE
Retreive lost webapp login credentials

### ISSUE THREAD

**Issue by AlexKalopsia** [dbeaver/cloudbeaver#426]
Hi,

I haven't used cloudbeaver in a while and I lost my webapp login credentials. I am struggling to understand how I can retrieve or reset them.

I am using the docker container `dbeaver/cloudbeaver:latest`

**Comment by kseniiaguzeeva** [comment]
Sorry for the long responce. In this case you should set admin credentials again in easy-configuration. Could you please remove files .cloudbeaver.conf and .cloudbeaver.runtime.conf if exists from workspace/.data/, restart container and go through easy-config again?
https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration

**Comment by kseniiaguzeeva** [comment]
Please feel free to ask any other questions
