### ISSUE TITLE
clickhouse driver is missing

### ISSUE THREAD

**Issue by einavdaniel** [dbeaver/cloudbeaver#428]
**Describe the bug**
Clickhouse driver not listed in drivers dropdown, using docker image dbeaver/cloudbeaver:21.1.0

1. Select Database connections in left menu
2. Click Add
3. Clickhouse driver not listed

**Desktop**
 - OS: widnows10
 - Browser chrome
 - Version 91.0.4472.124

listing drivers directory /opt/cloudbeaver/drivers shows clickhouse jars exist, Yet can't be found in web dropdown list

**Comment by tati-kru** [comment]
Thank you for the bug report. This bug was fixed in the version 21.1.1. The updated docker file will be available early next week.
