### ISSUE TITLE
Allow Xms and Xmx change via environment variable

### ISSUE THREAD

**Issue by tdelattreDecath** [dbeaver/cloudbeaver#429]
Hello everyone,

A few days ago I encountered OOM issues on a CloudBeaver container:
```
HttpChannel:qtp1766122814-254: /api/gql
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
```
To resolve the issue I tried to change the Xms and Xmx values, but I noticed the Xmx value is hardcoded in the run-server.sh file: 
```bash
#!/bin/bash

launcherJar=( server/plugins/org.eclipse.equinox.launcher*.jar )

echo "Starting Cloudbeaver Server"

[ ! -d "workspace/.metadata" ] && mkdir -p workspace/GlobalConfiguration/.dbeaver && cp conf/initial-data-sources.conf workspace/GlobalConfiguration/.dbeaver/data-sources.json

java -jar ${launcherJar} -product io.cloudbeaver.product.ce.product -web-config conf/cloudbeaver.conf -nl en -registryMultiLanguage -vmargs -Xmx2048M
```

Would it be possible to allow changing Xmx and Xms values from an JAVA_OPTS environment variable ?
for example: JAVA_OPTS=-Xms256m -Xmx512m

Thanks

**Comment by kseniiaguzeeva** [comment]
Thank you for your feature request and interest in CloudBeaver. We are going to add variables in release 21.1.4 at the beginning of September.

**Comment by kseniiaguzeeva** [comment]
The variables can be set in [the latest release 21.3.3](https://github.com/dbeaver/cloudbeaver). Here is the example:
`docker run  --name cloudbeaver --rm -ti -p 8080:8978 -e JAVA_OPTS=" -Xms2048m -Xmx2048m" -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:latest`
