### ISSUE TITLE
IE11 not work

### ISSUE THREAD

**Issue by robinhe87** [dbeaver/cloudbeaver#430]
when i open cloudbeaver with ie11 occur error:
![image](https://user-images.githubusercontent.com/37928952/127247777-3477dec6-7532-4e46-8a42-1512f0e335ad.png)
![image](https://user-images.githubusercontent.com/37928952/127247801-0f3c35ec-fa4d-4cee-b85a-dcfa522d0d42.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by kseniiaguzeeva** [comment]
Internet Explorer isn't supported anymore https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-end-of-support.
In any case thank you for your interest in CloudBeaver. Do not hesitate to ask any other questions.
