### ISSUE TITLE
Teradata connect error

### ISSUE THREAD

**Issue by wang-guanyi** [dbeaver/cloudbeaver#431]
I enabled the teradata in db list and built the cloudbeaver successfully. But when tried to connect, I got error message below
'{' ('7B'X) is not a valid Teradata SQL token. 

![IMG_20210802_144241.jpg](https://user-images.githubusercontent.com/88269662/127815576-9ae6eeae-7e7a-4f4c-980e-9d8fc46f8c0c.jpg)

**Comment by kseniiaguzeeva** [comment]
It is a problem with driver version https://support.teradata.com/community?id=community_question&sys_id=c275876b1b57fb00682ca8233a4bcb33 according Teradata documentation. Could you please try to correct the connection configuration?

**Comment by wang-guanyi** [comment]
> It is a problem with driver version https://support.teradata.com/community?id=community_question&sys_id=c275876b1b57fb00682ca8233a4bcb33 according Teradata documentation. Could you please try to correct the connection configuration?
> 

I tried the latest version (17.10.00.18) of teradata jdbc driver and got the same error. The same version is working fine with DBeaver.

**Comment by kseniiaguzeeva** [comment]
We are going to add Teradata driver to CB EE in 21.1.4 milestone, test it and make a fix, if it is on our side. Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
Teradata driver has been added to CloudBeaver Enterprise in the latest 21.2.0 release. It should work now.

**Comment by wang-guanyi** [comment]
I tried the community edition 21.2.0 version and still got the same error. Is it only supported in enterprise edition?

**Comment by kseniiaguzeeva** [comment]
Could you please tell me the details of your driver and server? It looks like the problem is in their compatibility.

**Comment by wang-guanyi** [comment]
Hi Kseniia, please find the versions as below. The driver is working fine in DBeaver CE 21.1.1, but using same driver to connect to same db server in cloudbeaver CE 21.2.0 is not working. 

![IMG_20211022_174816.jpg](https://user-images.githubusercontent.com/88269662/138434534-07b6c456-17c9-4c30-8351-3bf3f0384064.jpg)

![IMG_20211022_175153.jpg](https://user-images.githubusercontent.com/88269662/138434576-9af18fc5-cf6d-4d4f-9525-7cc49d513968.jpg)

**Comment by kseniiaguzeeva** [comment]
Thank you for the additional info. I'll inform you as soon as the reason will be found and fixed.

**Comment by kseniiaguzeeva** [comment]
I managed to reproduce the error, when I did not fill database field in the connection parameters. Could you please try to  fill it?
![Screenshot 2021-11-08 at 17 10 30](https://user-images.githubusercontent.com/51405061/140756722-a7840158-c158-4bb8-bf2a-cf70661b934f.png)

**Comment by wang-guanyi** [comment]
Hi Kseniia, it works after I fill the database. Thank you very much for your help.

**Comment by kseniiaguzeeva** [comment]
I'm glad to hear, that it works properly now. I close the ticket in this case. Please feel free to ask any other questions.
