### ISSUE TITLE
Change workspace location?

### ISSUE THREAD

**Issue by ericsgagnon** [dbeaver/cloudbeaver#434]
I'm making a container with cloudbeaver by copying /opt/cloudbeaver from the official image and am trying to move the workspace to $XDG_DATA_HOME/cloudbeaver as /home will be a volume. 

How can I change the workspace location? The only way I see to change the workspace is by modifying workspaceLocation in the server configuration file (/opt/cloudbeaver/conf/cloudbeaver.conf in the container). Is there a way to change workspace location without editing this file? I can do it with sed, but it's starting to feel hacky. I know I can override cloudbeaver.conf with (workspacelocation)/.data/.cloudbeaver.runtime.conf, but obviously I can't change the workspacelocation this way.

Thank you,
Eric

**Comment by kseniiaguzeeva** [comment]
If I understand you correctly, you do not use our official container. Could I ask you to give me more details why this way of working with CloudBeaver has been chosen? It can help me to give better assistance to you with the situation. 
While I can advise you to use our official container https://hub.docker.com/r/dbeaver/cloudbeaver and write home directory for config files when you run the container: `-v local_path:/opt/cloudbeaver/workspace`. Here is [instruction](https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container)

Please do not hesitate to ask any questions.

**Comment by ericsgagnon** [comment]
@kseniiaguzeeva 
We're using the official container as the source for cloudbeaver, but we're using multiple ide's in a single image (code-server, rstudio, jupyter, etc.) where each user gets a container. This allows us to update all of our tools and add/try new ones and make them immediately available to users.

**Comment by ericsgagnon** [comment]
I'm also running into an issue where some systems use the workspaceLocation and some appear to ignore it. Specifically, the url for the embedded h2 db is url: "jdbc:h2:${workspace}/.data/cb.h2.dat". But I also see .metadata and .work-data directories being created/used in /opt/cloudbeaver/workspace.

I've tested a symlink between /opt/cloudbeaver/workspace and $XDG_DATA_HOME/cloudbeaver and it looks like it's working so far. I will attempt to use this for now.

**Comment by kseniiaguzeeva** [comment]
Looks like it is the only available way now. 
Do not hesitate to ask any  other question and thank you for your interest in CloudBeaver.

**Comment by kseniiaguzeeva** [comment]
Please feel free to ask to reopen the ticket if it is still actual for you.
