### ISSUE TITLE
Auto Configure Issues

### ISSUE THREAD

**Issue by ericsgagnon** [dbeaver/cloudbeaver#437]
Several issues/questions about auto-configure as per https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#automatic-server-configuration.  

- pre-populating server.serverName in .cloudbeaver.runtime.conf appears to prevent proper initialization, causing the server to ignore environment variables (CB_SERVER_NAME, CB_SERVER_URL, CB_ADMIN_NAME, CB_ADMIN_PASSWORD). The result is that you can't login.
  - reproduce by providing workspace/.data/.cloudbeaver.runtime.conf with server.serverName populated and the aut-config environment variables.

- .cloudbeaver.auto.conf's exact syntax is unclear: should it be
```
{
  server: {
    name: "name",
    url: "url"
  },
  admin: {
    name: "admin',
    password: "password"
  }
}
``` 

or is it 

```
{
  serverName: "name",
  serverURL: "url",
  adminName: "admin",
  adminPassword: "password"
}
```

or something else?

**Comment by serge-rider** [comment]
@ericsgagnon 
`.cloudbeaver.auto.conf` file supposed to be in properties format.
Like this:
```
CB_SERVER_NAME = server name
CB_ADMIN_NAME= cb-admin
CB_ADMIN_PASSWORD = cb password
...
```
This file can be deleted after CloudBeaver first start.

**Comment by kseniiaguzeeva** [comment]
The first point looks like a bug. Thank you for the report.

**Comment by ericsgagnon** [comment]
Thank you for the responses!

Is it possible to completely disable auth? My container is designed to use caddy to reverse proxy. Each user gets their own container with multiple ide's (code-server, rstudio, cloudbeaver, pgadmin, etc.). Since each user has to sign in using oidc already, the additional login seems clunky.

Thank you,
Eric

**Comment by kseniiaguzeeva** [comment]
You can enable anonymous access in Administration. If you also disable Local, login option will disappear from Settings menu and only admin will be able to login by adding `admin` to URL in a browser.
![1](https://user-images.githubusercontent.com/51405061/129353292-721894d8-69f8-4f8d-9574-46cfa6b76291.png)

In order to anonymous users can see the existed connections, give access to user role in conection settings.
![2](https://user-images.githubusercontent.com/51405061/129353721-0210aef5-aeb4-41d2-93da-6672c4544bb2.png)

**Comment by kseniiaguzeeva** [comment]
I will appreciate your feedback whether your issues have been solved.

**Comment by ericsgagnon** [comment]
My apologies. I can disable the authentication, but it doesn't seem to persist connections from anonymous users. For now, I'm just using a dummy username/password credential.

**Comment by kseniiaguzeeva** [comment]
When you create a new connection in Administration menu, give access to User role to it. The connection will be available for anonymous users too in this case. 
![Screenshot 2021-09-09 at 10 11 52](https://user-images.githubusercontent.com/51405061/132640151-dc2f6fe8-6968-491d-aec6-d407f722f9ff.png)
![Screenshot 2021-09-09 at 10 17 11](https://user-images.githubusercontent.com/51405061/132640530-8c8606de-1c07-46da-ae8d-f6454e56ec19.png)

Please feel free to ask any other questions.

**Comment by MJLHThomassenHadrian** [comment]
I'm running Cloudbeaver versions:

Backend version
23.1.1.202306260905
Frontend version
23.1.1.202306260910

And am still getting the issue the OP described in their first bullet point:

pre-populating server.serverName in .cloudbeaver.runtime.conf appears to prevent proper initialization, causing the server to ignore environment variables (CB_SERVER_NAME, CB_SERVER_URL, CB_ADMIN_NAME, CB_ADMIN_PASSWORD). The result is that you can't login.

Is this going to be fixed or atleast documented somewhere? Took me half an hour to figure out this was the issue before i hit this github thread.

**Comment by corpulent** [comment]
@ericsgagnon Can you share how you where able to disable the login and the welcome screen?

**Comment by EvgeniaBzzz** [comment]
@corpulent 
Here is a wiki page about [skipping initial configuration](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#automatic-server-configuration).
And [this topic](https://github.com/dbeaver/cloudbeaver/issues/1902#issuecomment-1944121429) may also help you.

**Comment by corpulent** [comment]
@EvgeniaBzzz thanks, I was able to get the experience with the below configs. I already have an internal k8s secure proxy to the dbeaver pod, so I just needed to open up the entire thing (dbeaver) without any logins. My databases are externally managed so I mount the data-sources.json file which gets constantly updated, but I always need to restart the dbeaver container in order to get the updated db list in the UI. I might have to use a custom container to wrap dbeaver and manage the java process manually.

```
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8978:8978"
    volumes:
      - ./srv/db:/srv/db
      - ./srv/databases:/srv/databases

      - ./srv/configs/.cloudbeaver.runtime.conf:/opt/cloudbeaver/workspace/.data/.cloudbeaver.runtime.conf
      - ./srv/configs/GlobalConfiguration/.dbeaver/data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    environment:
      DEBUG: "false"

      CB_SERVER_PORT: 8978
      CB_SERVER_PUBLIC_URL: "http://localhost:8978"

      CLOUDBEAVER_APP_GRANT_CONNECTIONS_ACCESS_TO_ANONYMOUS_TEAM: "true"
```

**Comment by winstxnhdw** [comment]
Why is this so frustrating to do? 

```yaml
  cloudbeaver:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    init: true
    ports: [8978:8978]
    volumes: [./steward/database/.cloudbeaver.auto.conf:/opt/cloudbeaver/workspace/.data/.cloudbeaver.auto.conf]
    environment:
      CLOUDBEAVER_APP_GRANT_CONNECTIONS_ACCESS_TO_ANONYMOUS_TEAM: true
      CLOUDBEAVER_DB_DRIVER: postgres-jdbc
      CLOUDBEAVER_DB_URL: jdbc:postgresql://postgres:5432/development
      CLOUDBEAVER_DB_USER: postgres
```

This still doesn't work even though `.cloudbeaver.auto.conf` has all four required variables.

```bash
CB_SERVER_NAME="cloudbeaver"
CB_SERVER_URL="http://localhost:8978"
CB_ADMIN_NAME="techat"
CB_ADMIN_PASSWORD="Password1"
```

```bash
cloudbeaver    | 07-04-2025 13:13:30.264 [main] DEBUG i.c.service.security.db.CBDatabase -      Management database connection established
cloudbeaver    | 07-04-2025 13:13:30.265 [main] INFO  io.cloudbeaver.server.CBApplication - No auto configuration was found. Server must be configured manually
```

Can we just rely on environment variables for this setup please?

**Comment by EvgeniaBzzz** [comment]
@winstxnhdw Please place `cloudbeaver.auto.conf` in the same folder as `cloudbeaver.conf`.

If you're using Docker Compose, you can move these four variables from `.cloudbeaver.auto.conf` directly into the `docker-compose.yml` file.

**Comment by winstxnhdw** [comment]
Doesn’t work. The configuration page still appears when I spin CloudBeaver up.

**Comment by EvgeniaBzzz** [comment]
This configuration just worked for me.
```
services:
  cloudbeaver:
    build: .
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8978:8978
    volumes:
      - ./logs:/opt/cloudbeaver/logs
      - ./workspace-skip:/opt/cloudbeaver/workspace
    environment:
      - CB_SERVER_NAME=cloudbeaver
      - CB_SERVER_URL=http://localhost:8978
      - CB_ADMIN_NAME=techat
      - CB_ADMIN_PASSWORD=Password1

**Comment by winstxnhdw** [comment]
Ah, I left the `CB_ADMIN_NAME` as `admin`, which is apparently invalid. Finally got it working.
