### ISSUE TITLE
Is Hadoop Hive Supported 

### ISSUE THREAD

**Issue by adityasirohi-philips** [dbeaver/cloudbeaver#440]
Hi, 

Is there support for Hadoop Hive in cloudbeaver?

Thanks, 
Adi

**Comment by kseniiaguzeeva** [comment]
Enterprise Edition supports it or you can configure it manually https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers.

**Comment by adityasirohi-philips** [comment]
Hi, 

@kseniiaguzeeva : Thank you.

I followed the link above to add a custom driver for Hive. 
I could see my generic Hive driver into DBeaver client after build.
But i still don't see the generic HIVE driver on the Cloud Beaver. 

How are the artifacts in DBeaver and Cloud Beaver linked? What i may be missing in the below files?

Here is the DBeaver plugin.xml file. You can look into driver id="62E548A5-844D-5A89-5095-A1E94F57EE3F".
[DBeaverPlugin.txt](https://github.com/dbeaver/cloudbeaver/files/7009899/DBeaverPlugin.txt)

Here is the Cloud Beaver plugin.xml. 
[CloudBeaverPlugin.txt](https://github.com/dbeaver/cloudbeaver/files/7009911/CloudBeaverPlugin.txt)

**Comment by kseniiaguzeeva** [comment]
The driver is available in Enterprise Edition only.

**Comment by adityasirohi-philips** [comment]
Okay. Thank you.
