### ISSUE TITLE
More accurate date display

### ISSUE THREAD

**Issue by simsicon** [dbeaver/cloudbeaver#447]
Hi, CloudBeaver handles Postgresql date type, maybe other database date type as well I did not test, as datetime to display, which could be confusing, really looking forward to fixing it, thanks.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
The bug have been fixed in the latest release https://github.com/dbeaver/cloudbeaver/

**Comment by simsicon** [comment]
Thanks for the great response.
