### ISSUE TITLE
Type error : Loading chunk 9491 failed.

### ISSUE THREAD

**Issue by Geronium** [dbeaver/cloudbeaver#448]
Hello, 

**to reproduce** 

open a table as user or anonymous 

**Error** 

 i got this errors when i load a table, or i make a request

"expected expression, got '='"

"Can't load resource
Loading chunk 9491 failed.
(missing: http://mysite/cloudbeaver/9491.b76f903566e82527e0e8.bundle.js)"

**Desktop please complete the following information** 

OS : Ubuntu 18.04.5 LTS
Browser :  firefox 
Version : 78.11.0esr

**Comment by Geronium** [comment]
I can open the table with edge navigator, but i can't with firefox 78.11.0esr 

Thank you

**Comment by kseniiaguzeeva** [comment]
Which database driver do you use? Could you please tell me exact steps to reproduce?

**Comment by Geronium** [comment]
Hello,

i tried with oracle or postgres. 

When i open a table or do a select request, a popup appears with this errors ( you can see the result of the debugger), i don't have this erros with edge navigator.

the steps to reproduce 

open the database
open schemas
open Tables
and double click on a table

![errorcloudbeaver](https://user-images.githubusercontent.com/73563389/130238189-ef6b388f-28e2-4369-be61-690ae0478904.png)

**Comment by Geronium** [comment]
I tried with 

edge : no error
chronium : no error
firefox 92.0b6 : no error
firefox 78.11.0esr : error 
firefox 78.13.0esr : error

https://ftp.mozilla.org/pub/firefox/releases/78.13.0esr/linux-x86_64/fr/

Thanks

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. I reproduced it.

**Comment by Geronium** [comment]
Thank you again.

**Comment by kseniiaguzeeva** [comment]
The bug have been fixed in the latest release https://github.com/dbeaver/cloudbeaver/
