### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by thomasvvugt** [dbeaver/cloudbeaver#451]
**Is your feature request related to a problem? Please describe.**
I installed CloudBeaver on my machine today, and I noticed it does not currently support MongoDB. Do you have any plans for adding this feature?

**Describe the solution you'd like**
Just like MariaDB, Postgres and SQLite a connector for MongoDB in the Connection Management.

**Comment by kseniiaguzeeva** [comment]
CloudBeaver[ Enterprise](https://cloudbeaver.io/try-it-now/) already supports MongoDB. But you can add it manually to Community version too. This is the [instruction](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers).
