### ISSUE TITLE
installation issue with cloudbeaver

### ISSUE THREAD

**Issue by kcksmart** [dbeaver/cloudbeaver#452]
getting unable to connect error upon checking (https://dbeaver.io/eclipse-repo/p2.index)  this link in not found can some one guide me with this 

![image](https://user-images.githubusercontent.com/60355329/130433224-d93164e6-52e4-4335-aedf-67a0140e9927.png)

![image](https://user-images.githubusercontent.com/60355329/130433460-702c1b9f-7225-4c63-89ef-60e37897c421.png)

**Comment by kseniiaguzeeva** [comment]
Could you please describe your case in details and give steps to reproduce? It will allow me to assess the issue and help to solve it.

**Comment by kcksmart** [comment]
i am trying to install cloudbeaver in my linux system but getting struck at above step, i have added the https://dbeaver.io/eclipse-repo link to the proxywhitelisiting but whe i open the link  **https://dbeaver.io/eclipse-repo/p2.index** link in chrome it is throwing "not found " error.

**Comment by serge-rider** [comment]
@kcksmart What exactly command do you execute? Why do you need p2.index?

**Comment by kcksmart** [comment]
@serge-rider 
 don't need that p2.index but its running when I start the build.sh , 
actully the installation is not getting completed, let me attach the complete steps for better understanding of the issue 

![image](https://user-images.githubusercontent.com/60355329/130439050-3893b2b1-97e0-4d80-a375-78ed86b3db57.png)

![image](https://user-images.githubusercontent.com/60355329/130439340-bb0473e7-dc7e-44f9-a19d-e6448afd8445.png)

![image](https://user-images.githubusercontent.com/60355329/130439416-09565b58-e524-44dd-a746-0ad2d68823be.png)

![image](https://user-images.githubusercontent.com/60355329/130439461-9b932220-3ad3-46cf-9128-8e3d959ad3ec.png)

![image](https://user-images.githubusercontent.com/60355329/130439554-4645a9eb-c08a-4218-a096-31ff123cf383.png)

**Comment by Geronium** [comment]
i did the installation with a dockerfile and behind a proxy, and for that i had to create inside the home directory a ".m2" folder, and inside the ".m2" folder a file "settings.xml" with this content (replace myipproxy with your ip proxy, and myportproxy with your proxy port) to give the proxy parameters to nodejs   :

```
<settings>
<proxies>
    <proxy>
        <id>httpproxy</id>
        <active>true</active>
        <protocol>http</protocol>
        <host>myipproxy</host>
        <port>myportproxy</port>
        <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
    </proxy>
<proxy>
        <id>httpsproxy</id>
        <active>true</active>
        <protocol>https</protocol>
        <host>myipproxy</host>
        <port>myportproxy</port>
        <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
    </proxy>

</proxies>
</settings>
```


Maybe you have to do the same thing.

**Comment by serge-rider** [comment]
@kcksmart You seems to be behind a proxy. In order to build cloudbeaver from sources you have to have internet access to dbeaver.io website (as well as to some other websites like eclipse.org and maven central). 
You could configure proxy server in maven settings (see @Geronium comment above).

**Comment by kseniiaguzeeva** [comment]
Please feel free to ask to reopen the ticket if it is still actual for you.
