### ISSUE TITLE
Insert, update and delete statements for a table as DBeaver

### ISSUE THREAD

**Issue by yoavo-datricks** [dbeaver/cloudbeaver#458]
**Is your feature request related to a problem? Please describe.**
Unable to generate Insert, update and delete statements for a table as DBeaver.

**Describe the solution you'd like**
The small menu next to a table will allow to generate Insert, update and delete statements in the clipboard or new query tab.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We are going to implement it in 21.1.5 release.

**Comment by kseniiaguzeeva** [comment]
The feature is implemented and available in the latest release 21.1.5 https://github.com/dbeaver/cloudbeaver.
