### ISSUE TITLE
Commit / Rollback for Inserts / Updates DML

### ISSUE THREAD

**Issue by hugorn** [dbeaver/cloudbeaver#463]
**Is your feature request related to a problem? Please describe.**
No option in GUI for Commit / Rollback for Inserts / Updates DML

**Describe the solution you'd like**
Create the option like dbeaver
![image](https://user-images.githubusercontent.com/9035153/131722132-a2accba3-c697-45fe-919c-c71b46da5c06.png)

**Comment by kseniiaguzeeva** [comment]
The feature is in our plans, but I do not know the date of its implementation yet. It definitely will be after 21.2.0 release. 
Thank for the suggestion.

**Comment by kseniiaguzeeva** [comment]
We already have the similar ticket. Closed as a duplicate of https://github.com/dbeaver/cloudbeaver/issues/129
