### ISSUE TITLE
MongoDB and CacheDB (Intersystems) support

### ISSUE THREAD

**Issue by sheva7-zb** [dbeaver/cloudbeaver#468]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by kseniiaguzeeva** [comment]
MongoDB is already supported in Enterprise Edition. You can try it for free https://cloudbeaver.io/trial/.
Could you please send me a link of cache DB to look into it?

**Comment by sheva7-zb** [comment]
cacheDB： https://www.intersystems.com/products/cache/

**Comment by sheva7-zb** [comment]
cacheDB  is already supported in  dbeaver

**Comment by kseniiaguzeeva** [comment]
No, we are not going to support  CacheDB driver in the nearest future.
