### ISSUE TITLE
Please support PrestoSQL / PrestoDB connection

### ISSUE THREAD

**Issue by emhlbmc** [dbeaver/cloudbeaver#47]

**Comment by serge-rider** [comment]
Yeah, this makes sense. I think we'll include PrestoSQL (which is more "community friendly" as far as I know) first

**Comment by tnatssb** [comment]
Any progress on this? We would really push this with our customers/prospects.

**Comment by serge-rider** [comment]
New version will contain Trino (PrestSQL 351+) driver out of the box.

**Comment by kseniiaguzeeva** [comment]
The driver is available in the latest CE version 20.0.3.

**Comment by bobkernel** [comment]
how to build prestoDB connection, version lower than  351?
