### ISSUE TITLE
please reconfig language setting list

### ISSUE THREAD

**Issue by c0derGitHub** [dbeaver/cloudbeaver#475]
- [ ] Please,fix language setting list. '台湾人' 是 ‘中国人’，we are together ！you can change to  ‘繁體’ for users.

![QQ图片20210914102132](https://user-images.githubusercontent.com/7557637/133184720-f6b189fc-c3f4-4f09-b766-c3ed5a0dcccd.png)

**Comment by kseniiaguzeeva** [comment]
Could you please confirm that I understand you correctly: 
Should we change 中国人 (Chinese) on 繁體 (Taiwan)?

**Comment by c0derGitHub** [comment]
just ‘中文-简体’ or '中文-繁體’

**Comment by c0derGitHub** [comment]
Taiwan is a province of China，also Chinese.

**Comment by kseniiaguzeeva** [comment]
Thank you for the details. I compared CloudBeaver language menu with languages in DBeaver and took translations from there. We will fix it.

**Comment by c0derGitHub** [comment]
thanks :)

**Comment by kseniiaguzeeva** [comment]
The cause is in Eclipse Babel localization and it can be fixed from its side only. The same issue in DBeaver https://github.com/dbeaver/dbeaver/issues/13898

**Comment by kseniiaguzeeva** [comment]
I close the ticket, because its duplicate exists in DBeaver board. Do not hesitate to ask any other questions.
