### ISSUE TITLE
Add public key authentication for ssh tunnels

### ISSUE THREAD

**Issue by pietvanham** [dbeaver/cloudbeaver#482]
Would it be possible to add public key authentication as an option to ssh tunnel. 

I have tried to overwrite the data-sources.json file, but this fails to refresh/load.

`"ssh_tunnel": {
	"type": "TUNNEL",
	"enabled": true,
	"save-password": true,
	"properties": {
		"host": "xxx.xxxxxx.com",
		"authType": "PUBLIC_KEY",
		"port": 22.0,
		"keyPath": "/home/cloudbeaver/.ssh/id_rsa",
		"implementation": "jsch"
	}
}`

I would really like this feature because using ssh password authentication is not compliant with our security best practices.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We are going to implement it after 21.2.0 release.

**Comment by pietvanham** [comment]
Thanks, that would be great!

**Comment by pietvanham** [comment]
@kseniiaguzeeva is this still planned to be developed?

**Comment by kseniiaguzeeva** [comment]
Unfortunately, we had to move the task from 21.2 release. It is going to be implemented in 21.3.+ release.

**Comment by kseniiaguzeeva** [comment]
SSH public key support is added in [the latest release 21.3.3](https://github.com/dbeaver/cloudbeaver).
