### ISSUE TITLE
Build CloudBeaver on CentOS

### ISSUE THREAD

**Issue by sarma1807** [dbeaver/cloudbeaver#483]
I was able to build cloudbeaver Community Edition on ubuntu-20.04.3 x64, but same build process fails on CentOS_8.4.2015 x64.
is it supported on centos ?
can i build it on ubuntu but move the compiled code to centos ? if yes - then how ?

**Comment by kseniiaguzeeva** [comment]
Looks like a bug. Could you please send _server.log_ (you can find it here ...\cloudbeaver\workspace\.metadata)?

**Comment by kseniiaguzeeva** [comment]
There is no response in the ticket for a long time. Please feel free to ask to reopen the issue if it is still actual for you.
