### ISSUE TITLE
Add custom driver

### ISSUE THREAD

**Issue by sarma1807** [dbeaver/cloudbeaver#484]
CloudBeaver Community Edition - i am able to build it on ubuntu-20.04.3 x64

what is the step-by-step process to plug my own jdbc driver/jar ?

**Comment by kseniiaguzeeva** [comment]
Here is the instruction how to add new drivers here https://github.com/dbeaver/cloudbeaver/wiki/Driver-managements

**Comment by kseniiaguzeeva** [comment]
There is no response in the ticket for a long time. Please feel free to ask to reopen the issue if it is still actual for you.
