### ISSUE TITLE
logs the requests

### ISSUE THREAD

**Issue by Geronium** [dbeaver/cloudbeaver#488]
Hello, 

Can we have a log of the requests that have been made with cloudbeaver by the user ? (maybe it is already possible to configure it, but I did not find)

Thank you

**Comment by kseniiaguzeeva** [comment]
Thank you for the feature request. We will implement it, but I do not now a date for now. Another ticket with the same request already exists, so I close this one as the duplicate of https://github.com/dbeaver/cloudbeaver/issues/302.
