### ISSUE TITLE
autocomplete got a bug

### ISSUE THREAD

**Issue by sakikou** [dbeaver/cloudbeaver#507]
**Describe the bug**
it seems tobe a bug that when I choose a table from autocomplete pulldown window where comes to get an unexepected word.
**To Reproduce**
1.  enter any key to search an exist table
![image](https://user-images.githubusercontent.com/66810883/136722349-1fd73406-773a-4f21-9644-01acd9afc4e7.png)
2. Click on the name of the table or simply type enter key
3. see that the table will be typed out and after it comes with a word meaning of nothing.
![image](https://user-images.githubusercontent.com/66810883/136722640-aed82b8d-5d07-4ac8-8310-77ec8a3ee75b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/66810883/136722304-a84ec353-22c4-4418-8198-44c23a072c53.png)
**Desktop (please complete the following information):**
 - OS: macOSX
  - Browser chrome, safari
 - Version 1.2.0

**Comment by kseniiaguzeeva** [comment]
Thank you for the report, but it is the expected behaviour. Table aliases are added into queries in order to you could write them instead of long table names in your script.

**Comment by kseniiaguzeeva** [comment]
If you have any other questions, please feel free to ask them.
