### ISSUE TITLE
Cassandra support

### ISSUE THREAD

**Issue by yacut** [dbeaver/cloudbeaver#51]

**Comment by serge-rider** [comment]
There is no good open-source jdbc driver for Cassandra as far as I know. If you know one - please share.

**Comment by kseniiaguzeeva** [comment]
Enterprise Edition supports Cassandra driver. You can try it for free https://cloudbeaver.io/trial/
![Screenshot 2021-09-22 at 18 10 52](https://user-images.githubusercontent.com/51405061/134370689-ae1ff4ca-e8a5-4a42-b88e-6769b8706200.png)
