### ISSUE TITLE
Can I make connection for other databases?

### ISSUE THREAD

**Issue by richwxd** [dbeaver/cloudbeaver#515]
**Is your feature request related to a problem? Please describe.**
Since it can access SQLite, can a connection for MS Access be added? 
InfluxDB, TDEngine, ElasticSearch, they are more and more popular, could add supports for them?

**Describe the solution you'd like**
SQLite is based on file path, so It will be someway to add support for MS Access. Also hope ElasticSearch, TDEngine, Influxdb can be accessed from this tool.

**Comment by kseniiaguzeeva** [comment]
SQL Server driver is available in Community Edition. InfluxDB driver is available in Enterprise Edition.
You can add drivers which are not included to CloudBeaver yet using [this instruction](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers).

Please feel free to ask any other questions.
