### ISSUE TITLE
Custom Driver on Docker

### ISSUE THREAD

**Issue by bkief** [dbeaver/cloudbeaver#518]
I'd like to add a custom driver to the docker image using the cloudbeaver image as the base, but I notice the directory structure of `/opt/cloudbeaver` is different than what the driver wiki page indicates. Specifically the path `server/bundles/io.cloudbeaver.resources.drivers.base/plugin.xml` does not exist when I exec into the container. Is the setup a little different with the docker image?

**Comment by serge-rider** [comment]
In order to add new driver you need to build CB from sources. It is not enough to just change Dockerfile configuration.

You need to patch sources, build project and then run docker packager.
https://github.com/dbeaver/cloudbeaver/wiki/Driver-management

**Comment by kseniiaguzeeva** [comment]
Please feel free to ask to reopen the ticket if you still need some help with adding a driver.
