### ISSUE TITLE
Support for SQL formatting is expected！

### ISSUE THREAD

**Issue by frank-lam** [dbeaver/cloudbeaver#522]
Formatting with the SQL editor improves our experience, and double-clicking the table name automatically generates select statements. 
Hope the official can support~

**Comment by kseniiaguzeeva** [comment]
Thank you for the feature request. Could you please give me more details about generating of Select statement? Generation of SQL statements is already possible via the table context menu in the Navigator tree and the Metadata Editor. Does it cover your needs?
![Screenshot 2021-10-27 at 07 51 42](https://user-images.githubusercontent.com/51405061/139001964-55898b47-2b3e-4f0c-9f75-6a54554a9faa.png)

**Comment by frank-lam** [comment]
@kseniiaguzeeva 

This is also a good experience, but the SQL formatting scenario should be one where there is a tool for direct formatting when we write long SQL. It should be a format buttion like run in the sql editor page. This can greatly improve the efficiency of our SQL analysis.

**Comment by kseniiaguzeeva** [comment]
Thank you for the details. Do you want to click on a table name which is written in the SQL Editor for select statement generation?

**Comment by frank-lam** [comment]
@kseniiaguzeeva 

when I use many of web database, double click auto written in the SQL Editor, like Apache Druid,  it better experience for us to analysis for SQL.
Whether you double click or right click you can play with your own thinking space. With a lot of Web clients, CloudBeaver is really powerful and I like that.

**Comment by kseniiaguzeeva** [comment]
We will implement both features.  
I've created [another ticket](https://github.com/dbeaver/cloudbeaver/issues/529) for your request about opening a table from the SQL Editor. Most probably, it will not be a select statement, the table will be opened in the separate Metadata Editor.

**Comment by frank-lam** [comment]
@kseniiaguzeeva 
Cloudbeaver iterates very efficiently. Thumbs up. Will this feature be available in this month's version?

**Comment by frank-lam** [comment]
@kseniiaguzeeva 
In addition, whether the administrator can support configuring the default theme.Because dark themes are popular with many people, you have to re-select the dark theme color every time you open your browser and log in.

**Comment by kseniiaguzeeva** [comment]
We are going to add theme support via local config. This is [the ticket](https://github.com/dbeaver/cloudbeaver/issues/532) for the issue.

**Comment by kseniiaguzeeva** [comment]
SQL Formatting is implemented in the latest release [21.2.4](https://github.com/dbeaver/cloudbeaver).
