### ISSUE TITLE
Deploy of 21_2_0 failed with "Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))""

### ISSUE THREAD

**Issue by hellozdp** [dbeaver/cloudbeaver#524]
#### Describe the question
I'm trying to deploy 21_2_0 with JDK 1.8

#### Build environment
- OS: macOS 10.15.7
- Java version: 11.0.12, vendor: Eclipse Foundation
- Maven: 3.6.3
- Cloud Beaver: 21_2_0, Dbeaver: 21_2_0

#### Deploy environment
- OS: macOS 10.15.7
- Java version: 1.8.0_261, vendor: Oracle Corporation

#### Error respone
When run 'run-server.sh' script, got this response

```
Starting Cloudbeaver Server
An error has occurred. See the log file
/Users/phoenix/Documents/Repository/cloudbeaver/deploy/cloudbeaver/server/configuration/1635320202226.log.
```

#### Question
`Bundle-RequiredExecutionEnvironment` in MANIFEST.MF is `JavaSE-1.8`, but why I can't start server with JDK 1.8

#### Error logs
[1635318111911.log](https://github.com/dbeaver/cloudbeaver/files/7424145/1635318111911.log)

**Comment by hellozdp** [comment]
found `org.eclipse.equinox.common` in dbserver has two version
- org.eclipse.equinox.common-3.14.100.v20210212-1143
- org.eclipse.equinox.common-3.15.0.v20210518-0604

'Bundle-RequiredExecutionEnvironment' of `3.14.100.v20210212-1143` is  `JavaSE-1.8`, but it is `JavaSE-11` in `3.15.0.v20210518-0604`

How can I exclude the higher one?

**Comment by kseniiaguzeeva** [comment]
You should use Java 11. Some plugins depend on it.

**Comment by hellozdp** [comment]
> You should use Java 11. Some plugins depend on it.

Thank you for reply.  Is there any way to work around it?

**Comment by kseniiaguzeeva** [comment]
Unfortunately it is the limitation of DBeaver platform. Could you please clarify why you need another Java version?

**Comment by hellozdp** [comment]
> Unfortunately it is the limitation of DBeaver platform. Could you please clarify why you need another Java version?

Thanks for help. Because our product enviroment depends on JDK 8. The upgrade policy for JDK is too restricted.
