### ISSUE TITLE
Add  db2 iSeries / as400  driver

### ISSUE THREAD

**Issue by morandalex** [dbeaver/cloudbeaver#549]
It is missing the db2 iSeries / as400 driver
![image](https://user-images.githubusercontent.com/9484568/142842836-d26eed4b-cca0-4f0a-a0a4-5e7808073039.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for your feature request. The driver will be available in 21.2.3 release this week.
![Screenshot 2021-11-22 at 17 08 17](https://user-images.githubusercontent.com/51405061/142875988-8e1abc5f-b065-4b2b-96a8-e64a793b9a83.png)

**Comment by kseniiaguzeeva** [comment]
The driver is available in the latest 21.2.3 release.

**Comment by morandalex** [comment]
Fantastic, really thank you for your amazing work!
