### ISSUE TITLE
cannot scroll table view on safari

### ISSUE THREAD

**Issue by tsonglew** [dbeaver/cloudbeaver#559]
**Describe the bug**
cannot scroll table view on safari

**To Reproduce**
1. Go to any table
2. Try scrolling

**Screenshots**

<img width="963" alt="image" src="https://user-images.githubusercontent.com/14333766/144185530-2a2d2b63-eb5f-4a48-bee7-d8f245a44bbb.png">

as you can see, only 33 rows are shown no matter how I scrolling.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser: safari  15.1 (17612.2.9.1.20)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. We are going to fix it in 21.3.0 release

**Comment by kseniiaguzeeva** [comment]
Fixed in the latest release [21.2.4](https://github.com/dbeaver/cloudbeaver).
