### ISSUE TITLE
Github Releases and Tags

### ISSUE THREAD

**Issue by pha91** [dbeaver/cloudbeaver#565]
**Is your feature request related to a problem? Please describe.**
Currently we always have to watch the repository manually to get new releases. Github offers the possibility to be notified automatically when a release is tagged as github-release.
Also the current container tags are confusing . Currently latest points to version 21.2.2 while 21.2.3 is available

**Describe the solution you'd like**

- Publish new releases via github releases to enable notitifaction
- Automate the release process via github actions including docker tags

**Comment by Wroud** [comment]
Good point. Now we will publish releases in GitHub too.
