### ISSUE TITLE
How to import the cloudbeaver source code into the development tool eclipse or idea

### ISSUE THREAD

**Issue by dinsy008** [dbeaver/cloudbeaver#576]
How to import the cloudbeaver source code into the development tool eclipse or idea for secondary development

**Comment by kseniiaguzeeva** [comment]
Thank you for your interest in CloudBeaver. The way is the same as DBeaver has. You can use following instructions:
https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse
https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA

Please feel free to ask any additional questions.

**Comment by kseniiaguzeeva** [comment]
Also we've created the additional article in Cloudbeaver wiki [Develop in Eclipse](https://github.com/dbeaver/cloudbeaver/wiki/Develop-in-Eclipse).

**Comment by dinsy008** [comment]
> Thank you for your interest in CloudBeaver. The way is the same as DBeaver has. You can use following instructions: https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA
> 
> Please feel free to ask any additional questions.

reference resources https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA There is still a problem with the build
1. cloudbeaver-idea-project.git is not found in GitHub
2. .product or related documents are not found in .metadata/.plugins
Can you describe in detail how to build a development and debugging environment in idea

**Comment by lichaoge** [comment]
Does cloud dbeaver support Command line to pass parameters? Can parameters be passed in using Command line like windows when starting the dbeaver container? For example: https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by serge-rider** [comment]
Yes, you can pass command line parameters to CloudBeaver. But only parameters related to JVM (System parameters and VM arguments from the article mentioned above). You can add these parameters in the `run-server.sh` script or y setting `JAVA_OPTS` environment variable.

**Comment by kseniiaguzeeva** [comment]
Please feel free to ask to reopen the ticket if you have any additional questions.
