### ISSUE TITLE
MySQL Blob field with long text are truncated

### ISSUE THREAD

**Issue by tsonglew** [dbeaver/cloudbeaver#585]
**Describe the bug**
Blob field with long value are truncated

**To Reproduce**
1. Fill a field from any mysql table with long text
2. Go to that row and click the field
4. See that the value is not fully retrieved from mysql

**Screenshots**

the selected value of 11th row with id 34 should have 828bytes, but only part of the value are shown on cloudbeaver. btw, the value looks good on dbeaver for Mac. 

CloudBeaver:

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/14333766/145506639-5d8fb50c-1aec-4b16-b104-63ed0ac934cb.png">

DBeaver:

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/14333766/145507260-4e04b0e2-1ded-49a8-a644-ebc329cb40f0.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser Safari
 - Version 15.1

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
LOBs can be saved to in external file from the Data Editor in the current release 22.0.3.
The support of longer data display in the Value panel and changing the Value panel limits will be available in 22.0.4 release.

**Comment by kseniiaguzeeva** [comment]
The larger values can be displayed in the Value panel now. You can also [configure the Value panel limits in the configuration file](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#resource-quotas).
