### ISSUE TITLE
When I start cloudbeaver with docker, how do I specify the parameters according to https://github.com/dbeaver/dbeaver/wiki/Command-Line#system-parameters? Are there any relevant examples?

### ISSUE THREAD

**Issue by lichaoge** [dbeaver/cloudbeaver#597]
When I start cloudbeaver with docker, how do I specify the parameters according to https://github.com/dbeaver/dbeaver/wiki/Command-Line#system-parameters? Are there any relevant examples?
thanks

**Comment by serge-rider** [comment]
Hello,

I've create a wiki article about this: https://github.com/dbeaver/cloudbeaver/wiki/Command-line-parameters
