### ISSUE TITLE
Missing comma on Server config, typical example on the wiki 

### ISSUE THREAD

**Issue by Ricram2** [dbeaver/cloudbeaver#606]
**Describe the bug**
Missing comma on Server config, typical example on the wiki 

**To Reproduce**
1. Go to ['Server configuration in the Wiki'](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration)
2. Check the typical configuration: 
3. See sceenshot: 

**Screenshots**

![image](https://user-images.githubusercontent.com/24927430/147296819-b4a4e254-6c52-4a6e-93e0-a705abf1ef55.png)
![image](https://user-images.githubusercontent.com/24927430/147296829-9ff339c4-c7bf-4ee8-95e8-7304cd22f96d.png)

**Additional context**
Adding the comma is sufficient to fix this.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
Fixed
