### ISSUE TITLE
reverse proxy header authentication

### ISSUE THREAD

**Issue by skaravad** [dbeaver/cloudbeaver#612]
Is it possible to allow users and groups based on reverse proxy headers ?

For instance we can use X-Email as login and X-Group as user group for authenticating and authorizing users , this can be a very simple and effective authentication and authorization mechanism without complex integrations via SAML, LDAP etc.

Few systems which use this simple mechanism:
https://plugins.jenkins.io/reverse-proxy-auth-plugin/
https://grafana.com/docs/grafana/latest/auth/auth-proxy/

**Comment by skaravad** [comment]
please consider this feature for CE vs EE

**Comment by kseniiaguzeeva** [comment]
Thank you for the feature request. We are going to investigate and implement it.

**Comment by kseniiaguzeeva** [comment]
The feature is available in the [latest release](https://github.com/dbeaver/cloudbeaver).

**Comment by skaravad** [comment]
Hello there,
Thank you for enabling this feature, how to enable the auth method ? is there a  command line arg that we can use ?

**Comment by kseniiaguzeeva** [comment]
You have to add parameter `"enableReverseProxyAuth": true` to .cloudbeaver.rutime.conf and add parameters to nginx.conf:
```
 server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

		  location / {
			proxy_pass       http://localhost:8080;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_set_header X-User testtest;
			proxy_set_header X-Role admin|user;
		}
```
Here are related articles: [Reverse proxy header authentication](https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication) and [Server configuration](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration).

Feel free to ask any additional questions.

**Comment by skaravad** [comment]
Thank you for your quick response, enabled it and it is working as expected.
