### ISSUE TITLE
 Session is about to expire

### ISSUE THREAD

**Issue by chitfknc** [dbeaver/cloudbeaver#636]
Your session will expire in less than 5 minutes. To keep working, close this popup.

this noitce showed very many times when I just connect to Cloudbeaver about 1min .  i am sure that setup 30mins for timed out.

**Comment by kseniiaguzeeva** [comment]
We had a [similar issue](https://github.com/dbeaver/cloudbeaver/issues/527). Steps to reproduce weren't found and the user reported after some time, that the session expiration time began to work properly again. Could you please provide me with additional details? They should help me to find out the reason of the issue.
- What CloudBeaver version do you use?
- Did you change the defaut settings of session lifetime? If yes, did you do it via UI or local configuration files (\cloudbeaver\workspace.data.cloudbeaver.runtime.conf)?
- Could you please provide me with server logs completely (you can find server.log and .log in your local config files: cloudbeaver\workspace\.metadata\)?
- Your timezone
- Could you try to clean cookies and restart CloudBeaver?
- Any other additional information.

Thank you in advance. I'm looing forward to your answer.

**Comment by kseniiaguzeeva** [comment]
I have noticed that you have not updated your ticket for a long time. If you wish to reopen this ticket, please feel free to contact me.
