### ISSUE TITLE
Support for Script Import (or load/run of DDL script)

### ISSUE THREAD

**Issue by ravensorb** [dbeaver/cloudbeaver#65]
Are there any plans to add support to be able to load/import a DDL script?  It would be great if this could be add for both at the server connection level and within a specific database.

**Comment by serge-rider** [comment]
Could you please clarify?

Currently you can execute DDL in the SQL editor.
We will add support of native tools (like psql or mysql) in future versions.
Or do you mean something else?

**Comment by ravensorb** [comment]
Fair question -- it might seem small but a simple "import script" menu option that can allow for uploading small or large ddl scripts would be very helpful.

**Comment by serge-rider** [comment]
Good point

**Comment by zhicwu** [comment]
Would be really nice if script can be saved/loaded by user, which is common when we use DBeaver.  Able to share reusable script among users helps too.

**Comment by mksqllc** [comment]
Being able to save a script will be extremely useful. Thanks.

**Comment by kseniiaguzeeva** [comment]
Thank you for voting. I will discuss the date of the feature implementation with my colleagues. At the moment I can say that it will be after 21.2 release.

**Comment by zhicwu** [comment]
Thanks @kseniiaguzeeva. Definitely a feature worthy of waiting :)

**Comment by dshakey** [comment]
thanks for adding, saving been feature our team been asking for,

**Comment by kseniiaguzeeva** [comment]
The feature is implemented and available in [the latest release](https://github.com/dbeaver/cloudbeaver).
