### ISSUE TITLE
Dockerized Process in a Pipeline

### ISSUE THREAD

**Issue by marcellodesales** [dbeaver/cloudbeaver#663]
**Is your feature request related to a problem? Please describe.**

* Setting up DBeaver is extremely hard and requires multiple steps
* The environment is hard to setup for developers, and the scripts provided in the deploy directory makes to many assumptions
* The use of Docker in the project is very elementary, without properly taking advantage of Docker caches, eliminating scripts
* When I deploy DBeaver in private data center or the Cloud, I usually have to setup the servers over and over again... 
  * Even with Docker
* There's no official Docker Image that we can get from the project, built officially from the project

**Describe the solution you'd like**

* Create a Multi-stage Dockerfile that builds DBeaver along with the dependencies
  * Java
  * Web
  * Git dependency to Java dependencies
* Add a Github Pipeline that Publishes official versions of the project in a Docker Image that is reusable
  * It's small, concise, has only binaries and the web version
* We can run the same Docker image in different environments such as Local Host (Developer), Private Data Center (Docker Engine), or Cloud Schedulers (Docker Swarm or Kubernetes)

## Design

Here the pipeline of my Fork

![Screen Shot 2022-02-18 at 12 46 27 AM](https://user-images.githubusercontent.com/131457/154649107-16e01b63-f9c0-4146-88da-ba00caf5884c.png)

**Comment by serge-rider** [comment]
Thanks you for the contribs 👍 

Currently we are still thinking about different types of CloudBeaver packagings.

Generally we are trying to leave it as simple as possible - just a docker image with minimum requirements. All other things like orchestration, additional configuration, user data population etc is out of scope of CloudBeaver itself.

Maybe it would be a good idea to create a separate repository which will use CB repository or CB docker container as a base for improvements?

**Comment by marcellodesales** [comment]
@serge-rider Np problem!!!

I usually think when a developer starts using a new app they need NOT know how to build: they should just have the packaging system that is reliable on his/her OS. That said, I have been using Docker since 2014 and it has delivered on that requirement. 

The provided contribution only uses the best practice... I Don't provide data population nor orchestration, just the Dockerfile and the docker-compose.yaml. What I was adding on the PR was details on where I used the built docker image :) So, please review the changed files!

For this reason, I don't think it is NOT a good idea to separate repositories! As usual, Dockerfile usually lives in the root directory as to build the Docker Context, along with docker-compose.yaml, which makes it documented how to build and run a simple docker container!

**Comment by kseniiaguzeeva** [comment]
The answer has been given in the pull request. I close this ticket.
Feel free to contact me or open a new tcket if you have any additional questions.
