### ISSUE TITLE
SAP ASE 16 support

### ISSUE THREAD

**Issue by davidsoles** [dbeaver/cloudbeaver#680]
I'm trying to connect to SAP ASE 16 database using CloudBeaver but the driver is not available. It would be great if you could included.

Thanks.

**Comment by kseniiaguzeeva** [comment]
Thank you for the interest in CloudBeaver. Could you please try to configure the driver using this [instruction](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers)?
I appreciate your answer whether it's helped.

**Comment by kseniiaguzeeva** [comment]
Do not hesitate to ask to reopen the ticket if you have any additional questions.
