### ISSUE TITLE
Add option to save to Cloudbeaver local filesystem

### ISSUE THREAD

**Issue by JDarDagran** [dbeaver/cloudbeaver#681]
**Is your feature request related to a problem? Please describe.**
Now it's only possible to save query/exported data to user's PC via browser. There is no option to save files in Cloudbeaver's instance local filesystem.

**Describe the solution you'd like**
There could be two additional buttons for downloading/saving.

![image](https://user-images.githubusercontent.com/3889552/155695537-7e62702b-f3f3-46b9-83f2-e01818a230e9.png)

![image](https://user-images.githubusercontent.com/3889552/155695783-b6abfa68-d523-493f-8c37-0293240411b8.png)

There also could be created some helper local file browser in order to select export destination (example screen comes from VSCode):

![image](https://user-images.githubusercontent.com/3889552/155696857-a55fb242-bbc2-4c32-8a27-edc80a59eb54.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. The feature requires quite a lot of work. We will try to implement it in a 22+ release.

**Comment by kseniiaguzeeva** [comment]
The feature is available in the latest release 22.0.5.
