### ISSUE TITLE
connection to ClickHouse

### ISSUE THREAD

**Issue by Oleg-levwa** [dbeaver/cloudbeaver#712]
Please, describe your question in details.
Hello,
I'm trying to connect to ClickHouse database version 22.2.3.1 via cloudbeaver but only ClickHouse (Legacy) is listed in the driver list. 
<img width="1023" alt="image (1)" src="https://user-images.githubusercontent.com/46030666/158458103-9b2a364f-e1c3-45b3-809e-f0047bebff16.png">

When using it, an error occurs.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/46030666/158458177-b9664d2f-c950-41f5-9d63-b3fc86e380f3.png">

When using dbeaver with the ClickHouse driver, it connects without errors. Dbeaver has ClickHouse and ClickHouse(Legacy) drivers.
Can you please tell me if the error appears due to the Legacy driver?

**Comment by kseniiaguzeeva** [comment]
We will add newer versions support. Thank you for your question.

**Comment by kseniiaguzeeva** [comment]
The driver is available in the latest release 22.0.2.
