### ISSUE TITLE
Connect to Google BigQuery cloudbeaver

### ISSUE THREAD

**Issue by Oleg-levwa** [dbeaver/cloudbeaver#718]
Please tell me if there will be a connection to google bigquery via cloudbeaver ?

**Comment by kseniiaguzeeva** [comment]
Thank you for your question. It's already available in [Enterprise Edition](https://cloudbeaver.io/).
![Screenshot 2022-03-17 at 17 20 08](https://user-images.githubusercontent.com/51405061/158817337-d1462ba0-2afc-44e6-81e0-c1a4ccab98cc.png)
