### ISSUE TITLE
Autentication bug using ntlm authenticationScheme in sqlserver driver

### ISSUE THREAD

**Issue by btarazonaj** [dbeaver/cloudbeaver#732]
**Describe the bug**
When i try to authenticate with NTLM, it expects pass the password under the "password" field on the request, but the server sends the password under the field "userPassword" and it shows this error:

com.microsoft.sqlserver.jdbc.SQLServerException: "User" (or "UserName") and "**Password**" connection properties must be specified for NTLM authentication.
![imagen](https://user-images.githubusercontent.com/102534877/160428451-65f78fec-85f1-458e-b88e-c3ddaedacd8d.png)
![imagen](https://user-images.githubusercontent.com/102534877/160428652-56532bac-dc54-4c7b-973a-7bca847272d5.png)

If i specify in the driver properties manually fields "User" and "Password" it works and i can connect but the field Password in the driver properties appears in plain text... :(( 
Anyway the login window appears when you try to connect and it is useless because the driver properties configuration overwrites it.

**Driver Properties changes:**
authenticationScheme: "ntlm"
integratedSecurity: "true"

**Desktop (please complete the following information):**
 - OS: Docker
 - Version 22.0.1

**Comment by kseniiaguzeeva** [comment]
We are going to add support of diiferent authentication models for SQL Server. NTLM auth will work after that. 
Here is [similar ticket](https://github.com/dbeaver/cloudbeaver/issues/392).

**Comment by kseniiaguzeeva** [comment]
NTLM authentication is added for SQL Server. Could you please just select it in the Connection dialog and enter your credentials?

![Screenshot 2022-06-01 at 10 53 01](https://user-images.githubusercontent.com/51405061/171355262-4e08fca2-37b5-4f0b-9210-80ee710eda12.png)
