### ISSUE TITLE
Access DB via URL

### ISSUE THREAD

**Issue by ryjogo** [dbeaver/cloudbeaver#735]
**Is your feature request related to a problem? Please describe.**
A shorturl, or parameters to fall into a DB connection via an external link.

**Describe the solution you'd like**
For example, http://localhost:8080/#/?db=<dbname>

**Comment by kseniiaguzeeva** [comment]
Thank you for the feature request. We are going implement it.

**Comment by kseniiaguzeeva** [comment]
The feature is available in the latest release 22.0.5.

**Comment by ryjogo** [comment]
Any documentation on this feature?

**Comment by kseniaguzeeva** [comment]
Yes, you can find it here https://github.com/dbeaver/cloudbeaver/wiki/Access-to-an-existing-database-connection-with-a-link
