### ISSUE TITLE
Session Expired - Grammar/Typo

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#742]
**Describe the bug**
Reword session expire timeout since it seems to be incorrect grammar.
An option would be 
"Session has expired. Do you want to reload?"

**To Reproduce**
1. Wait for session to time out to see the message

**Screenshots**
![2022-03-30_09-01-51](https://user-images.githubusercontent.com/57646596/160880109-2db52f43-9f2d-4fce-bf88-197929a7172d.png)

**Desktop (please complete the following information):**
 - OS: Windows/Mac
 - Browser Chrome/Safari
 - Version 22.0.1

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
The bug is fixed in the latest release 22.0.2.
