### ISSUE TITLE
Does the web application support Windows authentication?

### ISSUE THREAD

**Issue by jorgia111** [dbeaver/cloudbeaver#757]
Does the web application support Windows authentication? or how do i authenticate numbers AD users against the web application ?  as I have number of users that requited access to cloudbeaver  web application .its hard to manage to create a users and give access for individual users to specific connection from the UI .I am using latest cloudbeaver community docker images ,any help with ?

**Comment by jorgia111** [comment]
any update on this ?

**Comment by kseniiaguzeeva** [comment]
CloudBeaver doesn't support Windows authentication for now. 
It is possible to use Federated auth (SSO and OpenId), AWS, Nginx.

**Comment by serge-rider** [comment]
In version 22.1 we added support of Azure AD authentication (over OpenId), see https://github.com/dbeaver/cloudbeaver/wiki/Azure-AD-authentication.

Native Windows authentication is not supported.

**Comment by LonwoLonwo** [comment]
Hello @jorgia111 

In CloudBeaver EE version, you can use the NTLM authentication:

![2024-03-12 10_49_00-CloudBeaver Enterprise](https://github.com/dbeaver/cloudbeaver/assets/45152336/7d20a5a2-8ed0-4e98-8a45-ceb099010420)

It looks like what you are looking for. And you can try it for free: https://dbeaver.com/download/cloudbeaver/

More about authentication methods you can read here: https://github.com/dbeaver/cloudbeaver/wiki/Authentication-methods

**Comment by LonwoLonwo** [comment]
There is no answer for a long time. So, I'm closing this ticket.

Feel free to open a new one with new details.
