### ISSUE TITLE
assureReadOnly

### ISSUE THREAD

**Issue by ryjogo** [dbeaver/cloudbeaver#758]
What does the assureReadOnly actually do? i was under the impression this would force the user into a read only "mode" on the db, of course the underlying connection would still have permissions.

**Comment by kseniiaguzeeva** [comment]
You can disable table data editing via the Data Editor and the ResultSet. You have to set the parameter in the config files (product.conf) for it:

`{
 "core": {
   "app": {
     "dataViewer": {
       "disableEdit": true
     }
   }
 }
}
`

![Screenshot 2022-04-08 at 16 53 52](https://user-images.githubusercontent.com/51405061/162450318-c898a307-ab53-44fc-b9b7-22c6f2783b7f.png)

But you still can edit data by executing queries in the SQL Editor (Insert,  Update, Delete).

**Comment by ryjogo** [comment]
Ah ok, thanks for your response. I was under the impression it was readOnly for all functionality - i guess for that to happen the only way is to of course make a read-only user on the DB itself. 

Thanks.
