### ISSUE TITLE
can you add swagger into this project?

### ISSUE THREAD

**Issue by hmtiannan** [dbeaver/cloudbeaver#761]
in order to we can easy to know more about the code , can you privide an api docs， thank you very much !

**Comment by alexander-skoblikov** [comment]
Hi!
We are using GraphQL and can't add a swagger to describe API, but you can use [GraphQL console](https://github.com/dbeaver/cloudbeaver/wiki/Server-API-explorer) to find the information you are interested in.
Feel free to ask, If you need more specific information about API,
