### ISSUE TITLE
Add Folder Manage

### ISSUE THREAD

**Issue by itman2022** [dbeaver/cloudbeaver#772]
I hope Cloudbeaver can do it，Thanks very much !!!

1.Folder Manage
Temporary is the default folder
![pic1](https://user-images.githubusercontent.com/49448987/163804409-883c0b5b-43f9-44dd-9363-4896e0593a74.png)

2.Save script

2.1 Click Save
![pic2](https://user-images.githubusercontent.com/49448987/163804431-748729fe-b462-4960-8752-08d4c6bbddcc.png)

2.2 Choose folder
![pic3](https://user-images.githubusercontent.com/49448987/163804460-3683e2a7-606d-4975-adc7-0b0b4459272d.png)

3.Sub Menu

![pic4](https://user-images.githubusercontent.com/49448987/163804492-d6104439-5c4d-463e-8586-038b08a14837.png)
Rename
Add Sub Folder
Delete Folder
......

![pic5](https://user-images.githubusercontent.com/49448987/163804512-9e93b36e-2491-4455-9b77-69c8a455e74c.png)
Open（Click）
Rename
Delete
......

**Comment by kseniiaguzeeva** [comment]
Thank you for the feature request. We are going to add possibility to save scripts and open them from Cloudbeaver in 22.0.4 release. Folders will be added later.

**Comment by kseniiaguzeeva** [comment]
The feature is available in the latest 22.1.2 release.
