### ISSUE TITLE
Trino - cancelling running query gives connection closed

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#782]
**Describe the bug**
Manually cancelling a running query gives "connection closed" errors on all subsequent runs or retries. 

**To Reproduce**
1. Run a query
2. Click cancel
3. Click retry or try running the query again

**Screenshots**
![2022-04-22_22-08-07](https://user-images.githubusercontent.com/57646596/164878690-d8de0060-acfc-4176-8d8b-7bb7189f24c3.png)

**Desktop (please complete the following information):**
 - OS: Windows/Mac
 - Browser : Chrome
 - Version : 22.0.3

**Additional context**
Caused by: java.sql.SQLException: Connection is closed
	at io.trino.jdbc.TrinoConnection.checkOpen(TrinoConnection.java:795)
	at io.trino.jdbc.TrinoConnection.prepareStatement(TrinoConnection.java:157)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:146)
	... 12 more

**Comment by kseniiaguzeeva** [comment]
Unfortunately, I cannot reproduce the issue.

https://user-images.githubusercontent.com/51405061/165068193-d3796ef5-af5a-4c91-806d-c18cf664f774.mp4

1. What type of query do you execute?
2. Do you connect to local Trino or via SSH?
3. Which Trino driver do you use (you can press Test Connection in the Edit Connection dialog and see it in the pop up dialog)?

![chrome_8Hz9u94ufo](https://user-images.githubusercontent.com/51405061/165068212-16ab506c-4581-401d-8f61-4b99169f652a.png)

**Comment by metalshanked** [comment]
Thanks @kseniiaguzeeva 
1. I tried various queries across data sources like Postgres, MS SQL which are connected via Trino
2. Cloudbeaver connects to the Trino coordinator server via the Trino JDBC Driver (currently 378) 
3. I use JDBC version 378 and Trino Server itself is also 378 ( the issue also occured on 376)

**Comment by kseniiaguzeeva** [comment]
I've found that it is the expected behaviour for a Trino driver. The driver doesn't support Cancel and CloudBeaver can do it on a server side only. 
Here are similar discussions  https://github.com/dbeaver/dbeaver/issues/3094#issuecomment-628222837 and https://github.com/trinodb/trino/issues/7587.

Please feel free to ask any additioanl questions.

**Comment by metalshanked** [comment]
Thanks @kseniiaguzeeva - makes sense. Just that from a user viewpoint, they dont know what to do when this error is displayed i.e. "Connection is closed". because none of the options in the UI, like retry,close etc will work.  
The only solution is to click "Disconnect" and reconnect which is unintuitive to the end user.

A message like "please try disconnecting and reconnecting" or even better the retry button automatically doing this would be great.

_None of the below options help_
![2022-05-29_18-46-18](https://user-images.githubusercontent.com/57646596/170902659-d6b0f129-b2bf-4f2a-a951-8d4505cdb3ae.png)

_Current solution (disconnect and reconnect)_
![2022-05-29_17-52-19](https://user-images.githubusercontent.com/57646596/170899156-74345734-4158-4811-b29b-9abd3edea8a2.png)
