### ISSUE TITLE
Admin username and password lost

### ISSUE THREAD

**Issue by AlexKalopsia** [dbeaver/cloudbeaver#797]
Hi, I run CB in a docker container. I forgot the username and password to enter the webUI and I am not sure what I can do about it. I checked through old issues as well as the documentation, but the only info I find is regarding setting username and password manually _before_ the wizard. 

I am trying to understand if there is something I am missing, I even checked all the internal files bashing in the container. 

If there is a way to reset this info I think it would be great to add a small guide in the docs.

**Comment by kseniiaguzeeva** [comment]
Hi,
you have to delete `.cloudbeaver.runtime.conf` and
- as you already found: to go through the Easy Confiuration;
- or create [a new server configuration via a command line](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#automatic-server-configuration), e.g. `docker run --name <a_name> --rm -ti -p <a_port>:8978 -e CB_SERVER_NAME=<a_server_name> -e CB_SERVER_URL=<a_url> -e CB_ADMIN_NAME=<an_admin_name> -e CB_ADMIN_PASSWORD=<an_admin_password> -v C:\var\...:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:...`

Do not hesitate to ask any additional questions.

**Comment by AlexKalopsia** [comment]
@kseniiaguzeeva I am just writing here because today I've updated CB and once again it stopped accepting my username and password (note that I did login with same credential earlier today, before the update). 

I am wondering if there is something wrong happening with the update process (I just pull latest image via docker and recreate the container)
