### ISSUE TITLE
Driver Properties - autoCommit property not working

### ISSUE THREAD

**Issue by raj7749** [dbeaver/cloudbeaver#807]
autoCommit property which is configured in driver properties while creating connection is not working.
All the statements executed are auto committed.

**To Reproduce**
1. Login with admin user
2. Go to 'Settings'
3. Click on 'Administration'
4. Click on 'Add new connection'
5. Choose 'oracle'
6. Add all db details
7. Goto Driver Properties tab
8. change autoCommit property to false
9. Perform DML operation and execute rollback
10. DML operations are not rollbacked as expected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [linux oraclelinux 8]
 - Browser [chrome]
 - Version [22.0.3]

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Manual Commit isn't implemented yet. CloudBeaver uses autocommit all the time for now. We will implement this feature in future. Here is [the feature request](https://github.com/dbeaver/cloudbeaver/issues/129).
