### ISSUE TITLE
can force the installation with a higher version of java

### ISSUE THREAD

**Issue by GiancarloAparicio** [dbeaver/cloudbeaver#810]
I want to install cloudbeaver on android through termux, the issue is that termux does not store old binaries and only has openjdk-17.

The same happens with nodejs, but this can be forced with the variable FORCE_NODE_VERSION=16.14, I don't know if java will have something similar (sorry if it has and it's obvious, but I've never used java)

When I try to install cloudbeaver I get this:
![image](https://user-images.githubusercontent.com/61440825/166861375-98a064cb-8a3a-4d42-815f-e8dec59640f8.png)

**Comment by kseniiaguzeeva** [comment]
We will investigate it. Thank you for the report.

**Comment by serge-rider** [comment]
WE updated Tycho version to the most recent (2.7.2). Besides other things it adds Java 17 support.
