### ISSUE TITLE
Cloudbeaver build and deployment

### ISSUE THREAD

**Issue by yunkuotianxian** [dbeaver/cloudbeaver#814]
My computer operating system: Windows Server 2012r2

I followed the guidelines:
git clone https://github.com/dbeaver/cloudbeaver.git
cd cloudbeaver/deploy
./build. bat

The error results are as follows:
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.3.0:com
pile (default-compile) on project org.jkiss.dbeaver.net.ssh.sshj: Compilation fa
ilure: Compilation failure:
[ERROR] C:\Users\Administrator\git\dbeaver\plugins\org.jkiss.dbeaver.net.ssh.ssh
j\src\org\jkiss\dbeaver\model\net\ssh\SSHImplementationSshj.java:[116]
[ERROR]         final LocalPortForwarder.Parameters params
[ERROR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] LocalPortForwarder.Parameters cannot be resolved to a type
[ERROR] C:\Users\Administrator\git\dbeaver\plugins\org.jkiss.dbeaver.net.ssh.ssh
j\src\org\jkiss\dbeaver\model\net\ssh\SSHImplementationSshj.java:[117]

What's the problem? thank you

**Comment by vivostar** [comment]
have you ever download the dbeaver-ce code?

**Comment by yunkuotianxian** [comment]
Are you asking me？Downloaded and pulled the devel branch。
They are all in my “git” directory,&nbsp; xxx/git/cloudbeaver,&nbsp; xxx/git/dbeaver
My dbeaver project has been running according to the guidelines。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/cloudbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/cloudbeaver] Cloudbeaver build and deployment (Issue #814)





 
have you ever download the dbeaver-ce code?

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It has been fixed. Could you please try again?

**Comment by yunkuotianxian** [comment]
The XXX \ git \ cloudbeaver \ deploy \ cloudbeaver directory was successfully generated without error.


Then execute the command:

cd XXX\git\cloudbeaver\deploy\cloudbeaver

run-server.&nbsp;bat


The command line outputs the following:

The system cannot find the specified file

"Startig Cloudbeaver Server"

1 file copied

Error: Unable to access jarfile io.&nbsp;cloudbeaver.&nbsp;product.&nbsp;ce.&nbsp;product





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/cloudbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/cloudbeaver] Cloudbeaver build and deployment (Issue #814)





 
Thank you for the report. It has been fixed. Could you please try again?

**Comment by serge-rider** [comment]
This is quite strange. And I can't reproduce this.
Could you try to delete folder deploy/cloudbeaver and rebuild it again?

**Comment by Wroud** [comment]
Please copy `run-server.bat` from `cloudbeaver\deploy\scripts` to `cloudbeaver\deploy\cloudbeaver` and try to run it

**Comment by kseniiaguzeeva** [comment]
I have noticed that you have not updated your ticket for a long time. If you wish to reopen this ticket, please feel free to contact me.

**Comment by jiangyutu** [comment]
I had the same problem and I don't think the problem was fully resolved

**Comment by yunkuotianxian** [comment]
succeed!&nbsp;I used a brand new server and rebuilt it again.&nbsp;Thank you very much


Now I try to import the dbeaver project into eclipse, and an error is reported in the import package, as shown in the following figure:






I have two servers, one in Germany and the other in Japan. Before, I could successfully import the package in the screenshot on the German server, but now eclipse on the German server and the Japanese server report the same error. Can you help me see this problem？


My first eclipse rap project also encountered problems. I searched Google and found no related problems.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/cloudbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月12日(星期四) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/cloudbeaver] Cloudbeaver build and deployment (Issue #814)





 
This is quite strange. And I can't reproduce this.
 Could you try to delete folder deploy/cloudbeaver and rebuild it again?
