### ISSUE TITLE
SQL Server, visibility of system objects

### ISSUE THREAD

**Issue by riccardomessineo** [dbeaver/cloudbeaver#820]
**Is your feature request related to a problem? Please describe.**
Using Cloudbeaver with SQL Server, it seems dangerous to have system objects available to users.
I'm referring to system databases such as "master", "tempdb" and system schemas as "dbo", "INFORMATION_SCHEMA" and "sys".

**Describe the solution you'd like**
I'd like an option to enable or disable the system objects visibility in the connections

**Comment by riccardomessineo** [comment]
If I am not mistaken, MS has an option to hide system objects on its SQL Server Management Studio: 
https://docs.microsoft.com/en-us/sql/ssms/object/hide-system-objects-in-object-explorer?view=sql-server-ver15&viewFallbackFrom=sql-server-linux-2017

**Comment by kseniiaguzeeva** [comment]
Thank you for your feature request. You can hide `msdb` database and `INFORMATION_SCHEMA`, `sys` schemas for now: disable **Show system objects** via the connection context menu in the Navigator tree.

![chrome_FcnlziFP5T](https://user-images.githubusercontent.com/51405061/168042991-5b696a7b-6574-4aa0-b1a2-2dc41d71597f.png)

**Comment by riccardomessineo** [comment]
Hello @kseniiaguzeeva , 
  thanks for the support.

I tried the setting and tt hides "msdb" database, "information_schema" and "sys" schemas.
Is it "complete" though? 
"master" and "tempdb" database and "dbo" schema are still displayed. 

Setting on ("show system objects"):
![image](https://user-images.githubusercontent.com/10194398/168047687-73016979-0d42-4420-9416-425cf8e15c46.png)

Setting off ("hide system objects"):
![image](https://user-images.githubusercontent.com/10194398/168047860-f6df8d84-b49a-4c05-b485-cec9752efd8d.png)

**Comment by kseniiaguzeeva** [comment]
I'm discussing the feature request with CloudBeaver team and give you an answer what can be done.

**Comment by serge-rider** [comment]
Good point. Databases `master`, `tempdb` and `model` must be marked as system databases.

Schema `dbo` is not a system schema. It is a default schema and it is widely used as a container of user tables.

**Comment by kseniiaguzeeva** [comment]
The improvement is available in the latest release 22.0.5.
