### ISSUE TITLE
Login link still present after allowing anonymous log in (How to remove it?)

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#823]
Please, describe your question in details.
I was using 22.0.3 earlier and the login link disappeared once anonymous login was enabled.
However. after upgrading to 22.0.4, the Login link shows up like below

Is there a way to disable the Login Link like before?

![2022-05-11_12-55-35](https://user-images.githubusercontent.com/57646596/167935210-d5ddd41a-a8ed-42d8-a6d0-f3f5a3add78e.png)

![2022-05-11_12-58-48](https://user-images.githubusercontent.com/57646596/167935638-81f4b8de-e4b9-444a-88c5-f7375a2b5c69.png)

Thanks!

**Comment by kseniiaguzeeva** [comment]
Thank you for the report but I cannot reproduce the issue. It looks like a mistake in configuration files or a cache issue:
1. could you check .cloudbeaver.runtime.conf file? Anonymous access has to be true:
```
 "app": {
    "anonymousAccessEnabled": true,
```
2. Could you try to clean cache?

If it doesn't help, could you please send me .cloudbeaver.runtime.conf file example (here or by email kseniia@jkiss.org)? It should help me to find out the issue.

**Comment by metalshanked** [comment]
Thanks @kseniiaguzeeva. I checked the `workspace/.data/.cloudbeaver.runtime.conf` file and it seems to be correct.
Also, cleared the Browser cache but the issue persists.

```
"app": {
    "anonymousAccessEnabled": true,
    "supportsCustomConnections": false,
    "publicCredentialsSaveEnabled": false,
    "adminCredentialsSaveEnabled": false,
    "enableReverseProxyAuth": false,
    "resourceQuotas": {
      "dataExportFileSizeLimit": 1.0E7,
      "sqlMaxRunningQueries": 100.0,
      "sqlResultSetRowsLimit": 100000.0,
      "sqlResultSetMemoryLimit": 2000000.0
    },
    ```

**Comment by kseniiaguzeeva** [comment]
Could you please try to delete .cloudbeaver.runtime.conf file and go through the Easy Configuration again?

**Comment by kseniiaguzeeva** [comment]
I have noticed that you have not updated your ticket for a long time. If you wish to reopen this ticket, please feel free to contact me.
