### ISSUE TITLE
Add some example in documentation `Server configuration`

### ISSUE THREAD

**Issue by crkcni** [dbeaver/cloudbeaver#827]
Hi, 
Can we add `createDatabase` under the `server.database` session into your WIKI, [Server-configuration#database-configuration](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#database-configuration) ?
Can we also add available `server.database.pool` parameters ?
Same with `anonymousUserRole`, who appear in Typical server configuration on server configuration page, but doesn't appear in `app` parameters.

Moreover, can you confirm that local name/password based authentication is saved into database specified in `server.database` connection string, but server credential datasources are stored on files based in `/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/` and can't be stored in CloudBeaver database ?

Finally, I have tried to configure `conf/cloudbeaver.conf` instead of `workspace/.data/.cloudbeaver.runtime.conf` file, but it seems this file is not even taken into account, not even as a lower priority file.

Thanks a lot,

**Comment by kseniiaguzeeva** [comment]
Thank you for your request. We are going to add the description to Wiki in the next release.

**Comment by alexander-skoblikov** [comment]
Hi! 
We have added more details about the possible server configuration to our [wiki page](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration).

> Can we add createDatabase under the server.database session into your WIKI

This is obsolete parameter that is no longer used and will be removed shortly.

> Moreover, can you confirm that local name/password based authentication is saved into database specified in server.database connection string, but server credential datasources are stored on files based in /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/ and can't be stored in CloudBeaver database ?

Yes, CloudBeaver database doesn't store database connection settings/credentials. The database stores information about users/credentials/permissions/available database connections(without settings). 

> Finally, I have tried to configure conf/cloudbeaver.conf instead of workspace/.data/.cloudbeaver.runtime.conf file, but it seems this file is not even taken into account, not even as a lower priority file.

Can you add some context on how you start the server, what settings do you change and what behavior did you expect?
