### ISSUE TITLE
Is there a way to create user in CloudBeaver out of GUI ? 

### ISSUE THREAD

**Issue by crkcni** [dbeaver/cloudbeaver#829]
Please, describe your question in details. ⬇️ 

Hi, I wanted to implement [Reverse-proxy-header-authentication](https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication), however I want to facilitated user creation, without interacting with Cloudbeaver Console (like with a curl, API or directly in database (but I don't know how should I implement my password in this format))

I saw from my browser console that there is multiples GQL requests that are sent, but I don't know how can I sent my password correctly.
Moreover, when I check in GQL console documentation, with `setUserCredentials` function, I don't see more details to `credentials` argument, except `An object scalar`.

Do you have any additional information on this ? ⬇️ 

Thanks a lot

**Comment by crkcni** [comment]
Well, I may found a way, as I can use `api/gql` endpoint and send a MD5 hash of my password

**Comment by Buronn** [comment]
> Well, I may found a way, as I can use `api/gql` endpoint and send a MD5 hash of my password

Could you show me an example of how you did it?
I would like to initialize _cbeaver_ without logging in and within a container database connection.

**Comment by kseniiaguzeeva** [comment]
When you use Reverse Proxy authentication, Proxy user is created automatically in CloudBeaver .
If you want to use api/gql to create a user, you can do it. [This ticket](https://github.com/dbeaver/cloudbeaver/issues/822) has some examples.

**Comment by kseniiaguzeeva** [comment]
I have noticed that you have not updated your ticket for a long time. If you wish to reopen this ticket, please feel free to contact me.
