### ISSUE TITLE
Cross domain problems

### ISSUE THREAD

**Issue by itman2022** [dbeaver/cloudbeaver#830]
Is there a property to set dloudbeaver to solve cross domain problems ？

I want to use "org.eclipse.jetty.servlets.CrossOriginFilter" , how to do it ?

MANIFEST.MF / FEATURE.XML / CloudbeaverServer.product.launch

**Comment by kseniiaguzeeva** [comment]
Thank you for the good idea. We are going to implement a property after 22.2.0 release

**Comment by Wroud** [comment]
can you please describe the problem?

**Comment by Wroud** [comment]
We want to know exactly why you need Cross Origin, to understand if we need to done some changes or not. So please give us more information :)

**Comment by kseniaguzeeva** [comment]
I noticed that there have been no updates for a long time. Please feel free to ask to reopen the ticket if it is still actual for you.
