### ISSUE TITLE
Why does Dbeaver have diagram viewer for free and cloudbeaver doesn't?

### ISSUE THREAD

**Issue by Buronn** [dbeaver/cloudbeaver#831]
It seems a bit strange to me that this feature is not for this version, honestly I don't see much point in this differentiation.
Perhaps you could give me a detailed answer on the reasons for this decision. Greetings

**Comment by kseniiaguzeeva** [comment]
Thank you for your interest in CloudBeaver. The implementation differs from DBeaver, especially routing. Its algorithms cannot be included into the open source product.
