### ISSUE TITLE
Protect "View system objects" and "Simple view" connection view settings 

### ISSUE THREAD

**Issue by riccardomessineo** [dbeaver/cloudbeaver#851]
**Is your feature request related to a problem? Please describe.**
I need to share cloudbeaver with other users which are less tech-savvy than me, so I want to disable "view system objects" and enable "simple view" on their connection (and block them).

**Describe the solution you'd like**
On "connection management" I'd like a panel to set view settings per connection, and maybe a flag to give the ability to users change it or not.

**Comment by kseniiaguzeeva** [comment]
We are going to implement it. Thank you for the feature request.

**Comment by UnleashSpirit** [comment]
Hello,
I would like this feature too ! :)
'Till now I manually edit the `workspace/GlobalConfiguration/.dbeaver/data-sources.json`
And remove (or set to false) the `"show-system-objects": true`

**Comment by kseniaguzeeva** [comment]
The feature is implemented in the latest 22.2.1 release. [Here](https://github.com/dbeaver/cloudbeaver/wiki/Product-settings-connections) is the description how to configure it.
