### ISSUE TITLE
Admin login with disabled local name/password based authentication

### ISSUE THREAD

**Issue by riccardomessineo** [dbeaver/cloudbeaver#853]
Hello,
  just a simple question: how can an admin login if it's disabled the local based authentication?

Should it access to runtime config and add "local" to "enabledAuthProviders": [] in the .cloudbeaver.runtime.conf?
I tried it but it seems the new rule it's not applied, maybe I should do a sort of "service cloudbeaver reload"?

**Comment by kseniiaguzeeva** [comment]
Just add `admin` to your URL (`http://localhost:8080/#/admin`) and the Authentication dialog will appear.

Feel free to ask any other questions.

**Comment by riccardomessineo** [comment]
Easy peasy.
Thanks!
