### ISSUE TITLE
Favicon not being pickedup in chromeos

### ISSUE THREAD

**Issue by wardy277** [dbeaver/cloudbeaver#858]
**Describe the bug**
Chromeos can create a webapp from any page. The icon not not get picked up on chromeos

**To Reproduce**
1. Navigate to cloudbeaver site
2. Click on the tree dots on top right -> More tools -> Create Shortcut
4. Icon is generic [C] and not the favicon

**Screenshots**
Cloudbeaver
![Screenshot 2022-05-26 11 59 27 AM](https://user-images.githubusercontent.com/4417572/170475158-de980d26-b1c5-40d2-9321-7e8f8826462f.png)
working example in github
![Screenshot 2022-05-26 12 01 48 PM](https://user-images.githubusercontent.com/4417572/170475533-e1bf15fd-27b3-4f07-84be-92e18e361754.png)

**Desktop (please complete the following information):**
 - OS: Chromeos
 - Browser Chrome
 - Version 101

**Additional context**
I appreciate this issue doesnt say how to fix it, just that the icon doesnt get picked up. Hopefully chrome browser itself has this issue so you dont have to find a chromeos device

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. We are going to fix it.

**Comment by kseniiaguzeeva** [comment]
The fix is available in the latest 22.1.0 release.
