### ISSUE TITLE
Error when saving script - Variable 'projectId' has coerced Null value for NonNull type 'String!'

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#865]
**Describe the bug**
Error when saving SQL script from UI

**To Reproduce**

1. Click on 'Save Script Icon"
2. Keep default script name
3. See error

**Screenshots**
![2022-05-26_16-46-54](https://user-images.githubusercontent.com/57646596/170601936-13263401-6b30-4b4e-9f6d-29643277fec1.png)

**Desktop (please complete the following information):**
 - OS: Windows/Mac
 - Browser Chrome
 - Version 22.0.5

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. It happens with anonymous access, because a user has to be logged in to use the Resource manager. The bug fix is included in the next release (June 06, 2022).

**Comment by kseniiaguzeeva** [comment]
The fix is available in the latest 22.1.0 release.
