### ISSUE TITLE
Make session expiration check configurable

### ISSUE THREAD

**Issue by JDarDagran** [dbeaver/cloudbeaver#866]
**Is your feature request related to a problem? Please describe.**
I'm keeping CloudBeaver session cookies behind reversed proxy. Therefore browser does not keep cookies. This results in session expired warnings.

**Describe the solution you'd like**
I'd like to set POLL_INTERVAL to be configurable from config

https://github.com/dbeaver/cloudbeaver/blob/fac1d3954d6a648601a9f728236769d8c5739cc9/webapp/packages/core-app/src/shared/SessionExpireWarningDialog/SessionExpireWarningDialogService.ts#L19

or to have session expired configurable to be turned off.

**Comment by kseniiaguzeeva** [comment]
Reverse proxy doesn't affect the session expiration time. Could you please try to configure it also in `.cloudbeaver,runtime.conf` (`expireSessionAfterPeriod`)?

**Comment by JDarDagran** [comment]
I have this configured to 1800000, still this does not help. The issue is that the browser does not have any CloudBeaver cookie and looking at the code of `SessionExpireWarningDialogService` if there's no cookie https://github.com/dbeaver/cloudbeaver/blob/fac1d3954d6a648601a9f728236769d8c5739cc9/webapp/packages/core-app/src/shared/SessionExpireWarningDialog/SessionExpireWarningDialogService.ts#L56

it will treat it as session expired.

**Comment by JDarDagran** [comment]
@kseniiaguzeeva do you think it's feasible to add as a feature?

**Comment by Wroud** [comment]
Hi, can you check if you have `cb-session-id` cookie please. If you don't have it, it's probably some issue with setting cookies in browser, it can be related to browser / nginx settings.

**Comment by JDarDagran** [comment]
I'm probably misunderstood. The browser does not keep cookies, it's forced per design we have as a workaround. Proxy stores cookies and attaches it back to CloudBeaver.
The question is if it would be possible to add what I asked for in the issue.

**Comment by Wroud** [comment]
I see, we can make session expire mechanism configurable

**Comment by JDarDagran** [comment]
That's great, thank you!

**Comment by devnaumov** [comment]
We've added the new parameter "core.cookies.disabled" to the [config](https://github.com/dbeaver/cloudbeaver/wiki/Product-configuration-parameters) in the 22.1.1 release. It will allow you to disable polling functionality.
Also, we are planning to rethink the Session Expired behavior in the 22.1.3 release so it doesn't depend on the specific cookies.
