### ISSUE TITLE
Undo SQL formatting

### ISSUE THREAD

**Issue by frank-lam** [dbeaver/cloudbeaver#873]
when I click `Format SQL`,  the script is formatted normally. However, you cannot use the shortcut keys Ctrl+Z to restore the script before formatting.

And the sql background has a layer of black highlight, I don't think the experience is particularly friendly, and there are fonts. The SQL editor can be optimized by referring to the codemirror component.

CodeMirror: Theme Demo
https://codemirror.net/demo/theme.html#hopscotch

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea. We are going to implement Undo shortcut for Format SQL tool in one of the future releases.
Regarding the second point could you please send a screenshot with unsuitable layer?

**Comment by kseniiaguzeeva** [comment]
Implemented
