### ISSUE TITLE
Reconnection options for Trino connection closed due to manual cancels

### ISSUE THREAD

**Issue by metalshanked** [dbeaver/cloudbeaver#884]
Thanks @kseniiaguzeeva - makes sense. Just that from a user viewpoint, they dont know what to do when this error is displayed i.e. "Connection is closed". because none of the options in the UI, like retry,close etc will work.  
The only solution is to click "Disconnect" and reconnect which is unintuitive to the end user.

A message like "please try disconnecting and reconnecting" or even better the retry button automatically doing this would be great.

_None of the below options help_
![2022-05-29_18-46-18](https://user-images.githubusercontent.com/57646596/170902659-d6b0f129-b2bf-4f2a-a951-8d4505cdb3ae.png)

_Current solution (disconnect and reconnect)_
![2022-05-29_17-52-19](https://user-images.githubusercontent.com/57646596/170899156-74345734-4158-4811-b29b-9abd3edea8a2.png)

_Originally posted by @metalshanked in https://github.com/dbeaver/cloudbeaver/issues/782#issuecomment-1140566979_

**Comment by kseniiaguzeeva** [comment]
Thank you for your idea. We are going to implement a tool for this case.

**Comment by metalshanked** [comment]
@kseniiaguzeeva  hi, is there any plans or ETA for this.
This will be a huge boon for trino users.  We get many queries from end users who are confused when this happens

**Comment by MarinaVorobeva21** [comment]
Hello @metalshanked ,
it is planned to be fixed in milestone 23.0.2.

**Comment by TatyanaSsau** [comment]
Waiting for https://github.com/dbeaver/pro/issues/1534
An implementation is going to be at 23.0.4 release.

**Comment by metalshanked** [comment]
@TatyanaSsau - Any update on this? Thanks!

**Comment by TatyanaSsau** [comment]
@metalshanked we have made improvements to Trino's functionality in 23.1.0 version. 
Resulting in more user-friendly error messages, especially when operations are interrupted. 

We will be happy to hear any new cases or feedback from you!

**Comment by metalshanked** [comment]
Thanks @TatyanaSsau. Upgraded to 23.1.0 and now see the below for manual cancels which allows retry as well.
The queries are killed on the Trino side correctly too.
Super useful. Will report if I encounter any issues.

Thanks again!!


![image](https://github.com/dbeaver/cloudbeaver/assets/57646596/569aabeb-1af9-43f7-8297-b8f871ba17d2)

**Comment by EvgeniaBzzz** [comment]
I believe everything is going smoothly. Please let us know if any issues arise
