### ISSUE TITLE
Remove "Edit connection" menu item for non-admin user

### ISSUE THREAD

**Issue by gualask** [dbeaver/cloudbeaver#891]
The "Edit connection" option should be removed for users who are not connection administrators.
This is because they cannot modify such data and furthermore sensitive information related to the connection and the driver in use are shown on that page.

![cloudbeaver_feature_request](https://user-images.githubusercontent.com/10849798/172382846-c0d71ea0-b95b-4312-a50b-75fe2863a694.jpg)

**Comment by kseniiaguzeeva** [comment]
Thanks for the suggestion. We're going to make the menu visibility configurable.

**Comment by ar3thien** [comment]
+1

**Comment by kseniaguzeeva** [comment]
The feature is available in the latest 22.2.5 release.
