### ISSUE TITLE
product.conf , Some configuration information in the file is not effective

### ISSUE THREAD

**Issue by itman2022** [dbeaver/cloudbeaver#892]
**product.conf** ，Some configuration information in the file is not effective ？

I set the property “defaultTheme” to “dark”, but still display “light”, 
and “defaultLanguage” is the same problem, other language is not effective except “en”:

![pic03](https://user-images.githubusercontent.com/49448987/172642492-df54400b-d71e-4bee-9dde-60b100416f7d.jpg)

![pic02](https://user-images.githubusercontent.com/49448987/172385471-5c10383b-437f-4d56-997e-4423d3058e84.jpg)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. The issue with language configuration is going to be fixed in 22.1.2 release.
`DefaultTheme` setting works as expected: the configured theme in `product.conf` is applied to the application. But when a user sets a theme via UI, the applcation becomes to use it instead of the setting in `product.conf`.

**Comment by itman2022** [comment]
thanks !

**Comment by itman2022** [comment]
the ".cloudbeaver.runtime.conf" is not effective ? 
![pic04](https://user-images.githubusercontent.com/49448987/172645887-a84286cb-54df-412c-90e5-c7c7d43d85da.jpg)
![pic05](https://user-images.githubusercontent.com/49448987/172649677-99c3dcda-72a1-4b13-89a3-b5467c4fb01d.jpg)
![pic06](https://user-images.githubusercontent.com/49448987/172649732-3e2c7e21-f8a0-4ee4-94b6-876143761a35.jpg)

**Comment by kseniiaguzeeva** [comment]
Language and theme are configured in `.product.runtime.conf`. You can find [here](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration), what can be configured in `.cloudbeaver.runtime.conf`.

**Comment by kseniiaguzeeva** [comment]
The bug is fixed in the latest 22.1.2 release.
