### ISSUE TITLE
Support connection folders

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/cloudbeaver#9]
We need connection folders (similar to DBeaver ones).

Currently if you copy datasource configuration from dbeaver into cloudbeaver all connections in folders will be invisible.

**Comment by FreeSoftwareServers** [comment]
@serge-rider were you able to get `data-sources.json` to work at all? Can you share a generic example for me to work off?

**Comment by serge-rider** [comment]
Sure, I do this all the time.
If your config contains connections in folders you need to remove folder (delete folder=xxx elements). Otherwise they will be hidden.
You can find example if GlobalConfiguration folder.

**Comment by serge-rider** [comment]
Resolved in 1.0.3
