### ISSUE TITLE
How to enable diagrams

### ISSUE THREAD

**Issue by xnYi9wRezm** [dbeaver/cloudbeaver#900]
Hello,

First of, pretty could project. It's great to be able to see all the different databases in the same app.

The diagram feature seems great, but I am not able to get the button. I suspect something has to be enabled somewhere.

I tried with Oracle, Postgres, and MySQL dbs.

Is there anything I should do to enable diagrams?

Thanks

**Comment by kseniiaguzeeva** [comment]
Thank you for your interest in CloudBeaver. [ERD](https://github.com/dbeaver/cloudbeaver/wiki/Entity-Diagrams) is available in Enterprise Edition only. All Enterprise features are marked by the star in the [wiki](https://github.com/dbeaver/cloudbeaver/wiki).

You can try [EE version](https://cloudbeaver.io/trial/) for free.

**Comment by xnYi9wRezm** [comment]
Got it. Thank you
