### ISSUE TITLE
How to set the encoding of exported csv files to utf-8

### ISSUE THREAD

**Issue by WainWong** [dbeaver/cloudbeaver#908]
I use the export function to export csv files, but there is a problem that the Chinese in the exported file will be displayed as garbled code, where can I set the encoding of the csv file?

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response. I cannot reproduce the issue. Hovewer we are going to investigate it and find out the reason of the issue.

**Comment by kseniaguzeeva** [comment]
The new feature is available in the latest 22.2.1 release:
you can:
- change encoding settings,
- unsert BOMs for exported data.

It should solve the issue. If the problem still exists, do not hesitate to contact me to ask to reopen the ticket.
