### ISSUE TITLE
provided-connections.json with access to anonymous users

### ISSUE THREAD

**Issue by guitcastro** [dbeaver/cloudbeaver#915]
**Is your feature request related to a problem? Please describe.**
I am trying to configure cloudbeaver with a provided connection, for anonymous users. However it's not possible to automated this. I have to manual log as admin and give access to "USERS" role.

**Describe the solution you'd like**
For the context, I work using infra as code and I am trying to use codebeaver to give teams readonly access to databases. We already deployed the cloudbeaver under an ouath2 proxy, thats why anonymous login is being used.

**Comment by kseniiaguzeeva** [comment]
Thank you for your intereset in CloudBeaver.
We are going to add the permission configuration for provided connections via the configuration file.

**Comment by marcellodesales** [comment]
Any plans on this?

**Comment by TatyanaSsau** [comment]
@marcellodesales, sorry, for really long time to response!
It is not completely dropped, but this task is in the long-term plans for our team.

Thank you for your interest in CloudBeaver!

**Comment by GenLN** [comment]
Hi any news on this?

**Comment by LonwoLonwo** [comment]
Hello @guitcastro 

Looks like you can do it now.

You need to configure these two files:

https://github.com/dbeaver/cloudbeaver/wiki/Pre%E2%80%90configured-permissions-for-connections
https://github.com/dbeaver/cloudbeaver/wiki/Connection-configuration#pre-configured-connections

And add them to your container.

Please let me know if it solves your request.

**Comment by guitcastro** [comment]
Hi @LonwoLonwo , Thanks for the response!

Just a doubt:

>  ["test_team", "test_user"] - list of users and teams who will have access for connection.

In my case where I want to allow anonymous, which string should I put in the array? `anonymous`?

**Comment by LonwoLonwo** [comment]
Like
`anonymousUserTeam: "user"`
From this doc https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration

**Comment by LonwoLonwo** [comment]
Could I close this ticket? Is this case solved?

**Comment by guitcastro** [comment]
@LonwoLonwo Yes, thank you!

**Comment by LonwoLonwo** [comment]
Thanks for your answer, @guitcastro and the interest in our product 🤗
