### ISSUE TITLE
 "Elements are limited to 500 items"

### ISSUE THREAD

**Issue by Geronium** [dbeaver/cloudbeaver#936]
**Describe the bug**
When we select a schema and list the tables we can't display more than 100 tables

**To Reproduce**
1. Go to a Schema
2. Click on "tables" to list the tables of the schema, 
3. See juste the 500 first tables, and after the 500 th  "Elements are limited to 500 items"

**Screenshots**

![Capture d’écran de 2022-06-29 15-50-15](https://user-images.githubusercontent.com/73563389/176453280-a9ec277a-f6fc-4eac-9c21-8e09392fef69.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 16.0.4
 - Browser firefox
 - Version : 91.4.1esr (64 bits)

**Additional context**
Add any other context about the problem here, e.g. error log.

Thank you

**Comment by kseniiaguzeeva** [comment]
You can change the number of the displayed elements in `product.conf` file using parameter `navigationTree.childrenLimit` ([here](https://github.com/dbeaver/cloudbeaver/wiki/Product-configuration-parameters) is the full description). Please note that displaying a large number of objects can slow down the application.

**Comment by kseniiaguzeeva** [comment]
I have noticed that you have not updated your ticket for a long time. If you wish to reopen this ticket, please feel free to contact me.
