### ISSUE TITLE
How to import this project into Intellij IDEA and run?

### ISSUE THREAD

**Issue by BlackMZ** [dbeaver/cloudbeaver#946]
I am trying to import this project into Intellij IDEA.  When I want to run clean command, I got this: 

![image](https://user-images.githubusercontent.com/25170511/176815275-62495bc8-5f67-4d56-a188-619c32da58da.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for your interest in CloudBeaver. We are going to write the article how to do it. While could you please try to use [DBeaver instruction](https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA) for CloudBeaver import?

**Comment by Wroud** [comment]
You need to follow this guide https://github.com/dbeaver/cloudbeaver/wiki/Develop-in-Eclipse
and then same steps as in https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA
you also can try to configure vs code https://github.com/dbeaver/cloudbeaver/wiki/Develop-in-VS-Code

**Comment by dariamarutkina** [comment]
@BlackMZ , Please reopen the issue if the comment above didn't help you
Thank you for interesting in CloudBeaver!
