### ISSUE TITLE
No preconfigured connections found

### ISSUE THREAD

**Issue by nicolamarangoni** [dbeaver/cloudbeaver#95]
**Description**
in the folder `cloudbeaver/deploy/cloudbeaver/workspace/GlobalConfiguration/.dbeaver`, I filled both `data-sources.json` and `provided-connections.json`.
After restarting CloudBever I don't see any preconfigured connection.

**To Reproduce**
1. Install CloudBeaver
2. Go to folder `cloudbeaver/deploy/cloudbeaver/workspace/GlobalConfiguration/.dbeaver`
3. Enter some connections in `data-sources.json` and `provided-connections.json`
4. Start CloudBeaver
5. Go to the start page
6. Search for preconfigured connections

**Server**
CentOS7

**Desktop**
 - OS: MacOS
 - Browser: Chrome, Firefox
 - Version latest

**Comment by serge-rider** [comment]
Please check error/debug log.
Perhaps something is wrong with connections configuration.
Debug log is in cloudbeaver/deploy/cloudbeaver/workspace/.metadata

**Comment by serge-rider** [comment]
I've reproduced this issue. It is fixed.
Please check the latest  version (devel branch or release 1.0.4).

**Comment by nicolamarangoni** [comment]
Many thanks! It works now!
However, the navigation bar remains empty as before. I just can use SQL-tabs to query objects.
I don't have any file in `cloudbeaver/deploy/cloudbeaver/workspace/.metadata`

**Comment by nicolamarangoni** [comment]
I also don't understand the difference between `data-sources.json` and `provided-connections.json`

**Comment by serge-rider** [comment]
Connections in `data-sources.json` are "pre-comnfigured" - you can add them into navigator manually (from the top bar menu).

Connections in `provided-connections.json` are always visible in the navigator (similarly to desktop dbeaver).

**Comment by nicolamarangoni** [comment]
This issue is closed because I can browse the datasources now (tested with 1.0.4)
