### ISSUE TITLE
install relpackage1.0.4,but has no login sub-menu

### ISSUE THREAD

**Issue by wengad82** [dbeaver/cloudbeaver#96]
i download the release package 1.0.4 ce,and start server
then goto http://xx.xx.xx.xx:8978
but has no **login** sub-menu 

i want to know  the feature "Administrative panel"  from ver 1.0.3 ,it mean i can manage user and role from cloudeaver ce , and it is independent with database link which i create and use?

**Comment by serge-rider** [comment]
You need to set `authenticationEnabled: true` in the configuration (`cloudbeaver.conf`)

**Comment by serge-rider** [comment]
We'll enable it by default.
