### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by itman2022** [dbeaver/cloudbeaver#965]
**Describe the bug**
When i execute sql , then show -> Cannot read property '0' of undefined

Cloudbeaver 22.1.2
OS: Windows 7
Browser chrome 81.0.4044.133

**Screenshots**
![error01](https://user-images.githubusercontent.com/49448987/178788989-341b1e90-748f-4104-9d88-1189d7f7893f.jpg)

![error02](https://user-images.githubusercontent.com/49448987/178789011-3f495c4c-788c-46d2-8496-37d51fae0433.jpg)

![error03](https://user-images.githubusercontent.com/49448987/178790166-d5a608ff-7761-4bc8-9f36-91b562e504a6.jpg)

**Comment by Wroud** [comment]
Could you please try to press Shift+F5 on the application tab (it's should clean browser cache for cloudbeaver)

**Comment by itman2022** [comment]
not works, Wroud

**Comment by kseniiaguzeeva** [comment]
It seems, the ticket duplicated the issue https://github.com/dbeaver/cloudbeaver/issues/942.
I've reproduced the issue on Chrome version 81.0.4044.129. Could you please try to update the browser version?

**Comment by Geronium** [comment]
Hello, i can't update the browser because the version of the browser is defined and managed by an other team, and i'm not the only user of cloudbeaver, i give a service with cloudbeaver inside a docker image for many users in the compagny. 
Thank you

**Comment by itman2022** [comment]
when i update chrome to 101.0.4951.67, then show ：

Uncaught (in promise) Server Error: Cannot return null for non-nullable type: 'String' within parent 'SessionInfo' (/session/locale)
    at c.overrideRequest (http://localhost:8978/index.f85b89fdd51e17c1bd3a.js:2:744508)
    at async uu.sessionExpiredInterceptor (http://localhost:8978/index.f85b89fdd51e17c1bd3a.js:2:1170838)
    at async jt.sessionExpiredInterceptor (http://localhost:8978/index.f85b89fdd51e17c1bd3a.js:2:978315)
    at async i.loader (http://localhost:8978/index.f85b89fdd51e17c1bd3a.js:2:702871)
    at async i.loadingTask (http://localhost:8978/index.f85b89fdd51e17c1bd3a.js:2:756785)
    at async i.taskWrapper (http://localhost:8978/index.f85b89fdd51e17c1bd3a.js:2:756911)
    at async s.task (http://localhost:8978/index.f85b89fdd51e17c1bd3a.js:2:756502)

![error06](https://user-images.githubusercontent.com/49448987/179391660-e173fedf-88fe-4566-896d-200e57140d29.jpg)

**Comment by Wroud** [comment]
@itman2022 can you please tell steps to reproduce?

**Comment by itman2022** [comment]
@Wroud
1. run-server.bat
2. open chrome -> http://localhost:8978/
3. F12
4. show : Uncaught (in promise) Server Error: Cannot return null for non-nullable type: 'String' within parent 'SessionInfo' (/session/locale)

**Comment by Wroud** [comment]
@itman2022  if you have built server from sources, please pull changes from `cloudbeaver` and rebuild it, we fixed this problem in https://github.com/dbeaver/cloudbeaver/commit/2a29a065c6344780a010b07ae0f3a5e21d3a7dbb

**Comment by itman2022** [comment]
it works !

**Comment by kseniiaguzeeva** [comment]
I'm glad to hear it.

**Comment by kseniaguzeeva** [comment]
The bug is fixed and available in the latest 22.2.0 release.
