### ISSUE TITLE
Unable to connect to non SSL SQL Server database

### ISSUE THREAD

**Issue by MingHuiLiu** [dbeaver/cloudbeaver#997]
The error is as follows：

Error connecting to database:
Connection failed:
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]".

**Comment by kseniiaguzeeva** [comment]
Could you please tell me some additional details:
- CloudBeaver version
- Browser version
- What SQL Server authentication method do you use?

**Comment by kseniaguzeeva** [comment]
I've noticed there is no updates during for a long time in this ticket. Feel free to contact me to reopen the issue if it's still actual for you.
